### ISSUE TITLE
Okular displays icons in wrong direction in PDF that was rotated using qpdf

### ISSUE THREAD

**Issue by rdrg109** [qpdf/qpdf#1005]
Let me show you a minimal working example for proving my point

```sh
$ convert -size 595x842 xc:white convert-1.pdf
$ convert -size 595x842 xc:white convert-2.pdf
$ convert -size 595x842 xc:white convert-3.pdf
```

The code block below shows two commands. `qpdf` is used to rotate the file `convert-2.pdf` and it is also used to merge the PDF files, which were generated using the commands from the previous code block.

```sh
$ qpdf --empty --pages convert-1.pdf 1 -- --rotate=90 qpdf-2.pdf
$ qpdf --empty --pages convert-1.pdf qpdf-2.pdf convert-3.pdf -- merged-using-qpdf.pdf
```

The code block below shows tow commands. `convert-2.pdf` is rotated using `convert` and the PDF files are merged using `pdfunite`.

```sh
$ convert convert-2.pdf -rotate 90 convert-2-rotated-using-convert.pdf
$ pdfunite convert-1.pdf convert-2-rotated-using-convert.pdf convert-3.pdf merged-using-convert-and-pdfunite.pdf
```

When I opened `merged-using-qpdf.pdf` in Okular and insert `Pop-up note`, the `Pop-up note` icon is shown rotated (please see image below). To me, this is unexpected behavior. The icon of the `Pop-up note` in `merged-using-qpdf.pdf` should be shown in the same direction as in the other pages. It is worth mentioning that when I save the file, the icon is shown in its correct direction.

![image](https://github.com/qpdf/qpdf/assets/74389646/b735411e-7272-489e-84fe-5b11da544bf6)

When I open `merged-using-convert-and-pdfunite.pdf` in Okular and insert a `Pop-up note`, the note icon is not shown rotated (please see image below). To me, this is expected behavior.

![image](https://github.com/qpdf/qpdf/assets/74389646/2c2e1161-4b26-4c78-98a5-3a7cee636990)

Is the unexpected behavior `okular`'s bug or `qpdf`'s bug?

**Comment by jberkenbilt** [comment]
Thanks for the detailed report. I will look at this when I have a chance. As you say, it's possible that it as an Okular issue, or it's possible that qpdf is doing something wrong. One thing you could try in the interim is testing with other viewers. Try loading the PDF file in ghostscript, chrome, or firefox (all three of which use different PDF engines) or using evince or atril or even Adobe Reader or commercial readers on non-Linux systems. If it works everywhere else, it's probably an okular issue, but it's also possible that qpdf is doing something wrong that other viewers are compensating for. Another thing to try is to see whether the annotation that gets damaged is handled differently if you put the file that originally contains it first. In other words, instead of `qpdf --empty --pages file1.pdf file2.pdf`, do `qpdf file1.pdf --pages . file2.pdf`. The file specified as the primary input file gets special treatment, and if something in document-level metadata that is copied from the first file is responsible, that could account for this. If that is the case, there are a number of long-standing omissions in qpdf's functionality that I am planning on addressing the next time I have a chunk of time to work on it.

Even if you conclude that this is an okular issue, it would be great if you can leave the issue open so I can study it. Even if it is an okular issue, it's not desirable for a file to render differently after passing through qpdf, so this may flag some aspect of the data that qpdf is not preserving correctly when merging pages, and I'd like to make sure I capture that when I do the pages work. (I'm adding my `pages` label as a reminder to myself.)

**Comment by jberkenbilt** [comment]
Note to self: at the time the `pages` label was added, it was not yet known whether this is a pages issue.

**Comment by m-holger** [comment]
This looks to me to be a Okular issue. The closed annotation is rotated according to the value of the /Rotate key (during the initial session).  12.5.6.4 of the PDF spec states that text annotations shall not rotate with the page.

It would be interesting to see convert-2-rotated-using-convert.pdf . I assume it does not have a /Rotate entry.

**Comment by jberkenbilt** [comment]
Closing as an okular bug. Thanks.

**Comment by jberkenbilt** [comment]
The convert/pdfunite one does not have a `/Rotate` as @m-holger speculated. Also, running `qpdf --flatten-rotation` on the qpdf version results in a file that okular does not rotate the annotation on.

**Comment by jberkenbilt** [comment]
@rdrg109 btw, thanks for the great bug report. I think you can create an issue with Okular and show them this report or provide the same information, adding the bit about the /Rotate key.
