### ISSUE TITLE
how do you use this program?

### ISSUE THREAD

**Issue by SRAHIMIAN24** [qpdf/qpdf#1008]
Can someone provide _**detailed**_ instructions on how to use qpdf once it is installed onto windows, the current documentation provides no instructions on how to use the program or its functions in powershell or any other program on windows post installation.

Regards

Stephen

Note:  for context, I work as an engineer and need this utility to decrypt a pdf someone sent our company.  I am able to install the qpdf following the instructions however I do not know how to proceed from there and nothing works in powershell or cmake

**Comment by mschilli87** [comment]
@SRAHIMIAN24: On Linux, you'd run `qpdf --help` in your shell to get *very* detailed documentation on how to use this tool. I do not provide free (as in free drinks) support for non-free (as in free speach) software. If your company want to hire me as a payed consultant, feel free (no pun intended) to reach out to discuss the details. I'd recommend switching operating systems instead though. Alternatively, you could try to get support from Microsoft, the company your company pays a lot of money for the operating system you are needing support with. :wink:
Joking aside, I am sure you can run `qpdf --help` somehow in Windows. If that doesn't work, you probably did a mistake during the installation. I cannot help with that though since I do not know how to install anything on Windows (though Microsoft support should know, I assume).

**Comment by rubyFeedback** [comment]
I am using Linux primarily, but I do also use Windows on a spare machine (Win10 that is) to my left side.

I also use ruby, both on linux and windows, but mostly on linux.

The wrapper project I use is a gem I maintain called pdf_paradise; it can be found here:

https://rubygems.org/gems/pdf_paradise

I do not recommend anyone else to use this gem, but for my own use cases, this works fairly well.

For GUI-related parts I use ruby-gtk and libui on linux; on windows only libui (and sometimes the
www, such as .cgi files, or sinatra, sometimes rails, but mostly sinatra really).

Documentation for pdf_paradise can be found here:

https://www.rubydoc.info/gems/pdf_paradise/

The documentation there is not great but I try to improve it every once in a while.

Anyway. This was the introduction, so now to your question(s).

> detailed instructions on how to use qpdf once it is installed onto windows

So, I actually do not use qpdf directly; I use it via ruby. Ruby then passes all
options that qpdf needs.

For instance, I bundle the action "delete the first page of a .pdf file" into
this class:

    PdfParadise::DeleteFirstPageOfThisPdfFile

The code can be found here:

    pdf_paradise/utility_scripts/delete_first_page_of_this_pdf_file.rb

Internally that class can decide what to use: hexapdf, qpdf, pdftk or
anything else I add support for. Usually I pick between hexapdf and
qpdf (interestingly enough, different libraries seem to implement 
the pdf specification differently, so sometimes you get better results
with one program and worse with another one, so this is why I have
to remain flexible. Also on windows not everything works, so this is
another reason I have to remain flexible).

Using the commandline on windows can be annoying though. You can
use KDE konsole, you can also use most of your aliases on windows if
you use "doskey.exe" (old but still works), but to make a long story
short, this is why I also use libui on windows. That way I can get
functionality on windows via a GUI, such as deleting the first page of
a .pdf file. The reason I need this is because I may read a .pdf file
such as to extend my knowledge, but after I have read the page
and taken local notes, I no longer need it so I remove the first
page, usually on the commandline (on linux), but also via a GUI
(on windows), through libui.

Here is how it looks on linux + IceWM:

https://i.imgur.com/p0Sly77.png

Does not look that great, I get it, but for me the functionality
is important. This is also just hackish quick-work; libui on ruby
can look much better, look at the awesome things Andy does
via glimmer + libui there:

https://github.com/AndyObtiva/glimmer-dsl-libui

The more important point is that it works (on linux right now;
I'll test it in the next days on windows and may add a new
screenshot).

Anyway, back to your question(s).

I myself don't know a whole lot. Whenever I learn something I
try to note down how it is done.

For instance, the ruby-wrapper code I use for qpdf to delete 
pages from a .pdf file is something like this:

    _ = 'qpdf --pages '+this_pdf_file+' 2-'+(has_n_pages.to_i).to_s+' -- '+
               this_pdf_file+' '+
               name_of_the_output_file

Notice the "2" there. If you omit the "1" then this means that the
first page (page 1) will not be part of the newly generated .pdf
file.

This is one example. You can also delete pages in the middle of
a .pdf and what not. (This is also in part why I asked whether 
qpdf could also support paragraph-operations or word-operations
so I can delete words or paragraphs, but this is probably out of
scope for qpdf, and I don't want to burden the qpdf author with
unpaid-for-additional-issues he'd have to invest his time. Time is
finite, so one has to focus on what seems useful, especially if
it is for many people to benefit, versus just a few or one, so that's
fine.)

> how to use the program 

You can basically use the qpdf commandline arguments just fine
on windows too, I think. Since that is tedious, I'd recommend to
write wrapper code. I did this in ruby but you can use python or
these commandlets or whatever the name was on powershell
(or just .bat batch files too I guess, but since I started ruby, ruby
replaced all my needs in this regard).

> need this utility to decrypt a pdf someone sent our company

I don't know how to decrypt a .pdf file myself, I'd have to research
how this is done. But if qpdf supports it then you just need to
find the appropriate commands.

qpdf --help shows this:

    Run "qpdf --help=topic" for help on a topic.
    Run "qpdf --help=--option" for help on an option.
    Run "qpdf --help=all" to see all available help.

    Topics:
      add-attachment: attach (embed) files
      advanced-control: tweak qpdf's behavior
      attachments: work with embedded files
      completion: shell completion
      copy-attachments: copy attachments from another file
      encryption: create encrypted files
      exit-status: meanings of qpdf's exit codes
      general: general options
      help: information about qpdf
      inspection: inspect PDF files
      json: JSON output for PDF information
      modification: change parts of the PDF
      overlay-underlay: overlay/underlay pages from other files
      page-ranges: page range syntax
      page-selection: select pages from one or more files
      pdf-dates: PDF date format
      testing: options for testing or debugging
      transformation: make structural PDF changes
      usage: basic invocation
    
    For detailed help, visit the qpdf manual: https://qpdf.readthedocs.io

I assume you may need to tap into the "encryption" subsection,
but I am the wrong one to be able to help here, since I have not yet
used that. If you find out, don't forget to let us know too!

I sometimes have encrypted .pdf files from other people and it
annoys me. That's why I keep all .pdf files I have without password.
(.epub files are even more annoying than .pdf files; that's another
reason for me to avoid .epub flies and just stick to .pdf files).

**Comment by jberkenbilt** [comment]
Thanks to the people who responded to this. I'm going to close this as I don't think there is anything that needs to be changed about qpdf or its documentation to address this at this time. Please feel free to reopen if there are concrete suggestions as to doc changes that would have helped.
