### ISSUE TITLE
qpdf --decrypt --remove-restrictions not working on docusign output

### ISSUE THREAD

**Issue by nicolausdewitt** [qpdf/qpdf#1015]
I'm trying to remove the editing restrictions on a document output from docusign using the decrypt and remove-restrictions parameters so it can be combined into another document.

I ran this on a file and it showed the restrictions are removed in the document properties but when I try to replace a page in acrobat pro it says "this operation is not allowed because the document is signed".

Edit: I have docusigned a copy of the qpdf manual that demonstrates this error, I'm happy to share the file and more info if that helps.

**Comment by jberkenbilt** [comment]
Sorry for the delayed response. Sharing the file and information about exactly what commands you're running and what version of qpdf you have would be helpful. I'm sure I have some docusigned files lying around. I keep thinking I have `--remove-restrictions` working, but it's a little complex, and I may well have missed some cases.

**Comment by nicolausdewitt** [comment]
@jberkenbilt no problem for delayed response, I really appreciate you looking into this.

I was using version 11.5.0 - here is the output of the manual from docusign - most things work, just seems to still have some "im signed" restrictions.
[qpdf-manual.pdf](https://github.com/qpdf/qpdf/files/12413463/qpdf-manual.pdf)

if I can help with anything let me know.

**Comment by jberkenbilt** [comment]
You had offered to share the file. Is that offer still good? I have been swamped with "real work" and have gotten behind on qpdf, but I will eventually have a good chunk of time to work on it . My next major epic with qpdf is to improve page splitting and merging, but I'm hoping to get to digital signature next. It will be a while, but hopefully it will happen. I'm hoping whatever's wrong here is just a small thing that I have continued to overlook.

**Comment by jberkenbilt** [comment]
I added the `next` label to make sure I don't forget to dig into this.

**Comment by jberkenbilt** [comment]
The issue here is not a document restriction but a digital signature. I would need to add something like `--disable-signatures`, which may be worth doing but it is not the same as removing restrictions. I think it would be pretty easy/

Iterate through all form fields. If `/FT` is `/Sig`:
* Remove the field from the list of form fields (leaving it as an annotation)
* Remove the `/FT`, `/V`, `/Lock`, and `/SV` keys

**Comment by jberkenbilt** [comment]
Looking at the code, this is practically already there. I'm going to go ahead and add this. I just coded it in about 5 minutes.

**Comment by jberkenbilt** [comment]
I verified that, with `--decrypt --remove-restrictions --disable-signatures` on this file, I can rearrange the pages in Acrobat pro and that without `--disable-signatures`, I can't. I believe this will address your issue. This will be in 11.7.0, which I intend to release today.

**Comment by jberkenbilt** [comment]
I changed my mind about adding a separate field and will instead release 11.7.0 (which I didn't quite finish yesterday) so that `--remove-restrictions` disables digital signature fields. I decided that one option is not really useful without the other, so there is no need to further complicate things. This use case will work in 11.7.0 with just `--remove-restrictions`.

**Comment by nicolausdewitt** [comment]
Sorry, this dropped off my radar and I only just got back to it! can't wait to test it out, it will be so helpful. I will get back to you asap with results.

**Comment by NoSOUP-4U** [comment]
Can anyone help me see the signature data on Docusign document my husband signed in 2021? He needs to verify the location or IP address and Inkeep getting dead ends. The file is not letting me view and save the metadata. It appears locked. Please help, I’m new to all this.
