### ISSUE TITLE
integer out of range converting

### ISSUE THREAD

**Issue by fmeneghetti** [qpdf/qpdf#1023]
I have a problem during **linearization** with a very large pdf (2.4GB) that contains a very large number of annotations.

`qpdf: integer out of range converting 2172622566 from an 8-byte signed type to a 4-byte signed type`

this pdf is obtained as a concatenation of about 1400 small pdfs (using pdftk), which were annotated using the pymupdf (fitz) library.

I get no error when I linearize the pdf resulting from the union of the 1400 pdfs **without** the annotations.

**Comment by fmeneghetti** [comment]
[pdf.json.zip](https://github.com/qpdf/qpdf/files/12395598/pdf.json.zip)

**Comment by jberkenbilt** [comment]
Thanks. I've gotten behind on qpdf, but I hope to have a chance to get caught up on recent issues soon.

**Comment by jberkenbilt** [comment]
The linearization code in qpdf is about the oldest part of the code and needs some significant rework, which I hope to do at some point. In the meantime, there are a lot of places in the code that use 32-bit integers. I'll have to review the spec to see whether that is because of bad choices I made 20 years ago or whether it is because of restrictions from the spec. It is unlikely that I will get to this soon, but I hope to get to it. There is some other effort going on to refactor the linearization code, and it might make sense to revisit that after that effort is completed.

**Comment by m-holger** [comment]
I had a quick look at linearizing big files. The problem appears to be with the 'first object offset' in the outline hint table, which is likely to be approximately the file size (if it is in part 9) and, to a lesser extent, in the shared object hint table. 

Both of these fields are 32 bit according to the PDF spec, which seems to put an upper limit to how large linearized files can get. That said, qpdf converts the offsets to int on the way, thus losing 1 bit. I think that avoiding this conversion will make all the difference for this particular file.

**Comment by jberkenbilt** [comment]
I don't have a really good way to test this, but I have included what I think should fix this issue in what I will release as 11.6.3 this weekend. I would be grateful if you could test it out. This issue will close automatically when I push the fix, but feel free to reopen if the problem is not fixed.

**Comment by jberkenbilt** [comment]
I have verified that this doesn't break linearization on large files that don't happen to have any offsets pointing past the 2GB mark.

**Comment by jberkenbilt** [comment]
@fmeneghetti 11.6.3 is out if you'd like to test. Hopefully this fix did the trick. If not, then I will need to figure out a way to construct a file that reproduces the problem. I can probably do it by just creating a file with annotations and then adding stuff to it until it's between 2 and 4 GB, perhaps by adding large attachments.
