### ISSUE TITLE
[Feature request] Invert color / grayscale

### ISSUE THREAD

**Issue by microraptor** [qpdf/qpdf#1026]
I think it would be helpful if qpdf could invert all colors in a pdf through a CLI command. So making a negative of the PDF. It could be used to make it easier to print PDFs with a dark background, or for converting PDFs with a light background and reading them on screen as a kind of "dark mode". In order to keep the colors somewhat the same a second option would be great, which only inverts the lightness in the HSL color space. So dark colors become light and vice-versa, but the hue and saturation stays the same. Perhaps also options make sense, where only the images or everything except images (text, background, etc) will be converted.

Implementing this would probably be similar to converting PDFs to grayscale, which might be useful as well in order to reduce file size.

Thank you for this great project.

**Comment by jberkenbilt** [comment]
Thanks for your kind words. It's unlikely that qpdf will get this feature. qpdf doesn't know how to render PDF files and doesn't have any facility for analyzing the colors. If someone wanted to write this, they could certainly use qpdf to get at the data along with some imaging library, but since this is not related to the structure of the PDF, it's not something that would be in scope for qpdf itself.

I'm going to close this, but feel free to ask further questions.
