### ISSUE TITLE
qpdf: operation succeeded with warning; resulting file may have some problems

### ISSUE THREAD

**Issue by kqe** [qpdf/qpdf#1027]
Hi, We run the following command to encrypt pdf files.  It goes well.

`qpdf --stream-data=preserve --encrypt  ` 

Recently we bumped into three files that the above qpdf command said:

> WARNING: test.pdf (xref stream, file position 1234567): Cross-reference stream data has the wrong size; expected = 808; actual = 812
> qpdf: operation succeeded with warning; resulting file may have some problems
> 

or

> WARNING: test.pdf (object 123 0): object has offset 0
> qpdf: operation succeeded with warning; resulting file may have some problems
>

and the exit code is 3, not 0.

But the resulting encrypted pdf look fine.

So Question: Can we safely ignore the error and assume the resulting encrypted file is just fine, if:
- qpdf exit code is 3
- it said "qpdf: operation succeeded with warning; resulting file may have some problems"
- resulting pdf file is within 10% difference in size to the original

In case you are curious, one such pdf file is produced by "HP Scanner", the other by "DynamicPDF for Java".

(By the way, qpdf has no command line to output the producer of the pdf file, right?)

**Comment by jberkenbilt** [comment]
When qpdf gives warnings and exits with code 3, it means it had to take a guess about something. Usually it is right, but sometimes it may not be. You should compare the files to see if they are correct. If qpdf didn't give any other warnings, it's _probably_ okay, but I couldn't say for sure. A mistmatch in the cross reference table size could indicate that there are some objects that qpdf didn't see, though qpdf is saying the actual cross reference table is larger than expected, which is odd. The problem is that there are lots and lots of broken PDF files, and all different PDF readers have to take their own best guesses. Sometimes qpdf correctly handles broken PDFs that other programs mess up on, and sometimes it's the other way around. There's no way to be sure without actually inspecting the files for correctness. That said, if you have a bunch of files from the same source with the same kind of warning and you determine one of them is okay, it's pretty likely that, whatever the problem is, qpdf is dealing with it, in which case you are probably safe. There are no guarantees though.

**Comment by kqe** [comment]
Thank you so much for the explanations, and suggestions.  Really appreciate!

**Comment by m-holger** [comment]
@kqe ,

> WARNING: test.pdf (object 123 0): object has offset 0

this is likely to fall into the category of "a common error handled correctly by qpdf and most other applications". If you have a sample file that you can share than that would be very helpful.
