### ISSUE TITLE
"endstream" should be preceded for PDF/A compatibility

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#103]
When qpdf is used to check any existing valid PDF/A, it will introduce one error per stream object that breaks PDF/A compliance. For example

```
qpdf "veraPDF test suite 6-2-10-t02-pass-a.pdf" out.pdf
```

will produce a file that is no longer PDF/A compliant. Acrobat reports "Indirect object endobj keyword not followed by EOL marker."

I realize that qpdf doesn't support PDF/A compliance checking but with a trivial fix it would be able to rewrite existing PDF/A files without breaking compliance. As Acrobat suggests, the issue is that the newline in front of "endstream" is required in PDF/A but optional in PDF. As usual the final \n does not contribute to /Length.

```
% Not accepted in PDF/A, produced by qpdf
begin
...any stream data...endstream
endobj
```

```
% Accepted in PDF and PDF/A
begin
...any stream data...
endstream
endobj
```

**Comment by jberkenbilt** [comment]
Agreed, this is trivial to fix and worth fixing. I'll include it next time I have a chance to work on qpdf, which will certainly be this summer if not sooner.

**Comment by jberkenbilt** [comment]
I will probably add a flag to enable this and have it be non-default behavior. The reason is that, while there is no guarantee that all versions of qpdf generate the same output on the same input and options, it is a constraint I have tried to maintain to avoid gratuitously breaking people's automated tests, caching systems, etc. In fact, changing this as a default breaks 43 test cases in qpdf's own test suite. Adding a flag to do this is trivial. I will try to do it for 7.0.0.
