### ISSUE TITLE
Requesting reconsideration of compression improvement options, eg for archival use cases

### ISSUE THREAD

**Issue by thinkpanzer** [qpdf/qpdf#1036]
qpdf is a canonical PDF processor in many workflows, including some of my personal ones. The capability I currently miss the most is allowing lossless recompression of large objects, resulting in smaller output filesize. Specifically, I'm most interested in enabling lossless jpeg compression, eg via MozJPEG (https://github.com/mozilla/mozjpeg), and lossless flate compression via zopfli (https://github.com/google/zopfli).

**Please note** that both of these implementations produce 100% compatible datastreams, decompressible by any standard jpeg- or flate-compatible decompressor, ie they produce PDF-compatible output, just smaller, at the expense of compute time.

Based on past closed issues (eg https://github.com/qpdf/qpdf/issues/68), I can also understand the desire to minimize qpdf's external dependencies.

That said, I was reminded by the recent closing of The Nib (https://thenib.com/the-future-of-the-nib/) that archive use cases are valid and deserve deliberate consideration. If one could reduce even by single digit percent the filesize of a PDF via losslessly recompressing jpegs and flated object streams, that not only is a benefit for the end-user who downloads a smaller but pixel-identical PDF, but this would also materially reduce the bandwidth cost, especially over time, of the archive delivering the PDFs, potentially allowing such an archive to operate for longer with finite funds. Such files will not be updated in the future, so generating the smallest possible PDF once is a clear benefit to everyone.

If the complexity of enabling more compressor implementations directly within qpdf is impractical, would it be possible to create a mechanism to enable such recompression via other means, eg via external process, and have qpdf integrate the result?

Thanks for considering.

**Comment by thinkpanzer** [comment]
At the risk of overstepping from the peanut gallery, a dependency on specific bytes being output from a compressor is definitely something I'd be strongly inclined to making less brittle asap. Eking even fractional percent out of flate will continue to be valuable in the future, if for no other reason than it's baked into many http client and server implementations at this point, so every literal bit saved turns out to matter at internet scale.

Fwiw, https://github.com/ebiggers/libdeflate is increasingly widely used because of its performance characteristics, especially — but not exclusively — on power- and/or cpu-constrained devices. 7-zip's flate compressor is also used in some applications where output size is being optimized for. `advzip`, part of https://github.com/amadvance/advancecomp, offers four flate libraries to choose from to recompress, eg.

I had a glance at QPDFStreamFilter.hh and before I fell down the rabbit hole of qpdf's inner workings was reminded that my days of writing production-quality C/C++ are long past. I don't understand the internals of qpdf at all, so am not equipped to opine on whether a flate or a jpeg compressor could be integrated this way.

Thanks for your quick responses, and hope that you can spend some time on this in a few months. I'm very certain that a lot of good for a lot of people will come out of being able to make both jpeg and flate as losslessly small as possible at a one-time higher compute cost.

**Comment by jberkenbilt** [comment]
You are not overstepping. I strongly agree with your points, and it is absolutely on my radar. Bear in mind that qpdf is a side project that started in 2002, so there is a lot of legacy. See #774 for some of my earlier thoughts. None of this is to push back against your comments. On the contrary, it is to assure you that you don't have to convince me -- I am right there with you. It's purely a question of time.

**Comment by jberkenbilt** [comment]
> Thanks for your quick responses, and hope that you can spend some time on this in a few months. I'm very certain that a lot of good for a lot of people will come out of being able to make both jpeg and flate as losslessly small as possible at a one-time higher compute cost.

I would likely use this myself. My employer uses qpdf for millions of pages a day, and we would definitely benefit from this.

**Comment by thinkpanzer** [comment]
Many thanks for the reassurance. Thanks also for the pointer to zlib-ng, which I'd not come across before, and which looks to be solving a similar problem to libdeflate.

Looking forward to future updates here in due course.

**Comment by rubyFeedback** [comment]
I have no stake or noteworthy opinion on this feature (neither pro nor con).

In my personal uses for foto (pictures) taken by old cameras but also digital cameras, I finally transitioned
into .avif rather than .jpeg or .png. .avif is really nice and I estimate I managed to cut off perhaps 30% on average
in total on all my old pictures and newer ones. And the quality is better than jpeg in many cases, at the least
when you have to modify it again (I modify old black white images to colour based on AI but I also do manual processing; many colour-changes by AI are just wrong, but some are super-good such as for grass/plants, these
work so much better than for human skin colour).

So, while the above does not have to do much at all with the feature request, I can understand the user's
focus on maximizing "storage efficiency" in .pdf files. Some .pdf files are small, some are mega-bloated. Many
of those who are mega-bloated come with fancy large images; others just by people who don't know what to
do (university professors trying to create .pdf files from their MS power point presentations for instance; many
of my downloads are about that).

I think if Jay ever gets to expand on qpdf, it would be kind of cool to be able to "micro-manage" some of qpdf's
workflow, such as: "qpdf, please minimize all images by about 25% or so, using any way you see fit to achieve
that". That way the dependencies could still be kept optional, but if something is available locally then qpdf
could make use of that. See pngoptimization for .png files and other tools (I don't know how PDF stores 
objects though).

Some of our use cases will be unique though. I am trying to get some kind of pdf viewer such as okular or evince
but also with the ability to remove individual pdf pages by clicking a button. I can do so via qpdf from the
commandline, but I don't quite know how to extend either okular or evince to allow for that. I need this mostly
because it is how I work with .pdf files these days: I learn the content, then I delete it (I can re-download if
need be, but mostly I am fine removing entries from .pdf files. I also keep local notes).

**Comment by jberkenbilt** [comment]
qpdf 11.7.0, recently released, can be built with different zlib implementations and will pass its test suite. It no longer has any tests that depend on a particular zlib. It should be possible to use zopfli or others as a drop-in replacement if they have a zlib-compatible API. If not, it is possible to write a pluggable implementation for the /FlateDecode filter using a different library, and as long as regular zlib can uncompress it, everything should work. As I believe that addresses this, I'll close this. If you try to use a different zlib with qpdf >= 11.7.0 and run into problems, let me know preferably by creating a new issue with the specific problem.

I know you waited a long time for this. I hope this finally meets the need.

**Comment by jberkenbilt** [comment]
To anyone following, zopfli support will be in qpdf 11.10. See https://github.com/qpdf/qpdf/issues/1323.
