### ISSUE TITLE
Difference between output.pdf AND --output.pdf

### ISSUE THREAD

**Issue by Geo-Van** [qpdf/qpdf#1041]
Hello,
Please let me ask, what is the difference between output.pdf AND --output.pdf , please, in the following example:
**-- output.pdf :**
qpdf --flatten-annotations=all  input.pdf -- output.pdf

**output.pdf:**
qpdf --flatten-annotations=all  input.pdf  output.pdf

BOTH above commands work and create an output.pdf file. 
But what is the difference between the two, please?

**Comment by jberkenbilt** [comment]
There is no `-- output.pdf`. The `--` terminates the options to `--pages`.

**Comment by jberkenbilt** [comment]
It seems that qpdf simply ignores `--` when it appears by itself. That's probably undesirable but also harmless. So there is no difference at all between your two commands.

**Comment by Geo-Van** [comment]
Thank you very much! 
So we will only use --  AFTER --pages to terminate its options.
In other cases like for example the following is not recommended to use -- output.pdf but just output.pdf
qpdf --flatten-annotations=all input.pdf output.pdf

**Comment by jberkenbilt** [comment]
Right. Basically `--` terminates some group of options for something that takes its own options. `--pages` is the main example, but also `--encrypt` and a few others use this. The command line parser uses `--` to mean to go back to parsing main options. I don't think I intended it this way, but it looks like when `--` is used when qpdf is parsing main, top-level options, it just does nothing. I don't think I'd change that now since it's harmless, and people may be relying on it in scripts. But you're right -- just use `output.pdf`, not `-- output.pdf`.

**Comment by Geo-Van** [comment]
Thank you very much!
