### ISSUE TITLE
"This Document enabled extended features"

### ISSUE THREAD

**Issue by kqe** [qpdf/qpdf#1043]
Hi, after running qpdf to encrypt certain pdf form files, then when opening it in Adobe Acrobat Reader, the users see this message:

"This Document enabled extended features in Adobe Acrobat Reader. The document has been changed since it was created and use of extended feature is no longer available. Please contact the author for the original version of this document. "

Also, it's impossible to fill in text in any fields in the form now.

I know this is because the author of the form enabled Adobe Pro's extended feature to sign the file, so qpdf's modification broke the signature.  So it's not really a qpdf's fault.

But, just in case, do you happen to have any suggestion to get around this problem?

**Comment by jberkenbilt** [comment]
You can use `qpdf --decrypt --remove-restrictions in.pdf out.pdf` to remove all the restrictions from the file. I believe the feature is imperfect at this time -- I have had reports that some files still are left with some restrictions. As you understand, there is no way for qpdf or anything else to modify the file while not invalidating the signatures. The qpdf options are intended to remove the signatures and the protections, so there's no deception or suggestion of authenticity. If you have a file that `--remove-restrictions` doesn't fully work for and you are able to share it, I can continue to improve that feature. I have been told in #1015 that the feature doesn't full work with docusign output. I haven't had time to investigate, but I will get to it. It's tricky to find all the cases since there are many proprietary ways to sign files. I will have to dig more deeply into the latest spec to make sure I've got all the edge cases that I am currently missing.

**Comment by kqe** [comment]
Thank you so much for the quick and helpful answer.  Indeed after doing this, we can fill up the pdf form now.  And at least we can choose Microsoft print to PDF option to indirectly save the result.

However when trying to fill up the form, a popup warns that we can only fill up and print, but can not save.  In fact the file security page shows a few options are not allowed, including:
- Document Assembly
- Page Extraction
- Commenting
- Signing
- Creation of Template Pages

So this must be what you described above that "--remove-restrictions doesn't fully work".  

I am so sorry I can not share the file for now.  If I obtain a version that be shared I will definitely send to you.

Thank you!

**Comment by jberkenbilt** [comment]
Great, thanks.
