### ISSUE TITLE
Consider enabling CPACK_NSIS_MODIFY_PATH to add qpdf.exe to PATH on Windows

### ISSUE THREAD

**Issue by cvrebert** [qpdf/qpdf#1054]
Currently, AFAICT, the `qpdf.exe` binary isn't added to the `PATH` when using the x64 Windows installer. This makes actual command-line usage of the tool a little bit clunkier, as one must either look up and copy-paste the absolute path of the binary when composing a command, or else perform a one-time addition of the `C:\Program Files\qpdf X.Y.Z` directory to their user's `PATH` (perhaps via clunky Control Panel).  However, the latter isn't truly one-time, due to the version number in the directory changing when periodically upgrading QPDF.

As shown circa Figure 6 of https://cmake.org/cmake/help/book/mastering-cmake/chapter/Packaging%20With%20CPack.html#cpack-variables-used-by-cmake-for-nsis , cpack can make the generated installer offer optional `PATH` modification by enabling the [`CPACK_NSIS_MODIFY_PATH` variable](https://cmake.org/cmake/help/latest/cpack_gen/nsis.html#variable:CPACK_NSIS_MODIFY_PATH). Thus, this is a feature request to please enable that variable. I would be happy to aid in any relevant installer beta-testing.

**Comment by jberkenbilt** [comment]
Great suggestion. I only know enough Windows to build qpdf and start a Linux vm. :-) I will put this in for the next qpdf release.

**Comment by rubyFeedback** [comment]
> I only know enough Windows to build qpdf

There you know more than I do!

Speaking of which: I may give it a try eventually. I have a Win10 machine on my left side
and I mostly only use it to test some stuff (ruby and java related). So I'll try to build
qpdf there and see how it goes in the coming days or weeks, perhaps straight from
github. (I added this to my local todo list, so I won't forget.)

**Comment by jberkenbilt** [comment]
@rubyFeedback There's some stuff in the README-windows.md file, and the build scripts used in CI (build-scripts/build-windows.bat as the entry point) are also authoritative.

Reminds me of back in the day....I used to say I only knew enough `vi` to configure and build `emacs`, but it doesn't work anymore since you don't need any editor to build emacs. Then I would say I only know enough Windows to run my Linux VM. Now I have to throw in "and build qpdf". (But seriously, at one time, I had survival Windows sysadmin skills, though it's now been about 9 years since I've needed those skills, and they have mostly atrophied.)

Good luck.
