### ISSUE TITLE
Asking for help decrypting a pdf file

### ISSUE THREAD

**Issue by Twinkle-Wong** [qpdf/qpdf#1055]
[bb.pdf](https://github.com/qpdf/qpdf/files/13108294/bb.pdf)
The hex key is：9E21C2E741A4910AE284888670DABD7A
The encryption dictionary is : <</Filter /Standard /V 4 /Length 128 /R 4 /O <1> /U <1> /P -4 /CF << /StdCF << /Type /CryptAlgorithm /CFM /AESV2 /AuthEvent /DocOpen >> >> /StrF /StdCF /StmF /StdCF>>

I am trying to decrypt this pdf file using Java, But there have been a series of errors, so please help me decrypt this file, and tell me the encryption mode and filling method of this pdf file, as well as how to obtain iv. It is known that this file uses AESV2 encryption. I hope you can provide the source code of cpp decryption, thank you very much. If necessary, please contact my email : h.shelter@outlook.com

**Comment by jberkenbilt** [comment]
This file uses an encryption filter called `/TTKN.PubSec`. This is the not the standard encryption filter and, as such, the file will not be usable by standard PDF viewers. The creator of the file must be using an extended, proprietary encryption technique, and most likely you will only be able open the file through the originating system. Unfortunately, the file encrypts its metadata, so I can't get any hints, and searching for TTKN.PubSec doesn't reveal any hints about who the owner might be.

**Comment by jberkenbilt** [comment]
By the way, to see this information:
* Open the PDF in a binary-aware text editor (emacs will work, no doubt others as well)
* From the end of the file, search back to %%EOF
* Immediately before that, is the trailer. Observe `/Encrypt 1105 0 R`
* Search backward for `1105 0 obj`. This brings you to the encryption dictionary, which is terminated by `endobj`
The contents of the encryption dictionary are
```
<</Length 40/SubFilter/TTKN.PubSec.s1/CF<</DefaultCryptFilter<</CFM/AESV2/Recipients[(AppendCA)]>>>>/Filter/TTKN.PubSec/StrF/DefaultCryptFilter/StmF/DefaultCryptFilter/EncryptMetadata true/R 2/V 2>>
```
In hear, you can see `/Filter/TTKN.PubSec` as well as `/SubFilter/TTKN.PubSec.s1`.
qpdf can only decrypt files with `/Filter/Standard`, and this is likely to be true of the vast majority of PDF readers. Appendix E of the PDF spec talks about extending PDF, and if you want to do that, you need a registered name, in this case `TTKN`. However I am not able to find who owns that name. Knowing that would probably point you in the right direction. Perhaps you know where the PDF came from and can already get that information.

**Comment by Twinkle-Wong** [comment]
Thank you for your answer, but I successfully decrypted using a Python library called pickepdf (which is power by QPDF)
The python code is.:
`from pikepdf import Pdf

out = open("11.pdf", "wb")
file_key = "9E21C2E741A4910AE284888670DABD7A"

Pdf.open("output.pdf", password=file_key, hex_password=True).save(out)
out.close()
`

**Comment by Twinkle-Wong** [comment]
I'm extremely sorry, the format of the PDF file I provided you above is not fixed. I will upload the file named **output.pdf** again. Could you please try decrypting this PDF file for me again

**Comment by Twinkle-Wong** [comment]
[output.pdf](https://github.com/qpdf/qpdf/files/13160627/output.pdf)

**Comment by jberkenbilt** [comment]
My guess is that there was probably a problem with your pikepdf code such that you were not seeing an error message. In any case, there is nothing I can do about this file. It is encrypted in a way that qpdf can't decrypt. It is not a limitation or bug with qpdf -- vendors are free to extend PDF by adding their own proprietary encryption filters, and tools that don't support them will not be able to open the files.

**Comment by Twinkle-Wong** [comment]
I think you may have misunderstood what I mean. bb.pdf did have the problem that the filter was not standard before, but the format of output.pdf has been repaired to standard pdf format, and pikepdf was successfully decrypted. I made sure that my python code did not have any problems, and the program did not report errors. Please try again to decrypt output.pdf, the key is: 9E21C2E741A4910AE284888670DABD7A
If possible, please add my telegram to contact you better.My tg is Shelter_wong

**Comment by jberkenbilt** [comment]
Please share the pikepdf code you used to decrypt the file. When I looked at output.pdf, it did not look like output from qpdf. I don't understand what issue you are having if you say pikepdf decrypted the file. What is there left to do? If you share your pikepdf code, maybe I can discover the disconnect.

**Comment by Twinkle-Wong** [comment]
output.pdf is from the bb.pdf repair format, which has nothing to do with his file name, I now want to implement the final decryption of the file on the Android side, so use java to write. Therefore, I need to know the encryption mode of the file, the padding method, and the iv required for AES decryption and so on. So I would like to ask how to decrypt this document using cpp, which may be a great help for me to decrypt this document using java

**Comment by Twinkle-Wong** [comment]
The py code is 
```
from pikepdf import Pdf

out = open("11.pdf", "wb")
file_key = "9E21C2E741A4910AE284888670DABD7A"

Pdf.open("output.pdf", password=file_key, hex_password=True).save(out)
out.close()
```

**Comment by jberkenbilt** [comment]
Okay, I reread this whole message. I definitely did not understand what you were asking before. Is this what you're looking for? This is the equivalent of the Python program above or the command line
```
qpdf` --decrypt output.pdf 11.pdf --password-is-hex-key --password=9E21C2E741A4910AE284888670DABD7A
```

```c++
#define POINTERHOLDER_TRANSITION 4 // suppress warning until qpdf 12
#include <qpdf/QPDF.hh>
#include <qpdf/QPDFWriter.hh>

int main() {
    QPDF pdf;
    pdf.setPasswordIsHexKey(true);
    pdf.processFile("output.pdf", "9E21C2E741A4910AE284888670DABD7A");
    QPDFWriter w(pdf, "11.pdf");
    w.setPreserveEncryption(false);
    w.write();
    return 0;
}
```
There are warnings in this file. I guess they are not issued by the pikepdf code. Maybe it changes warning flags by default or has some other mechanism to retrieve them.

**Comment by Twinkle-Wong** [comment]
Thank you very much for your reply. The ultimate purpose of this issue is to use **java** to decrypt this pdf file, but I have encountered some problems when trying to use some java libraries. Would you please give me some advice

**Comment by Twinkle-Wong** [comment]
I've tried to decrypt the file using the itext library before, but it doesn't seem to work with hexadecimal keys. So my current idea is to migrate part of the qpdf code to java, but my current problem is that I can't filter out the simplified cpp code, I hope you can provide me with a simplified qpdf library that is enough to decrypt this pdf file (meaning it needs to delete other useless classes).

**Comment by Twinkle-Wong** [comment]
![e88f01ef7ecb5fe6ab86cbb688dfc89d](https://github.com/qpdf/qpdf/assets/89621049/a4800b97-7714-4e38-83bf-df305b48005f)
I downloaded the include folder to the local, and used the code you provided, and the error was reported as shown in the figure. I guess some libraries are missing, please help to see which libraries are missing

**Comment by jberkenbilt** [comment]
I'm not sure what your platform is, but you need to link against the qpdf library. I thought that would be a given. For example

```
g++ qpdf_test.cc -lqpdf
```
You'll need to make sure you have the qpdf library and development files installed and cmake configured.

I'm happy to provide some assistance, but I think providing basic assistance on how to build C++ code is probably out of scope here. There's stack overflow and other ways to get basic help with building code.

**Comment by Twinkle-Wong** [comment]
Unfortunately, due to my limited personal ability, I still did not successfully decrypt the file using qpdf, but I am curious whether you have successfully decrypted the file, thank you for your answer

**Comment by jberkenbilt** [comment]
I don't understand what you mean. You've previously said that you did decrypt the file. Yes, I successfully decrypted the file with
```
qpdf --decrypt --password-is-hex-key --password=9E21C2E741A4910AE284888670DABD7A output.pdf /tmp/a.pdf
```
I've attached the decrypted file.
[decrypted.pdf](https://github.com/qpdf/qpdf/files/13249059/decrypted.pdf)

**Comment by Twinkle-Wong** [comment]
Yes, I successfully decrypted the PDF file, but I am using Python's pikePDF library instead of the qPDF library. What I need to do now is use Java to decrypt the file. In fact, it has been proven that my key is completely correct, so I would like to know how QPDF uses this key to decrypt PDF files. Is this key related to the owner password or user password of the PDF file? Can you provide relevant code, such as how to handle the key and how to decrypt data in the input stream. Thank you very much for taking the time out of your busy schedule to answer my questions. Thank you very much!

**Comment by jberkenbilt** [comment]
PDF encryption is fairly complex but well documented in the spec. The PDF code in qpdf is old (it's been there since the beginning, before qpdf was open source, and then enhanced later to add newer encryption schemes -- but still it's old) and references the PDF 1.7 spec mostly rather than ISO-32000. You can find the PDF spec free at https://pdfa.org/resource/iso-32000-pdf/. It was made free not that long ago (sadly after I had paid for my copy!). Encryption is described in section 7.6 of the PDF spec. I am not going to describe the whole thing here, but broadly, it works like this:

* The PDF file has an encryption dictionary (key `/Encrypt`) referenced from the trailer.
* The `/Encrypt` dictionary has keys `/R` and `/V` that specify which version of the algorithms to use
* Depending on the versions, there are keys `/O` and `/U` and, for some versions, `/OE` and `/UE`.
* Using these keys along with either the user or owner password, it is possible to extract the overall encryption key, which is what you have. I'm not aware of any software other than qpdf that can start with the key rather than the password. The password is used only to extract the key. If you have the key, that's all you need.
* Once you have the overall key, each individual stream and string in the file is independently encrypted using an object-specific key that is computed as a function of the overall key and the object ID.
* Using the object-specific key, the strings and streams are decrypted using either RSA or AES256, depending on the version. Newer formats also use CRC, meaning that there is some random data used to seed the decryption.
* There are facilities to indicate that embedded files may have different encryption from the rest of the file and to indicate whether metadata should or should not be encrypted. It is possible to extend encryption with proprietary filters as with the first file you uploaded.

Here are a few extra details:
* PDF files have an owner password and a user password.
* Older PDF encryption formats used RSA in a manner that is no longer considered secure. In those versions, the owner password was used to decrypt the user password, and the user password was used to decrypt the encryption key. Newer PDF files use AES256 encryption. In those, the global encryption key is independently encrypted using the user password and the owner password, and it is not possible to recover one password knowing the other.
* Conforming PDF viewers offer different features depending on whether the owner password or the user password was used, but qpdf is not a viewer, and for what qpdf does, it would be meaningless. Both passwords generate the same key, and qpdf doesn't treat them in different ways, though it does make available to the caller which password was used so a program could know and behave accordingly.
* At present, the qpdf API does not expose a way to get the encryption key for a particular object or to manually decrypt an individual stream. I have considered adding that feature to help with forensic analysis of badly damaged PDF files that can't be opened but may have some recoverable data. When I need to do this, I have ways of hacking around it, so I've never bothered to actually do this.

All the code in qpdf that deals with encryption is in QPDF_encryption.cc. I would refer you to https://qpdf.readthedocs.io/en/stable/encryption.html for some more explanation about encryption in PDF. The encryption algorithms used in PDF are implement in qpdf in three ways: an older "native" encryption that works fully but whose use is not recommended because that code has not had the scrutiny or performance tuning of dedicated encryption libraries, gnutls, and openssl. In my experimentation, openssl 3 performs the best with gnutls a close second. openssl 1 works but doesn't perform as well.

I would not recommend that you try to implement decryption yourself unless you are a security expert and are adept at reading and understanding detailed specifications. There is certainly Java code out there that knows how to read encrypted PDF files since plenty of people consume encrypted PDF from Java code. This is true of javascript, go, rust, Python, and just about any other language that has PDF libraries. PDF encryption is not for the novice programmer, but it's also clearly spelled out in the spec and uses only standard encryption and hashing algorithms that are readily available in all modern programming languages.

**Comment by Twinkle-Wong** [comment]
I am trying to read and understand encryption.cc, and here is my idea：

1. i found this function:
![4271699170728_ pic](https://github.com/qpdf/qpdf/assets/89621049/ae33ab22-6b98-4848-a05b-31dad3b2071f)
2. Then it gets the file source and process the password
![4291699170778_ pic](https://github.com/qpdf/qpdf/assets/89621049/c2ca6671-cf7a-49ff-b44c-753bc274e268)
3. Next, I studied the parse function and found that most of the previous ones were not very helpful to me, only the functions in the red box were more important
![4311699170864_ pic](https://github.com/qpdf/qpdf/assets/89621049/2a94cbca-20b3-4731-9a04-d5e974e674d4)
![4321699170913_ pic](https://github.com/qpdf/qpdf/assets/89621049/18c4955e-ccc2-426d-8989-e1016153dd21)
4. And then i came to the initializeEncryption function
![4361699171020_ pic](https://github.com/qpdf/qpdf/assets/89621049/4dfd8221-30d8-4d87-b83f-263cba1b2256)
5. The previous if conditional statement was not helpful to us, but the focus is still on the red arrow. I tested hex_ Decode(). It did not have any problems, which is consistent with the results output online, indicating that my thinking is not problematic until now
![WeChat6bc7126ce17b75785793c45c2f2773ba](https://github.com/qpdf/qpdf/assets/89621049/c250caec-6a53-4911-a188-3bb1d66e763d)
6. Then I thought about where the m ->encp ->encryption_ key was used，i found it finally:
![4461699171282_ pic](https://github.com/qpdf/qpdf/assets/89621049/32735ec4-6794-4311-850f-4e15c4e49032)
![4491699171349_ pic](https://github.com/qpdf/qpdf/assets/89621049/d802140a-ac20-44a3-838f-592bd25d213a)
7. But these codes already belong to qpdfwriter.cc,so I saw the following place:
![4531699171443_ pic](https://github.com/qpdf/qpdf/assets/89621049/a39e5dd2-39fd-4d96-88ec-aac6b6ea954d)
8. I think it should have obtained the encryption_key based on the key first, and then apply this encryption_key during the writing process, and then to setPreserveEncryption(false), I have looked at some more code, but I don't know how to continue. I hope to receive your guidance and help. Thank you very much!

**Comment by jberkenbilt** [comment]
Probably the function you are most interested in is decryptStream in QPDF_encryption.cc. Internally, qpdf uses the concept of pipelines. Each byte read from stream is written through a stack of pipelines. If a stream is encrypted, the code gets the specific encryption key for that stream and, based on the encryption method, creates the appropriate pipeline and adds it to the pipeline stack. There's something similar for encryption in QPDFWriter, and there's also something for strings. Maybe you can find those knowing what to look for.

**Comment by Twinkle-Wong** [comment]
May I ask if QPDF provides log viewing function? I would like to know if the decryption process is in progress

**Comment by jberkenbilt** [comment]
What you need to do is read through the public header files. You can run qpdf in a debugger or build it yourself and add print statements. I am going to stop answering questions that are basic software development issues. I'm sure you can understand.

**Comment by Twinkle-Wong** [comment]
I would like to ask how to read the encryption dictionary of a PDF. As you mentioned earlier, starting from the end of the file, you can read eof, but isn't eof the end of the file? Here is my Java code, and its error is shown in the figure. If possible, can you tell me how QPDF reads the encryption dictionary
![3355088841](https://github.com/qpdf/qpdf/assets/89621049/2da4e885-73d0-49ea-867e-f93dd7a649d2)

**Comment by jberkenbilt** [comment]
I'm sorry, I am not able to provide any more assistance with this.

**Comment by Twinkle-Wong** [comment]
all right , thank you very much
