### ISSUE TITLE
Can you please add "remove watermarks" option to QPDF

### ISSUE THREAD

**Issue by Nokia808** [qpdf/qpdf#107]
Hi.
1st of all I would like to thank you very very much for this super-excellent PDF tool.

Can you, kindly, add new option to "remove waterwarks" from PDF ? This option, if added, should not result in removal of contents other than watermarks.

Best.

**Comment by jberkenbilt** [comment]
Hi again. As you probably can guess, this would not be something I would add to qpdf. It is possible to use qpdf manually to remove watermarks if you know PDF format very well. Writing a general tool to remove watermarks would be hard though because there are so many ways they can be added. Some of them might not be possible to remove programmatically, such as if the watermark actually modifies images in the file.

**Comment by convexset** [comment]
Love `qpdf`. Latest thing I've used it for was (text) watermark removal: https://gist.github.com/convexset/28abc9c7be261954507ac705cbf64099
