### ISSUE TITLE
Question: is it possible to set minimum stroke ?

### ISSUE THREAD

**Issue by CanadianHusky** [qpdf/qpdf#1106]
I suspect what I am about to ask is not directly possible with the CLI Interface, but maybe I missed something in the documentation that I have been reading. So I would like to ask the expert.

My goal is to modify stroke thickness of line/path/curve objects in a PDF. These are `l,c,v,y,h,re` operators in the content stream.
The stroke thickness is set with manipulation of the graphics state and `w` operator.
PDFs created out of my control are created with 0 stroke and therefore print or preview too thin and faint. The goal is to thicken stroke values that are below a certain point.

does a command like 
`qpdf --setminstroke=x in.pdf out.pdf`
 exist at the moment, or can be done with a trick of any of the existing commands ?

I am very familiar with the PDF Syntax and the Adobe spec and am aware that QPDF does not have knowledge of content streams. So I suspect the answer will be no. 

At the moment I can do the above described process manually with a few steps thanks to the brilliant decode functions of QPDF, which brings me to my second question.

My current steps:
1- convert the original file to QDF Form using `--qdf`
2- modify output using own code and make changes as needed to the pdf syntax and repair the file back to a valid state using fix-qdf.exe
3- recompress streams using `qpdf --compress-streams=y in.pdf out.pdf`

This works well and reliable, but not as fast as a native C++ if it was done directly in QPDF.

My question: what are the recommended CLI arguments to convert and compress a QDF form file back into the most efficient, compressed plain PDF format. Is just `--compress-streams=y` enough ?

I can do the same processing using --json-output (manipulate) --json-input as well but I find QDF form is easier in my case. However the capability to do lossless back and forth pdf>json>pdf conversion is brilliant too.

Best Regards,

**Comment by jberkenbilt** [comment]
Thanks for your kind words. Something like what you're asking for will probably never be possible from the qpdf CLI. Getting into interpreting the meaning of content streams is not a direction I want to take qpdf into, so your intuition about this is correct. To answer your specific questions, from native C++ code, there are several different ways you can approach this. I'll first answer your specific questions, then make a few suggestions on how you might approach this.

> My question: what are the recommended CLI arguments to convert and compress a QDF form file back into the most efficient, compressed plain PDF format. Is just --compress-streams=y enough?

You don't need any arguments. The default behavior is that `qpdf` compresses any uncompressed streams, so a simple `qpdf in.pdf out.pdf` is all you need.

To do this in native C++, you have a handful of options. The most straightforward way to do it, particularly based on your current solution, would be to just get the stream data with [QPDFObjectHandle::getStreamData](https://github.com/qpdf/qpdf/blob/395bc7f8252d2438c8ee8b26cc430f154e179d1a/include/qpdf/QPDFObjectHandle.hh#L993), which returns a buffer. Then you can do what you want with that and call [replaceStreamData](https://github.com/qpdf/qpdf/blob/395bc7f8252d2438c8ee8b26cc430f154e179d1a/include/qpdf/QPDFObjectHandle.hh#L1090) with a new buffer. Just be careful about the possibility that a page's contents may be an array of streams rather than a single stream. There are methods in [QPDFPageObjectHelper](https://github.com/qpdf/qpdf/blob/main/include/qpdf/QPDFPageObjectHelper.hh) that can help you with this.

If you wanted to be a little more fancy, you could use a content token filter. This is something where qpdf will do the lexical portion of reading your token stream and send you each token. You can pass the token through, modify it, insert new tokens, buffer them up and write something completely different, etc. The [examples/pdf-filter-tokens.cc](https://github.com/qpdf/qpdf/blob/main/examples/pdf-filter-tokens.cc) example shows you how to do this. That example inverts strings and replaces color with grayscale by interpreting the token stream and modifying it on the fly. I suspect you could relatively easily build what you are trying to build using this. I'm not sure it would be any easier or more efficient than just grabbing the content stream, tweaking it, and writing it back. It might use less memory, and it would transparently handle things like if the page contents are an array of streams instead of a single stream.

My suggestion is to look through [QPDFPageObjectHelper](https://github.com/qpdf/qpdf/blob/main/include/qpdf/QPDFPageObjectHelper.hh) and read the comments, then check examples to see if there is anything that may be a good starting point.

Feel free to reach out with additional questions!

**Comment by CanadianHusky** [comment]
Thank you very much for the detailed guidance. I can take it from here.
