### ISSUE TITLE
Can you kindly add "ability to insert PDF file within other PDF file" ?

### ISSUE THREAD

**Issue by Nokia808** [qpdf/qpdf#112]
Hi.

I suggest to add this ability for QPDF. Let me explain: I have A.pdf which composed from 100 pages. I like to insert B.pdf within A.pdf to be part from it's body, let we say after page 5 or before page 7 of A.pdf

This should be work whether B.pdf is multipages PDF or composed from just single page, so that:

- user can specify where B.pdf should be inserted "after" or "before" page x of A.pdf
- all pages of B.pdf will be added to A.pdf to be located in their sequence between "x" page & next page to "x" of A.pdf if specify "after" & between page x & previous page to "x" if specify "before"
Best

**Comment by jberkenbilt** [comment]
You can already do this. It would look like this:

`qpdf A.pdf --pages A.pdf 1-5 B.pdf 1-z ./A.pdf 6-z A-new.pdf`

This is saying to start with A.pdf and create a new file with pages 1 through 5 of A.pdf, all the pages of B.pdf, and pages 6 to the end of A.pdf. The little ./A.pdf hack is an unfortunate limitation right now and has to do with how qpdf is mapping command line arguments to internal objects. I should fix it, but it has an easy workaround that is documented. Specifically to pull pages from the same file more than once, you have to give alternate names to access the file.

**Comment by jberkenbilt** [comment]
I'm going to go ahead and close this, but feel free to reopen or ask further questions. Thanks!

**Comment by Nokia808** [comment]
Thank you for your kind answer. But this - as I remember - not documented in read me of QPDF, isn't it ?

O.K if I like to insert a pdf let we named test1.pdf (whether it composed from multi-pages or single pages) inside a 2nd pdf called test2.pdf composing from 500 pages, so that test1.pdf as a whole added just after page 11 of test2.pdf (become located between pages 11 & 12 of original test2.pdf), what is the exact command to perform this ?

Best

**Comment by jberkenbilt** [comment]
It's not in the README, but it is in qpdf --help and in the manual. See section 3 of [the manual](http://qpdf.sourceforge.net/files/qpdf-manual.html) where it talks about page selection options. It's a little complex. Sorry about that.

For this new case:

```
qpdf test2.pdf --pages test2.pdf 1-11 test1.pdf 1-z ./test2.pdf 12-z -- new.pdf
```

In other words, take the first 11 pages of test2, all page of test1, and 12 to the end of test2 (referenced by a different path) and write the output to new.pdf.

**Comment by jberkenbilt** [comment]
I'm going to try to fix the thing that makes you have to specify the file in different ways if you grab more than one range of pages from it.

**Comment by jberkenbilt** [comment]
Actually, while what I said will work, I misspoke about the limitation. The limitation of having to duplicate the file with a different path only applies when you want the same page multiple times from the same file. So in your case, this more straightforward command will work:

```
qpdf test2.pdf --pages test2.pdf 1-11 test1.pdf 1-z test2.pdf 12-z -- new.pdf
```

You don't need ./test2.pdf the second time. You can just call it test2.pdf both times since you're not copying any page twice.

**Comment by Nokia808** [comment]
Hi. Thank you very much for explanations ! Very powerful program !

Just to issue 2 things:

1) regarding: 
qpdf test2.pdf --pages test2.pdf 1-11 test1.pdf 1-z test2.pdf 12-z -- new.pdf

Can I specify different pages ranges like:
qpdf test2.pdf --pages test2.pdf 6-11 test1.pdf 15-20 test2.pdf 12-59 -- new.pdf

2) regarding ./test2.pdf is it used in this example:
qpdf test2.pdf --pages test2.pdf 6-12 test1.pdf 15-20 ./test2.pdf 12-59 -- new.pdf

due to page 12 duplicated ?

**Comment by jsx97** [comment]
Hello, Jay.

> So in your case, this more straightforward command will work:
>
> ```
> qpdf test2.pdf --pages test2.pdf 1-11 test1.pdf 1-z test2.pdf 12-z -- new.pdf
> ```

Could you explain what is the purpose of using `qpdf test2.pdf...` instead of `qpdf --empty...`? I tried the following commands, and the resulting PDFs seem to be visually same:

- `qpdf --empty --pages input1.pdf 1-5 input2.pdf input1.pdf 6-z -- output.pdf`
- `qpdf input1.pdf --pages input1.pdf 1-5 input2.pdf input1.pdf 6-z -- output.pdf`

**Comment by jberkenbilt** [comment]
The first file is considered the "primary input." Document-level data (bookmarks, layers, links, metadata, many other things) are preserved from the primary input. Handling document-level data better with splitting and merging is the next frontier for qpdf, but it's very complex, and progress is slow. For simple files that just contain pages with visual contents, they will be visually the same. Some files, like those with layers, may present differently. If the files have hyperlinks, you may find that the links only work on the first file. As a rule, you will get better results if you give whatever you consider as the main file rather than `--empty`, but in many cases, either will work.

**Comment by jsx97** [comment]
Many thanks!

**Comment by jsx97** [comment]
And as far as I understand, there is no difference between the following two?

```
qpdf input1.pdf --pages input1.pdf 1-3 input2.pdf input1.pdf 4-r1 -- output.pdf
qpdf input1.pdf --pages . 1-3 input2.pdf . 4-r1 -- output.pdf
```

**Comment by jberkenbilt** [comment]
Correct, those are identical.
