### ISSUE TITLE
qpdf issue  when trying to merge files (ver 6.0.0)

### ISSUE THREAD

**Issue by rajankarthik** [qpdf/qpdf#115]
Hi,

I am trying to use qpdf to merge pdf files into one file using c++ /cli  (to create a wrapper for .net ). I ran into problems with the merge and so looked up the samples and found the same issue with them as well.  The issue seems to be around pages . When we use getAllPages(); to try and iterate over them, it seems to be initialized correctly but any attempt to access it fails. This could of course be a problem with the pdf I am using or something else that is environmental (we use visual studio 2008, on windows 10) or just my limited knowledge of c++

QPDF inpdf;
inpdf.processFile(infile);
std::vector<QPDFObjectHandle> const& pages = inpdf.getAllPages(); // this works and returns pages
int pageno_len = QUtil::int_to_string(pages.size()).length();  // this fails and sometimes i get vector<T> too long or nothing but it always fails.

btw: I think the pdf file is ok as qpdf can write it out with no problems it fails only when trying to access the pages.
Thank you.
Karthik

**Comment by jberkenbilt** [comment]
I'm sorry for having missed this issue for the last 6 years :-( but I don't understand the question. I think it may be a c++ programming issue. In any case, I am closing this because of its age, but if there is a problem, feel free to reopen or create a new issue. Since this was created, there have been many improvements to qpdf's API, so there may be better ways to accomplish whatever you are (where) trying to do here.
