### ISSUE TITLE
Allow Password Input From Standard Input for Increased Security

### ISSUE THREAD

**Issue by im7mortal** [qpdf/qpdf#1188]
## Description
Currently, the `qpdf` utility requires the password to be entered as part of the command line argument (`--password=password`). This method poses a security risk as the password can be stored in the shell command history or might be visible to others on shared systems.

## Proposed Feature
It would be highly beneficial for security purposes if `qpdf` could allow the password to be read from standard input (stdin). This change would enable scripts and users to provide passwords in a more secure manner, avoiding the need to expose sensitive information in the command line or scripts.

## Current Behavior
When trying to decrypt a PDF with `qpdf`, the command line syntax requires explicitly specifying the password in the command, as shown below:
```bash
qpdf --decrypt --password=password in.pdf out.pdf
```

This method outputs an error if tried without explicitly mentioning the password:

```
qpdf: --password must be given as --password=password
```

##  Suggested Solution

I suggest implementing a feature where qpdf can accept passwords piped from another command or inputted directly into the command prompt without showing up in the command history. This could potentially be implemented with a flag like `--password-stdin` which when set, makes qpdf read the password from stdin.

##  Temporary Solution Until Feature is Implemented

For those needing a secure method to input the password currently, the following workaround can be used:
```bash
read -s -p "Enter PDF Password: " PDFPASSWORD && qpdf --decrypt --password="$PDFPASSWORD" input.pdf output.pdf && unset PDFPASSWORD
```

**Comment by m-holger** [comment]
@im7mortal  , have you read the documentation for the `--password` and `--password-file` options at https://qpdf.readthedocs.io/en/stable/cli.html#general-options? I believe this covers what you are suggesting, but if it doesn't can you please explain.

**Comment by jberkenbilt** [comment]
@im7mortal As @m-holger points out, there is already a way to do what you want by writing the password to a file, so I don't think I will add a separate feature for qpdf to do this.

**Comment by cout** [comment]
The documentation states, "filename may be - to read the password from standard input, but if you do that the password is echoed and there is no prompt".  It would be useful to prompt for passwords without echoing verbatim.  Users are likely to put an encryption password on the command-line rather than to put it in a file.  Users that do put the password into a file must be careful to correctly set file permissions.

The workaround proposed by @im7mortal is also required for encrypting a pdf, because AFAICT there is no `--password-file` equivalent for user and owner password.

Consider also the caveats of putting a password into an environment variable.  Though I am skeptical of the risk, myqsl no longer recommends putting a password into the `MYSQL_PWD` environment variable, because "some versions of ps include an option to display the environment of running processes".

**Comment by im7mortal** [comment]
Yes.

`--password` leaves the password in the history.
`--password-file` leaves the password on the filesystem.

These are not alternatives to using stdin.
I can reopen the issue if you think it’s worth reconsidering. I only used qpdf once, and it wasn’t critical for me.

**Comment by m-holger** [comment]
@jberkenbilt  , I feel we should reconsider this

**Comment by jberkenbilt** [comment]
Yes, I agree. I've resisted because of making it hard to support across different operating systems, but it's not a good excuse.
