### ISSUE TITLE
Feature request: Add arbitrary comments/headers in PDF files to support formats such as PCLm

### ISSUE THREAD

**Issue by sahilarora535** [qpdf/qpdf#121]
`PCLm` is a strict subset of `PDF` which requires the following format in the first two lines of the file:

```
%PDF-VERSION_NUMBER
%PCLm-VERSION_NUMBER
```
For instance, it can be:
```
%PDF-1.3
%PCLm-1.0
```
For adding additional headers, `QPDFWriter` object has a function `setExtraHeaderText(std::string const&)`. When used, the `PCLm Magic Number`(line 2 in expected output) gets added to the third line of the file rather than the second line. The resulting file looks like:
```
%PDF-1.4
%BINARY_ENCODING
%PCLm-1.0
```
There is no such function in **QPDF** to support extra headers in specific lines. Since `PCLm` is a strict subset of `PDF`, it would be great if this feature of adding extra header in an arbitrary line in a `PDF` file can be introduced.

This issue is currently being faced here: https://github.com/sahilarora535/cups-filters/issues/2

**Comment by jberkenbilt** [comment]
Based on our many conversations offline, I'm inclined to not actually do this since I think we'll just handle PCLm as a separate case. Let me know if you think that's not reasonable. I think it's right though because adding extra comments like this is usually not useful outside the context of some specialized purpose that would require other code changes anyway.

**Comment by tillkamppeter** [comment]
OK, let us go the way as we have settled on with Sahil.

**Comment by jberkenbilt** [comment]
Closing issue as we have determined a different way to satisfy the requirement.
