### ISSUE TITLE
Read json from standard input

### ISSUE THREAD

**Issue by qooxzuub** [qpdf/qpdf#1211]
Would it be possible for the following to read json input from stdin?

```bash
qpdf --json-input - output.pdf
```

The discussion in #54 indicates that it isn't practical to read a pdf file from stdin, and one reason given concerns the xref table at the end of the pdf file.

I have the impression that qpdf doesn't rely on the xref table when reading JSON input. So I wonder if this feature might be practical. 

(Also, as qpdf can output json to stdout, taking json input on stdin would be pleasingly symmetrical.)

My use case is that I am calling qpdf from some rust code, essentially as follows. Note the use of two temporary files.

```rust
// call qpdf --json-output input_pdf and capture output
let json = Command::new("qpdf").args(["--json-output", input_pdf]).output()?;
write_to_tempfile(&json, "/tmp/tempONE.json");

// call qpdf --show-pages --json-input /tmp/tempONE.json and capture output, and extract page data
let page_data = Command::new("qpdf").args(["--show-pages", "--json-input", "/tmp/tempONE.json"]).output()?;
let page_data = extract_page_data(page_data);

// transform the json
let json2 = transform_the_json(json, page_data);
write_to_tempfile(&json2, "/tmp/tempTWO.json");

// call qpdf --json-input --object-streams=generate /tmp/tempTWO.json output_pdf
Command::new("qpdf").args(["--json-input", "--object-streams=generate", "/tmp/tempTWO.pdf", output_pdf]);
```

Both temporary files could be avoided if qpdf could read json from stdin.

**Comment by jberkenbilt** [comment]
As you correctly surmised, qpdf doesn't rely on a cross-reference table with JSON, but it still lazily loads stream data from the original JSON or the data files, so it is still not possible to read qpdf JSON from standard input. Bear in mind that qpdf streams can provide their data as external files, which further complicates this. When qpdf uses a JSON file as standard input, it reads all the objects into memory, and for each stream data, is uses a StreamDataProvider object to retrieve the stream data from a stored offset in the JSON file or from the external file containing the stream data. A single JSON is free to intermix those two ways of storing stream data, and qpdf fully supports that.

Looking at your example above, there a few ways I can see to possibly improve it, though the way you're doing it is okay.
1. Use something like the `tempfile` crate to create more security temporary files with unpredicatble names, which avoids clashes if you run this more than once concurrently. (Maybe you know this and are hard-coding the temporary file names for simplicity in your example.)
2. Use `--show-pages` on the original input instead of on the JSON output. qpdf is more efficient at reading regular PDF files than JSON files, and since `--json-output` preserves object IDs (unlike QPDFWriter), you can mine information from the original PDF. Alternatively:
3. Instead of using `--show-pages`, you can pass `--json-key=pages` as an additional parameter to the first command. The information about the pages will be included in t he JSON output in the `"pages"` key. You can mine the information from there, which is probably easier from the rust code and has the advantage that the syntax is guaranteed to be stable.

So I would suggest
```rust
// call qpdf --json-output input_pdf and capture output and page metadata
let json = Command::new("qpdf").args(["--json-output", "--json-key=pages", input_pdf]).output()?;
write_to_tempfile(&json, "/tmp/tempONE.json");

// transform the json, reading page data from `"pages"`, which is ignored by --json-input
let json2 = transform_the_json(json); // modify to look at "pages", not just "qpdf"
write_to_tempfile(&json2, "/tmp/tempTWO.json");

// call qpdf --json-input --object-streams=generate /tmp/tempTWO.json output_pdf
Command::new("qpdf").args(["--json-input", "--object-streams=generate", "/tmp/tempTWO.pdf", output_pdf]);
```
with the added enhancement of using better temporary files.

**Comment by qooxzuub** [comment]
Thank you for clarifying the situation with json input.

Thank you also for the code suggestions, they are very helpful. I didn't think of using ```--show-pages``` on the first run and wasn't aware of ```--json-key=pages``` at all.
