### ISSUE TITLE
FileName mask with dash

### ISSUE THREAD

**Issue by perverez** [qpdf/qpdf#1213]
Hey. Hey,

I want to search all files by the following mask: "515209.pdf" (exact number) or "515209 *.pdf" (space after number) or "515209-*.pdf" (dash after number). If I search for just a number or a number with a space, everything is fine, but if I add a number with a dash, I get an "invalid range syntax" error.

Is there a solution to specify a mask with a dash?

Thank you. P.

**Comment by jberkenbilt** [comment]
I'm not sure what you mean by "mask" or what you are trying to do when you say "search". Is there some qpdf command that you are running that's giving you this error? There are a few places in qpdf that parse page ranges. If possible, you could prefix with `./`, but to be able to answer your question well, I'd need to understand a little better what you are trying to do and what command you are running.

**Comment by perverez** [comment]
Hi,

example:
qpdf.exe --empty --pages "515209 *.pdf" "515209-*.pdf" "515209.pdf" -- OutFile.pdf

**Comment by perverez** [comment]
Example without formating:
`qpdf.exe --empty --pages "515209 *.pdf" "515209-*.pdf" "515209.pdf" -- f:\515209.pdf`

**Comment by jberkenbilt** [comment]
Try
```
qpdf.exe --empty --pages "515209 *.pdf" "./515209-*.pdf" "515209.pdf" -- OutFile.pdf
```

**Comment by jberkenbilt** [comment]
Also from 11.9.0, you can use non-ambiguous arguments like `--pages --file=...`, but that won't work with wildcards. You'd have to expand the wildcards in advance.

**Comment by jberkenbilt** [comment]
Actually....I think what is probably happening is something related to wildcard expansion. My guess is that, if there aren't any files that match `515209-*.pdf`, that literal string is being passed as an argument to qpdf. qpdf's behavior is to first try parsing as a numeric range. If that fails but a file exists with that name, then it treats it as a file. If there is no file, then it falls back to treating it as a range and gives whatever error the range parsing gave. It's potentially confusing behavior, but it does it this way because of qpdf's ability to optionally omit the range. Anyway, I think what you are tripping over is interaction between shell wildcard expansion and qpdf's page CLI parsing code.

**Comment by perverez** [comment]
Hi,

thank you for your answer. First I will create an exact list of files to pass as parameters. I will not use the wildcard.

P.

**Comment by jberkenbilt** [comment]
Great. I'll close this. Feel free to reopen if you have additional problems with this.
