### ISSUE TITLE
fraud detection and document comparison

### ISSUE THREAD

**Issue by arad2022** [qpdf/qpdf#1232]
I want to detect any changes in the pdf file. How can I do that?

In the first step, I have an original pdf file and the modified version, and I want to detect changes by comparing these two files.

It would be great if you can help me in this matter.

**Comment by Sicos1977** [comment]
If you only want to know that a file has changed you can even do something simple like calculating an MDF5 hash

**Comment by arad2022** [comment]
> If you only want to know that a file has changed you can even do something simple like calculating an MDF5 hash

No. I want to know what is the change and which part of the file has changed

**Comment by jberkenbilt** [comment]
This is going to be much harder than you think. There are tons of ways a PDF can change without affecting meaningful content. I think qpdf will not have the capabilities you need to do this kind of comparison. Even if you are just interested in structural changes at the PDF syntax level, it will be very hard because simple changes may cause objects to be renumbered and will definitely cause offsets in the file to change. That said, in an absence of a more detailed use case description, it's hard to say for sure. But I can't really think of a use case beyond testing qpdf where qpdf would be able to meaningfully compare PDF files and give an answer other than either "same" or "different".

**Comment by arad2022** [comment]
> This is going to be much harder than you think. There are tons of ways a PDF can change without affecting meaningful content. I think qpdf will not have the capabilities you need to do this kind of comparison. Even if you are just interested in structural changes at the PDF syntax level, it will be very hard because simple changes may cause objects to be renumbered and will definitely cause offsets in the file to change. That said, in an absence of a more detailed use case description, it's hard to say for sure. But I can't really think of a use case beyond testing qpdf where qpdf would be able to meaningfully compare PDF files and give an answer other than either "same" or "different".

I have Invoice Receipts and I want to detect any changes on them. In first step I have original and modified version but in the real world I don't have access to the original one.

For my first use case how can I compare two pdf files and detect any tampered?
I have one pdf file and I want to detect any changes on that and then find out what is the change on the pdf to detect any fraud. What is your suggestion?

**Comment by jberkenbilt** [comment]
Probably this problem is out of scope for qpdf, and the specifics are going to depend on a lot of things. If these are invoices, would it make sense to extract the text and compare? Are any of the invoices created in a manner that doesn't allow text extraction? What kinds of tampering are you trying to detect? I can imagine, for example, someone might use an annotation or overlaid image on an invoice with native text to make an invoice visually show one value but have the text extract to another value. A very sophisticated user could even go as far as adding a new font subset that could be used for specific characters that would replace the glyph for one number with another. These seem pretty extreme, but my point is to illustrate that detecting tampering at the PDF level in a way other than cryptographically verifying that the file has not been modified at all is going to be pretty hard. This is why my thought ends up going to either using something like digital signature or some kind of checksum validation to make sure the files are identical, or else comparing rendered images. If there are certain modifications that you allow, you will have to take these into consideration. The point I have to emphasize is that you are not going to be able to achieve these things using qpdf or any other tool that only looks at PDF structurally.

Have I gone overboard here? Perhaps I'm still not understanding your use-case. Bottom line: in the general case, tamper detection is likely to be based on some cryptographic approach, like digital signature or computation of a secure hash. Detection of visual changes will require something that can render PDF files.

**Comment by arad2022** [comment]
> Probably this problem is out of scope for qpdf, and the specifics are going to depend on a lot of things. If these are invoices, would it make sense to extract the text and compare? Are any of the invoices created in a manner that doesn't allow text extraction? What kinds of tampering are you trying to detect? I can imagine, for example, someone might use an annotation or overlaid image on an invoice with native text to make an invoice visually show one value but have the text extract to another value. A very sophisticated user could even go as far as adding a new font subset that could be used for specific characters that would replace the glyph for one number with another. These seem pretty extreme, but my point is to illustrate that detecting tampering at the PDF level in a way other than cryptographically verifying that the file has not been modified at all is going to be pretty hard. This is why my thought ends up going to either using something like digital signature or some kind of checksum validation to make sure the files are identical, or else comparing rendered images. If there are certain modifications that you allow, you will have to take these into consideration. The point I have to emphasize is that you are not going to be able to achieve these things using qpdf or any other tool that only looks at PDF structurally.
> 
> Have I gone overboard here? Perhaps I'm still not understanding your use-case. Bottom line: in the general case, tamper detection is likely to be based on some cryptographic approach, like digital signature or computation of a secure hash. Detection of visual changes will require something that can render PDF files.

You made it so hard. Please check this [tool ](https://www.qtrac.eu/diffpdf.html) for pdf comparison. I need something like that. I want to use some opensource libraries like qpdf to do that. If you have any solution related to that let me know or any experience with this library or other libraries for this goal

**Comment by jberkenbilt** [comment]
I don't know of any open-source tool that can do that. That doesn't mean there isn't one. It's definitely not something qpdf can do as it requires rendering of the PDF, which is not an intended feature of qpdf. If there is an open-source tool that does that, it probably uses ghostscript or something based on poppler libraries to do the rendering.

I probably shouldn't have wasted time explaining why it's hard without having a better understanding of your goal. Providing the link above would have clarified your ask. I think we can close this issue since this is not a problem that falls within the scope of qpdf, and this is not a general PDF tools forum.
