### ISSUE TITLE
Segmentation fault (core dumped) (qpdf version 10.6.3) 

### ISSUE THREAD

**Issue by GreyPerson2** [qpdf/qpdf#1250]
>Version: qpdf version 10.6.3
>OS: Linux Mint 21.3 x86_64 

I download QPDF from Software Manager, i was using QPDF from that before, but now, it just tell me
> Segmentation fault (core dumped)

This is my command:

> qpdf XXX.pdf --encrypt owner-password=9IsFMdpJkkaYiD4wXtw8RnGctOZ1lRhI4lvY0DHC 256 -- --modify=none --print=none ~/XXXX.pdf

Or:

> qpdf ~/Documents/VPS/XXX.pdf --encrypt owner-password=9IsFMdpJkkaYiD4wXtw8RnGctOZ1lRhI4lvY0DHC --bits=256 -- --modify=none --print=none XXX.pdf

It will be:
> qpdf: unrecognized argument --bits=256 (encryption options must be terminated with --)

I am not tech Savvy person enough who can build this software, sorry about that.

**Comment by jberkenbilt** [comment]
10.6.3 is very old. My guess is that the executable and library you have are in conflict. Perhaps you have multiple versions of qpdf installed with something having manually messed around with the shared library links? The `--bits=256` syntax was not present in 10.6.3, and if you want to use the new syntax with a current version, you will need `--owner-password=....`, but you are missing the dashes. Anyway, I suspect the issue is an installation problem.

**Comment by GreyPerson2** [comment]
>  but you are missing the dashes.

Can you give me an example how command should look like? I will be so thankfully about that.

And i was figure out alternative for me, [AESify](https://github.com/digidigital/AESify?tab=readme-ov-file)  now, atleast it work lil bit.
