### ISSUE TITLE
Best approach to use with Java

### ISSUE THREAD

**Issue by vivekvara** [qpdf/qpdf#1318]
I wanted to use QPDF in my Java project. What would be the best way to do it? I could not get any reference for the same.

**Comment by jberkenbilt** [comment]
It really depends on what you're trying to do. If you're just trying to do basic stuff like encrypting or linearizing files that can be done through the command-line, I wouldn't discount integrating with the shell. If you want tighter integration, you could consider JNI or [Project Panama](https://openjdk.org/projects/panama/). For work that is basically CLI-level stuff, you can use the qpdf JOB API, which allows you to give command-line arguments or JSON representations of qpdf operations. For lower-level access, there is a C API that exposes some, but not all of qpdf's functionality. Most higher-level abstractions are not exposed, but basic operations and nearly all the library's capabilities are available, and you have some ability to work with individual objects. You can use QPDF JSON (different from the job JSON I mentioned earlier) to convert PDF to a JSON format that is specific to qpdf but completely encodes the PDF file and can be bidrectionally mapped to PDF. This allows you to do low-level manipulations of PDF using JSON. I am not aware of any Java integrations with qpdf, but that doesn't mean they don't exist.

To dig into any of these more:
* https://qpdf.readthedocs.io/en/stable/library.html#using-qpdf-from-other-languages
* https://github.com/qpdf/qpdf/blob/main/include/qpdf/qpdfjob-c.h
* https://github.com/qpdf/qpdf/blob/main/include/qpdf/qpdf-c.h
* https://qpdf.readthedocs.io/en/stable/qpdf-job.html
* https://qpdf.readthedocs.io/en/stable/json.html

I hope this helps. There are native Java-based libraries for working with PDF, such as [itext](https://itextpdf.com/), which I think may be why there's not so much about using qpdf with Java. Anyway, I hope this information is useful.

**Comment by vivekvara** [comment]
@jberkenbilt This helps a lot! We’re planning to use qpdf for encryption while handling a high volume of concurrent requests, with an average PDF size of ~2MB. Our approach involves running the qpdf CLI in a Docker container using a Debian 12 base image and invoking the CLI through Java’s ProcessBuilder.

Do you foresee any risks or challenges with this setup, particularly regarding:
- Performance: Managing multiple concurrent requests spawning CLI processes.
- Security: Potential vulnerabilities or misconfigurations in this architecture.

Your expert advice would be greatly appreciated!

**Comment by jberkenbilt** [comment]
I created a production system at a previous that invoked a C++ program linked with the qpdf library from a go program using the shell in a similar way, and we ran over a million pages a day through it. I also did it using a docker image based on the latest debian stable release. I think this is a good way to go. These days, shell invocation is pretty cheap, and integration through the shell as you have described it has several advantages:
* It is loosely coupled; you can upgrade qpdf without modifying your code, particularly since I take great care to ensure that I don't break qpdf's CLI without a very good reason and clear documentation
* Running qpdf in a separate address spaces means that a (very unlikely!) crash of qpdf won't bring down your Java program
* It is simple -- no JNI/FFI/pipes etc.

I suspect you will find qpdf's performance to be very good in this regard. qpdf is a small, native executable with a very fast startup time, and it has always been a high-performance tool. Recent versions, thanks to some great work by co-maintainer, are much faster than earlier versions. Any small overhead from invocation of qpdf through the shell will be far outweighed by the improved efficiency of qpdf over some other solutions.

So, if you're content with the functionality of qpdf's CLI, then I think the approach you are describing is a good approach.

**Comment by vivekvara** [comment]
Thanks for your valuable inputs @jberkenbilt
