### ISSUE TITLE
How to rotate page(s) ?

### ISSUE THREAD

**Issue by Nokia808** [qpdf/qpdf#132]
What is (are) command(s) can be used to rotate page(s) of PDF ?

**Comment by jberkenbilt** [comment]
This is not an operation supported by qpdf.

**Comment by Nokia808** [comment]
Is there plan to add it ? It is related to structure not to contents as it appear to me (may be I'm wrong).

**Comment by jberkenbilt** [comment]
This is a frequently requested feature, and it's not hard to add. I'll strongly consider adding it for 7.0.0.

**Comment by Nokia808** [comment]
Thank you very much !

**Comment by jberkenbilt** [comment]
In qpdf 7.0.0, it will work like this:
`qpdf in.pdf out.pdf --rotate=[+|-]angle:page-range`
The `--rotate` option may be repeated. `angle` may be 90, 180, or 270. If preceded by `+` or `-`, the angle is added to or subtracted from the original rotation. Otherwise, the rotation is set.

For example, `qpdf in.pdf out.pdf --rotate=+90:2,4,6 --rotate=180:7-9` would rotate pages 2, 4, and 6 clockwise by 90 degrees from whatever rotation they originally had and would force the rotation of pages 7 through 9 to 180.

**Comment by saber7165** [comment]
@jberkenbilt, how can I rotate only the odd or even pages?

**Comment by jberkenbilt** [comment]
@saber7165 From version 9.1.0 on, you can use `qpdf in.pdf out.pdf --rotate=90:1-z:even` or `qpdf in.pdf out.pdf --rotate=90:1-z:odd` to specify even or odd pages.

**Comment by su-ex** [comment]
@jberkenbilt 
Why do you exclude 0 (without + or -) as angle? That would be useful to force re-set each page's rotation.

**Comment by su-ex** [comment]
And if it's possible to rotate depending on the current rotation, it should be possible to find out the current rotation from each page.
I mean it would be nice if there was a command to list the current rotation of each page, something like:

page 1: <page 1's current angle>
page 2: <page 2's current angle>
page 3: <page 3's current angle>
...

**Comment by jberkenbilt** [comment]
@su-ex Thanks for your comments/questions. It would be possible to implement your suggestions based on the value of /Rotate in the page dictionary, and that might be a useful thing to do, and certainly adding 0 as an allowable value is a good idea. Note that it will only affect the rotation that is done by changing the page metadata. There is no guarantee that the actual page content itself isn't drawn in a rotated fashion, in which case resetting the rotation to 0 won't necessarily make the page look upright. You could extract rotation information for each page using json mode right now with a little code. I'm not sure I would be inclined to add something to the CLI specifically for this purpose, but I could certainly add rotation to the json for pages, which would make it easier to extract. Right now, you'd have to use the pages information to get the page objects and the objects information to get the rotation. If rotation were in the pages object, you could do it with a simple jq command.

Please open a new issue for this suggestion. Comments on a closed issue will not be tracked, and I don't want to reopen the issue because I like to not track multiple things with one issue. I can open the issue myself, but I thought you might prefer to open it yourself. If I don't hear anything, I will open the issue. I'll leave the github email flagged in my inbox as a reminder to do this.

**Comment by ilovefreesw** [comment]
Can we rotate PDF by specific angle such as 30 degree or 45 degreee?

**Comment by jberkenbilt** [comment]
@ilovefreesw Comments posted to closed tickets are likely to be overlooked. At this time, qpdf can't do rotation by other than multiples of 90 degrees because the rotation uses the page metadata, and that's all it supports. I have plans in the relatively near future to add a different way to do transformations on a page that would make this possible, but it is not possible yet, and I'm not 100% certain that I will add that. I already have that specific item (performing arbitrarily matrix transformations) on my to-do list, so you don't need to create a separate issue, but if you want to follow the gory details as I work toward fully designing the feature, you can create a separate issue requesting this feature, and I will tag it.
