### ISSUE TITLE
Encryption with 256-bit key

### ISSUE THREAD

**Issue by teadawg** [qpdf/qpdf#144]
If pdf is encrypted with 256-bit key and empty owner-password, it can be viewed with Preview app (Mac) **without** password. Adobe Reader asks for password.

`--encrypt "secret" "" 256 --`

If pdf is encrypted with 128-bit keys and empty owner-password, Preview app asks for password to view.

`--encrypt "secret" "" 128 --use-aes=y --`

(Version: 6.0.0)

**Comment by jberkenbilt** [comment]
This is not a bug with qpdf. This behavior is actually specified by the PDF specification. In the PDF spec version 1.7, it's algorithm 3.3, step 1. In the ISO standard, it's item a of algorithm 3 in section 7.6.3.4. It states that if the owner password is empty, the user password should be used in its place. This algorithm applies to 128-bit and 40-bit encryption. In those cases, the file is encrypted with a key generated by the user password, and the user password is encrypted using the owner password.

For 256-bit encryption, the user and owner passwords can be used independently to decode an encryption key used for the whole file, and there is no special case around empty owner passwords.

What qpdf and many other readers do is to attempt an empty password if the file is encrypted and no password is given. Perhaps Adobe Reader doesn't attempt the empty string as an owner password.

**Comment by RobK88** [comment]
Thank you for the explanation.  Unfortunately, I suspect many users of qpdf do not realize that encrypting a pdf using AES-256 encryption with only a user password (and a blank or null owner password) will create very insecure PDF's (unlike PDF's encrypted using 128-bit AES or RC4).  How can such PDF's be secure when many PDF readers including Apple's Preview will open it up, decrypt it and display it without asking for a password!

I recommend that qpdf generate a warning message when encrypting PDF's using AES256 whenever the owner password is blank or null informing users that the resulting encrypted PDF is not very secure since the owner password has not been specified.

Since this is closed, I will open up a new feature request.

**Comment by RobK88** [comment]
Please note that it appears that one can create an encrypted PDF using AES256 encryption with only specifying a user password using other tools (like the free PDFEncrypt for Windows) that will NOT open in Apple's Preview without specifying the user password.

And if you open such a PDF up using Adobe Reader (or use pdfinfo from poppler), one can verify that only the user password is set but not the owner password (or permissions password).  

I really do not know how tools like PDFEncrypt create encrypted PDF's using AES256.  But it appears to be a more secure way than the way that qpdf currently employs.  You may want to see how others do it. 

In my view, if the official PDF spec is brain dead, it probably does not make sense to follow it!

**Comment by RobK88** [comment]
It looks like PDFEncrypt sets the owner password to the same value as the user password when encrypting a PDF using AES256 whenever the owner password is not specified.  As a result, one must enter a password whenever one tries to open such a PDF using any PDF Reader (including Apple's Preview).  

I also find it interesting that Adobe Reader shows that the user password is set BUT not the owner password (which is not technically true) for a PDF encrypted in this way.

I tried encrypting a PDF using qpdf with AES-256 encryption when both the user and owner password are set to the same non-empty value.  Adobe Reader also shows that the user password is set BUT not the owner password (which is not technically true).

I recommend that qpdf set the owner password to the same value as the user password whenever the user fails to provide an owner password (or if the owner password is empty) when qpdf is encrypting a PDF using AES-256.  Otherwise, the encrypted PDF's will NOT be secure at all since they can be opened up in various PDF Readers including Apple's Preview.

**Comment by tillmon** [comment]
@RobK88 did you read [Encryption](http://qpdf.sourceforge.net/files/qpdf-manual.html#ref.encryption)? The last paragraph explains your problem.

**Comment by RobK88** [comment]
Thanks.  Yes, the docs do explain that one can create a PDF with a blank or empty password using qpdf.  No doubt qpdf is a very powerful tool.  

But my point is trying to protect the average user.  If one creates an encrypted PDF using 128bit AES encryption with a user password and an empty owner password, the resulting encrypted PDF is secure (as long as you used a good password).  All the PDF readers (including Apple's Preview) will require a password before decrypting and opening the PDF.  But the minute you try to encrypt the same PDF using AES256 encryption, the resulting PDF will be encrypted BUT not secure at all if the owner password is left blank.  Some PDF Readers like Apple's Preview can open it up without requiring a password at all!  This is NOT obvious.  I found out about this quirk by mistake.

The developer, Jay,  is just following the crazy PDF spec.  But to protect the average user, there should be at least a WARNING when one tries to encrypt a PDF using AES256 when the owner password is left empty.  (e.g.  "The encrypted PDF is NOT secure when owner password is empty".).  Better yet, prevent the user from even creating such an encrypted PDF using AES256 unless the user specifies an over-ride flag on the command line (e.g. insecure-pdf=y).  

This issue only applies to PDF's encrypted using AES256 encryption due to the way the PDF spec is written.
