### ISSUE TITLE
qpdf can't merge more than "ulimit" for open files

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#154]
Command line `qpdf` can't merge (or otherwise work with) more than `ulimit -n` files, that is, the maximum number of file descriptors per process.

In some workflows it's helpful to create single page PDFs and merge them all as a final step. Since a 250 page PDF is not uncommon and ulimit is 256 on macOS, one can actually hit this wall in practice.

This appears to be ultimately due to the requirement that `copyForeignObject()` (and thus `addPage()`) requires any source files to remain open – the only solution is to create temporary  files to divide and conquer.

**Comment by jberkenbilt** [comment]
I don't think I'll address this for 7.0.0, but I think I could probably make qpdf close and reopen files as an option that could be automatically enabled by the command-line tool in this case.

**Comment by jberkenbilt** [comment]
This will be fixed for 8.1, which I hope to release today or tomorrow.

**Comment by jberkenbilt** [comment]
The behavior of this fix will change for 8.2.1. By default, this functionality will kick in if > 200 files are given, but it can be explicitly turned on or off with the `--keep-files-open=[yn]` flag. The reason is that the performance impact of this change is very high for networked file systems where the open/close file  overhead is high.
