### ISSUE TITLE
[Packaging request] Please provide a pre-built AppImage binary for QPDF

### ISSUE THREAD

**Issue by KurtPfeifle** [qpdf/qpdf#160]
I want to request an automatically built [AppImage](https://appimage.org/) package for QPDF.

I'm aware that QPDF currently does not release binaries at all, because it would be too much work to provide all the different packaging formats for different distros.

However, AppImage packages work on multiple distros, older and newer alike. Actually, AppImages aren't even "packages" in the same sense as other software packages. They bundle everything that is required into one file (which to the outside world appears as an ELF binary, but inside it is mostly an ISO file system tree). When an AppImage is run (even from a USB thumb drive), it is able to auto-mount itself to a mount point in */tmp/* and then run the binary from there (without unpacking).

The most basic principle of the AppImage format is: `"1 file == 1 application"`. Contrary to what the first reading of their website may lead one to believe (*"So this is for Desktop / GUI applications only?"*), AppImages work very well for CLI tools too. <sub>*(I've successfully tested AppImages made from the `ippsample` software, provided by the ISTO Printer Working Group [PWG] for prototyping and testing IPP Everywhere [Internet Printing Protocol] software.)*</sub>.

The `"1 file == 1 application"` makes it very easy for users to make use of the software:

1. Download + save 1 file only.
1. Make it executable.
1. Run it (from whereever you stored it).

The `"1 file == 1 application"` makes it also very easy for developers to provide their software to their audience:

1. An AppImage runs on most Linux distribution without change.
1. Different versions of a software may be used side-by-side (important for testers / developers / reviewers / trainers).
1. Even officially un-released versions of the software can be easily made available to those who love to run (or have to test) the "bleeding edge".

It would be easy to integrate the automated build of an AppImage via Travis upon every single Git commit by you.

I'm pretty sure that @probonopd, the lead AppImage developer will help to setup an automatic workflow for QPDF (maybe even prepare a pull request that you only need to test + accept).
<sub>(After all, even Microsoft now builds [AppImages for their PowerShell 6.0.0 Betas](https://github.com/PowerShell/PowerShell/releases), capable to run on multiple Linux distributions.)</sub>

Implementing this would help many users who want to run the latest QPDF release, but can't get hold of it because their Linux distro of choice distributes only older versions.

----

<sub>(In case you accept and implement this, I volunteer to prepare + publish an online tutorial about QPDF on my [ASCIInema channel](https://asciinema.org/a/145735) :)  )</sub>

**Comment by probonopd** [comment]
> I'm pretty sure that @probonopd, the lead AppImage developer will help to setup an automatic workflow for QPDF (maybe even prepare a pull request that you only need to test + accept).

Done. Let me know if you have questions or issues regarding it. Would be glad to see this merged.

**Comment by KurtPfeifle** [comment]
Hey, thanks @probonopd !
Boy, that was fast!

I downloaded your AppImage and tested it and made a little @asciinema cast about it (@sickill: ping!). See here:

[![asciicast](https://asciinema.org/a/145824.png)](https://asciinema.org/a/145824)

You may need to zoom out a bit from your browser window to see it all, since I started with too large a terminal window.

**Comment by jberkenbilt** [comment]
> (In case you accept and implement this, I volunteer to prepare + publish an online tutorial about QPDF on my ASCIInema channel :) )

If you do that, I would like to/be willing to review it.

**Comment by jberkenbilt** [comment]
I have every intention of accepting this. See my comments/questions on #161.

**Comment by KurtPfeifle** [comment]
> *"If you do that, I would like to/be willing to review it."*

I'll gladly let you review it. 👍 
Once I've gotten round to start with it, I can upload the first drafts to asciinema.org and send you the "private" URI which will enable you to view it.

**Comment by jberkenbilt** [comment]
I'm aiming for a qpdf 8 release soon. I'm going to see if I can finish this before then.

**Comment by jberkenbilt** [comment]
This is in master now. Can you check it out? I have not done anything about deploying it anywhere official. I will, at least, put the appimage on sourceforge with my other release, but I guess we need to include it in AppImageHub. I'm not sure how to do that.

**Comment by probonopd** [comment]
👍 I can include it in AppImageHub if there is a download link to the AppImage, preferably on GitHub Releases. https://github.com/probonopd/uploadtool can help you upload it there.

**Comment by probonopd** [comment]
The download from https://travis-ci.org/qpdf/qpdf/builds/342925880#L3124 appears to be working on my local Xubuntu 16.04 machine.

**Comment by jberkenbilt** [comment]
> I can include it in AppImageHub if there is a download link to the AppImage, preferably on GitHub Releases. https://github.com/probonopd/uploadtool can help you upload it there.

I've always done my releases from sourceforge, though I could possibly use github releases. You may or may not have noticed that I had the .travis.yml output a sha512sum of the app image to the console. That way, when I download it, I can verify that it's the right image. Does anything care about the name of the image? If I renamed it to something that included the qpdf version number instead of the sha, would that be fine? I can't see any indication that anything actually cares what the name of the file is. As for signing the file, my plan was just to include its checksums in the checksums files and sign that like I do for all the other releases. I wasn't completely clear from our earlier discussion whether signing the app image is a "thing" as is the case with some other package types, or whether I just sign it in the way I would sign the source tarball or the Windows binary downloads.

I'll try to find the answers to these questions, but my final questions are
* Can I rename the image `QPDF-x.y.z-x86_64.AppImage` where `x.y.z` is the semantic version number? I'm certain that the answer is yes since we are already renaming the file to include the git sha.
* Do I sign the AppImage in some way other than just providing a traditional .sig file? I'm not talking about mechanics here but about result. I know how to manually sign stuff or how to automate the signing.
* What are the advantages of putting it on AppImageHub?
* I think I can use github releases, but is putting it on sourceforge okay too, or should I upload to github releases as well?

**Comment by jberkenbilt** [comment]
One more question: I added a new icon. How can I see it? What software displays the icon? Sorry if this is a dumb question. My desktop consists of emacs, xterms, and xfce-panel, but I'm not using a graphical desktop environment. I am running under Xubuntu, but I don't know how look at the AppImage in a way that its icon would display.

**Comment by probonopd** [comment]
> Can I rename the image

Yes, `QPDF-x.y.z-x86_64.AppImage` would be a great name.

> Do I sign the AppImage in some way other than just providing a traditional .sig file? 

`appimagetool -s, --sign   Sign with gpg2` ([more information](https://github.com/AppImage/AppImageKit#appimagetool-usage)) will put a signature __inside__ the AppImage. It can be verified with the `validate` command line tool and may be used by the optional `appimaged` in the future. It does not hurt to provide a traditional `.sig` in addition, although the AppImage tools will not use that.

> What are the advantages of putting it on AppImageHub?

Getting more users, and appearing in software centers and "app stores" that use AppImageHub data.

> I think I can use github releases, but is putting it on sourceforge okay too, or should I upload to github releases as well?

Both are OK, but GitHub Releases makes it easier to parse using the GitHub API and get the latest version programmatically.

> I added a new icon. How can I see it? What software displays the icon?

The icon is used for the menu entry that is generated by the optional `appimaged` daemon, as well as the file icon for the AppImage file itself, also currently generated by the optional `appimaged` daemon.

**Comment by jberkenbilt** [comment]
Thanks for your responses. I think, starting with 8.0.0, I will put my releases on both sourceforge and github. I would completely move off sourceforge, but it is still the case that more people find things there than github, especially for people who want binaries. Github is still primary geared at developers, at least as far as I can tell. But I've done a quick spike, and I can definitely put my files in a github release. I'm using my own "tool" that I use to interact with github APIs rather than your upload tool since I have an already established convention for my tags, etc.

I'm not sure what to do about signing. I am absolutely not putting my private key in travis in any way, protected/private or otherwise, and I don't think I want to bother with creating a secondary signing key. What I may do is have the appimages that are generated by travis be unsigned and just go to transfer.sh, and I may use my local release creation process to create a signed app image locally and have that be the official one that goes into my official releases. It's not exactly a fully automated release pipeline (which is part of what I do for my day job), but I don't have the right machinery for secrets management in place to fully automate what I do.

Where I think I will leave things is as follows:
* Starting with qpdf 8, I will include local generation of a signed AppImage along with the bunch of other files I generate. I can use the same build script that travis runs locally. I have definitely tested this case. I will add a flag to make it signable, and I will pass that flag when I build locally but not from travis. For people who want to consume the AppImage from travis, they can verify the sha512sum in the output. I don't feel a need to support long-term downloads, so the 2 weeks things stay on transfer.sh is fine.
* Starting with qpdf 8, I will upload all my artifacts, including the signed AppImage, to github in addition to sourceforge.

Thank you so much for doing most of the work in making this a reality. This additional delivery package will make life easier for a lot of people. Now I will have a good answer for the occasional emails I get from people who are trying to run newer versions of qpdf on older linux distributions. I'm not too worried about stuff with an older libstdc++ than Ubuntu 14.04 at this point.

**Comment by jberkenbilt** [comment]
Sorry, one last question. Can the AppImage be called `qpdf-x.y.z...` instead of `QPDF-x.y.z...`? If I change the case, do I have to change it in the desktop file? I'm guessing I use lower-case without changing the desktop file. I will see if I can figure out what to do on my system to have the experience a user would have.

**Comment by jberkenbilt** [comment]
For now, I'm changing the name in the desktop file to `qpdf` instead of `QPDF`. I may just leave it that way unless I'd be breaking some convention by doing so.

**Comment by probonopd** [comment]
According to https://github.com/qpdf/qpdf/blob/master/README.md, the name of the application is "QPDF". We recommend the filename to reflect the application name. Why do you think that is a bad idea? On the Mac, no one would ever have the idea to make all applications lowercase...

**Comment by jberkenbilt** [comment]
> According to https://github.com/qpdf/qpdf/blob/master/README.md, the name of the application is "QPDF". We recommend the filename to reflect the application name. Why do you think that is a bad idea? On the Mac, no one would ever have the idea to make all applications lowercase...

So, I guess I'm not moved by arguments about what the README says because I kind of wrote that. :-) I don't consider the case of the word to be part of the application name. The name of the command-line tool is `qpdf`, and the name of the packages all use lowercase. I notice that I do often use all uppercase in the manual, but the only thing I'm pretty careful about is not using `Qpdf`. I tend to use it in all caps at the beginnings of sentences or in titles and all lower-case in other places.

Anyway, my concern here is more about file names....if the AppImage has an all uppercase QPDF in it, it makes it stand out in a disproportionate way. But ultimately, my biggest concern is that qpdf look like it belongs in whatever ecosystem is part of. I don't want it to look like a visitor from some other land. Browsing through AppImages, I see all lowercase would be an anomaly, so I'll go back to QPDF. Thanks for indulging me in this discussion.

**Comment by KurtPfeifle** [comment]
I have the impression that Apple on macOS has a convention where they tend to spell CLI tools and packages as all lower case, whereas were a GUI is involved they use CamelCase or other uppercase-involving spelling.

When I started to work on the AppImage improvements I took it that the lower-case spelling was "officially" qpdf (hence my #xx) because of me also using it as a lower case CLI all the time, and because the GitHub project is spelled like that too. Only later I consciously recognized that there are QPDF occurrences in the docs.

In any case: it's up to you what you prefer for the AppImage file name. Every spelling "works"...

----

@probonopd , @jberkenbilt:

P.S.: Can you please have a look at my latest AppImage test builds sporting the extended AppRun script as soon as you can spare a few minutes?
https://github.com/KurtPfeifle/qpdf-appimage-testing/releases

**Comment by probonopd** [comment]
> I have the impression that Apple on macOS has a convention where they tend to spell CLI tools and packages as all lower case, whereas were a GUI is involved they use CamelCase or other uppercase-involving spelling.

Correct. That is the macOS convention. I am following it for _my_ Linux GUI applications (uppercase name) and command line tools (lowercase name), too - but I realize it's not a common convention in the Linux world.

**Comment by probonopd** [comment]
> Can you please have a look at my latest AppImage test builds sporting the extended AppRun script 

Looking good to me on a quick test. :+1:
