### ISSUE TITLE
unable to acquire crypt context when user not signed into Windows

### ISSUE THREAD

**Issue by mikeelston** [qpdf/qpdf#163]
I am running QPDF from a web application in IIS to encrypt PDFs.
`"qpdf.exe" --encrypt SECRET SECRET 256 -- "input.pdf" "output.pdf"`

The AppPool is running as a specific user.  If I am connected to the server through RDP using the same user as the AppPool. encrypting works. 

If the user does not have a active Windows session it fails with 
`unable to acquire crypt context`

**Comment by jberkenbilt** [comment]
Thanks for reporting. I have no idea how to fix this or test it as I pretty much only use Windows for creating the Windows build of qpdf. I'll leave this open. Maybe someone with more Windows development knowledge can supply a solution.

**Comment by eesheesh** [comment]
I suggest that you store the return value of GetLastError() and include it in the text of the exception thrown in https://github.com/qpdf/qpdf/blob/1e52d338223a744003136f90cca3bf6a549e1946/libqpdf/SecureRandomDataProvider.cc#L75 (instead of just checking it in https://github.com/qpdf/qpdf/blob/1e52d338223a744003136f90cca3bf6a549e1946/libqpdf/SecureRandomDataProvider.cc#L57). That way we can check what error it failed with, find it in [the API docs](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379886.aspx), and try to fix it.

**Comment by mikeelston** [comment]
thanks,  I'll see if I can't get a build going on windows with the additional debug info included.

**Comment by jberkenbilt** [comment]
I'm closing this because the inclusion of the error message is done in #286 which I am about to merge. See #286 for status. The fix will be in qpdf 9.

**Comment by Cloudmersive** [comment]
Was there any resolution to the underlying issue (not the error message)?

**Comment by jberkenbilt** [comment]
@Cloudmersive Thanks for #387.
