### ISSUE TITLE
Build on Ubuntu 14.04

### ISSUE THREAD

**Issue by wmbutler** [qpdf/qpdf#168]
I couldn't get this to configure or build from the latest release tag, however, I dound it on sourceforge and was able to get it working with this order of operations. In particular, the `make install` failed to place the library in a usable location.

```
# Build qpdf from scratch
cd ~
sudo apt-get -y install libjpeg-dev
wget https://downloads.sourceforge.net/project/qpdf/qpdf/7.0.0/qpdf-7.0.0.tar.gz
tar xvfz qpdf-7.0.0.tar.gz
cd qpdf-7.0.0/
./configure; make; sudo make install
sudo ln -s /usr/local/lib/libqpdf.so.18 /usr/lib/libqpdf.so.18
```

**Comment by jberkenbilt** [comment]
As it happens, right now, there are no differences between the latest release tag and 7.0.0, so you're good. Building from a pristine checkout requires some additional steps and additional dependencies. These are documented in the top-level README.md file. The procedure you've outlined is fine though -- perhaps not absolutely optimal, but it will do the job and can also co-exist peacefully with the qpdf that will be installed in 14.04 to support printing.

I'm going to close the ticket because there's no actual bug here, but feel free to comment if you need additional clarification.
