### ISSUE TITLE
Error: getStreamData called on unfilterable stream

### ISSUE THREAD

**Issue by hobbsi** [qpdf/qpdf#171]
Error "getStreamData called on unfilterable stream" while converting PDF file:
https://spectreattack.com/spectre.pdf

**Comment by jberkenbilt** [comment]
Thanks. I can reproduce this, so I should be able to at least make it produce a reasonable error message and recover. Thanks for the report and for providing the file.

**Comment by jberkenbilt** [comment]
I have fixed the error condition so that files like this in the future will produce a reasonable error message. In this case, the problem is that the xref stream is compressed with a predictor function that is not supported, but it will be very easy to add. This is the first example file I've seen with this, but this example will enable me to fix this for 7.1.0 which I am hoping to release this weekend.

**Comment by jberkenbilt** [comment]
qpdf 7.1.0 will be able to handle this file. Thanks very much for the report. I'll be pushing changes to master soon that include the fix.
