### ISSUE TITLE
discussion of enhanced AppImage

### ISSUE THREAD

**Issue by KurtPfeifle** [qpdf/qpdf#181]
In *"man fix-qdf"* the synopsis section states:

>     qpdf < infilename > outfilename

Shouldn't this rather read as

>     fix-qdf < infilename > outfilename

?

----

<sup>(I'm currently working to prepare a pull request for the creation of an improved version of a QPDF AppImage, which includes access to its manpages and other documentation and provides an easier discoverability of all its internal functions. That's when I noticed the above small flaw...</sup>

**Comment by jberkenbilt** [comment]
Thanks for catching it just in time for 8.0.0. :-)

**Comment by jberkenbilt** [comment]
I will hold off on releasing until I get your AppImage pull request. I'm probably a few days away best case anyway as I still have docs, and building my releases is still manual because of all the Windows binaries.

**Comment by jberkenbilt** [comment]
I just pushed a few changes to master, so please make sure your pull request includes my latest push. Thanks.

**Comment by KurtPfeifle** [comment]
My PR will include the following major changes:

* Enhanced and extended custom AppRun script with the following major features:
    - Implement a '--usage' parameter for the AppImage which helps new users to familiarize with various ways to work with it and with QPDF as a CLI in general
    - Let 'fix-qdf' and 'zlib-flate' work as "sub-commands" (not only as symlinks) to the AppImage
    - Support running the payload also when extracted into an AppDir (after running the AppImage with `--appimage-extract` the AppDir is in './squashfs-root/')
    - Support to list and display embedded manpages, PDF, HTML, READMEs, licenses and binaries (invoke AppImage with '--usage' or '--list-{pdf,html,man,readme,license}' to see them all)
    - Prepared it for future embedding of additional binaries or helper scripts (currently tested by embedding 'env', 'busybox'  and 'less' -- to be removed again if this is not useful)

* The QPDF logo is now scaled up for the 512x512 icon category (using the PNG version since I'm not sure if SVG works on all distros -- need to inquire with @probonopd)

* Added support for 'AppStream' metadata (a FreeDesktop.org "standard" which unfortunately isn't very easy to follow or validate because of its frequent changes and inconsistent tooling)

* Added comment block at start of and many comments into 'appimage/build-appimage' for the benefit of casual users who happen to run it locally on their cloned Git sources

Grab my current AppImage build here:

* https://github.com/KurtPfeifle/qpdf-appimage-testing/releases

Please test it and see what remains to be improved or should be changed.

Now I need to figure out how to create the pull request from my modified fork...

**Comment by jberkenbilt** [comment]
I'm glad you like the logo. I'm happy with it too. I sketched out a bunch of things quite literally on the back of an envelope. This one appeals to my minimalistic tastes, is easy to hand-code in PostScript (which is what I did), and grabs your eyes and makes them naturally follow the lines. Also, all the spacing is set up mathematically to create uniform spaces. I generate the 128x128 png from the svg using `convert`, so I can change it to generate a 512x512 icon easily. I had the svg naturally be 128x128 because I thought it worked best when included in html using markdown image tags, but whatever works is fine.

Regarding a pull request, if you want, just send me the name of your branch or whatever. I can handle the details. I virtually never merge pull requests because I almost always end up tweaking something.

Regarding your other suggested changes, I glanced through your branch, and it looks really good, though there are a small handful of things I'd like to change. Either I can accept your branch whenever you are ready and tweak it, or we can collaborate and you can get it in shape. The best way to work would be for you to create a pull request, which you can do by just clicking on the `New pull request` button:

![a](https://user-images.githubusercontent.com/997128/36383433-1fae7b62-155a-11e8-88f3-cc19b02f7c0f.png)

From there, I will comment on the pull request on things I'd like you to consider changing. When you think it's ready to go, you can tag me. I will squash all your commits and merge them either onto master or onto a branch thus preserving your commit with you as author. Then I will make any additional tweaks I need to make.

I just changed the name back from qpdf to QPDF based on discussing with probonopd, so you'll unfortunately have to once again rebase off my latest master. I'd like to not commit the 512x512 png since it can be generated with ImageMagick trivially as is already done with the 128x128 png. I notice you are including the raw .so file. That's only required for linking, which is why I removed it. The so.n file is the one that's needed for runtime.

My convention is to update the version number in the code as the last step before release. I would only want to include the version number in the appimage name for an official release. Right now, for example, master still has 7.1.1 as the version but the code is not binary compatible with 7.x. I will bump to 8.0.0 and update the shared library info right before I release.

If I continue to manually build the official, signed AppImage, I will probably use a docker image based off of trusty. I will want to update my README-maintainer notes to indicate that. The fact that you check in the script is good as it will prevent me from forgetting to do that.

I'm excited about your contributions here. Thank you for helping to make qpdf better. This is the dream of every open source author, but I never imagined how much external help would come.

**Comment by KurtPfeifle** [comment]
- My last two AppImage builds were lower-cased already
- I noticed you hand-coded the PostScript version (and I appreciate that too :-)
- I used your PS logo source to also let Ghostscript create a PDF (not committed) and two scaled up PNG versions (one with white, one with transparent background). These needed some parameter tweaking to get them centered onto the canvas. I can dig out the exact commands I used an note them in a comment somewhere.
- The .so file's relevance wasn't exactly clear to me and was a thing I wanted to ask you about anyway. So now I know...
- I included the 7.1.1 in the name (actually, it's automatically created and inserted by running s.th. like *`'qpdf --version | grep "qpdf version" | awk '{print $3}''`*) because with "bleeding edge" AppImages I want to have a rough indication on what stage of the source development they are based on. (I use a few more AppImages which are CLI tools -- as it happens, I'm also preparing a PR for the ImageMagick folks [here](https://github.com/KurtPfeifle/ImageMagick/releases) who will soon offer IM as a binary AppImage too...).
- I'll extend the *`README-appimage.md`* a bit as soon as I have some more time to work on it.

**Comment by jberkenbilt** [comment]
@KurtPfeifle Okay, I'm going back to `qpdf` in lowercase. It's what I prefer. Sorry for all the back and forth. I'll keep it lower-case unless there is a strong reason not to have it be lower-case.

You can just change the build-appimage to use convert to generate the 512x512 in the way I was generating the 128x128 and then just omit copying the svg to the image if you want. That's better than committing the 512x512 png.

Any ideas on when you'll get this done? I'd like to push a release out in time for the Ubuntu 18.04 feature freeze which is just a few days away.

**Comment by jberkenbilt** [comment]
Regarding your image, it seems fine to me, though it means the AppImage will now support some modes of operation that are different from the regular distribution, such as the subcommands. As long as `qpdf zlib-flate ...` does not work but `qpdf-x.y.z-x86_64.AppImage zlib-flate` does, I'm fine with it. I'm not sure `--usage` is good....how will anyone know it's there? Can you hook it into `--appimage-help` or have it be called something like `--appimage-usage`? I know that could clash with a future appimage flag, but it's more obvious that `--appimage-*` are flags that only work in the appimage, and I don't want the appimage to behave too differently from the base command.

**Comment by probonopd** [comment]
> I virtually never merge pull requests because I almost always end up tweaking something.

There is an option to let the receiver of pull requests make changes to the pull request before merging. (Just saying because I find that to be a useful GitHub feature.)

**Comment by KurtPfeifle** [comment]
@jberkenbilt:

Ha-ha... :-)     
I just uppercased everything again (well, IIRC it was 4 spots in 1 file) for my most recent AppImage build (which includes your other recent upstream changes). I must have mis-understood some earlier comments of you and thought that you wanted it uppercase.

Whatever we end up with, for the AppImage name side to be changed isn't much effort.

Next point:

- `'qpdf zlib-flate'` (or `'qpdf fix-qdf'`) *should* work...
    + ...either if the AppImage's name itself is also `qpdf`,
    + ...or if the AppImage's name is `$whateveryoulike`, but a symlink named `qpdf` points to `$whateveryoulike`
- `'zlib-flate'` (and `'fix-qdf'`) direct invokations should work...
    + ...either if symlinks called `zlib-flate` and `fix-qdf` are pointing to `$whateveryoulike`
    + ...or file copies of the AppImage exist under these names (which prolly no one in his right mind would seriously consider).

        ![Screenshot of output for command 'zlib-flate.ai' (no additional flags](https://user-images.githubusercontent.com/4747960/36390610-f7545ebc-15a3-11e8-85ed-7f0cdaa0ac27.jpeg "Screenshot of output for command 'zlib-flate.ai' where 'zlib-flate.ai' is a symlink to a file named 'QPDF-7.1.1-git.71ee41c-x86_64.AppImage'") 
<sup>(Hover mouse pointer over image to see caption...)</sup>

The additional sub-command feature I only implemented in order to avoid fiddling with symlinks for every fresh download and new version. (Of course I could download to a fixed local name every time, or proxy-symlink to a fixed name.... but I like to have different versions of the same software around (which do neither mess with my systems' installations nor with each others'), bleeding edge "nightlies" as well as "stable" released versions, for testing and comparing and other purposes, so AppImages fit the bill perfectly. So sub-commands (for software which includes multiple binaries) appear to me to be the most convenient way of handling these...

I'm open for using a flag name different from `'--usage'` for the thing it does. You are right in that there should be emerging a sort of "standard" flag for any separate help hints which *ANY* custom AppRun in the future may want to provide to its users. An `'--appimage-...'`-prefix will have to be blessed by @probonopd and the AppImage development team (which has a better-than-zero chance to get, I guess).

BTW, the `'--help'` for the AppImage will work just like `'qpdf --help'` does; *THAT* is still supported by my AppRun (just as `'--usage'` also tells, see further below). In general, if we'd be guilty of destruction of functionality which is present in regular distributions instead of enhancing/extending and making it easier to use, manage and "not-install" it, we'd be cursed by many:

![Screenshot of output for command 'qpdf.ai --help'](https://user-images.githubusercontent.com/4747960/36390047-d30c83ec-15a1-11e8-8133-71f5e971ab18.jpeg "Screenshot of output for command 'qpdf.ai --help' where 'qpdf.ai' is a symlink to a file named 'QPDF-7.1.1-git.71ee41c-x86_64.AppImage'") 
<sup>(Hover mouse pointer over image to see caption...)</sup>

If one re-names or sym-links the AppImage for local usage simply to/as `'qpdf'` it will be very hard for most users to discover any differences in behavior. Here is a screenshot of my own symlink's output  which I named `'qpdf.ai'`:

![Screenshot of output for command 'qpdf.ai --usage'](https://user-images.githubusercontent.com/4747960/36389136-77a44344-159e-11e8-8186-160811c46a7d.jpeg "Screenshot of output for command 'qpdf.ai --usage' where 'qpdf.ai' is a symlink to a file named 'QPDF-7.1.1-git.71ee41c-x86_64.AppImage'") 
<sup>(Hover mouse pointer over image to see caption...)</sup>

So I don't think the modes of operation of the AppImage are *VERY* different from the regular distributions. 

> *"`--usage`[...] ....how will anyone know it's there?"*

Well... we'll have to tell and teach them :-)      
Just as with AppImages in general -- they are not *yet* universally adopted in the Linux world :-)

**Comment by jberkenbilt** [comment]
I guess I don't want anyone thinking that `qpdf zlib-flate ...` or `qpdf fix-qdf ...` is valid. My suggestion would be wire it up so that if `$(basename $0)` is one of the executables, including qpdf, don't allow subcommands, but if it is something else, do. Or just drop the subcommand thing entirely and tell people to make qpdf, fix-qdf, zlib-flate symlinks to qpdf-current-x86_64.AppImage and make *that* a link to the real AppImage. I may actually move fix-qdf into qpdf proper. It's on my roadmap now that I've rewritten the lexical layer to be good enough to possibly write a lexical fix-qdf in C++. This would both make it possible for it to be more robust and also eliminate perl as a runtime requirement of qpdf.

So....I guess my preference is to drop subcommands, but if you feel strongly, then my request is to not allow them to work if the executable is invoked under a name that matches one of the supported binaries.

The same thing would work for `--usage`: only accept it if the app image is not invoked as qpdf, fix-qdf, or zlib-flate. This gives you the advantages of your features but precludes people from writing scripts or whatever that only work with the AppImage. If you do that, we can just describe it in the README for the appimage. Also, feel free to edit README-what-to-download.md to link to the appimage readme in the section that describes the appimage.

**Comment by jberkenbilt** [comment]
I looked over the changes on your branch. Whenever you think you've got them in a good state, let me know, or open a pull request. With the exception of the things I mentioned above, I like just about all of it, and I think it will make a good enhancement. One thing though: I'm not interested in having .travis.yml create github releases or upload artifacts to them. I'm happy to have 14-day artifacts uploaded to transfer.sh, but I want to restrict my github releases to only official releases, and I am unwilling to create a github token to give to travis. I will therefore most likely not take the changes to .travis.yml.

8.0.0 is ready to go except the AppImage changes, and I'm also waiting for 8.0.a1 to clear debian's NEW queue, which usually takes two or three days. My hope is to release this weekend, and it would be great of your AppImage changes are in. I'm perfectly willing to do a little work to get it to where I want it based on your excellent contributions.

At this point, I would make the following changes:
* Not take most of the after_success changes to .travis.yml, but I would keep the apt-get commands to make the doc generation work
* Tweak the English in the README file changes
* Refill README and comments to 80 columns
* Disable subcommands for the cases when `$(basename $0)` is one of the executables inside the AppImage
* Change the OS Version checks in build-appimage to be just 14.04 and not specifically 14.04.5. I don't want this to break when 14.04.6 comes out. It doesn't matter what update of 14.04 it is.
* Use convert to convert the svg logo to 512x512; don't commit the png file. I will keep the change of not copying the svg into the image.

For any changes that are just formatting, I will ensure that your authorship is preserved for purpose of git annotate.

I am okay with leaving the copyright as you have it on the AppRun script and build-appimage script, and I'm okay with those being released under the MIT license. I will want to update NOTICE.md and the debian copyright file (in the debian package, not in the qpdf repo).

I won't have to make any of the above changes that you make, but even if you handed off what you have in its present state, it wouldn't take me very long to make these updates.

I'm reopening this issue because it has been repurposed as a discussion of this topic.

**Comment by jberkenbilt** [comment]
@KurtPfeifle I just now got word that qpdf is going to be one of this coming week's projects of the week on sourceforge on February 26. Therefore I really want to make sure I have 8.0.0 released by no later than February 25. Also, it just cleared debian NEW, so there are no additional obstacles.

**Comment by jberkenbilt** [comment]
I saw the discussion about categories and the pull request on the desktop file, which I will accept. Can you let me know if/when I should take your AppImage changes? While I would very much like to do an official 8.0 release Saturday 2/24 or no later than Sunday 2/25, it is more important for me to take enough time to get it right than to force it out by an arbitrary date. But the Ubuntu feature freeze and project of the week are both immovable deadlines. Of course, there will be future releases after 8.0. :-)

**Comment by jberkenbilt** [comment]
Thanks for your hard work and clarification. Ready to move discussion to #185 now.
