### ISSUE TITLE
Merging feedback

### ISSUE THREAD

**Issue by wmbutler** [qpdf/qpdf#200]
Regarding merging pages:

```
qpdf --empty --pages infile-* -- outfile.pdf
```

1. Curious to know about any performance limitations. If I'm joining 5000 single page documents into 1, would you expect memory issues or performance limitations?
1. I'd be interested in compensating you for adding feedback to STDOUT that would report progress `0-100` regarding completion time.

**Comment by jberkenbilt** [comment]
There's an open issue regarding qpdf being inefficient in its use of open files for this type of case as it would have to have all 5000 files opened at the same time, so it would take a little work, but not that much work, to make how it does this better. The performance should be decent, but resource utilization might not be great. I'm not sure which would be better: either writing a separate program that does this, or making it so that qpdf --pages will do it well. Adding feedback would probably not be that hard.

I'd be happy to take this on. This is the kind of situation where compensation would make me get to it sooner or bump it higher on the priority list but that I'd probably do either way since it's a good idea that would benefit all users. qpdf 8.0.0 has a `--verbose` flag that indicates what files it is writing. It might make sense to have `--verbose` print some kind of progress indicator here too.

As I write this, I realize that `--verbose` as currently implement is not compatible with writing PDF to STDOUT, which qpdf can do. I'll have to either document that or have `--verbose` write to STDERR in the case of the output being STDOUT.

**Comment by wmbutler** [comment]
I like the idea of -verbose writing progress to STDOUT. 

We found with PDFUNITE, that it's more efficient to break large numbers of files into batches of child processes in order to maximize the experience. The problem from your end is that you have no idea how many processors we may have. An interesting solution may me to offer a flag that will fire up X processes to compile the different sections and then join those afterwards.

Example:

```
qpdf --empty --workers=5 --pages infile-* -- outfile.pdf
```

would work 5 batches of 1000 files each creating 5, 1000 page pdfs and then would join those 5 files into a single 5000 page file. This way, if we had a server with 16 cores, we could set --workers=12 and still have headroom on the server.

**Comment by wmbutler** [comment]
> What are the characteristics of your files, typically? Are they mostly images, mostly regular text, or some arbitrary combination of these?

Mostly text, but we do have images as well.

> What platforms does this have to work on?

Ubuntu and OS X, but mainly Ubuntu Xenial. Yes, I can see how threads on varying platforms might be difficult.

> preferably with sensible defaults for both

Probably safest to leave this at 1 to cause the least trouble for you

Would be happy to pay for this enhancement. If successful, a similar strategy could possibly be employed on the splitting side as well.

**Comment by jberkenbilt** [comment]
I'm sorry to be taking so long with this. A lot of stuff has been going on. I haven't forgotten about it. I hope to be able to carve out some time before too much more time passes.

**Comment by wmbutler** [comment]
@jberkenbilt not a problem. When you get some more time, I'd also really like to discuss (on a separate issue), the common index/directory file and it's structure for native PDF's. There are situations where we can have a PDF that is 25MB, and, after splitting it into it's 1000 pages, each page is still 25MB. From what I've read, this is related to a shared index that must accompany each page. We resolve the issue by converting these pages to images with gs, but I'm wondering if there is a more elegant solution that would allow the PDF to remain native while discarding the unnecessary parts of the index.

Feel free to move this part of the conversation to another issue. I only brought it up here because I had your attention.

**Comment by jberkenbilt** [comment]
@wmbutler Looks like you created #203 for this, so I'll respond there.

**Comment by jberkenbilt** [comment]
I fixed #154, so it is now possible to merge a bunch of files at once. Thinking through this more, I don't think it's worth pursuing the multi-threading option. I don't think it will actually help the way qpdf writes files. However, I have an idea about the progress indicator. I'm going to give that a quick check and see if I can get it work.

**Comment by jberkenbilt** [comment]
I will definitely have some kind of progress reporting in 8.1.

**Comment by jberkenbilt** [comment]
What will be in 8.1:
The `--progress` flag will give feedback at ~1% intervals while writing the output file
The `--verbose` flag, in addition to what it already does, will print information about each file that is used as merge input.
Running with `--verbose` and `--progress` will give you a lot of output. Hopefully not more than you want,

**Comment by wmbutler** [comment]
@jberkenbilt can you post hours allocated to this issue here? We will likely use this feature. @mccool

**Comment by jberkenbilt** [comment]
@wmbutler @mccool I'd estimate around 6 hours on this task.

This included about 3 hours to identify and fix a problem in the library around copying PDF objects that had to be resolved before I could propagate shared metadata to pages and mutate it safely without affecting other pages, about two hours to implement the changes, and about an hour of creating test files, updating tests, and doing general bookkeeping of commits, documentation, changelogs, etc. I wasn't tracking time that carefully, but about six hours elapsed on the clock between starting and finishing this activity.
