### ISSUE TITLE
Object streams not generated with newline before endstream when requested

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#205]
If a QPDFWriter is configured like so

```c++
QPDFWriter w(...);
w.setObjectStreamMode(qpdf_object_stream_e::qpdf_o_generate);
w.setNewlineBeforeEndstream(true);
w.write();
```

where the input to w was a PDF/A, then verapdf complains that

```
The stream keyword shall be followed either by a CARRIAGE RETURN (0Dh) and LINE FEED (0Ah) character sequence or by a single LINE FEED (0Ah) character. The endstream keyword shall be preceded by an EOL marker
```

In short it seems that the object streams qpdf generates do not contain a newline before endstream.

**Comment by jbarlow83** [comment]
Sorry I took me a while to get back to you. I reproduced it on the command line using 8.0.2 using one of the test files in ocrmypdf.

[input.pdf](https://github.com/qpdf/qpdf/files/1970095/input.pdf)

veraPDF confirms that input.pdf is a valid PDF/A. (FWIW Acrobat disagrees, and is probably correct, on account of an unrelated problem within the XMP metadata.)

Then run

```
qpdf --object-streams=generate --newline-before-endstream input.pdf output.pdf
```

The hope in doing that was to rewrite the file with object streams to make it smaller, while preserving PDF/A.

The output file will fail PDF/A validation with veraPDF, giving the same error as above.

**Comment by kilburn** [comment]
The issue is not in the `--newline-before-endstream` part, but in `--object-streams=generate`.

For instnace, this keeps PDF/A validity using @jbarlow83's test input.pdf:
```
qpdf --object-streams=preserve --newline-before-endstream input.pdf output.pdf
```

**Comment by jbarlow83** [comment]
@kilburn The input file has no object streams in it, so `preserve` has no effect here (and `--newline-before-endstream` works correctly on regular streams).

**Comment by kilburn** [comment]
Well, I also tested with the example file I added to #133, which is one of the bugs that lead to the implementation of the `newline-before-endstream` option.

That file does have streams, and its PDF/A compliance is broken with `--object-streams=generate` but not with `object-streams=preserve`. Thus, I was only adding information that the bug seems to be in the content stream generation code, not in the newline-before-endstreams code.

**Comment by jbarlow83** [comment]
The input test file has stream objects, but not object streams. Object streams are always marked `/Type /ObjStm`. (To make the naming even sillier, an object stream *is* a type of stream object. For the leading creative software company, Adobe's naming decisions are not exactly inspired.)

**Comment by jberkenbilt** [comment]
I'm guessing this will be as easy fix. I'll look at it soon. Thanks for the additional information.

**Comment by jberkenbilt** [comment]
If you could please check to see if the fix is correct, that would be great. If you're on Linux, the easiest way to do this is to download the [AppImage associated with this commit](https://transfer.sh/KgY9F/qpdf-git.078cf9b-x86_64.AppImage), which will be available for two weeks, or of course you can build from source. See [README-appimage.md](https://github.com/qpdf/qpdf/blob/master/README-appimage.md) for details on using the AppImage, but basically, download it and execute it in place of the qpdf binary.

**Comment by jberkenbilt** [comment]
Also the above-linked commit will work as a patch against any recent version. It's a trivial change.

**Comment by jbarlow83** [comment]
AppImage works for me - thank you!
