### ISSUE TITLE
Virus Warning

### ISSUE THREAD

**Issue by camxct** [qpdf/qpdf#216]
The PDFs in "\qpdf\qpdf\tree\master\qpdf\qtest\qpdf" are throwing virus warning for MAL/PDFEx-H.

**Comment by jberkenbilt** [comment]
Yes, the qpdf test suite includes some bad PDF files to ensure that qpdf does not stumble over them. Unfortunately, in order to test qpdf's resilience to this kind of issue, I have no option but to include files that some virus packages consider to be infected. The only think I can think of to get around this is to do something like base64-encode the files and decode them during a run of the test suite, but even if I do that, it is still necessary to disable most antivirus software when running qpdf's test suite. This is actually documented in the README file for Windows. Thanks for the report.

I'm going to go ahead and close this because I don't consider it to be something that needs fixing. These files are not installed in any qpdf installation.

Thanks for the report!

**Comment by camxct** [comment]
Thanks for the info! Just a suggestion, but it may be a good idea to put a warning in the README so there's no confusion!

**Comment by jberkenbilt** [comment]
Yes, that's a good idea. Thinking about it, I think I can probably rework the tests so that I don't have to have the files at all...base64-encoding them and then feeding them to stdin....I'll reopen this and tag it "next". The next release will either resolve the issue or warn about it. Thanks for the report and the suggestion.

**Comment by jberkenbilt** [comment]
Note to self: infected files are issue-51.pdf and issue-118.pdf.

**Comment by jberkenbilt** [comment]
@camxct Master now has the "infected" files obfuscated so that they never appear on disk at any time during the test suite. On my mac, Sophos no longer complains about any of the files. Can you check to see if a git clone from master still contains any files that appear to be infected? Thanks!
