### ISSUE TITLE
Encryption in QPDF - usage of external library?

### ISSUE THREAD

**Issue by zdohnal** [qpdf/qpdf#218]
Hi Jay,
I'm Zdenek Dohnal and I'm a maintainer of QPDF in Fedora and RHEL. I would like to ask you about encryption feature of QPDF. 
IIUC QPDF implements several encryption algorithms  (RC4-40, RC4-128, RC4-256 and AES-256) by itself. Why doesn't QPDF use a cryptographic library (f.e. gnutls) instead? 
Would you mind considering an usage of cryptographic library? I can cooperate with you, if you are interested.

**Comment by mschilli87** [comment]
@zdohnal : Recently, @jberkenbilt [commented](https://github.com/qpdf/qpdf/issues/200#issuecomment-379601225) on [another issue](https://github.com/qpdf/qpdf/issues/200):

> I have purposely aimed to keep external dependencies and operating system-specific code to a minimum, and I have also stayed away from C++11 or newer features, which is appreciated by some of my users who build qpdf on embedded platforms or other environments for which more modern tools are less available.

I'm not sure how widespread gnutls is and to what extend it would limit the systems QPDF could run on, but this might have been a reason to go down the road taken so far.

**Comment by zdohnal** [comment]
@mschilli87 Gnutls was the first one came on my mind, if the widespreading is critical factor, then OpenSSL can be better in the aspect.
It could have been done by a ifdef preprocessor macro (so when you want crypto from external library, compile qpdf with -D_XY).

**Comment by jberkenbilt** [comment]
I think it's a reasonable request since there's inherent security risk with embedding any crypto or other potentially security sensitive logic inline. I also wear a package maintainer hat, so I fully appreciate the issue. I would also be concerned about license compatibility. qpdf uses the Apache license (and/or the Artistic license). I'm not fully up to speed on the current state, but I know there are historically issues with openssl's license being incompatible with other things, I don't know what license gnutls uses.

If I would support external libraries for this, I would want it to be enabled with a ./configure option, such as `--with-gnutls` or `--with-openssl`, and the choice of underlying implementation would be hidden behind some abstraction. I don't want `#ifdef`s litering the main code. There is already support for replacing the random number generation piece, so that might establish somewhat of a pattern. It's been a few years, so I don't remember exactly how I set that up.

For what it's worth, there are outstanding requests for qpdf to support digitally signed PDF, which would definitely require one of those libraries or some other one I'm not aware of. Implemeting the hashing functions inline is one thing, but full digital signature support is something entirely different. If I were to do that, it would probably require adding a new external depedency, though doing so is a decision I don't take lightly at all.

**Comment by simo5** [comment]
Just FYI.
Newest OpenSSL (3.0 up) switches to the Apache License 2.0:
https://github.com/openssl/openssl/blob/master/LICENSE

This should help allay any licensing issues.

**Comment by jberkenbilt** [comment]
@simo5 This is excellent, and I was not aware. Thanks for pointing it out.

**Comment by zdohnal** [comment]
@jberkenbilt Hi Jay!
I was thinking about using gnutls - it has LGPLv2+ license for library and Apache License 2.0 is compatible with GPLv3, so according this table https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#GPLCompatibilityMatrix LGPLv2+ is compatible with GPLv3, so ASL2.0 is compatible with LGPLv2+.
Currently I was digging into code, hash+cipher algorithms and crypto algorithms defined by PDF standard, but I'm not sure if I understood purpose of some classes:
- I managed to point out files where encryptions are defined - MD5.cc, sha2.c, sha2big.c, RC4.cc, rijndael.cc
- I'm not sure about purpose of Pl_AES_PDF, Pl_MD5, Pl_RC4, Pl_SHA2 - they are just interface to encryptions for pipeline usage?
- algorithms defined by PDF standard are in QPDF_encryption.cc and they instantiate objects from previous files and call their methods

Are my findings correct? Or are they more tangled into themselves?

**Comment by mschilli87** [comment]
Just to add to the list: I am happily running LibreSSL on most of my systems (though I'm a consumer only, I've never developed against it) and [Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_TLS_implementations#Overview) claims the following license(s):

> Apache License 1.0, 4-clause BSD License, ISC License, and some are public domain

**Comment by jberkenbilt** [comment]
Since @zdohnal has done the bulk of the heavy lifting in #357, I'm willing to do some work to get this over the finish line during the next time I put a significant surge of effort into qpdf hopefully sometime in the next several months.

**Comment by jberkenbilt** [comment]
@zdohnal Reading the gnutls docs, they recommend using the nettle library for encryption. The nettle library is itself a dependency of gnutls. Can you think of any good reason not to use nettle directly? Adding a dependency on gnutls adds a lot of additional dependencies to qpdf. I may still be able to conditionally support it, since you have done the work, but using nettle for symmetric encryption adds only nettle as an additional dependency. Also, openssl brings with it no additional external dependencies and has a compatible license.

**Comment by simo5** [comment]
@jberkenbilt just FYI
In RHEL we prefer to use GnuTLS because this library provides API and ABI guarantees nettle doesn't.
Nettle will break ABI liberally on new releases due to the way it exposes internal structures to callers. We also FIPS validate through the GNuTLS interfaces so using Nettle directly would cause us also certification hurdles.

**Comment by jberkenbilt** [comment]
@simo5 This is very helpful. Thanks.

What I have decided to do is to refactor the crypto in qpdf so that the things that do crypto call through a crypto provider interface that I will create for the specific things that qpdf uses. Then we can provide multiple implementations of that. For now, I will start with the internal one and a gnutls one, since the work has already been done to provide the crypto based on gnutls. I will make it possible to turn them on and off at compile time so that you can build packages for RHEL/Fedora that don't include the native implementations. For Linux distributions that live in good packaging ecosystems where a dependency on gnutls is easy, that can be used. For other cases, people can use other things. In time, either I may add additional crypto implementations or someone else may contribute them. For example, sometime I might add digital signature to qpdf, which would certainly require either gnutls or openssl, and having a good pattern for pluggable crypto providers would be very useful in that event.

**Comment by zdohnal** [comment]
Thank you for working on it, Jay! Please let me know if you need to help with anything.

**Comment by simo5** [comment]
Nice plan!

**Comment by jberkenbilt** [comment]
I have completed the work but have a little more documentation to do before I am ready to merge.

The implementation uses C++-11 features in a non-trivial way, so whatever version of qpdf includes this will require a C++-11 compiler. I already announced the announce list that I was planning on doing this soon, and I got no pushback. I have determined that the changes are binary compatible with qpdf 9.0, so this doesn't require an soname bump and can therefore be included in qpdf 9.1.0.

Here's a summary of how it works.

qpdf now has the concept of crypto providers. There are two fully working providers: native and gnutls. When ./configure is run without any special options, the native crypto provider is built, and if gnutls is present (via pkg-config), then the gnutls provider is also build and is made the default.

This can be tweaked in several ways:
* You can explicitly enable or disable crypto providers, and you can also explicitly disable ./configure's automatic enabling of crypto providers that happen to work.
* If you explicitly enable the gnutls provider, then configure will fail if gnutls is not present
* You can explicitly configure which crypto provider will be the default provider if multiple are supported. If you don't configure, then gnutls takes precedence over native. That means that, by default, if qpdf is built with gnutls present, the gnutls provider will be used, but the native provider could be selected at runtime.
* As such, if you configure with `--enable-crypto-gnutls --disable-implicit-crypto`, then qpdf will be built without inclusion of the native crypto provider. The native implementations will not be compiled or linked into the qpdf library. This gives you a hard guarantee that the gnutls implementation is being used.

Additional relevant information:
* The CLI option `--show-crypto` has been added, which lists the crypto providers available, showing the default provider first.
* In CI, for the Linux build, the entire test suite is run with every provider with both a normal build and the build with all the memory sanitizers enabled. This ensures that both providers work and are free of memory issues.
* The environment variable `QPDF_CRYPTO_PROVIDER` can be set to the name of a crypto provider, which will cause qpdf to use that provider. This feature will greatly assist in debugging of any weird issues that we may encounter as it will make it possible for users to try situations with multiple providers when trying to reproduce or report bugs. Of course, there aren't any bugs, so it is purely academic, but still. :-)
* It is also possible for a developer to call `QPDFCrytpoProvider::setDefaultProvider` to set the default provider. Developers can also register their own crypto providers. Implementing a crypto provider is as simple as creating a class that implements all the methods in `QPDFCryptoImpl`, ensuring the class can be constructed by a default constructor with no arguments, and calling `QPDFCryptoProvider::registerImpl` and `QPDFCryptoProvider::setDefaultImpl`. This makes it possible for an end user to implement a completely new crypto provider without modifying the qpdf library at all. This is great for people who want to do their own thing, but it would also help a future contributor who wanted to contribute a provider based on nettle or openssl to do so easily.

It took me about a day to do the refactoring, and then it took only a couple of hours to create the gnutls crypto provider using @zdohnal's PR as a guide for how to do the actual method implementations. Then it took about another half a day to get all the build and test integration working properly. This also sets a precedent for how to make certain things pluggable. This might make it possible to eventually allow users to add their own stream filtering algorithms, replace Flate compression's zlib-based implementation with one that generates better compression (an often requested feature), or other things I haven't even imagined.

This code uses C++-11 in both trivial and non-trivial ways. I enjoyed using `std::uniqe_ptr` and `std::shared_ptr` instead of `PointerHolder`, and I enjoyed being able to use `auto`, `constexpr`, and `nullptr`. Those were all just nice to have perks. However I also used `<functional>` to greatly simplify the registration of new crypto providers and relied on the C++-11 guarantees of thread safety of block-scoped static initializers to enable qpdf to automatically register built-in providers safely using the same interfaces that an end user would use. `QPDFCryptoProvider` uses a singleton pattern hidden behind static methods to give a hard guarantee that setup and registration of crypto providers is deterministic in the default case and also in the case where a developer should supply their own providers. All in all, I'm quite pleased with how this turned out.

**Comment by jberkenbilt** [comment]
The above comment will be the basis for what I will include in the qpdf manual for this change, though it will be split out for different audiences including some notes about the design, material targeted toward someone who wants to add a new provider, the package maintainer, or someone who is trying to troubleshoot or measure performance.

**Comment by zdohnal** [comment]
Nice work, Jay! Thank you for making this possible!

**Comment by jberkenbilt** [comment]
@zdohnal @simo5 How do you feel about libgcrypt? I notice that other PDF readers in debian (okular, atril) use gcrypt for their crypto. It is much lighter weight than gnutls.

**Comment by jberkenbilt** [comment]
@zdohnal @simo5 My question about libgcrypt is academic as 9.1.0 will definitely go out with gnutls. I am going to disable native crypto and enable gnutls for the debian packages and AppImage as well. For 9.1.rc1 at least, the Windows builds will still use the native crypto, but maybe I can fix that for 9.1.0 or later.

**Comment by simo5** [comment]
@jberkenbilt we strongly prefer GnuTLS over libgcrypt on various grounds.
