### ISSUE TITLE
Share reference stream data when copying objects

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#219]
It would be very helpful to [pikepdf](https://github.com/pikepdf/pikepdf) or anyone who attempts to create bindings for qpdf for other languages to relax the restriction described here: 

>when you copy objects from one QPDF to another, the source QPDF object must remain valid until you have finished with the destination object. This is because the original object is still used to retrieve any referenced stream data from the copied object. 
>(http://qpdf.sourceforge.net/files/qpdf-manual.html#ref.foreign-objects)

While it's understandable that the restriction exists, it can be difficult to enforce it in practice in high level languages. It's possible in Python because of reference counting, but in a garbage collected language it's probably a dead end.

A few notable use cases come to mind:
* copying a foreign page and destroying the source
* copying a foreign page through a chain of QPDF objects and destroying a link
* copying a foreign page, and then deleting it from the source
* copying a foreign page, then delete it from the target, and accessing it from the source

**Comment by jberkenbilt** [comment]
This has to do with the fact that stream data is accessed lazily, but it would probably be possible to add a way to force qpdf to break ties from the original. Doing so would very likely require the use of some kind of temporary file, which adds another layer of complexity. Anyway, I'll definitely consider it.

**Comment by jberkenbilt** [comment]
I spent a few minutes reading through the code, and I believe this is pretty easy to fix. It requires the following changes, which I am recording here for my future reference:
* Generate a uuid for each QPDF object. It doesn't have to be an actual uuid. It just has to be unique within the lifetime of the application. I'm thinking a long long with half its bits from a timetsamp and half its bits from a random number would be more than adequate.
* Change the map key of object_copiers from `QPDF*` to the uuid so we can determine when we copy objects from the same QPDF object again without having to rely on long-lived pointers. (I should have done it this way from the beginning -- using pointers as map keys is dubious.)
* Change the behavior of `CopiedStreamDataProvider` to grab the foreign stream data at the time of registration and store it off somewhere that can be provided when the stream data is requested.

I'm pretty sure I can implement all of this without changing the binary interface since all objects that have to be modified are already protected behind a level of indirection using `PointerHolder`.

Regarding the store it off somewhere bit, here's some additional background:
* While QPDFWriter does store each stream fully in memory at some point, it takes care never to store an unbounded number of streams in memory. Regardless of the size or number of streams in a PDF file, qpdf should never store more than a small constant number of streams in memory at once.
* There are three ways that a stream can provide data: as a buffer, using a function to provide the stream data, or from the original source file. In the buffer case, I wouldn't feel too horrible about just copying the buffer because the programmer has already decided that it's okay to have the stream in memory. The function case is harder because a function could potentially generate a large amount of stream data, and holding all generated data for all streams in memory would be a potentially radical change to the memory footprint. The original file case is the worst though because holding that in memory would completely smash the rule about not holding more than a constant number of streams in memory and will destroy the ability to copy pages from files that are too big to fit in RAM. The naive solution of storing a reference to the input source with offset and length information would work in simple cases, but it will not work at all with encrypted files because a lot of metadata information is required in order to decrypt the stream.

The only way I can see to reliably work around these issues is to use a temporary file, which is kind of sad because qpdf currently doesn't keep any state around while it's running, and managing temporary files is a pain. It's also not needed if you do keep the QPDF objects around, which the qpdf CLI itself does. So here's what I'm thinking:

* Do the QPDF object uuid thing regardless as it's an improvement to the existing code
* Add a method to QPDF that tells the library that you are not keeping QPDF objects around after copying.  This method would allow you to indicate either that copies of stream data should be stored in memory or temporary files. If temporary files, it would be possible to specify the location of a temporary directory, and it would be documented that there must be enough space to create temporary files whose size is the sum of the sizes of the files from which objects are being copied. I would manage the temporary files in some way that avoids creating files that are too big or creating too many files. Probably something like not allowing a file to exceed 1 GB in size and creating extra temporary files as needed.
* I'd probably create some kind of file-based temporary buffer that handles the spitting and stuff and can act as an InputSource. Then I can test it with smaller chunk sizes in the test suite. I'll have to think about the implementation a bit, but it shouldn't be hard.
* For testing, I will want to enhance the large file tests to exercise this as well so I can be sure that it works properly for very large files, and I will want to add some tests that copy foreign streams from encrypted files and with data providers and buffers as well as just normal PDF files.

In spite of the size of this explanation, I don't think it's going to be very much code or very complicated code. I could probably do it in a few hours. I'll see if I can work this in during my next qpdf work session.

**Comment by jbarlow83** [comment]
Thinking about this some more, it might work if you used a `PointerHolder<QPDF>` to keep track where some copied stream needs to be retrieve from and let reference counting sort the rest out. That of course would not protect against a stack-allocated QPDF object from disappearing, but I don't have to worry about that case since everything I make is (or could be) on the heap.

When Python decreases the reference count to 0 on a Python object that wraps a QPDF object, it will call `delete ptr` to release the storage. If ptr is a shared pointer, then it just drops the C++ reference count, so if that reference count accurately reflects internal dependencies it *should* take care of everything. (I currently store my QPDF's in `shared_ptr` and would have to switch to `PointerHolder` but I don't think that's a problem.) 

Either way the UUID change sounds like a good idea.

On the other hand, it would be nice to pickle arbitrary QPDFObjectHandles one day (mainly for interprocess communciation) and a temporary file storage mechanism that lets us sever all dependencies to the source file might help with that. That said, I'm still not sure how feasible it is to marshal any object with indirect references without getting people thoroughly confused. And I have enough other things that I want to do that this is fairly far down the list....

**Comment by jberkenbilt** [comment]
Note to self: rethinking this, I prefer not to use temporary files if I can avoid it. Perhaps we can refactor pipeStreamData to be able to use external encryption keys. Then QPDF can keep track of the input sources and additional parameters.

**Comment by jberkenbilt** [comment]
I have coded a fix for this that does not use temporary files. In the case of streams whose contents come from buffers or the original file, the restriction of having to keep the original QPDF object around is lifted, but the memory buffer or original file (input source) must be kept around. This is a much less drastic restriction.

In the case of where a StreamDataProvider is used, the original QPDF object must still be kept around. This is the case of where QPDF q1 has a stream for which replaceStreamData was called to provide a StreamDataProvider, and then that stream from q1 was subsequently copied to q2. In that case, q1 must be kept around until q2 is written. That is a pretty unusual case as, most of the time, people could just attach the stream data provider directly to the q2. That said, it actually appears in qpdf itself. qpdf allows you to combine the --merge and --split options. In that case, a merged file, which uses StreamDataProvider to access the original stream, is subsequently copied to the final split output files. Solving this restriction is much more difficult and would probably require breaking source compatibility because QPDF_Stream doesn't have enough information to know whether the original QPDF object is needed by the stream's data provider. Also, the interface is designed to pass the object ID and generation of the object whose data is being provided so the provider can use it for lookup or any other purpose. As such, copying a stream data provider to a new stream potentially changes the meaning of the parameters passed to the provider. I will document this in the notes, but I don't think I will ever fix it. This is a very rare case, and it's certainly not worth going the temporary file route to solve it or breaking source compatibility for stream data providers.

**Comment by jberkenbilt** [comment]
@jbarlow83 I hope this satisfies your requirements, but in case not, 8.4.0 will have an additional change (already in master) that will allow a SOURCE QPDF object to be marked in such a way that the destination object will copy streams into RAM. I had a user who was process files in memory and didn't want to keep all the memory around but was willing to keep all the copied streams in memory. This made perfect sense for his use case. Basically the new flag will make qpdf convert any copied streams into PointerHolder<Buffer> so that the original file and its input source can both disappear regardless of the type of streams it has.

**Comment by jbarlow83** [comment]
Thanks. I think avoiding temporary files was definitely optimal.

I think I will wait for 8.4.0 to tackle my memory leaks, because I can't guarantee the availability of the input source in some cases.

I don't subclass StreamDataProvider so I think I avoid that complication. I allow create streams by copying bytes into QPDF via `newStream(... data_bytes)` or copying from another object.

**Comment by jberkenbilt** [comment]
Given the way that you are copying data bytes, the 8.4.0 solution should fit your needs exactly since that's what it does. Thanks.
