### ISSUE TITLE
Merge all pdfs in Windows

### ISSUE THREAD

**Issue by bup4gr** [qpdf/qpdf#224]
As i read here https://github.com/qpdf/qpdf/issues/11, the command
`qpdf --empty --pages *.pdf -- out.pdf`
don't work in Windows.

With pdftk the command
`pdftk *.pdf cat output out.pdf`
work in Windows also if there is a wildcard.

Is possible to make the command `qpdf --empty --pages *.pdf -- out.pdf` work in windows (by modifying qpdf)?

**Comment by jberkenbilt** [comment]
I didn't know it didn't work in Windows. I will see if I can reproduce it. If so, then I should have an idea of how to fix. If not, then I will ask for additional information.

**Comment by eesheesh** [comment]
In Window, the shell doesn't expand wildcards, so qpdf needs to expand the wildcards itself.

**Comment by eesheesh** [comment]
This might be the answer: https://docs.microsoft.com/en-gb/cpp/c-language/expanding-wildcard-arguments

**Comment by jberkenbilt** [comment]
Looks relevant and useful. Thanks. Having lived in a UNIX environment all my life, I am still occasionally surprised by Windows. I knew old DOS programs had to do that, but I didn't know it was still true. Hopefully this will be an easy fix.

**Comment by jberkenbilt** [comment]
I am not able to reproduce this on my Windows 10 VM.

**Comment by bup4gr** [comment]
You are right. In Windows 10 with qpdf 8.1.0 or 8.2.1 everything works without errors.
The problem is only with old qpdf 6.0.0 (there was the error: `open *.pdf: Invalid argument`).

**Comment by SumatraPeter** [comment]
@jberkenbilt: I've been breaking my head for hours over this, trying _every_ 32-bit MSVC version from 8.2.1 onwards till the latest (as of date 9.0.2). Can someone please tell me why it keeps giving me the dreaded `open *.pdf: Invalid argument` error?

![image](https://user-images.githubusercontent.com/15380332/67342174-37dd9200-f54f-11e9-8f2c-036b38b57725.png)

**Comment by SumatraPeter** [comment]
@jberkenbilt: Perhaps this got overlooked since I commented on an old closed issue. Should I open a new issue for this?

**Comment by jberkenbilt** [comment]
@SumatraPeter I reopened the issue and will try to remember to look at it before the next release. I updated the version of msvc recently, and maybe that broke it. I will try to see if I can add a test for this so it is not a regression.

**Comment by jberkenbilt** [comment]
I have been able to reproduce this locally, but unfortunately I have not been able to reproduce it in CI. This means that I will probably have the bug fixed for 9.1.0, but I can't guarantee that it won't break in future releases. I will make a note to myself to try to figure out how to test it in CI. The problem is that it doesn't happen unless you run from cmd, and my test suite doesn't really have a way to do that because the tests run from msys.

**Comment by jberkenbilt** [comment]
Actually, also, the fix breaks this when running from msys because quoting the wildcard prevents it from being expanded since it is now being expanded by main. :-(

**Comment by jberkenbilt** [comment]
So I'm not really sure how to fix this.

**Comment by jberkenbilt** [comment]
Actually, never mind, I think I have it working. But still not sure how to test it in my automated test environment.

**Comment by jberkenbilt** [comment]
I'm still having trouble getting this to work. I may or may not fix it for 9.1.

**Comment by SumatraPeter** [comment]
> I have been able to reproduce this locally, but unfortunately I have not been able to reproduce it in CI.

Sorry, I don't know what CI is. Google tells me "Continuous Integration"?

> Actually, also, the fix breaks this when running from msys because quoting the wildcard prevents it from being expanded since it is now being expanded by main. :-(

Not sure whether I'm missing something here, but wildcards don't need quoting at the command prompt/Windows command line.

> I'm still having trouble getting this to work. I may or may not fix it for 9.1.

:( If I may ask, how does the MinGW version work? Is it handling the wildcard expansion itself whereas the MSVC version isn't?

**Comment by jberkenbilt** [comment]
If you actually a file literally named `*.pdf`, in a UNIX environment, you would be able to quote it, as `"*.pdf"`, to prevent the shell from expanding the wildcard. I am not able to find a way to do this in Windows with the msvc executable, but the behavior is consistent as with other Windows/DOS commands when run from cmd. The mingw executable behaves more like UNIX, where `*.pdf` is expanded but `"*.pdf"` is not. I don't know why the behavior is different.

For 9.1.0, I will link the msvc executables to expand wildcards. In the extremely unlikely event that someone has a file called `*.pdf`, they can either put the string `*.pdf` in a file and use `@file` to pass it to qpdf, or they can use a pattern that happens to match that. Without this fix, there's no way to do wildcard expansion, and files with wildcard characters literally in their names are kind of pathological, so I'm thinking things are much better with the fix than without.

Yes, CI is continuous integration. Ideally, I would like to add an automated test that would fail without this fix so that I'll notice if I break it again, but I am having a hard time figuring out how to have my test suite run the command in the same way cmd does, even by literally invoking cmd, which doesn't seem to work in azure pipelines even though it works when I run it locally. In the meantime, I've just made a note to keep this issue in mind when migrating to a new version of MSVC or a new build environment.

So this should work fine in 9.1. I'm planning on releasing a release candidate of 9.1 this weekend since there are so many build-related changes, and then hopefully putting out the final 9.1 next weekend.

**Comment by jberkenbilt** [comment]
Looking good so far. This issue will close automatically when I merge the fix. I will have to wait until the CI-built executable is ready before I can do a final manual test, but it is looking promising for 9.1.

**Comment by SumatraPeter** [comment]
> For 9.1.0, I will link the msvc executables to expand wildcards. In the extremely unlikely event that someone has a file called *.pdf, they can either put the string *.pdf in a file and use @file to pass it to qpdf, or they can use a pattern that happens to match that.

Umm, if someone's using the Windows binaries then you don't even _need_ to be bothered with handling such file names, because they're not even allowed by the shell!

Here's a screenshot from Win10's File Explorer, but these characters have been prohibited going back to the MS-DOS era:

![image](https://user-images.githubusercontent.com/15380332/68551195-445b5900-0430-11ea-822f-f4d651f184e7.png)

**Comment by jberkenbilt** [comment]
@SumatraPeter Ah, that would explain why "invalid argument" instead of "file not found" :-) Thanks. Okay, then I think we're in good shape for 9.1.0. I'm releasing 9.1.rc1 tonight, but I will fix up the docs for this before the final 9.1.0.
