### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [qpdf/qpdf#235]
Would you like to [wrap any pointer data members](https://github.com/qpdf/qpdf/blob/e8b845dd0344c797b58bfa31b810af53595d2599/libqpdf/Pl_AES_PDF.cc#L12 "Update candidate: Pl_AES_PDF class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by jberkenbilt** [comment]
For a variety of reasons, I'm staying clear of C++11 for now. This may eventually change, but I have a number of users who build qpdf with older compilers that don't yet have C++11. It's why I am still using PointerHolder.

**Comment by elfring** [comment]
Did better smart pointer classes become available for general reuse in the meantime?

**Comment by jberkenbilt** [comment]
I don't understand the question. PointerHolder is deeply embedded into qpdf's API. There are definitely better smart pointer options, and I even agree that a more modern qpdf API that uses them would be an improvement, but migrating would be a low-value activity that would break backward compatibility, and as I have very limited time for qpdf, I am not going to do it.

**Comment by elfring** [comment]
How do you think about to improve exception safety by other software approaches (in the meantime)?

**Comment by jberkenbilt** [comment]
Can you explain how this is hurting exception safety? Perhaps I am not fully understanding the issue you're bringing up.

**Comment by elfring** [comment]
I suggest to [achieve safe resource management](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "C++ core guideline “R.11: Avoid calling new and delete explicitly”").

**Comment by jberkenbilt** [comment]
As far as I know, PointerHolder, though neither modern nor the best available smart pointer implementation, satisfies the requirements. There are a very small number of explicit new/delete calls, but they are around small bits of code without potential for exceptions being thrown. (I'd have to actually audit the code to be 100% ceratin of this claim, but I know there are very few new/delete calls.) Every release, I run qpdf's thorough test suite with address sanitizer, which catches memory leaks and also exercises all reproducible errors.

Are you aware of any specific cases where use of a smart pointer is not being done but needs to be done?

Do you agree with my assessment that PointerHolder, though not ideal, is sufficient?

**Comment by elfring** [comment]
>…, but they are around small bits of code without potential for exceptions being thrown.

How do you think about to care a bit more for [the potential of an exception like “`std::bad_alloc`”](https://en.cppreference.com/w/cpp/memory/new/bad_alloc "Description for std::bad_alloc")?


>Are you aware of any specific cases where use of a smart pointer is not being done but needs to be done?

Yes. - [I suggest to take another look at source code places](https://github.com/qpdf/qpdf/blob/95ba7125ffa4efd4022fd27ab61ff739b0864258/libqpdf/Pl_PNGFilter.cc#L12 "Another update candidate: Pl_PNGFilter class") around implementations of resource allocations.


>Do you agree with my assessment that PointerHolder, …, is sufficient?

I propose to reconsider the circumstances.

Can this class be used in a way which would be compatible with [the standard specification “`std::make_unique`”](https://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique "Description for std::make_unique")?

**Comment by jberkenbilt** [comment]
It occurred to me as I was writing that memory allocation errors could cause exceptions to be thrown, and the example you linked to is a potential leak because if allocation of buf2 fails, buf1 will be leaked. I am going to leave this issue open but most likely not attempt to address it for 8.2.0 which I'm trying to get out in the next week. I will have to study this more carefully and figure out what I can do with trashing the API.

**Comment by elfring** [comment]
>…, and the example you linked to is a potential leak because if allocation of buf2 fails,

Smart pointer classes were designed to take care of this programming concern.


>buf1 will be leaked.

This conclusion can be questionable for the concrete implementation of the class “Pl_PNGFilter” when the provided destructor will be executed.
[The class “Pl_AES_PDF” is still affected](https://github.com/qpdf/qpdf/blob/e8b845dd0344c797b58bfa31b810af53595d2599/libqpdf/Pl_AES_PDF.cc#L12 "Update candidate: Pl_AES_PDF class"), isn't it?


>… what I can do …

… without trashing …? :wink:

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/qpdf/qpdf/commit/6c39aa87638f7a6f96a97627ac112fb2022bd3a7 "Favour smart pointers").

Will C++ standard functionality become more attractive in comparison to [a customised class like PointerHolder](https://github.com/qpdf/qpdf/blob/aa602fd107a622a3f12e6530220bb0303b95b520/include/qpdf/PointerHolder.hh#L25 "Description for PointerHolder class")?

**Comment by jberkenbilt** [comment]
There's no question that standard functionality would be more attractive than PointerHolder, but for various reasons, I'm keeping qpdf compatible with the C++99 standard and avoiding any C++11 or newer features for now. I have a few users who support applications based on qpdf using very old compilers, like Visual C++ 2010, and I don't want to break them when the core of qpdf predates C++11 and works with older compilers. At some point, I may decide to cut loose and go with C++11 (or C++14 or C++17 or whatever), at which point, I could consider switching to a standard pointer class. Since PointerHolder is everywhere in qpdf's API, that would most likely be by making PointerHolder a wrapper around a standard smart pointer. However, for now, it will have to be PointerHolder.
