### ISSUE TITLE
No Longer any Way to Open Recently Used in a New Tab.

### ISSUE THREAD

**Issue by DiagonalArg** [qpdf/qpdf#241]
Control-T pops up the folder to select a file.  I don't see any way to create a new tab and then open a recently used file in there.

I'll add that despite having "Restore Tabs" checked, it lost mine since the last update.

**Comment by jberkenbilt** [comment]
It looks like you may have reported an issue against the wrong package. This qpdf is a command-line tool and C++ library and doesn't have a graphical UI. I think there are other packages with similar names that might have tabs and so forth. Since this issue doesn't apply to this package, I'm closing it. I hope you will be able to report it to the right place since it's helpful to projects when people report issues. Thanks.

**Comment by DiagonalArg** [comment]
Oops.  Yes, thanks.  qpdf*view*
