### ISSUE TITLE
Error when duplicating the same page

### ISSUE THREAD

**Issue by halloleo** [qpdf/qpdf#272]
Say I try

    qpdf A.pdf --pages A.pdf 1 A.pdf 1 -- 'A_x2.pdf'

then I get the error:

> A.pdf (page 1 (numbered from zero): object 2 0): duplicate page reference found; this would cause loss of data

This looks like the title of issue #127, but that issue is closed. BTW I use the newest version 8.3.0.

IMHO qpdf should be able to handle duplication of pages.

**Comment by jberkenbilt** [comment]
You have to use this workaround: `qpdf A.pdf --pages A.pdf 1 ./A.pdf 1 -- A_x2.pdf`. By referring to A.pdf using two different but equivalent paths, it allows qpdf to copy the same page twice. It's an unfortunate limitation, but fixing it for real turns out to be quite difficult, and the workaround is pretty easy. Maybe someday I will be able to remove this limitation.

**Comment by halloleo** [comment]
Thanks. That works. Definitely not perfect though: Quite cumbersome when you want to use qpdf in a script (You have to split the potentially absolute file path in directory path & file name, etc...). But, hey, it *does* work. :-)

**Comment by jberkenbilt** [comment]
Let's leave this open as a reminder for me to see if I can resolve it. There have been several enhancements I've made recently that may make this easier to solve right.

**Comment by jberkenbilt** [comment]
I'm going to mark this "next" so I remember to prioritize analyzing it.

**Comment by jberkenbilt** [comment]
I think I can fix this by just having qpdf.cc keep track of which pages it has copied from which files and, if copying the same page twice, just shallow copy the page dictionary and add the page. If I'm right, it will be a very small fix.

**Comment by halloleo** [comment]
Cool. Happy to test it when it's done.

**Comment by jberkenbilt** [comment]
I will be pushing a fix to this to master in a few minutes after CI finishes. You will know that the fix is there when this issue closes. Please feel free to test if you'd like.

While I was at it, I added another enhancement: you can use `.` to represent the original input file. I don't know why I didn't do something like that originally. So you can now say `qpdf A.pdf --pages . 1,1 -- A_x2.pdf'`. This fix will be in 8.4.0.
