### ISSUE TITLE
Roadmap Question: Glyph Positioning

### ISSUE THREAD

**Issue by drcdr** [qpdf/qpdf#275]
We're looking to be able to get bounding boxes from BT/ET text objects.  Currently, we're using pdfminer.six, which seems accurate, but we would much prefer a C++ solution.

Is there any future plan for QPDF to support information related to glyph positioning and/or bounding boxes?  Perhaps this could be done as an ET callback, I don't know.  And, do you suspect there would be problems with internal vs. external fonts?

xpdf seems like it could support this with mods, but it looks like there are some (at least on some files we've tested, it might be a font problem).

**Comment by jberkenbilt** [comment]
At this time, qpdf doesn't have any direct support for interpreting content streams, nor does it have any direct support for dealing with fonts. It is possible that qpdf may evolve in this direction, but not soon. qpdf does have enough support for lexical interpretation of content streams that it would be possible to use qpdf as the basis for an implementation of what you're looking for. qpdf's specialty is structure of PDF files, not content streams. It would be possible to use a token filter with QPDF, gather up tokens between BT and ET, find the Tf operator and figure out which font was referenced, look it up in the resource dictionaries based on whether it's from a form XObject or page, find the font metric information, if any, etc., but it would be a lot of work in qpdf since qpdf is not a full PDF interpreter like xpdf, ghostscript, etc. are.

To answer your direct question about future plans, supporting something like this is not on the current roadmap.

Please let me know if you have additional questions about this. Thanks.

**Comment by drcdr** [comment]
Thanks for such a quick and detailed response!
<pre>
It would be possible to use a token filter with QPDF, gather up tokens between BT and ET, 
find the Tf operator and figure out which font was referenced,
</pre>
I got this far already, which was straightforward (QPDF is nice!)
<pre>
look it up in the resource dictionaries based on whether it's from a form XObject or page, 
find the font metric information, if any, etc., 
</pre>
This is where I got blocked.  I had a test file for which I'd already used --split-pages to divide into pages.  pdfminer.six still handles the page correctly (AFAICT), presumably because they are standard fonts?  But I don't see a way in qpdf to output font dictionary information into each split page (e.g. so they could be processed in parallel).

I suppose an implementation might also require large data-tables for font-metric information (to handle your "if any" case), such as:
   https://github.com/tmyroadctfig/xpdf/blob/master/xpdf/BuiltinFontTables.cc

**Comment by jberkenbilt** [comment]
You are correct that you would need font tables for built-in fonts, which qpdf does not have. If the font is embedded, you will be able to access it with qpdf, but if not, you are out of luck, I'm afraid. qpdf 8.3.0 introduced annotation flattening and form field appearance stream generation, and there are certain things it can't do because of lack of font information. I imagine it's only a matter of time before qpdf grows a FontObjectHelper or similar, and at that time, I may end up biting the bullet and including font metric information, presuming I can find it with a license as permissible as qpdf's. You could probably include this information in your own application and make use of it if the PDF file doesn't have it.

If you get further along and want me to look at some code or if you have some sample code you can share that I might be able to use if I ever add the functionality to qpdf, that could be helpful. Occasionally I have had someone ask a question like this and, later when I add functionality to qpdf, they are able to simplify their code using new library functionality. It works well for everyone if I have some use cases or examples to ensure that my new APIs are meeting their established use cases. Once or twice a year, I take some leave from work to put energy into qpdf. These are the times when I can undertake chunkier projects. I feel like font awareness is going to have to be addressed at some point before too much longer. Actual content parsing/interpretation is probably in the more distant future if ever. That said, qpdf does a lot of things that I never thought it would do. As it gains popularity, people are more likely to offer great ideas or code, and there is even some precedent for commercial organizations sponsoring enhancements. The json mode added in qpdf 8.3.0 is one such feature. I sign up for these kinds of arrangements sparingly and with conditions (e.g. it has to be on my schedule, and all changes go into the official qpdf with the same permissive licensing terms). Mostly though I just try to prioritize features based on community interest, especially when it benefits other open source projects. I have made many enhancements to support the Linux Printing project, for example, including the recently added form and annotation stuff. I suspect font awareness would likely fall into this bucket.

**Comment by drcdr** [comment]
OK, thanks again for all the great feedback.  We'll think about this some more about how me should proceed in the long-term; meanwhile, we'll continue with pdfminer.six in the near-term.

P.S. I think the font table information could be generated "automatically"; start from a Word document (e.g.) filling out the {font,glyph} space; then save-as-PDF, then process the font-related objects and write out a .c file.
