### ISSUE TITLE
QPDFExc - breaking ABI change (I think...)

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#281]
I believe commit c18ee440a38c7078e92c917bbe8fe1ad290a292d may have broken the ABI since the change causes QPDFExc to become no longer virtual, resulting in errors like (macOS/clang):

```
ImportError: dlopen(/usr/local/Cellar/ocrmypdf/8.0.1/libexec/lib/python3.7/site-packages/pikepdf/_qpdf.cpython-37m-darwin.so, 2): Symbol not found: __ZTV7QPDFExc
```

Name demangling says that's the virtual symbol table for QPDFExc.

Discovered while trying to update homebrew qpdf:
https://github.com/Homebrew/homebrew-core/pull/36728

**Comment by jbarlow83** [comment]
This seems to have the side effect of preventing try-catch blocks that catch `QPDFExc` from working. Instead they see only `std::runtime_error`.

**Comment by jberkenbilt** [comment]
I will look into this at the earliest opportunity. Either there is a compiler bug somewhere or a bug in my brain or both. It seems like the change I made to fix a problem with one compiler caused it in another. I have tests for binary compatibility but it's quite likely that the tests would not catch the behavior you are describing. If this is an ABI breakage, I will fix it and release 8.4.1 rather than bumping to version 9 or make the fix mingw only until I'm ready to break the ABI.

**Comment by jberkenbilt** [comment]
I am not able to reproduce this problem. I wonder if the homebrew package is compiled with different flags or something. I added explicit tests for throwing different types of exceptions and catching them across the shared library barrier, and they pass on all platforms with all compilers that I test with in CI, and when I run nm --demangle on Linux on libqpdf.so, I see the QPDFExc virtual table. The function is also declared virtual in QPDFExc.hh, and that should make it virtual even though the destructor is inline. I'm running a throw-away CI build right now that runs nm --demangle on the library. I should results in 10 minutes or so.

**Comment by jberkenbilt** [comment]
If you go to [this azure pipelines build](https://dev.azure.com/qpdf/qpdf/_build/results?buildId=177&view=logs), select "macOS Job" on the left, and then "Mac build and test", you can see `d vtable for QPDFExc` on line 3763. As far as I understand, this indicates that there is a vtable for QPDFExc in the library. I wonder whether there was a problem with the brew build. Let's get to the bottom of this. I don't want there to be a binary compatibility error floating around with qpdf, whether my fault or otherwise. Thanks.

**Comment by jbarlow83** [comment]
Thanks for all this checking... C++ can be quite *special* and frustrating.

I can't reproduce the result that the Homebrew build servers get either. I do get test failures in qpdf 8.4.0 because this exception translator below fails to catch any `QPDFExc` when a `QPDFExc` is thrown. With qpdf 8.3.0 there are no failures

(The purpose of this code is to intercept `QPDFExc` and translate it to a Python error, while actual `std::runtime_error`s get translated to `RuntimeError`.)

```c++    
    static py::exception<QPDFExc> exc_main(m, "PdfError");
    static py::exception<QPDFExc> exc_password(m, "PasswordError");
    py::register_exception_translator([](std::exception_ptr p) {
        try {
            if (p) std::rethrow_exception(p);
        } catch (const QPDFExc &e) {
            if (e.getErrorCode() == qpdf_e_password) {
                exc_password(e.what());
            } else {
                exc_main(e.what());
            }
        }
    });
```

And what's going on amounts to:

```c++
   try {
       throw QPDFExc(...);
   } catch (const QPDFExc &e) {
       // does not catch
   }
```

The symbol Homebrew complains about *is* present in my version of libqpdf 8.4.0. So it's probably not the ABI, but something else.

I saw that Debian sid has accepted both qpdf 8.4.0 and pikepdf 1.0.5 right now, and my test suite passes just by running it against the two precompiled systems versions.

Now I wonder if it's a clang bug....

**Comment by jberkenbilt** [comment]
I made the change of inlining the destructor because a recent version of mingw32 stopped generating a vtable for QPDFExc when it was not inlined. I'm not sure, but it's possible that the binary called g++ on the mac build may actually be clang. It is on my work mac, but I don't know about azure pipelines macs. It's possible that that information is in the build log linked above.

**Comment by jbarlow83** [comment]
`g++` on mac is `clang`.

**Comment by jbarlow83** [comment]
So Homebrew re-tested the PR to update qpdf to 8.4.0 and it passed their test infrastructure, so they merged it. Maybe Homebrew updated some other part of their toolchain that had some effect. I'm not entirely sure why this worked for them, but it did.

I still see the behavior that when pikepdf is linked against qpdf 8.4.0 (both built with clang) exceptions of type QPDFExc don't get trapped by `catch (QPDFExc)`.

**Comment by jberkenbilt** [comment]
A simple program that links against the shared library with 8.3.0 and catches QPDFExc still works when resolving again 8.4.0, at least on Linux with gcc. I wonder whether it would be possible to narrow it down. I've never extended Python so I have no guesses. I could try on my work mac with a standalone program by just doing something that throws that exception

**Comment by jbarlow83** [comment]
Finally figured it out... it's specific to pikepdf being compiled with `-fvisibility=hidden`.

**Comment by jbarlow83** [comment]
PR in #302
