### ISSUE TITLE
Failing tests in case of too old Ghostscript: "Error: File has unbalanced q/Q operators (too many q's)"

### ISSUE THREAD

**Issue by ams-tschoening** [qpdf/qpdf#287]
I had Ghostscript 9.19 from 2016 installed on my Windows 10 1809, which lead to errors like the following:

	qpdf test 375 (convert original file to image) FAILED
	cwd: C:/Users/[...]/Win32/Debug/out/qtest/qpdf
	command: (cd tif1; gs 2>nul -q -dNOPAUSE -sDEVICE=tiff24nc -sOutputFile=a.tif - < ../large-inline-image.pdf)
	 at qpdf.test line 4031.
		main::compare_pdfs("large-inline-image.pdf", "a.pdf") called at qpdf.test line 756
	--> BEGIN EXPECTED OUTPUT <--
	--> END EXPECTED OUTPUT <--
	--> BEGIN ACTUAL OUTPUT <--

	   **** Error: File has unbalanced q/Q operators (too many q's)
				   Output may be incorrect.
	--> END ACTUAL OUTPUT <--
	--> DIFF EXPECTED ACTUAL <--
	--- C:/Users/[...]/testtemp.3676/expected	2019-02-14 14:10:06.794747700 +0100
	+++ C:/Users/[...]/testtemp.3676/actual	2019-02-14 14:10:06.794747700 +0100
	@@ -0,0 +1,3 @@
	+
	+   **** Error: File has unbalanced q/Q operators (too many q's)
	+               Output may be incorrect.
	--> END DIFFERENCES <--

Updating to the most current version 9.26 and testing manually on the shell with the mentioned files resolves the issues, not error message is printed and the expected file created. I didn't test any older newer version to know when exactly this has been fixed.

You might want to add some docs mentioning trying a newer version or such in the [README for Windows](https://github.com/qpdf/qpdf/blob/master/README-windows.md). Feel free to close this otherwise, the issue itself might be enough documentation already.

**Comment by jberkenbilt** [comment]
Thanks for the report. I probably won't do anything with this...I think most people don't run the image comparison tests, and as you point out, it works with the latest ghostscript. The particular file in question is not compliant with the PDF spec, and some other viewers have trouble with it. Some viewers, including Adobe Reader, are able to handle it, and since files like this have been seen in the wild, I wanted to make sure qpdf could handle it.

I agree that this issue is good documentation -- if anyone else encounters it, hopefully they will find this issue, or if not, I will point them to it. Thanks again!
