### ISSUE TITLE
Split an input into multiple output files

### ISSUE THREAD

**Issue by spl** [qpdf/qpdf#30]
I may be missing the obvious, but is it possible to use qpdf to split a single PDF input into multiple PDF outputs, one per page range?

The [documentation on page selection](http://qpdf.sourceforge.net/files/qpdf-manual.html#ref.page-selection) refers to "splitting," but from what I can tell, there is always one output document. Every other PDF tool I've looked at (e.g. PDFtk, Poppler, Ghostscript, PDFTron, PDFLib) uses "splitting" to refer to breaking a file into multiple outputs, but the manual seems to refer to "splitting" as drawing from multiple possible inputs into one output.

I would like to know if there is a way to do this currently with qpdf. If so, can you give examples in the manual? If not, I propose it as a feature.

**Comment by jberkenbilt** [comment]
This is a frequently requested feature. I think I'll add something to do it from the main qpdf tool.

**Comment by Nokia808** [comment]
Hi. Thank you for fix. But I visited link for example above & not  understand how to apply it !

Does it as following ?:
a) to extract pages 4-10
$ qpdf input.pdf --pages input.pdf 4-10 --split-pages -- output.pdf

b) to extract all pages:
$ qpdf input.pdf --pages input.pdf l-z --split-pages -- output.pdf
where:
l = 1st page
z = last page

Could you, kindly, explain more ?

**Comment by clandmeter** [comment]
Would it be possible to add a feature so one can specify the page count to split the pages into? I have a few use cases where the split should happen every 1,2,3,4 pages so something like --split-pages 3 would split after each 3rd page.

**Comment by jberkenbilt** [comment]
I'll do the split-pages thing. I'll replace single-pages with split-pages and have an optional argument specifying the number of pages per group. I wouldn't change the interface after release, but there's been no released version with single-pages.

**Comment by jberkenbilt** [comment]
Okay, I'm going to push the change.

`qpdf --split-pages=5 11-pages-in.pdf out.pdf` will generate out-01-05.pdf, out-06-10.pdf, out-11-11.pdf.

**Comment by Nokia808** [comment]
Hi again. 

I did not understand command ! I feel that this out of the aim ?

Please to clarify confusion, kindly can you answer these point by point:

1) I have a PDF composed from 200 pages. I need to split ALL it's pages to individual PDF files (each page in a separate PDF file: totally 200 individual PDF files). So, what is the future command for that ?

2) I have a PDF composed from 200 pages. I would like to separate pages 5 - 150 ONLY into separated PDF files (file for each page). What is the command for that ?

3) I have a PDF composed from 200 pages. I like to split pages 1 - 5, page 11, page 60, pages 70 - 100 into MERELY individual pages. How to do this ? What is the command for that ?

4) regarding your example:
 pdf --split-pages=5 11-pages-in.pdf out.pdf 
will generate out-01-05.pdf, out-06-10.pdf, out-11-11.pdf.

2 points:
1st point: are you sure that this example correct ? Where is pages 6 to 10 range ??

2nd point (important): it lead that pages 1 to 5 will be in a SINGLE pdf output file ! But this is not the goal ! Our aim is pages 1 to 5 into 5 INDIVIDUAL pdf files (one for each page).
We have already an option to extract pages into a single output pdf file as following:
[[To extract a pages range of PDF to single PDF, with preserving their metadata:
$ qpdf input.pdf --pages input.pdf 1-10 -- output.pdf
To extract a pages range of PDF to single PDF, without their metadata:
$ qpdf --empty --pages input.pdf 1-10 -- output.pdf
To take pages 1–5 from file1.pdf and pages 11–15 from file2.pdf in reverse:
$ qpdf file1.pdf --pages file1.pdf 1-5 file2.pdf 15-11 -- output.pdf
Note: the page range is a set of numbers separated by commas, ranges of numbers separated dashes, or combinations of those. The character “z” represents the last page, while the character “l” represent the first page. Pages can appear in any order. Ranges can appear with a high number followed by a low number, which causes the pages to appear in reverse. Repeating a number will cause an error.
Example page ranges:
• 1,3,5-9,15-12: mean pages 1, 2, 3, 5, 6, 7, 8, 9, 15, 14, 13, and 12.
• you can specify single page only.
• z-1: mean all pages in the document in reverse.]]
This is what documented in the manual ! Isn't it or I'm wrong ? Please correct to me.

Best

**Comment by jberkenbilt** [comment]
1) to split a 200 page PDF into 200 individual one-page PDF files, you would run `qpdf in.pdf out.pdf --split-pages`. This would generate files `out-001.pdf` through `out-200.pdf`, each containing a single page.

2) To do the above but only on pages 5 through 150, you would run `qpdf in.pdf out.pdf --pages in.pdf 5-150 -- --split-pages`. The files would be called out-001.pdf through out-146.pdf because qpdf does all the page selection first and the splitting at the end. The result is what you would get if you did this in two separate commands.

3) To do the same but only with pages 1-5, 11, 60, and 70-100, you would run `qpdf in.pdf out.pdf --pages in.pdf 1-5,11,60,70-100 -- --split-pages`. This would generate out-01.pdf through out-38.pdf, each consisting of a single page in the order specified for the same reason is item 2.

Regarding my example that `qpdf --split-pages=5 11-pages-in.pdf out.pdf` would generate out-01-05.pdf, out-06-10.pdf, out-11-11.pdf, this is correct. Pages 6 to 10 are in out-06-10.pdf. The reason that each file here contains 5 pages is because `--split-pages=5` was given. The argument to `--split-pages` is the number of pages per file, and if not specified, it is 1. This is just a generalization of what I implemented the first time. You can achieve your goal of having individual single-page files by just specifying `--split-pages` without an option or by explicitly saying `--split-pages=1`. The enhancement did not remove the ability to create single-page files. It enhanced that with the ability to create multi-page files too.

Hopefully this clears up your doubts.

**Comment by clandmeter** [comment]
@jberkenbilt thanks a lot for adding this. What is your planning regarding the v7 release?

**Comment by jberkenbilt** [comment]
@clandmeter There are two google summer of code projects that are connected with qpdf. That period ends on Monday August 21. At that point, I will be focused on final integration work. I hope to get a release out shortly thereafter, possibly be the end of August or soon after.

**Comment by Nokia808** [comment]
Every think now is very clear ! Many thanks for this explanations !
