### ISSUE TITLE
qpdf consumes all my memory and crashes for a specific file

### ISSUE THREAD

**Issue by balaprassanna** [qpdf/qpdf#311]
I am using `qpdf version 8.4.0`
While running `qpdf --check-linearization qpdfhike.pdf`, qpdf consumes all the machine memory and crashes.

https://drive.google.com/file/d/15Fhh-Vk37YvDO7yh9tfFqHukHssVxTEr/view?usp=sharing

**Comment by balaprassanna** [comment]
Is there a way to limit maximum memory used by qpdf?

**Comment by jberkenbilt** [comment]
Sorry for the delay here. I see no reason that qpdf shouldn't be able to handle this file, but it is having trouble with it. This is similar to #311 I think. This file has 1364 pages and 168,523 objects, so it is similar in size to the other file. I will find some time to study why qpdf is taking so long. There's obviously some kind of performance problem here. Thanks for the report.

**Comment by NicolasGoeddel** [comment]
We got a similar issue here. On bigger PDFs (400+ pages, 10-20 MB) the qpdf process consumes more than 20 GB of RAM and then many other processes crash because of too less memory. In the end it is even hard to SSH into the machine and kill qpdf.

**Comment by jberkenbilt** [comment]
Addressing this is my top priority on qpdf right now.

**Comment by jberkenbilt** [comment]
There seem to be at least two separate problems here, but the two files (this one and #305) share a common attribute: object streams containing objects that are arrays containing a very large number of elements (like around 100,000). One thing is that qpdf's memory usage, which is intended to be nearly constant throughout file processing, actually grows with the number of object stream objects. This is the result of a design flaw that I should be able to correct. The other problem is that the parser seems to be intolerably slow for these very long arrays. I will have to study that a bit more. I'm hopeful that I can get the performance reasonable for these files though.

**Comment by jberkenbilt** [comment]
Also, just for the record, I ran this with a profiling build by launching an ec2 instance of type x1e.2xlarge (244 GiB RAM). It took 43 minutes and used 27.59 GB of RAM. So that's the starting point. I'm pretty embarrassed by this. Looking at the profile output, there's no obvious smoking gun. qpdf's liberal use of STL and smart pointers is taking its toll. I always favored readability, maintainability, and safety of the code over performance, but maybe it's time to do a little optimization. I was hoping I was going to find something dumb like an inefficient graph traversal, but in the end, it's just that qpdf is slow parsing certain types of things. I can certainly fix the memory issue, though it would probably be at the cost of even more performance. Anyway, I should be able to make some progress on this for qpdf 9, but I'm not sure how long it will take to make the performance acceptable. We'll see. Thanks for sharing the file. It's a big help.

**Comment by jberkenbilt** [comment]
Great news -- I've found a fix to the memory problem with this file. After my fix, the file uses about 534 MB instead of 28 GB. It's still slow, but also not anywhere near as slow. On my i9 with 16 cores, it takes under 4 minutes to run --check on the file. The fix will be in 9.0.0.

**Comment by NicolasGoeddel** [comment]
Where exactly can I find that fix? You have only linked changes to TODO, Changelog and qpdf-manual.xml.

**Comment by jberkenbilt** [comment]
I haven't merged it yet. This ticket will close when the change is in master. If you're not up for building from source out of github, you'll have to wait for the 9.0.0 release. I'm going to try to get it out as soon as possible. Unfortunately, it's a fairly substantive change since I completely reworked the internals of QPDF_Array (an internal class), and the changes use things that I've introduced since the latest release. If you're subscribed to qpdf-announce, you will get a notification when 9.0.0 is released.

**Comment by jberkenbilt** [comment]
@NicolasGoeddel Also you can find the automated builds from Azure Pipelines. This includes the regular source package with build documentation, Windows executables, etc. You can [download all the distributions here](https://dev.azure.com/qpdf/f24ef40e-3b5d-43d6-ac5d-40e46e203e50/_apis/build/builds/308/artifacts?artifactName=distribution&api-version=5.2-preview.5&%24format=zip), unzip this, and pull out the distribution you want. They will be called 8.4.2-ci but they are very close to what 9.0.0 will look like.
