### ISSUE TITLE
Introduce "Save" like option

### ISSUE THREAD

**Issue by Nokia808** [qpdf/qpdf#321]
To clarify this, let we take --decrypt:
Currently, if I have encrypted PDF - let we call it in.pdf - to decrypt it we need to use:

qpdf --decrypt in.pdf out.pdf

this is corresponding to "Save as with new name" option in GUI. But I can not perform:

qpdf --decrypt in.pdf
or
qpdf --decrypt in.pdf in.pdf
both are corresponding to "Save" option in GUI.

From that, currently, each step or operation in QPDF need to create new PDF. This needed in some situation. But in many other situation it is annoying to create many PDF files (each per process achieved by QPDF.

I wish that I was clear in my suggestion & in explain my idea. It is very excellent to make possible to do:
qpdf --decrypt x.pdf
as a correspondence to
qpdf --decrypt x.pdf x.pdf

This should not be limited to "--decrypt" option, but to all aspects & powers of QPDF. This will make QPDF highly easer. I used "--decrypt", just, as an example.

**Comment by jberkenbilt** [comment]
This is an often requested feature. I will think about how to do it. Right now, qpdf already knows how to detect when the output file is overwriting the input file, so it wouldn't be that hard to have it handle this case specially. Do you think it would be okay to require a flag like `--replace-input` to enable this? Another option might be to have some kind of flag that would indicate what to do with the original, such as to rename it with some kind of backup suffix, though this might be overkill.

**Comment by jberkenbilt** [comment]
I'm going to mark this as "next" so I don't forget to look at it again soon. I am hoping to get 8.4.1 with a few fixes out very soon, and it may not make the train for 8.4.1.

**Comment by Nokia808** [comment]
@jberkenbilt 
Dear I do not think that adding new flag is good idea because we are already many flags & commands of QPDF are long enough which make me asking repeatedly for GUI.

It will be much better to make it just:
qpdf --option x.pdf
to be "save" process in opposite to
qpdf --option x.pdf z.pdf
which is already "save as with name"

**Comment by mschilli87** [comment]
@Nokia808: I see your point but I think backwards compatibility is more important than usability here.
This can be easily be worked around by a wrapper (be it a shell alias, a CLI script or a GUI tool).

**Comment by jberkenbilt** [comment]
I'm not going to make qpdf willing to overwrite its input files by default, but I can make it detect when you try to do it and mention the new flag in the error message. If qpdf is going to annoy people, I would rather have it annoy people by making them type extra command line flags than by making it clobber people's files.

**Comment by ams-tschoening** [comment]
Two additional thoughts: If I read something like `qpdf --option x.pdf`, I expect output on STDOUT/STDERR first and I think that is a strong convention especially on Linux. Overwriting the input file instead would surely be surprising to many users familiar with that convention.

The second thing is remembering differences on OS/file system level: Shared access to files is forbidden by default on Windows and one needs to explicitly opt-in instead:

> dwShareMode

> If this parameter is zero and CreateFile succeeds, the file or device cannot be shared and cannot be opened again until the handle to the file or device is closed. For more information, see the Remarks section.

https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew

Remember the [UTF-8/Unicode-problems](https://github.com/qpdf/qpdf/issues/298) you had some months ago, so you might not want to introduce new features which too heavily rely on certain aspects of the used OS/FS.

**Comment by Nokia808** [comment]
@jberkenbilt 
Okay, I agree with you: add, kindly, this new feature by using additional new flag like:

qpdf --decrypt input.pdf --overwrite

or something like this ..........

**Comment by jberkenbilt** [comment]
If I do this, it would necessarily be something like writing a new file to a temporary location and then, at the end, overwriting the input file. It's the only safe way to do it, and qpdf requires access to the input file for the whole time it is working with it, so it can't be destroyed until the very end anyway.

**Comment by jberkenbilt** [comment]
I'm hoping to get qpdf 9 out today, but definitely this weekend. I'll include this feature. I'm thinking of this:
* If --replace-input is given, no output is given, so for example, you could run `qpdf --lineraize input.pdf --replace-input`
* If there are any errors parsing the file, the input file will be left alone.
* qpdf will write the file to input.pdf.~qpdf-temp. If there are any errors during creation of the output (rare), the temporary file will be retained.
. If the operation is successful, input.pdf will be renamed to input.pdf.~qpdf-orig, then input.pdf.~qpdf-temp will be renamed to input.pdf.
* If there were no warnings, input.pdf.~qpdf-orig will be deleted. Otherwise, it will be left behind for inspection.

I could make it more flexible, but I don't think I will. If people want more flexibility, they can script it. Since qpdf's exit code of 2 or 3 indicates errors or warnings, the behavior I decsribed could be easily scripted, and that would give people flexibility on names and locations of temporary files, etc. This feature will be geared more toward the casual user who just wants to overwrite some files.

**Comment by ams-tschoening** [comment]
Generally agree with your approach, just want to mention one thing: LibreOffice would use a naming scheme like e.g. `.~qpdf-temp.input.pdf#` instead what you suggest, so that the files e.g. are marked as hidden by default. Did you consider such a scheme as well, but don't want to use it by purpose? I can think of some reasons not using it, like simply grouping the files by their name. I only have the feeling that is a somewhat standard way to handle such things and should at least be considered.

**Comment by jberkenbilt** [comment]
@ams-tschoening Sure, I can do that. You caught me just in time.

**Comment by jberkenbilt** [comment]
I'll keep my convention for the orig file and use the other one for the temp file. If the orig file is left behind, it's because there was a potential problem, and the expectation is that the user may want to actually do something with it.

**Comment by jberkenbilt** [comment]
I'm not going to actually release for a few more hours, so I'm open to any arguments in favor of using a different convention for the orig file. I had considered trying to preserve the original suffix, but I think this will lead to trouble. I can just image `a.~qpdf-orig.~qpdf-orig.pdf`...

**Comment by jberkenbilt** [comment]
New behavior:
* write to `.~qpdf-temp.infile#`
* if warnings:
  * move orig to `infile.~qpdf-orig`
* else
  * move orig to `.~qpdf-orig.infile#`
  * move `.~qpdf-temp.infile#` to `infile`
  * delete `.~qpdf-orig.infile#`

Rationale: Use of hidden temporary files prevents flicker in file managers and so forth. Although QUtil::rename_file will overwrite a destination, adding the extra rename step in the no-warning case reduces the chances of a problem resulting from, say, a read-only file or a file the user doesn't have permission to delete. If the final delete fails, the cruft left behind will be a hidden file.

**Comment by jberkenbilt** [comment]
It was harder than it should have been to get this working in Windows. I had to add methods to the QPDF object to close the file....anyway hopefully the current implementation is clean and working. CI will tell momentarily. This is the last change before 9.0.0.

**Comment by rubyFeedback** [comment]
I found this indirectly.

I discovered --replace-input and I use it via rotate, to correct wrong .pdf
files. qpdf creates a backup file of the .pdf in the current directory; I use
ruby to automatically delete that backup file (in that particular use case
I want to flip all wrong .pdf files to their right position, then merge them;
having stray .pdf files even backups in the current working directory confuses
me).
