### ISSUE TITLE
qpdf 8.4.1 Heap corruption in qpdf_read

### ISSUE THREAD

**Issue by snoozamoorooed** [qpdf/qpdf#330]
Hello.
I've compiled qpdf 8.4.1 source code with MS Visual Studio 2017 and msys2 following instructions listed in README-windows.md
While using qpdf21.dll in Visual Studio in debug mode i've noticed an error after calling qpdf_read.
Debugger says something like that
Windows has triggered a breakpoint ... 
This may be due to corruption of the heap, which indicates a bug ...

After some digging i've found the line which causes that behavior.
It's in QUtil.cc near line 374
Here is that line
PointerHolder<wchar_t> wmodep(true, new wchar_t(strlen(mode) + 1));

It seems to me that statement new wchar_t(strlen(mode) + 1) allocates new single object of wchar_t instead of an array

The same thing with another parameter looks like this
PointerHolder<wchar_t> wfilenamep(true, new wchar_t[wlen + 1]);

Here is correct array allocation: new wchar_t[wlen + 1]
After changing line with wmodep variable to this
PointerHolder<wchar_t> wmodep(true, new wchar_t[strlen(mode) + 1]);
everything works fine.

**Comment by jberkenbilt** [comment]
Thanks for this report. Coincidentally I just became aware of this problem a few days ago in a private email. I will fix this and release 8.4.2. For the Linux build, I run full tests with a memory analyzer, but I have no such tool that I know for Windows. I will have to figure out how to do this kind of testing in that environment. In the mean time, I will fix the problem here. There are extremely few bits of code that are Windows-only, and pretty much all of them are in QUtil.cc.

**Comment by jberkenbilt** [comment]
@snoozamoorooed I pushed the fix to master. I will post a link to binaries here if you'd like to test. I have the other user also testing. This is worth doing a release for, so if all good, I will release it. I have made no other changes since 8.4.1.

**Comment by jberkenbilt** [comment]
https://dev.azure.com/qpdf/f24ef40e-3b5d-43d6-ac5d-40e46e203e50/_apis/build/builds/214/artifacts?artifactName=distribution&api-version=5.1-preview.5&%24format=zip
