### ISSUE TITLE
Split operation failing on a specific file

### ISSUE THREAD

**Issue by wmbutler** [qpdf/qpdf#331]
Unfortunately I'm unable to provide the source doc but when here is some output. If there is anything I can provide, I'm happy to get some additional info:

```
Bills-MacBook-Pro:test billbutler$ qpdf --check test.pdf
checking sullivan.pdf
PDF Version: 1.6
File is not encrypted
File is not linearized
WARNING: test.pdf (offset 418837): stream /DecodeParms length is inconsistent with filters
```

**Comment by jberkenbilt** [comment]
If you can send the output of `qpdf --json` on the file, that would be helpful. That way I can see the values of /Filters and /DecodeParms on the stream in question. It's hard for me to guess what the best way of dealing with this case is, unless the length of /DecodeParms is 1 and the length of /Filters is more than 1. Or maybe /DecodeParms contains values that only pertain to one of several applied filters.

That part of the code is pretty old. If the json output is not clean enough for you to send, I can just go through that part of the code and take my best guess at tightening up the error recovery and see if it helps.

**Comment by wmbutler** [comment]
It's a 10,000 page file so.... let me know if you still want the output :)

**Comment by jberkenbilt** [comment]
Compressed, I suspect the output would be very small. qpdf's json output should compress into almost nothing, especially if compressed with a modern compression tool like xz. To be fully useful, I would also need the xref table, which you can get with `--show-xref`. However, you can actually get the exact information with a little work. Using `--show-xref` and a little shell work, you can figure out which object is at offset 418837, then you can use `--show-object` to get the object, which will exclude stream data. From there, we can see the actual values of `/Filter` and `/DecodeParms`.

To get the object from the offset, you'd just have to find the object with the highest offset less than or equal to 418837. Since this is a stream, we can disregard object stream objects. Objects are not necessarily in numeric order in the file, so you'd have to sort by offset. Something like this would work:

```
qpdf --show-xref file.pdf | grep offset | sort -n -k 5
```

From there, you can easily find the object in progress at offset 418837. Given that information, I can probably see what's going on. It would be useful to see the first few bytes of the stream data too so I can see what the truth is about the encoding. Hopefully the first few bytes won't contain any sensitive information. For example, if the object shows as 4520/0 in the xref output, you could use

```
qpdf --show-object=4520,0 file.pdf
```

to get the stream dictionary and

```
qpdf --show-object=4520,0 --raw-stream-data file.pdf | dd bs=1 count=50 | od -t x1
```

to get a hex dump of the first 50 bytes, which is hopefully enough to be able to validate which filters are in use.

Note that `--show-xref`'s output is object/generation, where `--show-object` takes object,generation. If the generation is 0 (which it almost always is), you can omit the generation entirely, show `--show=object=4520` would have worked fine in the above example.

If you can provide this much information, I can let you know if I have any follow-up questions. If you don't want to provide the first 50 bytes of the data, just provide the stream dictionary, or even just the `/Filter` and `/DecodeParms` keys. That may be enough.

**Comment by wmbutler** [comment]
I'll get this to you soon. Thanks!

**Comment by wmbutler** [comment]
Offset <= 418837:
```
27/0: uncompressed; offset = 418671
```

```
BBUTLER-MAC:Documents bbutler$ qpdf --show-object=27,0 file.pdf
Object is stream.  Dictionary:
<< /BitsPerComponent 8 /ColorSpace [ /ICCBased 28 0 R ] /DecodeParms [ ] /Filter [ /DCTDecode ] /Height 3304 /Length 924131 /Subtype /Image /Type /XObject /Width 2550 >>
```

```
BBUTLER-MAC:Documents bbutler$ qpdf --show-object=27,0 --raw-stream-data file.pdf | dd bs=1 count=50 | od -t x1
50+0 records in
50+0 records out
50 bytes transferred in 0.000141 secs (354249 bytes/sec)
0000000    ff  d8  ff  e0  00  10  4a  46  49  46  00  01  01  01  01  2c
0000020    01  2c  00  00  ff  db  00  43  00  04  02  03  03  03  02  04
0000040    03  03  03  04  04  04  04  05  09  06  05  05  05  05  0b  08
0000060    08  06                                                        
0000062
```

**Comment by jberkenbilt** [comment]
Perfect, thanks. Okay, this will be trivial to fix. The stream is a normal JPEG stream, and /DecodeParms is an empty array. I will just have to add a trivial amount of code to treat an empty /DecodeParms array as if the parameter is absent. It will definitely be in the next release. Would you like a patch in the mean time?

**Comment by jberkenbilt** [comment]
[313-patch.txt](https://github.com/qpdf/qpdf/files/3233692/313-patch.txt)

**Comment by jberkenbilt** [comment]
Patch attached. Here it is inline. I will update this with proper testing, etc., but if you apply this patch, it should get you by for now. It should apply cleanly to any recent version.

```patch
diff --git a/libqpdf/QPDF_Stream.cc b/libqpdf/QPDF_Stream.cc
index 3733940..3ddb149 100644
--- a/libqpdf/QPDF_Stream.cc
+++ b/libqpdf/QPDF_Stream.cc
@@ -391,6 +391,10 @@ QPDF_Stream::filterable(std::vector<std::string>& filters,
 
     QPDFObjectHandle decode_obj = this->stream_dict.getKey("/DecodeParms");
     std::vector<QPDFObjectHandle> decode_parms;
+    if (decode_obj.isArray() && (decode_obj.getArrayNItems() == 0))
+    {
+        decode_obj = QPDFObjectHandle::newNull();
+    }
     if (decode_obj.isArray())
     {
         for (int i = 0; i < decode_obj.getArrayNItems(); ++i)
```

**Comment by jberkenbilt** [comment]
Note to self: for the full fix, consider also detecting this in QPDFWriter and deleting /DecodeParms at write if it is an empty array.

**Comment by wmbutler** [comment]
We will wait for the next version rather than compiling the patch.
