### ISSUE TITLE
[RFE] Configure option defining which encryption key lengths are permitted

### ISSUE THREAD

**Issue by zdohnal** [qpdf/qpdf#358]
Hi,

I was thinking about QPDF encryption features, because our crypto people would like to get rid MD5 hashes, RC4 ciphers and other things they mark as security risk and I think the permission of only certain key lengths are allowed would cover their use case, but I'm not sure if it is something what QPDF project would like.
What is your opinion on the topic? Could QPDF benefit from such configure options (like --disable-encryption-keys-40b, --disable--encryption-keys-128b), if I will prepare the patch for it?

**Comment by jberkenbilt** [comment]
I don't think I would accept that patch. From a philosophical approach, I have avoided any compile-time configuration that might make one build of qpdf incompatible with a different build of qpdf. It is possible to configure qpdf with different random number generators, but using a different random number generation algorithm does not change the behavior of qpdf in any way that users would be able to detect. That's enough of a reason for me to not want to accept such a change, but there are also other reasons.

One of the big uses of qpdf is to convert PDF files into formats that can be read in environments that aren't modern. This can be important for people generating PDF files for testing purposes as well. For example, there is one user whom I have talked to privately on many occasions who uses qpdf in a tool that looks for malware embedded in PDF. Also I have myself used qpdf to generate files with supported but unusual combinations of features and have found many bugs in many PDF readers. I also have a strong compatibility guarantee. I know for sure that there have, at times, been people who have used qpdf to decrypt encrypted files and re-encrypted them with older formats so they can be read with older viewers. qpdf was one of the first open source tools to support 256-bit encryption and is still one of very few that supports the undocumented /R5 encryption format used by only one version of the Acrobat products. However, now-a-days, there are almost no reasons for normal people to care about this because virtually every PDF tool that's actively maintained supports 256-bit keys. For real security, you shouldn't rely on PDF encryption though.  Even the PDF spec tells you this.

That said, I'd certainly be open to discussing approaches. For example, I would be open requiring an additional argument from the qpdf CLI such as --allow-insecure-crypto that has to be provided at runtime or maybe even a library routine that has to be called to enable QPDFWriter to generate insecure crypto.

Another challenging here is qpdf's deterministic ID feature. There are some people who rely on the fact that qpdf --deterministic-id will generate the same ID when qpdf is run in exactly the same way with exactly the same options. This uses MD5 under the covers, and if I change the implementation, it will break the deterministic ID guarantee for existing files. Deterministic IDs are not intended for cryptographic security and are, in fact, disallowed when creating encrypted files.

Thoughts?

**Comment by zdohnal** [comment]
What I had on mind was only the configure affecting only --encrypt option - that means the change should only affect encrypting a new pdfs - it should still allow to decrypt old pdf which were crypted by old hashes/ciphers (according to crypto people), and deterministic ID feature is not cryptographic use case according their standards, so it will be allowed. Which covers compatibility in my opinion.
Their main concern is to not create more weak crypted files.

> That said, I'd certainly be open to discussing approaches. For example, I would be open requiring an additional argument from the qpdf CLI such as --allow-insecure-crypto that has to be provided at runtime or maybe even a library routine that has to be called to enable QPDFWriter to generate insecure crypto.
IMO the both are great - if qpdf/libqpdf will use stronger crypto for encrypt by default and weaker ciphers will require --allow-insecure-crypto. 
This option will set new private attribute of QPDFWriter - insecure_crypto - to true (through public method), which will be false by default. The attribute can be checked in setRXEncryptionParameters and when user will want to use weak crypto and attribute is false, it will raise a exception.

What do you think?

**Comment by jberkenbilt** [comment]
Sorry, it looks like I lost track of this, but it came back to my mind, and I am going to implement something for qpdf 10.4 (to be released very soon) that will warn at least in some cases.

**Comment by jberkenbilt** [comment]
My plan:
* qpdf 10.4.0 will warn from the CLI if RC4 is in use unless the `--allow-weak-crypto` flag is passed.
* Hopefully qpdf 11 will also be able to protect at the library level as well. Doing that reliably will require an API change, so I can't do it without a major release. Rather than have the library warn (which is really bad manners), I was thinking of making a non-compatible API change like renaming the functions for weak crypto to include Insecure or Weak or something in them. I have it on my ABI list for qpdf 11. I hope to work on that soon.

**Comment by zdohnal** [comment]
Hi Jay,

thank you for looking into it! My concern behind the issue was qpdf to be able to work/recover if some hashes and algorithms are disabled by crypto-policies package (which governs over big crypto providers - openssl, gnutls, nss - disabling ciphers based on crypto community decisions, which ciphers/hashes aren't secured enough. f.e. ARCFOUR-128 cipher is disabled in TLS connections by default in Fedora 34).

One of the ways which are acceptable for crypto people is preventing of creation a new files with weak encryptions, but have the weak encryptions around for decrypting old files, which already use the weak encryptions. I brought up this RFE to check whether it is possible to implement this approach in qpdf.

Ad the plan:
It would be great if qpdf failed when RC4 is requested for encryption or when MD5 is chosen for hashing a key, unless ```--allow-weak-crypto``` is passed - but a warning, which will turn into an error in the future, is okay as well... I wouldn't print the warning during decryption though.
Ad the API changes - sounds good!

**Comment by jberkenbilt** [comment]
There's no risk that qpdf itself will completely stop working. Since qpdf includes its own internal implementations of all the crypto algorithms, so worst case, I could add runtime autoconf checks for whether the various crypto functions are working and fall back to internal rc4/md5 if needed while still delegating AES, SHA, etc. to gnutls or openssl. I just added openssl3 support to qpdf, and there, you have to jump through extra hoops to get rc4 and md5, but the code does that, so we should be good unless someone builds without support for those. I can't imagine MD5 support is going anywhere anytime soon -- it's just in too widespread use.

I think I can probably disable creation of new rc4 without a flag. There's already an `--allow-insecure` flag that you have to use if you want to create a file with 256-bit encryption, an empty owner password, and a non-empty user password. Rather than adding yet another flag, I can just make that flag required also for using rc4 encryption. Avoiding md5 is harder because of the deterministic ID feature. I'll probably have to take the same approach of giving a warning/error from the CLI and changing the library to add a new deterministic ID feature while renaming the functions. So, maybe in qpdf 11, QPDFWriter::setDeterministicID could be changed to setMD5DeterministicID and a new setSHA256DeterministicID could be added. My goal is always to make adjusting for non-compatible API changes require only localized changes.

The only place I'm thinking of not complaining is when you just use qpdf without specifying any encryption arguments at all if the input file uses insecure encryption. In that case, qpdf copies the encryption parameters from the old file, though it does already take the liberty of changing 128-bit with RC4 to AES. So the plan will be to require `--allow-insecure` for any explicitly requested encryption that uses RC4 or MD5. For preserving existing encryption, I'll have to decide whether to give a warning or just remain silent, but my impulse is to just remain silent. I'll have to review that part of the code.

I'm planning on closing this issue with a merge for 10.4, but I'll open a separate ticket for the API changes and tag you on it, or if you want to be the owner of the issue, then you can go ahead and create an issue now requesting API changes to discourage use of weak crypto.

This is the last ticket I'm planning to work for 10.4 unless coincidentally some bug comes in in the next few days. Once I have this nailed down, I'll release. I'm happy to run it by you before I release to make sure you think the incremental step in 10.4 is satisfactory.

**Comment by jberkenbilt** [comment]
Leaning toward the "warning now, error later" solution.

**Comment by jberkenbilt** [comment]
Some of the above may change a little. I will summarize when I'm done with the change rather than updating each time I think of something.

**Comment by jberkenbilt** [comment]
What I am ending up with:
* `--allow-weak-crypto` is a top-level argument. I can't reuse `--allow-insecure` because that is inside of `--encrypt ... --`.
* In 10.4, `--allow-weak-crypto` suppresses a WARNING that is issued if the user explicitly requests 40-bit keys or 128-bit keys without AES (both of which use RC4) from the command line. No warnings are issued by the library.
* Added a section to the manual discussing weak crypto and how qpdf will deal with it
* This bug will be closed by that change.

For qpdf 11, my plans are
* Make it an error to try to create files with weak crypto from the CLI or the library without explicit acknowledgment. This will most likely be implemented by adding a QPDFWriter::allowWeakCrypto method or similar and having it raise an exception if any attempt is made to write using insecure crypto without calling it
* Have the CLI call that method when `--allow-weak-crypto` is called and probably also when just transforming a file that happens to be encrypted with weak crypto when no encryption flags are in use.
* Other details are in the TODO file.

I will open a new github issue to track.

**Comment by jberkenbilt** [comment]
@zdohnal I'm closing this issue now, but until I actually release 10.4, it's not too late to tweak. But I think the plan is pretty solid now. I will probably get 10.4 out in the next few days, maybe even tomorrow.
