### ISSUE TITLE
What's your take on binary compatibility?

### ISSUE THREAD

**Issue by tsdgeos** [qpdf/qpdf#374]
Asking because i found out QPDFPageObjectHelper::placeFormXObject where the std::string should be passed by const & for optimal performance but it is not.

Changing it will break the binary compatibility of that class/method.

Is it something you care and i should not change it (maybe create a MR saying "TODO change it when we break binary compatiblity") or it's fine to break it and i can create a MR changing it?

**Comment by tsdgeos** [comment]
Also is there a better place to ask this than here?

**Comment by jberkenbilt** [comment]
Yes, you are right -- it seems like this should have been a std::string const&. I must have been having a bad brain day. Creating this issue here is perfect. I will just add this to the list of things to change the next time I break ABI (e.g. 10.0.0). You could do a PR that requests it, but just creating the issue is better so that I can follow my undocumented convention for noting these. I'll mark this "next" so I'll be sure to get to it.

**Comment by jberkenbilt** [comment]
I've added this to the list in TODO and will remove the next label from this issue. This will get done with the release of qpdf 10, whenever that is.

**Comment by jberkenbilt** [comment]
I have to break ABI for another change, so this is going in.
