### ISSUE TITLE
--linearize has unneeded whitespace in dictionary objects

### ISSUE THREAD

**Issue by bulk88** [qpdf/qpdf#379]
qpf created PDF files have dict objects that have unnecessary whitespace in dictionary objects. --linearize in qpdf should be extra conservative on whitespace since the output is not to be human read usually. Acrobat when emitting PDFs writes smaller dict objs with minimal whitespace. Check example files, blank.pdf is pretty printed before. Then I attached acrobat vs qpdf minified PDFs.

Acrobat
```
9 0 obj
<</CropBox[0 0 612 792]/Parent 4 0 R/Contents 10 0 R/Rotate 0/MediaBox[0 0 612 792]/Resources<</XObject<</Fm0 12 0 R>>>>/Type/Page/LastModified(D:20191028192537-04'00')>>
```
Qpdf
```
9 0 obj
<< /Contents 11 0 R /CropBox [ 0 0 612 792 ] /LastModified (D:20191028192537-04'00') /MediaBox [ 0 0 612 792 ] /Parent 1 0 R /Resources << /XObject << /Fm0 12 0 R >> >> /Rotate 0 /Type /Page >>
```

**Comment by bulk88** [comment]
[blank.pdf](https://github.com/qpdf/qpdf/files/3781095/blank.pdf)
[blank_acro_linearize.pdf](https://github.com/qpdf/qpdf/files/3781096/blank_acro_linearize.pdf)
[blank_qpdf--linearize.pdf](https://github.com/qpdf/qpdf/files/3781097/blank_qpdf--linearize.pdf)

**Comment by jberkenbilt** [comment]
You are correct that qpdf creates extra white space in these cases, but I am not going to fix it. The additional whitespace is harmless and adds negligible size to most PDFs, especially if object streams are used. Changing this now would change the output qpdf generates in very many cases, which could be quite disruptive to users who are relying on some consistency in the output. Basically I want to avoid making any sweeping changes that aren't necessary.

Thanks for your suggestion and observation and taking the time to report. I am going to close this since it is not something I intend to fix.
