### ISSUE TITLE
[Feature Request] Exit code for --show-encryption

### ISSUE THREAD

**Issue by mplx** [qpdf/qpdf#390]
When calling `qpdf --show-encryption` on a encrypted pdf file it show the encryption data and exits with code 0.

Using it on an unencrypted file it outputs `File is not encrypted` and also exits with exit code 0.

```
qpdf --show-encryption --show-encryption-key unencrypted.pdf
File is not encrypted

echo $?
0
```

When using qpdf from within an script the only option is to parse the output to differ between encrypted and unencrypted pdfs where it would be much easier if the exit code was <>0 (it even can be considered an error case if using the show command on unencrypted pdf files).

Feature request:
set exit code <>0 when using `--show-encryption` on files which are not encrypted.

**Comment by jberkenbilt** [comment]
This is a great idea, and I think it's important to have scriptable options that don't rely on parsing output. I can't implement it as you suggest because doing so would break backward compatibility, but I can give you two other options:

* Have `qpdf --is-encrypted` exit with 0 if encrypted and 1 if not encrypted, making it possible to say `if qpdf --is-encrypted file.pdf; then ...; fi`
* Add another json key that will have an always-present boolean indicating whether the file is encrypted and will expose information about the encryption (basically what's in show-encryption) in a predictable, backward-compatible way

These are both easy features, so I will add them for the next release. Thanks for the suggestion.

**Comment by mplx** [comment]
Sounds great - thanks very much! :)

**Comment by jberkenbilt** [comment]
Based on comments in #159, I will also make sure there is a way to test whether a file is password-protected. `--is-encrypted` will exit 0 if the file is encrypted, whether password-protected or not. `--is-password-protected` will exit non-zero for both encrypted files that don't need passwords and for non-encrypted files. I'll find a way to represent both values in json as well. I'll give some thought to making it possible to classify a file into one of three categories with a single qpdf invocation: 1) not encrypted, 2) encrypted but no password, 3) password required. I plan to get to this in the next few days and it get it out for 9.1.1. Maybe `--is-password-protected` could have a different non-zero exit code for the encrypted and non-encrypted case. I'll have to given some thought to the json data, but it should contain the same information as `--show-encryption`.

**Comment by jberkenbilt** [comment]
The option will be `--requires-password` rather than `--is-password-protected` and can be used to check the correctness of a supplied password. Details will be in the docs when the feature is completed.
