### ISSUE TITLE
Page Rotate - feature request

### ISSUE THREAD

**Issue by jvenator** [qpdf/qpdf#41]
Feel free to slap this down with vigor :)

I've been thoroughly searching the space for server-side PDF solutions, and qpdf is really solid. I think adding page rotation would be a logical and valuable feature addition. Trim, split, merge re-order and rotate are the basic things many users/programs need to do with a PDF. They represent modifications of the page containers/document container without modifying the content. Filling in forms, annotations, etc. is definitely a different level of interaction.

I think with page rotation added (and possibly form flattening) qpdf would be one of the best options available for getting a PDF into the desired order and optimized state for distribution.

**Comment by jberkenbilt** [comment]
I pretty much agree with all your points. I think it would be pretty easy to implement page rotation using qpdf. It could be done in just a few lines of code. It's unlikely that I will have time to add the enhancement to qpdf itself anytime soon as I barely have any time right now to work on qpdf. I have a long list of enhancements I want to make.

The pdftopdf program that's part of the cupsfilters package used by open printing may already implement page rotation using qpdf. Anyway, I'll leave the issue open and, rather than slapping down with vigor, will just gently say that you shouldn't hold your breath. In a few years hopefully I will have a bit more free time again and will be able to push forward on some of the requested features or things I want to do. For now, I'm staying on top of bug reports but am not doing much with enhancements.

Thanks for the comments and suggestions!

**Comment by Quasilyte** [comment]
If you need an example, here it is:
https://github.com/qpdf/qpdf/pull/88

**Comment by jberkenbilt** [comment]
I'm going to close this in favor of #88 and #89. Thanks!

**Comment by jberkenbilt** [comment]
I think I am going to add this to qpdf 7.0.0.

**Comment by jberkenbilt** [comment]
See #132
