### ISSUE TITLE
Can QPDF manipulate "header" & "footer" of PDF?

### ISSUE THREAD

**Issue by Nokia808** [qpdf/qpdf#412]
Hi. I would like to ask: can QPDF be used to manipulate header & footer in PDF?
I mean by that: adding footer, adding header, remove already existing footer, remove already existing header from PDF.

If yes, then can you, kindly, explain how?

**Comment by jberkenbilt** [comment]
PDF doesn't have any concept of header and footer, so there's no way that qpdf could systematically manipulate these per se. However recent versions of qpdf do support overlay and underlay. If you had a file that rendered footers for your pages in a manner that didn't obscure what was below them, you could use the overlay feature to add headers or footers. However removing headers or footers would not be possible in general. If you were trying to do it with a specific file, you could always cover up the header and footer with an opaque rectangle, but that's not a real solution.

Reminds me of a classmate in college who didn't want a page number on the first page. The thesis was written using LaTeX. I helpfully pointed out that she could put `\thispagestyle{empty}` at the top of the document to suppress the first page number. She said, "I have another way to suppress the page number," and pulled a bottle of white-out out of her bag. Always stayed with me for some reason.

**Comment by vstepaniuk** [comment]
You can try converting your PDF to Word (with Microsoft Word or OneDrive) and them removing them (in some word processing software) and saving back to PDF, or indeed redact/crop them..

**Comment by jberkenbilt** [comment]
qpdf can't do anything on headers and footers specifically because there is no PDF concept of header or footer. It's just marks on a page. A PDF expert could use qpdf to convert the PDF to qdf format and edit it in a text editor if you're lucky, but the thing you'd be editing would not be text but code. In most cases, the text is not even recognizable as matching the text on the page. I have successfully done many transformations on PDF files manually in an editor aided by qpdf, such as removing headers, footers, or watermarks, but this is me as an expert using qpdf to help with the bookkeeping aspects of the file format, not qpdf having any intelligence about headers and footers.

There may be other tools out there that allow editing a PDF file like a word processing document, but these either work by treating the PDF more like a graphics file and allowing you to work with the things that are on the page, including being aware of fonts and characters, or they are very sophisticated pieces of software (like Acrobat) that are performing lots of logic, effectively reverse engineering the page. Certainly the problem of recognizing and decoding strings of text is not that complicated, so it wouldn't surprise me if there aren't several tools that can do this to varying degrees.

Also, note that I am describing a general case. There are certain patterns that can be exploited in many PDF files that would make results pretty good even with fairly simplistic approaches. Anything that can convert a PDF file to Word (or Google docs or similar) is applying logic to infer the semantics of the page. But in any case, qpdf doesn't do anything like that, at least for the foreseeable future.

**Comment by jberkenbilt** [comment]
Heh, I just typed all that without remembering that I had already replied to this. Sorry for the duplication. At least I'm consistent.

**Comment by jberkenbilt** [comment]
I'm going to close this because it is not something qpdf is likely to be able to do.
