### ISSUE TITLE
boringssl random data provider

### ISSUE THREAD

**Issue by deanscarff** [qpdf/qpdf#418]
BoringSSL is Google's fork of openssl, see: https://boringssl.googlesource.com/boringssl/

I'm considering implementing a RandomDataProvider based on BoringSSL's RAND_bytes: https://commondatastorage.googleapis.com/chromium-boringssl-docs/rand.h.html#RAND_bytes
I expect it will be compatible with openssl.

I can send a PR if you're interested in merging it in... though this doesn't seem to be quite as pluggable as crypto right now.  Let me know if there's a particular pattern for the configure/preprocessor symbols you'd prefer.

**Comment by jberkenbilt** [comment]
The random data provider code is much older than the crypto code and was never intended to be selectable at runtime. It was just a fallback, and I should probably remove the insecure bit altogether. My impulse on this would be to actually move the random number service into the crypto provider. At this point, I have a hard prohibition of adding compile-time selection of implementations that make it impossible for me to ensure that all code in the system is always built and tested when I run CI on Linux, mac, and Windows. Also bear in mind that nothing in the public API (anything in include/qpdf) can see any preprocessor symbols from config.h. This is intentional.

Note that, for a specific case, you can always provide your own random data provider as described in the top-level README.md. I actually implemented this change for someone who uses qpdf for an internal product whose customer had a hard requirement to use a specific random number implementation.

As an alternative, if you implement a RadomDataProvider based on boringssl and we don't make a change at how the random data stuff works, there are two things I could in the short term: 1) create a contrib directory in which you could put your provider and sample code that uses it, or 2) link in the documentation to a place where you make that available.

Another option would be to make the random data provider pluggable at runtime like the crypto is. This would probably be my approach if we want general support for building with different random data providers.

**Comment by jberkenbilt** [comment]
I think I'm going to rework the random stuff to make crypto work. It should be a very small change. If it goes well, I'll get it in for 10.

**Comment by jberkenbilt** [comment]
In qpdf 10, the crypto provider will be the default source of random data.

**Comment by jberkenbilt** [comment]
Thank you once again for providing this idea and pointing me to how to do with openssl.

**Comment by jberkenbilt** [comment]
As an added bonus, this is actually more performant than what was previously there. :-)
