### ISSUE TITLE
unable to acquire crypt context with new keyset: error number 8009000f: Object already exists.

### ISSUE THREAD

**Issue by smiles3983** [qpdf/qpdf#432]
What does this error mean when trying to encrypt:

unable to acquire crypt context with new keyset: error number 8009000f: Object already exists.

**Comment by smiles3983** [comment]
Figured it out.  The RSA key that gets created isnt deleted after encryption is done.  So another user on that same machine cant encrypt because they dont have any acccess to that keyfile.  IMO, the key here should get deleted after the encryption is finished:  C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\3310a4fa6cb9c60504498d7eea986fc2_848c9f64-ec57-4922-ada2-30b5890172f8

**Comment by smiles3983** [comment]
will they always start with 3310?

**Comment by jberkenbilt** [comment]
This problem with qpdf's random number generation has been a thorn in the side of qpdf for Windows for a long time. Since I am not a Windows developer, I have never really gotten to the bottom of it. In 10.0.0, which I just released recently, random numbers are provided by the crypto provider. The Windows build still uses the native crypto provider, but I hope a future Windows build will generate crypto, and therefore random number generation, to either openssl or gnutls, at which point hopefully this issue will be gone. In the mean time, I'm afraid I'm not able to provide any help with this particular problem.

**Comment by smiles3983** [comment]
is there a way to tell the windows crypto provider to dispose of the key (delete the file) when your done?

**Comment by jberkenbilt** [comment]
Not at present. I didn't even know that was a thing. :-( This is the *one* part of the qpdf code that was contributed and that I don't understand as well as if I had written it myself. That's why I'm eager to switch to one of the libraries. However I would still accept patches to that part of the code.

**Comment by smiles3983** [comment]
@Cloudmersive

**Comment by jberkenbilt** [comment]
@smiles3983 In case you didn't see, @oltolm has offered a fix to the crypt problem. Hopefully that will help whenever the next qpdf release is out.

**Comment by smiles3983** [comment]
thanks @oltolm!!
