### ISSUE TITLE
Using qpdf it's possible use urls as source and destination?

### ISSUE THREAD

**Issue by neo7BF** [qpdf/qpdf#434]
I'm sorry if this it's not a correct place where to ask a question.
I would like to avoid using the disk for reading / writing (at least not the one where the process runs).
Is it possible to use it in this way?
`qpdf [options] infilename [outfilename]`

where:

`infilename `= http://myserver:8080/in.pdf
`outfilename `= http://myserver:8080/out.pdf

or

`infilename `= \\\\mylanfolder\in.pdf
`outfilename `= \\\\mylanfolder\out.pdf

Thanks

**Comment by jberkenbilt** [comment]
The second form should look like just local files to qpdf, so that should work. The first form is not possible from the CLI and is not something I will plan to add since I don't want to have to build HTTP client support in or add additional dependencies. Also, qpdf needs the input to be seekable, meaning that the whole input has to be available to it at once.

All that said, it wouldn't be hard to write an external program either in C++ or in Python with the pikepdf module that would read from a URL into memory, have qpdf process from the memory buffer, which is already there in the library, write its output to a memory buffer, and then send the memory buffer to the output location. However writing to a URL requires some kind of application on the receiving side, so it would be application-specific.

**Comment by neo7BF** [comment]
Thanks for the reply
