### ISSUE TITLE
Apply the same page range to several input documents

### ISSUE THREAD

**Issue by pagiraud** [qpdf/qpdf#440]
Hi,
Thank you for this great piece of software. I use it for a few months in replacement of pdftk and I'm very happy with it.
But, right now, I'm facing a problem. I was looking for a way to easily concatenate a bunch (34) of PDF files without their respective first page.
So, I thought of something like : 
qpdf --empty --pages *.pdf 2-z -- out.pdf
But it turned out the first page was removed only from the last file of the list…
It think it would make more sense if the page range applied to all the files implied by the star.
Best Regards,

**Comment by jberkenbilt** [comment]
@pagiraud Hello. Thanks for your comments and suggestions. There's no way really implement the idea of having the page range apply to all files matched by the star without breaking compatibility. Wildcards are expanded by the shell, so there's no way for qpdf to even know whether a wildcard expression was given or whether each file was listed out. I suppose it might be possible to modify the command line syntax in a way that would explicitly tell qpdf to treat a single page range at the end of a list of files as applying to all the files, but this would add complexity to what is already a very complicated command line interface.

However, you can still do what you want to do in other ways. I'm not sure whether you're in Windows or a UNIX-like (Mac/Linux) environment. If you run from bash (in any platform, including Windows, you could run something like this:

```
qpdf --empty --pages $(for i in *.pdf; do echo $i 2-z; done)  -- /tmp/out.pdf
```

In the above example, I used /tmp/out.pdf rather than out.pdf because I wouldn't want a subsequent run of the same command to unintentionally match out.pdf on the input. But if out.pdf doesn't exist when you run the command, the shell will expand the loop before qpdf creates out.pdf, so it would still work.

There may be a way to do this from the cmd prompt in Windows. I'm not enough of a Windows shell expert to know. I'm sure it would be possible to write a .bat script that would do this, but modern versions of Windows have bash available, I think. I don't know PowerShell, but I'm sure there must be a way to do it in PowerShell too.

I hope this helps.

**Comment by pagiraud** [comment]
@jberkenbilt Thanks a lot for your answer. It helps me a lot, both to achieve what I wanted and to understand why it is not already implemented in qpdf.
I can live with that solution. :) I close the issue.
Best regards,
