### ISSUE TITLE
ParserCallbacks - Timings

### ISSUE THREAD

**Issue by drcdr** [qpdf/qpdf#442]
I'm using ParserCallbacks to do stream parsing, and I'm looking at trying to improve the performance timings.  It appears that a lot of time is spent in QPDF outside of handleObject(), and I'm trying to figure out what to do next.  (I'm using QPDF libraries, not building from source.)

On one PDF file I've been using, times using std::chrono::steady_clock are:
- parsePageContents(cb): 273 ms total
- cb::handleObject(): 60 ms total

As part of that, I've separately timed just the stream extraction of all of the relevant page /Contents streams (using pipeContentStreams) and that's 1.8 ms.

So, about 273-60-1.8 = 210 ms is in QPDFObjectHandle::parseContentStream_data(), outside of cb::handleObject(). 

I'm not sure how to proceed with potential optimization.  Are there any "simple" things that you can think of that could be done?

**Comment by jberkenbilt** [comment]
@drcdr It's funny you should bring this up. In my TODO file on my work branch (not yet in master), I have notes about optimizing the lexical layer of qpdf. I have not done detailed performance measurements, but I have a strong suspicion that a lot of the performance issues with the qpdf library stem from the lexer (QPDFTokenizer) being inefficient. It's not super bad....but there's a lot of function call and string copying overhead that could be improved. It is my intention for an upcoming release to put some energy into optimizing it. However, that's going to be tricky, and it's unlikely I would accept a pull request because I am going to want to think hard about the API, and it will dig deep into the library internals.

As far as simple things, if you are on Linux or another UNIX variant (possibly including macos), you might consider using mmap on your input file and using processMemoryFile to read the file. I have never tried this myself, by I think it should work fine. Alternatively, could read the whole file into memory and use processMemoryFile. qpdf can in some cases read the same parts of a file multiple times, especially where streams are involved, because its default behavior is to keep memory usage low even for very large files.

If you have any performance benchmarking you'd like to share, I can keep it in mind when doing optimization. With the release of 10.0.0, I added a bare bones performance checking script, checked in as performance_check, that runs the qpdf command line with various flags and times how long it takes. It's not very granular, but I would be expanding it somewhat to be able to get timings separately on the lexer. If you have any sample code you could share, I could possibly use it as I measure and try to improve performance.

As always, I have no time commitment on any of this. qpdf is mostly a spare time project for me. But the release of 10.0.0 was focused largely on performance, and I am definitely interested in trying to make qpdf more efficient in coming releases. The code base is sufficiently mature at this point that it's worth optimizing some of the code paths that get heavier use.

**Comment by drcdr** [comment]
Thanks for the quick response, your explanation of QPDF tradeoffs makes sense.  For now, I'm on Windows 10.  I did a quick test, enabling one or the other of:
```
#if 1  // File Based
    pdf.processFile(filename.c_str());
#else  // Memory Based
    std::vector<char> filebuffer = readfile(filename.c_str());
    pdf.processMemoryFile("filebuffer", filebuffer.data(), filebuffer.size());
#endif
```
If I use the shorthand "lexing time" for (parsePageContents(cb)-cb::handleObject), then the average results over several timing runs for each approach is:
- memory-based approach: total time = 325 ms, lexing time=212 ms
- file-based approach: total time = 347 ms, lexing time=219.5 ms
- savings: 6.5% on total time, 3.4% on lexing time.

This is just one (14 page, 432 kB) file, I'm sure things could vary in other scenarios.

If/when you start work on this, let me know what code you might need.   For now, I'd think that just putting timing around the lexing portion, with a dummy handleObject(), would give you most if not all of the information you'd need.

You may or may not be thinking about multithreading along with this.  This could occur just at the page level (no impact) or also at the stream-within-/Contents-array level (might affect the optimization implementation).  My $0.02 would probably be to avoid the latter.

**Comment by jberkenbilt** [comment]
No need to supply code. I will comment on this when I am ready to work on it and see if I need anything.

I have avoided multithreading within qpdf up to this point because I didn't want to deal with doing it portably or with extra dependencies. Now that I am requiring C++-11, the portability part goes away, but multithreading is a great source of bugs, and making QPDF fully re-entrant would be very hard given that it was not designed with this in mind. It would also probably hurt performance. However QPDF is MT-safe as long as you don't use the same QPDF object in more than one thread. There are no unsafe static variables. I am aware of some users who are using QPDF in multithreaded environments. I may be doing that myself. But as far as the library itself is concerned, I will probably stay away from it unless I can do it very safely. Probably lexing is not a candidate. Something like image optimization may be a good candidate.

It might be possible to make certain specific methods safe to call in multiple threads. As you say, having multiple pages parsed in different threads might be possible to support.

**Comment by jberkenbilt** [comment]
I believe you will see a big improvement here after the work @m-holger did on #749.

**Comment by jberkenbilt** [comment]
I'm going to close this with that commit, but if it's not satisfactory, feel free to reopen.
