### ISSUE TITLE
qpdf create pdf file success but open failed

### ISSUE THREAD

**Issue by lugeluge** [qpdf/qpdf#459]
I am using qpdf to create PDF files, but sometimes the generated PDF files fail to open because of the following figure
![image](https://user-images.githubusercontent.com/16603407/88025950-ae073780-cb67-11ea-8a3f-06190f34571b.png)
![image](https://user-images.githubusercontent.com/16603407/88026826-fffc8d00-cb68-11ea-9634-94e5e4f84488.png)

**Comment by jberkenbilt** [comment]
I've never seen this behavior before, but it's very likely that the cause is that the code in qpdf that converts numbers to strings is sensitive to locale settings in the caller's environment. If so, this would be a bug that I should fix. In the meantime, it would help if you send me the output of

```
printenv | grep LANG
printenv | grep LC_
```

Please check the output to make sure no sensitive information is disclosed before you post on the ticket. If you run qpdf in a shell. That might help me in reproducing this so I can be sure my fix is correct.

As a workaround, if you run qpdf in a shell where the LC_* environment variables are unset, do you still see the problem? What about on a completely clean system? It's also possible this is not based on the environment but based on something else on the system, or if you're calling libqpdf from a C++ program, something else in your application. The main thing I need to do is to ensure that my use of the library calls is protected against contamination from the outer environment.

**Comment by lugeluge** [comment]
The character set is en_US.UTF-8
![image](https://user-images.githubusercontent.com/16603407/88133818-91293d80-cc15-11ea-9fe5-8817d619e9f0.png)

**Comment by lugeluge** [comment]
I have find the bug, std::locale::global(std::locale("")); is added before using qpdflib library;So it leads to the format problem of qpdf library

**Comment by jberkenbilt** [comment]
Okay, thanks. I will have to look into exactly what this does and make sure that I can prevent it from messing up qpdf since the numeric conversion routines in qpdf are explicitly not intended to be locale-aware. In the mean time, my guess is that it would be sufficient to just ensure that, whatever this does, it is not in effect for the QPDFWriter::write() call. More likely than not, nothing else going on in the library should be adversely affected. That's not a guarantee since I've never tested it in this way. It's possible that it could affect error messages. Unfortunately qpdf is not properly internationalized, but there are numeric values in some error messages. But nothing should care about that.

I'll leave this ticket open as a reminder to protect qpdf against user-provided locale settings. Thanks for following up.

**Comment by jberkenbilt** [comment]
qpdf 10.0.2 (or whatever's next) will work correctly even if you call `std::locale::global(std::locale(""));` in your own code. I have updated the numeric conversion code to protect itself against the caller's locale. Thanks for bringing this to my attention. The idea that my numeric conversions were prone to this had completely escaped my notice.
