### ISSUE TITLE
Linearize removes embedded XMP data

### ISSUE THREAD

**Issue by AlexanderWillner** [qpdf/qpdf#46]
Version: 5.1.2

Steps that will reproduce the problem?
1. Create a PDF file with embedded XMP information, e.g. by using the LaTeX package xmpincl
2. Linearize the PDF
3. Try to extract the XMP information again

What is the expected result?
Seeing the XMP information.

What happens instead?
They are gone.

Possible workaround:
Do not linearize.

Any additional information:
None.

**Comment by jberkenbilt** [comment]
It would be very helpful if you could attach a file that loses the XMP information during linearization. While it may be possible for me to reproduce the issue following your prescribed steps, it would save me trouble if you could just attach a file.

**Comment by AlexanderWillner** [comment]
Of course. And to be precise: the issue appear when multiple "/Type /Metadata /Subtype /XML" objects have been added. https://dl.dropboxusercontent.com/u/1358485/bugs/qpdf/a.pdf

**Comment by jberkenbilt** [comment]
(Note to self: file stored as ~/tmp/qtmp/qpdf-46.pdf)

**Comment by jberkenbilt** [comment]
The reason that these are dropped is because nothing in the PDF file refers to these objects. Right now, qpdf drops all objects that are not referred to in traversing from the root. I'm not sure whether it's supposed to be necessary to refer to these objects or not for them to be useful, so I'm not sure whether this is a flaw in the code that is adding these to the file or whether I need to handle preservation of certain unreferenced objects. There have been other requests for being able to preserve unreferenced objects, and there's already an item in the TODO list to add an option, but I didn't expect it would ever be on by default. I will have to look into the issue a little more deeply to understand what the proper fix is.

**Comment by jberkenbilt** [comment]
I'm going through and cleaning up very old issues. In the current version of qpdf, the metadata is no longer lost. The file has multiple metadata keys, and qpdf handles this better. Also, the `--preserved-unreferenced` flag would preserve it even if it were completely unreferenced.

**Comment by AlexanderWillner** [comment]
Thanks ;)
