### ISSUE TITLE
Potential Malware in Fuzzer Seed Corpus

### ISSUE THREAD

**Issue by h0bd0b1in** [qpdf/qpdf#460]
Disclaimer: I know nothing about what the fuzzer does and its use within qpdf so this may be a false report.

I use qpdf 9.1.1 within a Docker project and build it from source. After a recent switch to using Sophos Intercept X, it has flagged two files within the qpdf build overlays as malware, particularly the `Mal/PDFEx-H` variant. This malware [appears to only affect Windows OSes](https://www.sophos.com/en-us//threat-center/threat-analyses/viruses-and-spyware/Mal~PDFEx-H.aspx) so we are "safe" (running the build and Docker on Ubuntu). I'm not sure whether these are false positives but felt it would be remiss of me if I didn't at least report it.

The files in question (if this is helpful) are:
`fuzz/build/qpdf_fuzzer_seed_corpus/351a734b3c4e2b7a284539bbcf4ffdeee9e23a1b`
`fuzz/build/qpdf_fuzzer_seed_corpus/4d523755b3f3bf48a85bff1354d51f7b2acbdcc4`

**Comment by jberkenbilt** [comment]
Thanks for drawing this to my attention. This happens sometimes, but the modifications made by the fuzzer are random, and it's important to make sure qpdf doesn't trip over these files. In order to avoid virus scanners and so forth tripping over these, when I identify them (or someone else does), I obfuscate them, which keeps them from causing any problems for anyone. There is already a mechanism in the test system for handling this, or I might just decide to remove these files. I'll leave this open as a reminder.
