### ISSUE TITLE
Adobe Reader gives an error after using fix-qdf on files with removed objects

### ISSUE THREAD

**Issue by dittnamn** [qpdf/qpdf#465]
I'm not sure if this is a bug in fix-qdf or if the manual is missing something. When I try to remove a reference to an object in a QDF file, I can create a PDF file and it looks fine in other tools. In Adobe Reader I get a warning that the file is broken.

The manual says: "It is not generally practical to remove objects from QDF files without messing up object numbering, but if you remove all references to an object, you can run qpdf on the file (after running fix-qdf), and qpdf will omit the now-orphaned object."

So, I attach an example PDF file that I've converted to QDF.
[test-qdf.pdf](https://github.com/qpdf/qpdf/files/5218409/test-qdf.pdf)

In this file, I can remove the red image (object 15) by removing the reference /REI0 15 0 R. After that, I run fix-qdf and can send the file through qpdf without warnings.

When I open the resulting file in Adobe Reader, it says that there's an error in the file. The same file can be opened in other PDF readers without errors.

The same thing happens if I remove the contents from object 15 as well or if I just remove the stream.

QPDF version: 10.0.1

**Comment by jberkenbilt** [comment]
Removing the reference to the object in the page dictionary is in fact sufficient to make qpdf drop object 15, but /REI0 is pointing to an image, and that image is being drawn in the content stream for the page. In line 129 of the file, which is the 18th line of object 6, the contents for page 1, you will see

```
/REI0 Do
```

which is drawing the image. If that line remains but the object and reference to the object in the resource dictionary are removed, the file is broken because the content is referencing an unknown object. qpdf does not validate that case as it generally doesn't know how to interpret content streams. Other readers are probably silently ignoring the non-existent resource reference.

You could either remove just that one line, or you could remove the block that draws the image, which starts at the preceding `q` and ends at the following `Q`. In this case, that would be

```
q
0.00000 0.00000 m
70.00000 0.00000 l
70.00000 -71.00000 l
0.00000 -71.00000 l
0.00000 0.00000 l
h W* n
72.00000 0 0 72.00000 0.00000 -72.00000 cm
/REI0 Do
Q
```

That code is just creating a clipping region and rendering the image within the clipping region. You could remove that entire block as well as the reference `/REI0 15 0 R`, then run `fix-qdf`, then run `qpdf`, and the resulting image should work with no errors in Adobe Reader.

**Comment by jberkenbilt** [comment]
By the way, thanks for including a test file, detailed information about what you were doing, and the version of qpdf you are using. :-)

**Comment by dittnamn** [comment]
Ok, thank you. I'll have to see how this relates to other PDF files, and if I can recognize the parts to remove.

Would it be possible to make qpdf or fix-qdf automatically remove these unused resources in a future version? It might be helpful enough to just get a warning when running the commands.

**Comment by jberkenbilt** [comment]
It wouldn't be appropriate for fix-qdf to remove them -- fix-qdf is explicitly designed only to update cross reference tables and lengths. In fact, I use qdf all the time to create erroneous files for testing. However having `qpdf --check` detect and warn about this seems like a good idea. I've opened #466 to track this. I don't have much time to work on qpdf, so I doubt this will happen anytime soon, but it's worth tracking as a possible enhancement. Thanks for the suggestion.

**Comment by dittnamn** [comment]
Ok, thanks. I guess you can close this bug report now.
