### ISSUE TITLE
Hack/remove the protection of a PDF file

### ISSUE THREAD

**Issue by xmha97** [qpdf/qpdf#486]
I don't know the password to unlock the PDF.
Can I use `qpdf` to hack/remove the protection of a PDF file?

**Comment by jberkenbilt** [comment]
Bottom line: qpdf can't remove protection from a file with no known password, but it may be able to help you if you are trying to do a brute-force search for the correct password.

Ordinarily, the password is used to derive an encryption key, and the process of going from password to key requires its own processing. Using the `--password-is-hex-key` option, you can bypass this and supply the encryption key directly. In some cases, doing a brute-force search for the key may be faster than doing a brute-force search for the password. You can see a discussion of this for files with 40-bit keys [here](https://blog.didierstevens.com/2017/12/28/cracking-encrypted-pdfs-part-3/). Note that this was written prior to the addition of `--password-is-hex-key`. The blog post includes links to some modified qpdf binaries, but if you are using a version >= 7.1.0 (10.0.4 is current), you don't need modified binaries, and instead of using `--password=key:xxxx` as in the block post, you would use `--password-is-hex-key --password=xxxx`.

If you have a file with a 128-bit or 256-bit key, it may be that a brute force attack with keys will be worse than with passwords. Certainly qpdf can be used in a script to do brute-force attacks on the password more easily than a GUI would be able to do it. But if you have a password with a 256-bit key and a strong password, you're probably out of luck.

Good luck.

**Comment by xmha97** [comment]
Thanks for your explanation 🙏
