### ISSUE TITLE
Behavior of closed QPDF objects: throw exception on invalid access?

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#495]
If we retain a handle to an object that came from a closed PDF, it appears to me that:
* if the object was previously loaded in QPDF's cache, it will be returned with some, but not all indirect references attached replaced by null objects
* some actions will trigger a segfault (because some QPDF APIs assume the input source is available)

I don't know exactly what QPDF caches but it seems to have a limit to how "deep" it will explore before the absence of the underlying input source prevent it from giving an answer from cache.

```c++
#include <qpdf/QPDFObjectHandle.hh>
#include <qpdf/QPDF.hh>
#include <iostream>

int main(int argc, char **argv)
{
	QPDF q;
	q.processFile(argv[1]);

	auto foo = q.getRoot().getKey("/Foo");
	std::cout << "Close the file" << std::endl;

	std::cout << "We can still access foo:" << std::endl;
	std::cout << foo.unparseResolved() << std::endl;

	auto bar = foo.getKey("/Bar");
	std::cout << "We can still access bar:" << std::endl;
	std::cout << bar.unparseResolved() << std::endl;

	auto baz = bar.getKey("/Baz");
	std::cout << "We can still access baz:" << std::endl;
	std::cout << baz.unparseResolved() << std::endl;

	auto whatsnext = bar.getKey("/Whatsnext");
	std::cout << "But this is a null when it should /Name /WhatsNext:" << std::endl;
	std::cout << whatsnext.unparseResolved() << std::endl;

	return 0;
}

            
```

If possible I'd prefer to see QPDF not answer from cache at all when the input source is closed - I think it would be better to throw an exception indicating the underlying file is not available. My concern is, in pikepdf it's easier to loose track of the origins of objects compared to C++, and as the example demonstrates, the result returned from cache eventually diverges from reality when the input source is closed.

**Comment by jbarlow83** [comment]
Here's the file and relevant data.
[qpdf-issue495.pdf](https://github.com/qpdf/qpdf/files/5761398/qpdf-issue495.pdf)

<img width="364" alt="image" src="https://user-images.githubusercontent.com/1825843/103475746-d9bc5980-4d64-11eb-8228-8361cd99bcdd.png">

I went with global data attached to /Root because QPDF's caching behavior where page data is concerned may be more complex.

**Comment by jberkenbilt** [comment]
I'll give a more detailed response later, but all bets are off if you close the input source, and changing that behavior would be impossible without a significant performance hit and is off the table. I can describe in more depth what the caching behavior is and why. Maybe you can help me understand what's causing this situation to be a problem and we can discuss. By the way I'm going to get 10.1 out in the next several days, and I'm hoping to get qpdf to use mmap when it can.

**Comment by jberkenbilt** [comment]
So I'm trying to understand the issue here. As I think about this, I'm not sure there's actually a concept of a closed input source, and I don't see how qpdf could actually know if the input source is available. The input source is a PointerHolder<InputSource>, so the lifetime of the memory should not be an issue. So I guess I don't really understand what the problem is.

Regarding the cache, it's probably best to think of qpdf as lazy-loading from the file. qpdf maintains a map from object/generation to PointerHolder<QPDFObject>, and copies of that smart pointer are what is used to populate QPDFObjectHandle instances. Basically what qpdf does is to first look in the cache, and if not found, resolve using the xref table and, if needed, read from the file. Once the object is in the cache, it stays forever. If anything is modified, the modifications are performed in the cache, which means it's not really a cache. It's really an in-memory representation of the PDF file that is loaded from the input source as needed. There is no concept of depth of how far it looks or anything like that. However, if qpdf resolves any object in the object stream, it loads all the objects in the object stream.

When qpdf loads an object from the file, the QPDFObjectHandle has a pointer to the owning qpdf object, but there are plenty of ways for objects not to have an owning PDF. In particular, objects that are created using the qpdf APIs generally don't have owning qpdfs. As such, in general, API calls that access an object don't even necessarily have to go back to the originating QPDF object.

When a QPDFObjectHandle is initially created from an indirect object that is inside another object, the QPDFObjectHandle is internally not resolved; that is, it's internal PointerHolder<QPDFObject> is empty. QPDFObjectHandle handles this transparently -- any object will "resolve" the object handle, and this operation is what hits the cache. If the object is already in the cache, the pointer is just supplied. Otherwise, it is read from the file.

There are many instances in which QPDF returns a null, and there are more now than there used to be. Basically if you ever access something in the wrong way, you get a null back. This turns out to have vanquished many issues found by the fuzzer, and it makes qpdf much more robust against programmer assumptions as applied to bad files. For example, if you expect obj to be a dictionary with a /K that points to a boolean and do something like obj.getKey("/K").getBoolValue(), if obj is not a dictionary, then obj.getKey("/K") returns a null, and then null.getBoolValue() returns false. If possible, qpdf will generate warnings for all these events, but if you do this on things that don't have an owning QPDF, then the library has no path through which to issue a warning (and writing directly to stderr is evil for libraries), so there is no warning. qpdf also returns null if it can't read from the input source for some reason.

Recently I did a fairly deep exploration of whether it would be possible to selectively flush the cache (because memory is getting too full, for example), but the idea that, once resolved, an object lives permanently in the cache is baked in pretty deeply into many places in the code. It is the basis for all mutability of objects in qpdf.

Hopefully this helps, but I must still not be entirely understanding what the real issue is here.

**Comment by jbarlow83** [comment]
Thanks for the explanation.

I realize one is not supposed to close the input source, and behavior is effectively undefined when this happens, but users will be users. I was hoping to find a way to improve the behavior that does occur when the input source is closed, to be more defensive about this case, even if the solution is not exhaustive.

What was I trying to demonstrate was that because of the cache, after closing the input source, one gets a cache-conditional response that may or may not be correct. I think it's better practice to throw an exception than give an answer that may be wrong. Or equivalently, closing the input source should also invalidate the cache.

When a QPDFObjectHandle is not attached to a PDF or input source, there's no issue. Those should continue to work.

For example `QPDF::closeInputSource` releases `m->file` but leaves most of the other QPDF::Members initialized even though some of them are probably invalid without the input source being open. So why not release some of them at that time? The API "contract" says that nothing can be relied on except for access to warnings. That being the case, can we can release other data held by a QPDF object at this time too? I don't think it would hurt performance for functions that rely on QPDF being in a "processed" state rather than "closed" or "uninitialized" to check that it's in a valid state first. That's a single `if`.

The general place this is coming from is the expectation in Python or any other interpreted languages for misbehavior to result in exceptions rather than segfaults. I can trap a C++ exception, repackage it as a Python exception and raise it to the user, but I can't trap a segfault as effectively.

**Comment by jberkenbilt** [comment]
I forgot that there was even a `closeInputSource()`. Your example in the description doesn't actually call that. It just prints "Close the file". Also, the example code doesn't do what the print statements say it's doing. You have `bar.getKey("/Whatsnext")` when I think you mean `baz.getKey("/WhatsNext")`. If I use this (I think) corrected example:

```c++
#include <qpdf/QPDFObjectHandle.hh>
#include <qpdf/QPDF.hh>
#include <iostream>

int main(int argc, char **argv)
{
	QPDF q;
	q.processFile(argv[1]);

	auto foo = q.getRoot().getKey("/Foo");
	std::cout << "Close the file" << std::endl;
        q.closeInputSource();

	std::cout << "We can still access foo:" << std::endl;
	std::cout << foo.unparseResolved() << std::endl;

	auto bar = foo.getKey("/Bar");
	std::cout << "We can still access bar:" << std::endl;
	std::cout << bar.unparseResolved() << std::endl;

	auto baz = bar.getKey("/Baz");
	std::cout << "We can still access baz:" << std::endl;
	std::cout << baz.unparseResolved() << std::endl;

	auto whatsnext = baz.getKey("/WhatsNext");
	std::cout << "But this is a null when it should /Name /WhatsNext:" << std::endl;
	std::cout << whatsnext.unparseResolved() << std::endl;

	return 0;
}
```
then I get a segfault accessing bar, which is what I would expect:

```
Close the file
We can still access foo:
<< /Bar 3 0 R >>
We can still access bar:
[1]    31367 segmentation fault (core dumped)  ./a.out ~/tmp/net/qpdf-issue495.pdf
```

I'm going to push a commit to my fork that improves this behavior but it won't propagate an exception out. Instead, it will issue warnings, which is what qpdf does when it can't read the input source. After this change, you get this output:

```
Close the file
We can still access foo:
<< /Bar 3 0 R >>
We can still access bar:
WARNING: closed input source: object 3/0: error reading object: QPDF operation attempted after closing input source
null
WARNING: object 3 0: operation for dictionary attempted on object of type null: returning null for attempted key retrieval
We can still access baz:
null
WARNING: object 3 0 -> null returned from getting key /Baz from non-Dictionary: operation for dictionary attempted on object of type null: returning null for attempted key retrieval
But this is a null when it should /Name /WhatsNext:
null
```

**Comment by jberkenbilt** [comment]
Let me know what you think of this solution. Sorry it missed the train for 10.1.

**Comment by jberkenbilt** [comment]
I'm going to go ahead and push my change to master, which will close this issue. Propagating the exception up would be quite invasive in the code and would be a behavior change in that accessing things from the PDF doesn't do that right now, so I'm inclined to leave it at this. However, if you feel strongly about it or want to discuss it further, please feel free to reopen.
