### ISSUE TITLE
Help me understand the PDF Warnings?

### ISSUE THREAD

**Issue by vuciv** [qpdf/qpdf#498]
Thank you for your incredibly useful tool.

I am debugging a pdf tokenizer whose first step is to go to the startxref offset, and then go to that byte and begin reading from the xref table.

I've been testing it with random pdf documents, and have found it to fail on one pdf where the startxref offset is not the byte where the xref table actually begins.

This led me to to verify this through `qpdf --check`. This command outputs the following:

```
checking test.pdf
PDF Version: 1.7
File is not encrypted
File is linearized
WARNING: linearized file contains an uncompressed object after a compressed one in a cross-reference stream
WARNING: first shared object offset mismatch: hint table = 1326624; computed = 1326052
WARNING: page 0 has shared identifier entries
WARNING: page 0: shared object 1154: in hint table but not computed list
```

These warnings have helped me verify that there is something wrong with this pdf file, but I'm not able to understand more deeply how to resolve such an issue through a tokenizer... Perhaps this is beyond the scope of this tool, but it would be nice if the warnings pointed to pdf documentation that may account for why this error may occur.

This is a long shot, but from these warnings, would anyone be able to tell me exactly why the startxref offset is off? I assume it's the uncompressed object that is taking up more bytes than anticipated, but I want to be sure. 

In addition, if you happen to have the time, an explanation as to how a tokenizer can and should handle an xref offset mismatch, or pointing me to documentation that describes such a case, would be very useful.

**Comment by jberkenbilt** [comment]
I'm glad you're finding qpdf useful.

These warnings are about the file's linearization hint tables and don't indicate that the startxref offset is off. The startxref can be off for a variety of reasons, but the main one is that there are lots of really buggy PDF creation tools out there. A big part of the effort that's gone into qpdf is making it tolerate more and more types of broken files. It is also the case that qpdf compensates for files that have garbage preceding the `%!PDF` header and subsequently treats all offsets as offsets from the beginning of the header rather than the beginning of the file. It's possible that you may be dealing with a file like that. I think the PDF spec recommends searching within the first 1024 bytes for the header. If that's not the situation and the startxref is just wrong, then why it's wrong is an unanswerable question without access to whatever created the file. Unfortunately most people who create PDF file validate that they're "correct" by testing whether Adobe Reader can open them, and Adobe Reader is tolerant of lots of deviations from the spec (as any good reader should be). qpdf actually started its life as a PDF checker, but over time, I have removed some checks for things that don't actually matter and have made qpdf much more tolerant of broken files as well, though generally it gives warnings.

I hope this is at least somewhat helpful even if it doesn't shed too much light on your specific situation.

**Comment by vuciv** [comment]
@jberkenbilt Thank you, this is very helpful.

I do believe that the startxref is just wrong. The last thing I'd want to ask you if you're okay with it, is how qpdf ends resolves such an issue? Or does qpdf not concern itself with the startxref offset.

**Comment by jberkenbilt** [comment]
If qpdf finds that startxref is wrong, it goes into a recovery mode that is more or less described in an appendix one of the pre ISO32000 versions of the PDF spec. Basically it starts at the beginning of the file and scans forward looking for things that look like the beginnings of objects appearing at the beginning of the line (two numbers followed by "obj"), along with some other sanity checking, and uses this to attempt to reconstruct the xref table. All bets are off for object streams (a.k.a. compressed objects). If PDF files follow certain lexical conventions, this can work okay. Since Adobe Reader and other PDF viewers apparently use similar recovery strategies, it often happens that files with broken startxrerf that work in other viewers will work with qpdf. However there is always a risk that qpdf will lose information when it writes the output, a fact that qpdf warns about when it discovers this situation.

If you run `qpdf your-input.pdf new-output.pdf`, the resulting file will have gone through the recovery process if the startxref is in fact wrong. You can use your own methods to validate whether the file is intact. A reliable method is to use a tool to convert the PDF pages into images and then to compare the images. In the qpdf source tree, you can find the function `compare_pdfs` in `qpdf/qtest/qpdf.test` for the code the qpdf test suite uses to ensure that various transformations it performs have not altered the way the page ultimately renders. There's a decent amount of code there, but ultimately it boils down to using ghostscript with the tiff24nc device and tiffcmp to compare the resulting images. I use tiff24nc because it is a non-lossy format capable of representing color images and multiple pages. This requires libtiff and ghostscript. You can find more information in the qpdf manual in the section "System Requirements". Search for "comparing the images." Here's a [link to the section in the latest version of the manual](http://qpdf.sourceforge.net/files/qpdf-manual.html#ref.prerequisites).

**Comment by jberkenbilt** [comment]
Also regarding your earlier question about error messages containing references to the spec, I don't have any intention of putting the effort into that, but there are plenty of comments in qpdf's source code, particularly in the linearization section, that refer to sections of the spec. qpdf started its life a long time ago, perhaps 2002, long before ISO32000 was published, and so different parts of the code refer to section numbers of different versions of the spec. Mostly I was good about being specific. Most of the PDF references published by Adobe early on had similar section numbers, but things got changed pretty significant for the ISO standard.

**Comment by vuciv** [comment]
@jberkenbilt Thank you so much. This has all been very helpful for me. Your dedication and knowledge on the subject is amazing.
