### ISSUE TITLE
Feature Request -- Generate a Warning Message when Encrypting PDF's using AES256 and a null or blank Owner Password

### ISSUE THREAD

**Issue by RobK88** [qpdf/qpdf#501]
PDF's encrypted using 256 AES encryption when no owner password is specified, can be opened, decrypted and read by many PDF readers (including Apple's Preview) without asking for a password!  

Apparently, this is not a bug in qpdf.  qpdf is following the PDF spec,  Please see Issue #144.

Unfortunately, I suspect many users of qpdf do not realize that encrypting a pdf using AES-256 encryption with only a user password (and a blank or null owner password) will create a very insecure PDF (unlike a PDF encrypted using 128-bit AES or RC4).  Many PDF readers including Apple's Preview will open it up, decrypt it and display it without asking for a password!

I recommend that qpdf generate a warning message when encrypting PDF's using AES256 whenever the owner password is blank or null informing users that the resulting encrypted PDF is not very secure since the owner password has not been specified (or something to that effect).

Since the PDF Spec looks brain dead, you might even consider deviating from the PDF spec and setting the owner password to the user password when the owner password is left blank or null.

**Comment by RobK88** [comment]
As noted above, it may not make sense to strictly follow the official PDF spec if the spec is brain dead. 

It appears that one can create an encrypted PDF using AES256 encryption with only specifying a user password using other tools (like the free open source PDFEncrypt for Windows) that will NOT open in Apple's Preview without specifying a password.

It looks like PDFEncrypt sets the owner password to the same value as the user password when encrypting a PDF using AES256 whenever the owner password is not specified or is empty.  As a result, one must enter a password whenever one tries to open such a PDF using any PDF Reader (including Apple's Preview).  It is interesting that Adobe Reader shows that the user password is set BUT not the owner password (which is not technically true).

I tried encrypting a PDF using qpdf with AES-256 encryption when both the user and owner password are set to the same non-empty value. Adobe Reader also shows that the user password is set BUT not the owner password (which is not technically true).

I recommend that qpdf set the owner password to the same value as the user password whenever the user fails to provide an owner password (or if the owner password is empty) when qpdf is encrypting a PDF using AES-256. Otherwise, the encrypted PDF's will NOT be secure at all since they can be opened up in various PDF Readers including Apple's Preview.

**Comment by jberkenbilt** [comment]
I appreciate all these comments and agree with pretty much all of your points. I will think about how to address this, but it won't be to change what qpdf actually does when you invoke it with specific arguments since that would break compatibility. One of the things you've actually done here, which is to look at the way different viewers respond to different types of PDF files, is an important thing that qpdf enables. I want it to be possible for qpdf to be able to be used to generate weird files that you probably wouldn't actually want so you can see how other viewers would respond to them, but really, it's the backward compatibility reason that's the strongest.

That said, I agree with you that, under ordinary circumstances, you would never want to create a PDF whose owner password is blank, and in reality, you'd never want to create a PDF whose owner and user passwords are the same. I think it's entirely reasonable for qpdf to generate a warning in this case, so I will most likely make that change. Thanks for taking the time to investigate this so thoroughly.

**Comment by RobK88** [comment]
Many many thanks for revisiting this issue.  qpdf is one of the very few free (and open source) programs that will encrypt and decrypt PDFs (amongst other things!).  I know many people on Mac OS and Linux use it just for encryption purposes.  (Yes, there is pdftk but it only supports the old RC4 algorithm and only up to 128-bit in key length)

I am worried that many people will unknowingly use qpdf to create a very insecure encrypted PDF using AES256 when they only specify a user password.   As noted in my previous posts, it is possible to open up such a PDF without entering any password at all using Apple's Preview (and many other tools like the pdf related binaries in poppler).  So the encryption is really irrelevant.  

It could be really disastrous if a person encrypted really sensitive information (like financial info) this way using qpdf and AES256 and sent it off on the internet thinking it is secure.   It would have been better if the person used qpdf to encrypt the PDF using AES128 since the resulting PDF is actually much more secure and cannot be opened by Apple's Preview without entering the user password for the PDF.

I realize that the official PDF spec states that AES256 encryption be handled differently.  But the spec is brain dead IMHO. The spec should not allow for the creation of insecure encrypted PDFs with empty passwords!

I also checked another popular PDF tool for the Mac -- PDFPen Pro.  I created an encrypted PDF using AES256.  PDFPen just asks for a password during the creation.  The resulting PDF is encrypted and secure.  Apple's Preview will not open it unless you enter the valid password for the PDF.  (Adobe Reader shows that the user password is set BUT not the owner (or permissions) password).

Given the danger, I would **at minimum** warn qpdf users whenever they attempt to create an encrypted PDF using AES256 without specifying an owner's password.  (e.g..  WARNING -- PDF's encrypted using AES256 are NOT secure unless the owner password is also set).

I am always worried about the tyranny of defaults.  Personally, if qpdf was my project, I would not let users create encrypted PDF's using AES256 without the owner password being set unless the user enters some sort of over-ride flag on the qpdf command line.  (e.g. strict-PDF=y ).

P.S.  For anyone reading this post, if you want to use qpdf to create an encrypted and secure PDF using AES-256 without setting an owner (or permissions) password, you can do it by setting the owner password to the same value as the user password when using qpdf to create the encrypted PDF.  I know this is not intuitive!  But when you open up such a PDF in Adobe Reader (after entering you user password), Adobe Reader shows that the user password is set but not the owner password.  (FYI -- When one sets the user password to the same value as the owner password when creating an encrypted PDF using qpdf, the resulting PDF will only have the user password set (and not the owner password) according to Adobe Reader no matter what type of encryption you specify or the bit length).

**Comment by jberkenbilt** [comment]
Your arguments are very convincing. Maybe I'll make it so that you have to give a parameter like `--force-insecure` to do something that is definitely insecure. I think that's a reasonable compromise.

**Comment by RobK88** [comment]
Thanks Jay.  Your name for the over-ride flag is a lot better than mine.  --force-insecure
I look forward to seeing a new release of qpdf in due course.  Again many thanks for addressing this issue.

**Comment by jberkenbilt** [comment]
@RobK88 Thanks for bringing it up. I'm working on 10.2 which I hope to get out in the next few weeks. I'll make sure this is included in 10.2.

**Comment by jberkenbilt** [comment]
The option will be `--allow-insecure`. Without `--allow-insecure`, qpdf will refuse to allow either an empty owner password or an owner password that is equal to the user password.

**Comment by jberkenbilt** [comment]
Also, it will be inside the `--encrypt` options, e.g., `qpdf --encrypt pass pass 128 --allow-insecure -- a.pdf b.pdf`

**Comment by RobK88** [comment]
Thanks Jay!  That will help make sure people do not accidentally create an encrypted but highly insecure PDF using AES256 that can be opened with Apple Preview without having to enter a password! 

Please note the old version of qpdf always created encrypted and secure PDF's when using 40bit RC4, 128 bit RC4 and 128 bit AES and when the owner password was empty.   Only PDF's encrypted using AES256 and an empty owner password could be opened using a blank owner password.  

You may want to consider restricting the use of the new --allow-insecure flag to only encryption using AES256.

I am not sure why you consider PDF's insecure when the user and owner password are the same.
of course, it is better if they are different in most cases.  But if they are the same and NOT empty, then the encrypted PDF will be secure.  One can only open it if one knows the password.

**Comment by jberkenbilt** [comment]
I'll reopen while I consider. My reasoning on user = owner is that viewers behave inconsistently. Some viewers make it impossible to open the file without restrictions, always treating the password as the user password and not checking the owner password, while other viewers treat it as the owner password and don't enforce restrictions. So someone could use the same password as user and owner, test out in one viewer, and think the security options are enforced when other viewers are not. This is a minor point though since there are always tools like qpdf that can be used to bypass all security settings with just the user password.

Regarding empty owner password with 40 and 128 bit, the PDF spec says that, in that case, the owner password should be considered the same as the user password, and this is what qpdf does. The algorithms work if you don't do this (if I comment out the one line of code, I can create a file with an empty owner password with a 40-bit or 128-bit key that some viewers can open without a password prompt).

As I write this, I think I am convinced that your original suggestion is correct. I was thinking more about consistency, but you're right -- a password is required, even with a tool like qpdf, so the file is only really insecure, in that no password is needed, with the single case of an empty owner password with 256-bit. I think I will adjust the code.

Thank you for what has been one of the most thorough, thoughtful, and well articulated bug reports and for following up to make sure I implemented the suggestion correctly.

**Comment by jberkenbilt** [comment]
I'm going to push up a new fix to by private build branch now and, if all is well, I will push to master when I get a chance, probably sometime tomorrow. Thanks again.

**Comment by jberkenbilt** [comment]
I'm also only complaining if the user password is non-empty. Pushing up a fix.

**Comment by jberkenbilt** [comment]
If you still feel it's wrong, please keep at it. :-) I want to get this right.
