### ISSUE TITLE
multiplex two PDFs

### ISSUE THREAD

**Issue by tobwen** [qpdf/qpdf#505]
## preface
I'm sorry to have to ask the question here. After much research and trial and error, I have not found a solution.

## problem
I want to multiplex two files into one as follows:
```
file A: pages 1 & 2
file B: pages 1 & 2

file A: pages 3 & 4
file B: pages 3 & 4

[...]

file A: pages 99 & 100
file B: pages 99 & 100
```

## possible solution
Seems like scripting via bash/powershell is the only solution right now?

## workaround
A workaround would be to split the files into a folder and merge them afterward. But this only works when the amount of pages from each file is equal (like in my case). It wouldn't work for this:
```
file A: pages 1 & 2
file B: pages 1 - 6

file A: pages 3 & 4
file B: pages 7 - 12
```

**Comment by dreua** [comment]
Do I understand correctly that you only want to reorder the pages of two documents into one? I don't know about qpdf but it's an easy task with pikepdf and a few lines of Python.

As I understand it:
```
inputs:
A.pdf: A1, A2, A3...
B.pdf: B1, B2, ...

Output: A1, A2, B1, B2, A3, A4, B3, B4, ...
```

Is this correct?

**Comment by tobwen** [comment]
> Is this correct?

Yes, this is correct.

> easy task with pikepdf and a few lines of Python

I've done it in _mµPDF_ tonight. It doesn't need an external interpreter, since it comes with a Javascript compatible one. I'll contribute the code to their repository or GIST soon and link it here.

I hope I can contribute this to _qpdf_, since I don't want to mix so many tools.

**Comment by jberkenbilt** [comment]
@tobwen I'll mark this as an enhancement. I've been considering adding more options to handle different kinds of interleaving like this, including some book mode, n-up, and so forth, similar to the old pstops. This seems like it fits into that category. If you have any suggestions as to what the command-line syntax should look like, I'd welcome your (or anyone's) suggestions. See also #493 which is similar.

**Comment by tobwen** [comment]
My current implementation in _mµpdf run_ could be translated to:

### for A1 A2 B1 B2
```
--multiplex A.pdf --from=1-2 b.pdf --from=1-2 
````

### for A1 B1 B2 B3 A2 B4 B5 B6
```
--multiplex A.pdf --from=1 b.pdf --from=1-6
````

### remark
`1-6` is more like a _step size_; 1 to 6, 7 to 12, 13 to 18, etc.

**Comment by jberkenbilt** [comment]
Thanks. What I'll probably do is to study pstops (which I used to maintain for debian and was quite familiar with back in the day) and compare that with other issues including this one, then create a proposal and mention it in one of the issues. Please note that this is not currently scheduled, so it will probably be a while before I get to it. I'm going to be working on enhancing page splitting and merging to handle document-level structures probably as the next significant feature enhancement. It might be worth squeezing it in there. No guarantees. Thanks.

**Comment by jberkenbilt** [comment]
Also note that qpdf has a `--collate` option. Your specific use case could be achieved by adding some kind of step size to `--collate`. That might be an easy interim solution. In fact, looking at the code, I think it should only be a few lines of code to do. I'll see if I can get that in for 10.2. Not a fully general solution, but good enough for your use case.

**Comment by jberkenbilt** [comment]
In qpdf 10.2, which I plan to get out in the next day or so, you will be able to `qpdf --collate=2 --empty --pages A.pdf B.pdf -- out.pdf`. Not the full degree of flexibility, but it least it gets you the two at once case. It's not good enough enough do 2 from A and 6 from B. That will have to wait for something more general. Ordinarily I'd close the issue in a commit, but I'll leave this open for now since I am only partially fixing it.

**Comment by jberkenbilt** [comment]
Removing the `next` label since I've gone as far as I'm going to for now.

**Comment by rubyFeedback** [comment]
What I kind of do is to just happily combine any different(ial) tools for pdf-related tasks, with ruby as the glue language (I suppose the above comment by tobwen is similar to that, just using python rather than ruby).

I realized that, for me, it is simpler to just move on, use whatever tool works, to have the desired outcome. I have not thought about the "multiplexing" situation much at all; if I understood it correctly then this simply refers to cherry-picking individual .pdf files, and then combining them yes? I guess in the worst case one could split up all individual .pdf pages, and then just merge the new ones. But a direct "multiplexing" is probably more elegant.

Feel free to correct me if I am incorrect but for qpdf I suppose the question is more how much it may want to aim for a general pdf-toolkit related project, e. g. similar to ffmpeg perhaps for audio and video data, and imagemagick for images (although there is evidently some overlap, e. g. convert from imagemagick can be used to convert an image to a .pdf file; I have not yet tried that with qpdf I think. I use qpdf primarily to chop off individual pages from pdf-books I have read and want to "finish" reading ... :D)

**Comment by jberkenbilt** [comment]
This idea is on my pages roadmap. I will start working on that soon. I'm not sure when/if this specific feature will make it in.

**Comment by jberkenbilt** [comment]
I'm not sure whether I will do exactly this, but it occurs to me that extending `--collate=n` to `--collate=a,b,c`, where `a,b,c` is a comma-separate list of numbers equal to the number of "groups" of pages would allow the use case above. So the argument `collate`, if absent, would be equivalent to `1`, and if present, would either be a single number or a comma-separated list of numbers equal to the number of groups.

**Comment by jberkenbilt** [comment]
I decided to go ahead and implement that since it wasn't very hard. `qpdf --collate=2,6 a.pdf --pages . b.pdf` would now take 2 from a.pdf, 6, from b.pdf, 2, from a.pdf, 6.pdf, etc. until it ran out of pages with each file. This change will be in 11.7.1.
