### ISSUE TITLE
can not decrypt pdf

### ISSUE THREAD

**Issue by Gaoey** [qpdf/qpdf#519]
I am trying to decrypt the pdf but it seems like the file is damaged. The error is shown below here.
This pdf is generated by a bank so it's should not be damaged. We have tried multiple files.
Thank you for your help. 

command
```
qpdf --decrypt --password=20122534 STM0364_0544XXXX8354.PDF test.pdf
```

console response
```
WARNING: STM0364_0544XXXX8354.PDF: file is damaged
WARNING: STM0364_0544XXXX8354.PDF (offset 69331): xref not found
WARNING: STM0364_0544XXXX8354.PDF: Attempting to reconstruct cross-reference table
qpdf: operation succeeded with warnings; resulting file may have some problems
```

PDF version 1.4
[STM0364_0544XXXX8354.PDF](https://github.com/qpdf/qpdf/files/6329372/STM0364_0544XXXX8354.PDF)

**Comment by jberkenbilt** [comment]
The file you attached is two apparently valid PDF files concatenated together. The first one is not encrypted and appears to be valid. The second one is encrypted and requires a password to open, so I can't tell if it's actually valid, but a quick spot check of the xref table suggests that it is at least structurally valid. The second file begins at offset 69987.

**Comment by dreua** [comment]
> This pdf is generated by a bank so it's should not be damaged

Why would you think that? :laughing:

**Comment by Gaoey** [comment]
> The file you attached is two apparently valid PDF files concatenated together. The first one is not encrypted and appears to be valid. The second one is encrypted and requires a password to open, so I can't tell if it's actually valid, but a quick spot check of the xref table suggests that it is at least structurally valid. The second file begins at offset 69987.

 Thank you for taking a look. Would you be able to tell me how I can go about fixing this?

**Comment by jberkenbilt** [comment]
@Gaoey I don't have a general solution for you. I figured out what was going on in this file by loading it up in a text editor, looking at the xref table, looking at the actual offsets in the file where objects were, and looking for whether the file was "appended" when I happened to notice that it seemed like maybe it was multiple files. I split the file where I found a second PDF header and that seemed to be it, but I've looked at lots and lots of PDF files. Is this a one-off, or do all the files you download have this problem? I suspect that, if the latter, the bank will have to fix it since this file would probably not work right in any viewer. If this is a one-off, then I wonder whether there's something you might have done to cause this in the way you downloaded or saved the file.

I'm attaching the two halves of this specific file, both of which are valid PDFs, but I don't have a solution you could use in general.

If you are comfortable with working with PDF files in an editor that is capable of working safely with binary files, you can search for `%%EOF` and `%PDF-1.` to find a likely end and beginning marker, and split the file at that point. I just did that in emacs for this file.
[1.pdf](https://github.com/qpdf/qpdf/files/6331680/1.pdf)
[2.pdf](https://github.com/qpdf/qpdf/files/6331681/2.pdf)
