### ISSUE TITLE
add --quiet option for --check mode

### ISSUE THREAD

**Issue by pabs3** [qpdf/qpdf#522]
Using qpdf in a static analysis setting for checking PDFs is hard because `qpdf --check` outputs information about the PDF even when no problems are found.

So whatever runs qpdf needs to post-process the output by removing information about the PDF, but that output could change, leading to the post-processing being outdated and causing false positives.

It would be nice to have a `--quiet` feature that would hide messages in `--check` mode that do not indicate known problems of any severity (such as `ERROR`, `WARNING`, `PEDANTIC` or similar).

```
$ qpdf --check example.pdf
checking example.pdf
PDF Version: 1.4
File is not encrypted
File is not linearized
No syntax or stream encoding errors found; the file may still contain
errors that qpdf cannot detect
```

```
$ qpdf --check-linearization --check example.pdf
checking example.pdf
PDF Version: 1.4
File is not encrypted
File is not linearized
No syntax or stream encoding errors found; the file may still contain
errors that qpdf cannot detect
called readLinearizationData for file that is not linearized
```

**Comment by pabs3** [comment]
PS: this would be useful for @collab-qa's check-all-the-things project, which allows easily running various static analysis tools.

**Comment by jberkenbilt** [comment]
Given that qpdf writes errors and warnings to stderr and informational messages to stdout, is `qpdf --check > /dev/null` an option for you? There have been some bugs in the past where errors were occasionally written to stdout, but I am pretty sure these have all been fixed in 10.3.1 and other recent versions.

Anyway, I can probably add this. It's not quite as trivial as it seems because some of the very old checking code is actually in the library, and I'd have to add some mechanism for overriding where the output goes, but it's still not a very hard change.

**Comment by jberkenbilt** [comment]
It's also true that `qpdf --check` exits with status 0 only when there are no warnings or errors.

**Comment by pabs3** [comment]
I hadn't noticed the different error streams.

I think that sending stdout to /dev/null will work for me.

So feel free to either close this bug or add --quiet as you prefer.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
One further thought, if you decide not to implement --quiet, please
document for the --check option that errors/warnings are output to
stderror and messages not indicating problems go to stdout.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by jberkenbilt** [comment]
I'll update the docs rather than implementing yet another command-line argument. Thanks for the suggestion.
