### ISSUE TITLE
Decrypting signed documents

### ISSUE THREAD

**Issue by BrendanAnnable** [qpdf/qpdf#53]
Hi,

Couldn't find any info on this, but I'm trying to remove the protection on a PDF file that has be securely signed. There is no password, and it is a legitimate document, but adobe won't allow me to combine it with another pdf when the security is there, so I want to remove it.

When I try to use qpdf, I receive this error: "(encryption dictionary, file position 9336): unsupported encryption filter". Is this a known limitation?

**Comment by jberkenbilt** [comment]
Yes, at the moment qpdf doesn't have any support for signed documents. It's a big thing to support, and as I don't have much time to work on qpdf, I'm not expecting to get to it in the foreseeable future. If my understanding is correct, there are some document signing issues that qpdf or other readers can't solve because they require having private keys from Adobe, such as indicating that a document's forms can be saved with Adobe Reader, but also using keys to encrypt/decrypt documents is not supported by qpdf. We can leave this open as a reminder that someone wants this feature. If you have a file that is signed in this way that you're willing to donate and allow to be redistributed, I may be able to include it in a possible future test case. I'm hoping that there will come a time when I can devote some time to doing more substantial qpdf enhancements again, and supporting a wider range of encrypted files would be nice. qpdf is already among very few open source tools that can read and write PDF files with 256-bit keys.

**Comment by jenoworld** [comment]
Hello, I know this is old, is there any chance to support this?

**Comment by jberkenbilt** [comment]
Maybe sometime, but not soon. I have very limited time for qpdf right now with issues going on in my life. I plan on taking some time this summer to do some work, but I have a considerable backlog ahead of this. Feel free to continue to check in. I am hoping to find a way to get more consistent time for qpdf enhancements, including possibly involving some other developers. We'll see where it goes.

**Comment by aaronburnie** [comment]
Hello, I believe the decryption of signed documents isn't supported yet. I am getting the following error: (encryption dictionary, offset 16560724): unsupported encryption filter

The document I am trying to open is locked by FileOpen DRM.

**Comment by jberkenbilt** [comment]
Still not supported, but the barriers to supporting it are lower now that we have crypto provided by openssl or gnutls. However note that there are some systems that qpdf will never be able to support because they use encryption managed by a third party service. I believe FileOpen DRM falls into this category.

**Comment by bmariuszb** [comment]
decrypt pdf
	qpdf @- --decrypt protected.pdf out.pdf
	Once you enter that, qpdf will be waiting for input from stdin. You can then type:
	--password=<yourpassword>
	Ctrl+d
If someone wants to please provide an update on how you can pass a password with stdin, this isn't the best solution

**Comment by jberkenbilt** [comment]
Looking back over this, I think there is nothing qpdf can do. Other than having a user write a custom filter handler, most non-standard filters are not documented, so qpdf won't be able to support them. Recent versions fo qpdf have `--remove-restrictions`, and in qpdf 11.7.0, that option also removes digital signatures, but looking at the description here, I think this is about a non-standard filter.
