### ISSUE TITLE
Add digital certificate

### ISSUE THREAD

**Issue by leandrocombr** [qpdf/qpdf#535]
Can I add a digital certificate to .PDF?

.pfx .crt .pem

**Comment by jberkenbilt** [comment]
If you are asking whether qpdf can sign a PDF using PKI, the answer, unfortunately, is not at this time. See also #201. This is something I would like to support, and since the original issue, some of the prerequisites have been satisfied (e.g. being able to link with gnutls or openssl), but right now, we are not particularly close to this functionality.

If that's not what you're asking, please clarify. Once I'm sure I'm answering the right question, if that's what you're asking, I'll probably close this in favor of #201 and invite you to subscribe to that issue if you're interested in following the progress. Thanks!

**Comment by leandrocombr** [comment]
Correct, I need to add digital certificate to PDF file!

I will follow up as a post!
