### ISSUE TITLE
Applying page selection on *.pdf

### ISSUE THREAD

**Issue by Moghi** [qpdf/qpdf#537]
Hi, 
First of all thank you for qpdf, what a useful  tool!

I am using qpdf to merge all pdf files in a directory and I would like to merge only the first page of multiple inputfiles. According to the [qpdf documentation on page-selection](http://qpdf.sourceforge.net/files/qpdf-manual.html#ref.page-selection),  this should be possible. I have tried couple variants without luck:
```
qpdf --empty --pages *.pdf 1-1 -- "output.pdf"
qpdf --empty --pages *.pdf 1 -- "output.pdf"
```

Is it possible that page-selection is not applied to the results of `*.pdf`?

**Comment by jberkenbilt** [comment]
This isn't really a qpdf issue. It's really a shell issue. qpdf never sees `*.pdf` since the shell expands this and replaces it with all the files on the command line, so you are actually running `qpdf --empty --pages file1.pdf file2.pdf file3.pdf .. 1 -- output.pdf`, which is why the selector only applies to the last file. On Windows, you get identical behavior even though the wildcard substitution is performed a little later.

If you are using Linux, MacOS, or another UNIX-like environment,  you can run

```
qpdf --empty --pages $(for i in *.pdf; do echo $i 1; done) -- output.pdf
```

If you are in Windows, the above would work in bash. I don't know how to do it in powershell or cmd, but it would be easy to script.

**Comment by Moghi** [comment]
thank you for the answer. Now I get my error, I mistakenly expected the page option to be applied to all of the input files.
Yes I am using qpdf on Linux and MacOS, so I appreciate the example.
Do you think it would be a plausible request to add this functionality to qpdf for ease of use?
