### ISSUE TITLE
stdin as input file

### ISSUE THREAD

**Issue by jmettraux** [qpdf/qpdf#54]
Thanks a lot for qpdf, it's a wonderful tool.

I'm trying to do things like
```
qpdf --qdf --object-streams=disable x.pdf - | qpdf - - | gzip -c > x.clean.pdf.gz
```

instead, I have to do
```
qpdf --qdf --object-streams=disabled x.pdf _tmp.pdf
qpdf _tmp.pdf - | gzip -c > x.clean.pdf.gz
rm _tmp.pdf
```

Please consider letting us use "-" as "infilename".

**Comment by KurtPfeifle** [comment]
What you want to do is not possible. At least not without some crazy tricks on the part of QPDF.

Any consumer (viewer, processor) wanting to process it in a meaningful way has to start reading it from its end, because there is a "table of content" of its objects. That means, the consumer has to wait for the complete bytes to have arrived before it can start interpreting the PDF data.

There ***ARE*** applications which pretend to process PDFs via stdin/stdout. But these do not really do so: they create/handle/read/delete all the required temporary files in a way that is hidden from the user...

What you want to do you could also implement in a little shell script or in a Bash function. The core of the required code is already in your posting above.     :-)

**Comment by jmettraux** [comment]
Thanks.

**Comment by jberkenbilt** [comment]
Thanks for your comments and suggestion. The other commenter is right that PDF in general fundamentally can't work with non-seekable files like standard input or pipes. It would be possible for qpdf to read the whole file into memory and operate on it that way. While the command-line tool doesn't support this operation, the C++ API does. The QPDF::processFile methods are the usual ones, but there are also processMemoryFile and processInputSource methods. Using processFileMemory, you could read stdin into a buffer and process it that way. If you do this, you have to be careful to avoid someone sending you a huge input buffer or otherwise causing you to allocate unbounded amounts of memory. For processInputSource, I'd refer you to comments in QPDF.hh.

I'm not planning on adding this to the main qpdf command-line tool because I don't think the behavior is what people would be expecting.

**Comment by jberkenbilt** [comment]
One question though....what is your use case for running the file through qpdf twice?

**Comment by jmettraux** [comment]
> I'm not planning on adding this to the main qpdf command-line tool because I don't think the behavior is what people would be expecting.

OK understood. Maybe I'm very naive, I was expecting that behaviour. I wasn't expecting streaming at all, I was just expecting it to behave, on the surface, like a vanilla *nix tool.

Most of the PDFs in my use cases are at most  200K (400K when streams uncompressed). I'm using qpdf command-line tool to prepare PDFs "templates" for later modification with incremental updates. I'm not piping blindly some web input into it.

> One question though....what is your use case for running the file through qpdf twice?

The tool I built is naive, it expects as input PDFs with a vanilla xref table, not one placed in an object stream. At first I used pdftk to uncompress the input PDFs and prepare the template, then I wanted to recompress the stream (keeping the xref table out of a stream). I discovered qpdf (thanks a ton!) via some answer on Stack Overflow. I was planning on inflating with pdftk then deflating with qpdf, then I noticed that qpdf did the inflating part as well. The machine I prepare the PDFs on is a OSX one, since qpdf is readily available via Homebrew (and pdftk is not) I focused on qpdf.

Your question made me test `qpdf --object-streams=disable in.pdf out.pdf` and it behaves like the `qpdf --qpdf --object-streams=disable in.pdf | qpdf - out.pdf` I was longing for. Thanks for the hint.

Please close this issue then. Thanks for your hard work.

**Comment by tobiasBora** [comment]
Just to let you know, I'd also be interested in this feature. The use case I've in mind is that I'd like to automatically add some numbers on top of a file. I can do is using pdftk using:

    echo "I will be stamped on top of the page" | enscript -B -f Courier-Bold16 -o- | ps2pdf - | pdftk input.pdf stamp - output output.pdf 

However, with qpdf I need to use a temporary file, and it's not super elegant:

    tmpfile=$(mktemp) && echo "I will be stamped on top of the page" | enscript -B -f Courier-Bold16 -o- | ps2pdf - "$tmpfile" && qpdf out_merge.pdf --overlay "$tmpfile" --repeat=1-z -- out_oneline.pdf

I also don't care about efficient piping, it's mostly a convenient function.
