### ISSUE TITLE
Removing blank-white pages from PDF

### ISSUE THREAD

**Issue by g-pane** [qpdf/qpdf#540]
Like the title, is possible to remove ALL the blank-white pages without specify the page numbers?
Thanks

**Comment by jberkenbilt** [comment]
No, qpdf does not know how to detect a blank page.

**Comment by g-pane** [comment]
Well i have resolved in this way: extracted all the page, check the page size (white pages are less then few kb), delete that, merge all again. In theory can by applied also to the qpdf

**Comment by jberkenbilt** [comment]
This may work some of the time, but it isn't reliable. You could have a blank page that is large because of non-visible annotations, unused font references, boilerplate content like state save/restore and scaling operations, or other things that don't render on the page, and you could have a non-blank page that is tiny because it it contains is a single word or number. Detecting whether a page is truly blank is subtle and probably requires a full-fledged PDF interpreter like ghostscript or poppler. You might get by with extracting pages to images using one of those tools and then determining whether the image is completely blank.

**Comment by rubyFeedback** [comment]
Not that I recommend anyone do this, but this may be an interesting challenge for anyone who has too much time: determine whether g-pane's made claim is indeed correct (e. g. kb threshold). Perhaps it may be applicable to most pdf files in the wild, then it could work to some degree of usability. (I am not entirely sure why the pages would have to be extracted though ... is it not possible to check the individual size of a page in a .pdf file as-is?)

**Comment by Sicos1977** [comment]
You can do this with Ghostscript, it has an inkcov device that will tell you what kind of colors are used on a page. Is no collors are used at all then it will return something like this

gs -o- -sDEVICE=inkcov Y.pdf
gs -o- -sDEVICE=inkcov Y.pdf
The devices print their output in a format like this:

Page 1
 0.10022  0.09563  0.10071  0.06259 CMYK OK
Page 2
 0.06108  0.05000  0.05834  0.04727 CMYK OK

**Comment by Sicos1977** [comment]
And if you want to do something simular with a scanned page that turned gray then first process the page with something like ImageMagick to convert it to black and white with otsu thresholding

```c#
WriteToLog("Converting image to black and white with auto threshold method OTSU because the option 'ConversionOptionImage.ToBlackAndWhiteAutoThreshold' has been set");
                image.AutoThreshold(AutoThresholdMethod.OTSU);
                WriteToLog("Image converted to black and white");
```

**Comment by jberkenbilt** [comment]
I'm going to close this issue since there is no actual qpdf problem here. If you need further help, please reopen.
