### ISSUE TITLE
not support file name include exclamation mark 

### ISSUE THREAD

**Issue by raidsan** [qpdf/qpdf#549]
win10:  qpdf 10.3.2,   msvc version

issue:  not support file name include  exclamation mark : "!" 

execute;
qpdf.exe --decrypt  xxx!.pdf   xxx!_d.pdf

prompt:
open xxx!.pdf: No such file or directory

**Comment by jberkenbilt** [comment]
This is most likely not a qpdf issue. qpdf doesn't care what the file name is. This is probably some kind of shell quoting issue. I am not sufficiently familiar with Windows command-line to know what it might be. Certainly in bash or a similar UNIX-like shell, the ! character is interpolated as a history reference, but that doesn't appear to be happening here.

**Comment by rubyFeedback** [comment]
(This is mostly a comment to raidsan)

I use a ruby script that renames awkward or questionable characters in files in general; most
importantly the " " actually because bash on linux struggles with it, so it becomes "_". ! or ? and
() are also good candidates to get rid of them. You could try putting them in "" quotes and see 
whether that makes a difference.

If you really want to work with files that contain odd characters then perhaps a small test suite could be added to verify that qpdf would work with these, but I am not even really sure it's worth it. It seems such a small issue compared to what most people probably use qpdf for. In my case I would not even run into such a particular issue simply because I just use ruby to sanitize file names in general.

**Comment by raidsan** [comment]
Sorry, please close this issue.   
I checked it again and found it's dos shell issue.
for %a in (*.pdf) do qpdf --decrypt "%a" "%~na_d.pdf"
It can't support  exclamation mark param.

**Comment by jberkenbilt** [comment]
Thanks for the follow-up.
