### ISSUE TITLE
Use consistent font names?

### ISSUE THREAD

**Issue by shreevatsa** [qpdf/qpdf#550]
This is a feature request, I think, unless this already exists: Is there a way to rewrite a PDF such that a font name like `/F4` always refers to the same font, across all pages?

Background (apologies as I'm likely using some terminology incorrectly): I'm trying to get a list of all the `Tj` operations in a certain PDF, grouped by font. (To see which glyphs are used how often from which fonts.) Running `qpdf --qdf foo.pdf foo2.pdf` is very useful, as (at first sight) it reduces the problem to—instead of using a full-fledged PDF parser—just `grep` in `foo2.pdf` (for lines starting with `/F` to see which font is being chosen, and for lines ending with `Tj` to see which glyphs are used). 

Unfortunately, it turns out that the mapping from font name to actual font object is not one-to-one; for instance all four of these lines occur:

```
      /F4 15454 0 R
      /F4 15461 0 R
      /F5 15454 0 R
      /F5 15461 0 R
```

So if there's a way to have font ids (names) globally correspond one-to-one to the objects they're referencing (like, say: `/F4` always means `15454` and `/F5` always means `15461`), it would be convenient.

I skimmed the qpdf manual a bit, but the closest thing I found was about sharing resources (like fonts) across multiple pages. Which I guess is happening here, just with different names each time, so it would be nice if qpdf could also clean up the names to keep them consistent.

**Comment by jberkenbilt** [comment]
One could probably write code to do this, but it's not at all straightforward since the fonts are referenced in content streams in various ways, and in some versions of PDF, even nested form xobjects might reference fonts defined in pages the contain them. Trying to group by font using the symbolic font name is not a sound approach, and even if the font references were consistent, it wouldn't behave correctly for subsetted fonts. If you really want to group by font, you will have to build in a little more knowledge about how fonts are represented in the PDF, such as resolving the font reference to a font dictionary, checking to see if it's subsetted and going back up to the base font, etc. Once you have resolved the symbolic font name back to the real font, you could group by underlying font object rather than by font name. This would work well in some cases, but it would still not be perfect in cases in which the same font was embedded in the file multiple times, which could happen if pages were combined from multiple files. There's an open request to add code to qpdf that would detect when identical objects were added to a file multiple times and coalesce them. If that were implemented, it might help further, but I'm not sure if/when I would implement that. Even if I did, it would have to be conditional since sometimes it is the intention to embed identical objects multiple times, or more accurately, to have certain objects be non-shared even if they happen to be identical to other objects.

I hope this explanation helps.

**Comment by shreevatsa** [comment]
Thanks a lot for taking the time to explain!

The specific PDF I was working with didn't have many of these complications (the font was always either in the page's resources, or in the nested form xobject's associated dictionary, if I understand correctly), so I think that keeping this consistent in at least one direction (namely: avoid reusing a symbolic font name to refer to different things, e.g. `/F4` always means the same font, but it's ok if the same font could have multiple names like `/F4` and `/F5` and so on…) might still be useful in at least some cases, but I do understand that it would not be perfect in the general case, and this seems a niche use case anyway. (I started looking at a proper PDF parser in the meantime too.)

Thanks again,
