### ISSUE TITLE
learnability issue: can't use --pages for more than 1 time

### ISSUE THREAD

**Issue by colourful-land** [qpdf/qpdf#555]
This works ( page 1-4 from the first file, then every page from the 2nd file)

````
$ qpdf /tmp/edcon.pdf --pages . 1-4 /tmp/Hotel\ Bogota.pdf -- /tmp/outfile.pdf
````

This doesn't ( page 1-4 from the first file, then every page from the 2nd file, then page 5-6 from the first file)

````
$ qpdf /tmp/edcon.pdf --pages . 1-4 /tmp/Hotel\ Bogota.pdf --pages . 5-6 -- /tmp/outfile.pdf

qpdf: error at * in numeric range *--pages: unexpected separator

Usage: qpdf [options] infile outfile
For detailed help, run qpdf --help

````

This format doesn't work either

````
$ qpdf /tmp/edcon.pdf --pages . 1-4 --pages /tmp/Hotel\ Bogota.pdf 1-10 --pages . 5-6 -- /tmp/outfile.pdf
````

The correct format turned out to be:

````
$ qpdf /tmp/edcon.pdf --pages . 1-4 /tmp/Hotel\ Bogota.pdf . 5-6 -- /tmp/outfile.pdf
````

This issue is about *learnability*, that is an average user will only have about 1/2 hour to play with various options following the manual, so if one of these "should work" syntax is wrong for such users, then the syntax can be improved to improve learnability. 

I don't have a more learnable syntax to propose right now, but please kindly not close this issue by stating the user used a wrong syntax and since the bug reporter already learned the right one there is no issue.

**Comment by jberkenbilt** [comment]
I know that qpdf's command-line syntax is a train wreck. However I have a strict backward compatibility policy -- I will make a lot more enemies by breaking people's scripts with upgrades than by having a challenging and sometimes obtuse command line syntax.

I will leave the issue open as you suggest and tag it as documentation. I'm not sure actually what qpdf does with multiple `--pages` options. It's probably not a case I tested. I will figure out from the code whether it does something sensible, but doesn't appear to be. If not, then I will either make it so that all the different `--pages` options concatenate, which would have made your original guess work, or else will have it give a sensible error message, like saying that `--pages` may be given once.

You said you don't have a more learnable syntax in mind, but maybe you can suggest an error message that would have pointed you in the right direction more quickly?

Thanks for taking the trouble to report this even after figuring it out. Usability issues are still issues.

**Comment by rubyFeedback** [comment]
> I know that qpdf's command-line syntax is a train wreck.

I work around this by trying to stay to what is simple.

For example, I have a ruby script that just delegates to qpdf for removing a single page. That script generates e. g. the string command:

    qpdf foo.pdf --pages foo.pdf 1-124,126-z -- output.pdf

which is then executed via ruby's system(). (Or `` or popen if necessary but system() suffices).

I tend to forget options in general. If you are worried about qpdf, you may not have yet tried
ffmpeg filter's syntax or imagemagick's more advanced commands. I use ruby to try to simplify
the complexity and reduce it; admittedly this may not be a common use case so this may not
be useful for colourful-land.

Perhaps you could say the backwards compatibility is retained, but at the same time find a 
way to design syntax that may be "more understandable", like if qpdf would not have this,
how it may look if you were to re-design or create it anew / from scratch. People could also
provide some input.

Personally I actually prefer verbose options (because I autogenerate them via ruby anyway)
and I also prefer using =, simply because my brain has an easier time dealing with this, such
as --output=/foo/bar.pdf. But admittedly the raw commandline users will prefer to omit the "="
which I can understand as well.

For the "maybe you can suggest an error message that would have pointed you in the right
direction more quickly" - I am not the issue starter so I can not talk for him. However had 
when qpdf understands the syntax or intent, it could recommend an alternative. This is kind
of what the "did-you-mean" gem in ruby does. It's more for typos, like when you mis-spell a
method name, but the underlying idea is quite nice. Or the fish shell - while I still use bash,
I like that the fish shell tries a different approach.

I think the primary issue may be the --pages option. Perhaps it could help if there is a file
with recommended syntax that also works. (Come to think about it I would not know how
to look, but you could recommend this via the commandline if so desired; some rust-specific
projects also provide direct links to github issue trackers. I think I saw this with GraalVM as
well. Of course the question is whether you want to use the issue tracker as additional 
helper or not, but these are just a few examples where information could be shown. I
admittedly make heavy use of StackOverflow too, it's better than reading man-pages.
Even after almost 20 years of using Linux, I have almost never read a local man-page.
It's like the 1970s are haunting us still! :D )

**Comment by colourful-land** [comment]
>  like if qpdf would not have this,
> how it may look if you were to re-design or create it anew / from scratch. People could also
> provide some input.

Okay, if I empty my brain, unlearn whatever I learned about qpdf, then I probably would guess the following:

### Take out page 1.

    $ qpdf in.pdf --pages 1 > out.pdf

Or

    $ qpdf in.pdf --pages 2 -o out.pdf

One might argue for  `qpdf -i in.pdf --pages 2 out.pdf`, which is what `ffmpeg` does. (That is, bare filename are the output, input files are prefixed `-i `). I feel qpdf users are more likely familiar with `curl` then `ffmpeg`.

Running the following produces an error

    $ qpdf in.pdf --pages 1
    Cowardly not printing PDF to the console. Redirect the output to a file, or use `-o -`.

### Display information about in.pdf, no processing command such as `--pages` given.

    $ qpdf in.pdf

### Take out page 1, 3 and 5-7

    $ qpdf in.pdf --pages 1,3,5-7 > output.pdf

### Take page 1 from file in1.pdf, page 2 from file in2.pdf

     $ qpdf in1.pdf --pages 1 in2.pdf --pages 2 > output.pdf

### Split pages

     $ qpdf in.pdf --split-pages -o output#.pdf

Running the following produces an error

     $ qpdf in.pdf --split-pages > output.pdf
     When using --split-pages, the output can't be redirected. Try -o output#.pdf

### Multi-process

Take first 3 pages then split them.

      $ qpdf in.pdf --pages 1,2,3 --split-pages -o output#.pdf

This produces the same result:

     $ qpdf in.pdf --pages 1,2,3 | qpdf --split-pages -o output#.pdf

**Comment by jberkenbilt** [comment]
@colourful-land What I'm going to do is have the CLI notice that `--pages` is given more than once and give an error. Unfortunately most of your suggestions for alternative command-line syntax don't feel any clearer than what I have and, in some cases, can't be generalized or create other problems. I appreciate the thought you put into it. Note that the PDF file format requires the input to be seekable, so pipes and so forth don't work. Any PDF-reading application that reads from stdin must be creating temporary files or reading into memory.

**Comment by jberkenbilt** [comment]
I have also tried to notice if someone forgot to end `--pages` with `--`. So now your earlier guesses say

```
qpdf: the --pages option must be terminated with -- by itself

Usage: qpdf [options] infile outfile
For detailed help, run qpdf --help
```
