### ISSUE TITLE
Page selection: Exclude pages instead of include? (for example --pages 1-z,x5,x17,x23)

### ISSUE THREAD

**Issue by amishmm** [qpdf/qpdf#564]
I have a big PDF file with say 100 pages.

I do not want some random pages in it (say page 5,17,23,29,75 so on)

So for page selection I have to do --pages in.pdf 1-4,6-16,18-22,24-28,30-74,76-z.

Is there an easier way where I can specify pages to exclude?

Like --pages in.pdf 1-z,x5,x17,x23,x29,x75 so on? This will select all pages except page 5,17,23,29,75

If feature is not there then I would like to propose the feature.

Feature can be extended as a range say, x5-10 i.e. exclude pages 5 to 10. Keep rest.

If there is conflict then last one wins, for example,
--pages in.pdf 5-10,x6 - will exclude page 6
But
--pages in.pdf x6,5-10 - will include page 6

Thank you.

### Originally discussed in https://github.com/qpdf/qpdf/discussions/563

**Comment by jberkenbilt** [comment]
Thanks for creating the issue. I'm tagging this with `pages`, which I will check when I'm updating the page handling code in the library for qpdf 11.

**Comment by jberkenbilt** [comment]
This is similar to #790

**Comment by jberkenbilt** [comment]
@amishmm I think I will take your syntax suggestion. I had been thinking `2-5,-3` would mean pages 2, 4, and 5, but I think `2-5,x3` is probably less confusing. Anyway, I plan to do this next.

**Comment by amishmm** [comment]
Great! Thanks!

Yes only -3 is confusing because hyphen (-) is already used for page range.

And x3 can mean exclude 3 where x means exclude.

**Comment by jberkenbilt** [comment]
Here's what I'm planning on building. A numeric range consists of a sequence comma-separated of "groups" where each group is `(x?)(z|r?\d+)(?:-(z|r?\d+))?`. Here, the first capture group is either `x` or empty, and the second and, if present, the third, are specifications of a single page. If there's no `x`, it means what it means now. `x` is disallowed for the first group. Otherwise, it means to exclude a page from the most recent non-`x` group. Example: `1-5,x3,2-7,x4-5` = `1,2,4,5,2,3,6,7`. This works for all the examples in your original description except `x6,5-10` would be invalid by itself, but as you suggest, it would include page 6 if it were preceded by other valid groups.

I was going to do this as part of `pages`, but instead, I will do it immediately before since it doesn't require changing anything except numeric range parsing. Thanks for the great suggestion, complete with syntax. Too bad it took me over two years to get to it, but such is the world of small open source projects!

**Comment by jberkenbilt** [comment]
(Plus, as now, if the whole range ends with `:even` or `:odd`, only even or odd pages are selected from the entire group.)

**Comment by amishmm** [comment]
Great. Thanks for implementing.

**Comment by amishmm** [comment]
Hope this would also consider this case 1-z,x5-10 --- include all pages except 5 to 10.

Also I think there is slight confusion for your example: `1-5,x3,2-7,x4-5 = 1,2,4,5,2,3,6,7`

In this case I would expect parsing as follows:

1-5 pick page 1 to 5 --- pages to include 1,2,3,4,5
x3 exclude page 3 - pages to include now 1,2,4,5
2-7  -- pages to include now 1,2,3,4,5,6,7 (3 gets reintroduced)
x4-5 ---- pages to include now 1,2,3,6,7

So I would expect final output as 1,2,3,6,7

**Comment by jberkenbilt** [comment]
My original example is correct -- pages don't get "reintroduced" since you can repeat pages.

**Comment by jberkenbilt** [comment]
From the test suite and manual:
```
   - - ``4-10,x7-9,12-8,xr5``
     - In a 15-page file, this is 4, 5, 6, 10, 12, 10, 9, and 8 in
       that order. That is pages 4 through 10 except 7 through 9
       followed by 12 through 8 descending except 11 (the fifth page
       from the end)
```
