### ISSUE TITLE
linearize pdf doesnt help random page access

### ISSUE THREAD

**Issue by pkgitlab** [qpdf/qpdf#569]
I have many pdfs that were ocr-ed  by archive.org.  When I try to linearize them with qpdf I do not get much help, for example when I load the sample pdf below using pdf.js (disable autofetch and streaming) and jump to page 44 or 99 it downloads over 8MB each time.  I expected it to download at maximum 200 or so KB.  Is something wrong with the pdf, or is qpdf unable to linearize it?

Sample pdf: https://assets.studyring.org/assets/books/baws/TN/Tamil_Volume10_opt.pdf

Thanks!

**Comment by jberkenbilt** [comment]
Linearization enables the browser to start displaying the file before it is downloaded. To display a specific page, you still have to download up to the page. Also, the viewer has to specifically take advantage of linearization, and a quick search through pdf.js source code suggests that it is not handling linearized files specially. The way the PDF file format works requires the viewer to have the entire file before it can process since cross reference tables are located at the end. Linearization is a special format that adds secondary information to the beginning of the file that allows the browser to start displaying the file before it is fully downloaded. It doesn't enable the browser or viewer to download only the page being viewed.

Please let me know if I have misunderstood something about the issue. Thanks.

**Comment by jberkenbilt** [comment]
I'm going to close this, but feel free to reopen if there is still a problem after my explanation. Thanks!

**Comment by pkgitlab** [comment]
Thank you, i actually got it all working well.  The qpdf coalesce function is what I was also assuming linearization will do.  After i switched to coalesce the pdf things work as I expected.  The main idea is to keep all data required by a page close by and possibly pages are kept sequential for the special scanned pdf that I am using.

**Comment by jberkenbilt** [comment]
Great to hear it. Thanks for following up.
