### ISSUE TITLE
Slow exit on some windows 10 versions

### ISSUE THREAD

**Issue by merco** [qpdf/qpdf#577]
Using the --check --warning-exit-0 options, it happens that on some PCs the exit from qpdf takes up to several minutes (2m20s), compared to other PCs (only 50 seconds).
For what reason?
[a.pdf](https://github.com/qpdf/qpdf/files/7554034/a.pdf)

**Comment by jberkenbilt** [comment]
This file has pages with complex vector graphics that are drawn out in the PDF, so the PDF page content streams are very long and take a long time for qpdf to parse. You see this with `--check` because it actually parses every content stream in that case, though normally qpdf doesn't do this. As for why it's slower on some computers than others, I don't have an answer to that. Some PCs are slower, have less RAM, slower disks, slower network connections, whatever. More likely than not, you're just noticing a difference because this file is complicated and computationally intense to parse.

**Comment by jberkenbilt** [comment]
I'm going to close this issue, but if you discover a problem with it and need more assistance, please feel free to reopen.
