### ISSUE TITLE
WRONG EXIT STATUS

### ISSUE THREAD

**Issue by gittrolo** [qpdf/qpdf#578]
**This simple php code:**
`exec('"qpdf.exe" --encrypt "pass" "pass2" 128 --modify=none --extract=n --annotate=n -- "file.pdf" "file_crypt.pdf" 2>&1',$output,$exit_status);`
`print_r("EXIT STATUS: ".$exit_status."\n"); `
`print_r("OUTPUT: ".implode(' ',$output));`

**produce this result:**
`EXIT STATUS: 0`
`OUTPUT: qpdf: writing a file with RC4, a weak cryptographic algorithm Please use 256-bit keys for better security. Pass --allow-weak-crypto to suppress this warning. This will become an error in a future version of qpdf.`

**According to the documentation the exit status should be 2 no 0:**

The exit status of qpdf may be interpreted as follows:

0: no errors or warnings were found. The file may still have problems qpdf can't detect. If --warning-exit-0 was specified, exit status 0 is used even if there are warnings.

2: errors were found. qpdf was not able to fully process the file.

3: qpdf encountered problems that it was able to recover from. In some cases, the resulting file may still be damaged. Note that qpdf still exits with status 3 if it finds warnings even when --no-warn is specified. With --warning-exit-0, warnings without errors exit with status 0 instead of 3.

**Comment by jberkenbilt** [comment]
The behavior is as intended. It is a warning, not an error, so it definitely should not be 2. The reason it is 0 and not 3 is that it is not a warning about the file but rather a warning about the usage of the program. An exit status of 3 implies that there could be something wrong with the input file or output file, which is not the case here. I actually explain this in a comment in the code, but it appears that I left it out of the documentation. In any case, it was definitely intentional as I didn't want to create a situation where files that worked perfectly and gave an exit status of 0 suddenly started giving an exit status of 3 on a minor upgrade from 10.3 to 104.

**Comment by gittrolo** [comment]
Ok. Thank you very much
