### ISSUE TITLE
Unable to link to QPDFObjectHandle::addTokenFilter in libqpdf

### ISSUE THREAD

**Issue by plsmphnx** [qpdf/qpdf#580]
When attempting to use `addTokenFilter`, I receive the following error from ld:
```
/usr/bin/ld: /tmp/ccwhwjYs.o: in function `redactPage(Arguments&, QPDFPageObjectHelper&)':
redact-pdf.cc:(.text+0x367): undefined reference to `QPDFObjectHandle::addTokenFilter(PointerHolder<QPDFObjectHandle::TokenFilter>)'
```
Hazarding a guess, could this be related to `QPDF_DLL` missing on that method and/or `QPDF_DLL_CLASS` on the class?

Running on Debian unstable (libqpdf-dev@10.4.0-1) through WSL.

**Comment by jberkenbilt** [comment]
Wow, you're right. I guess no one has tried calling this before. If I fix this right now, I'll have to bump the version to 10.5. Is this blocking you, or do you have a workaround? Is there a reason that you need to call this rather than QPDFPageObjectHelper::addTokenFilter as suggested by the comment? In any case, this is an oversight, and I will definitely make sure the fix is in whatever the next qpdf release is > 10.4.x.

**Comment by plsmphnx** [comment]
It's not blocking for my specific use-case, so no rush. In the general case, I'm trying to make minimally-invasive edits, which is why I'd prefer `addTokenFilter` (which can act on streams independently) over `addContentTokenFilter` (which will always do a coalesce first).

**Comment by jberkenbilt** [comment]
> It's not blocking for my specific use-case, so no rush. In the general case, I'm trying to make minimally-invasive edits, which is why I'd prefer `addTokenFilter` (which can act on streams independently) over `addContentTokenFilter` (which will always do a coalesce first).

Make sense. Okay, I will definitely make sure this is in the next release that adds interface. I have a few more changes piling up, so I don't think it will be long, though I can never commit to a hard timeframe.
