### ISSUE TITLE
Segfault on qpdf_cleanup

### ISSUE THREAD

**Issue by lklein53** [qpdf/qpdf#583]
Hi together,

I am trying to use qpdf (version 10.4.0 with libqpdf.so.28) from C# and have been successful so far, but now I am encountering the following error.
A call to `qpdf_cleanup` segfaults if i previously obtain the creator of a pdf file via the following C# code:
```
var trailer = qpdf_get_trailer(qpdfData);
var infoId = qpdf_oh_get_key(qpdfData, trailer, "/Info");
var creatorId = qpdf_oh_get_key(qpdfData, infoId, "/Creator");
var creator = qpdf_oh_get_utf8_value(qpdfData, creatorId);
```
If i remove `var creator = qpdf_oh_get_utf8_value(qpdfData, creatorId);` everything works fine. I checked that the value obtained via `qpdf_oh_get_utf8_value(qpdfData, creatorId)` is the correct creator of the pdf file.
Could you maybe give me a hint what I am doing wrong ? 

Kind regards,
Lars

**Comment by jberkenbilt** [comment]
You haven't actually included a call to `qpdf_cleanup` in your example, so I don't have much to go on, but I'm going to go out on a limb and guess that you are calling `qpdf_cleanup(qpdfData)` instead of `qpdf_cleanup(&qpdfData)`. I don't know C# so I don't know what the syntax is for passing a pointer or if you can even do that, but `qpdf_cleanup` takes a pointer. If that's not it, please supply a little more context and maybe I can help, or maybe one of the helpful people who occasionally comment on issues created by people using platforms I'm not familiar with will chime in.

**Comment by lklein53** [comment]
Hi,
thanks for the quick reply. Oh sorry forgot to include the call to `qpdf_cleanup`. 
I saw that it takes a pointer to qpdfdata and I call it like this:
```
var qpdfData = qpdf_init();
...
qpdf_cleanup(ref qpdfData);
```

I also don't get the segfault without the call to `qpdf_oh_get_utf8_value(qpdfData, creatorId)` whereas if i only pass `qpdfdata` (without the ref) to `qpdf_cleanup` i always get a segfault even without the call to `qpdf_oh_get_utf8_value(qpdfData, creatorId)`.

**Comment by jberkenbilt** [comment]
Have you carefully read the comments about strings in qpdf-c.h? I had forgotten this myself until I just looked through the code. The functions that return `char const*` are returning a pointer into an internal buffer that is reused and destroyed by `qpdf_cleanup`, so you always have to copy the result. It's not a beautiful interface, but it basically delegates the memory management to the caller, and since the C API is primarily intended for use by callers from other languages (such as what you are doing), I didn't want to have it returning dynamically allocated strings, not being sure exactly how that would work across various languages. Rather than implementing my own kind of heap management or something, I went with the decision to have the library return pointers to an internal buffer. I think if you copy the null-terminated char* into a proper string, you should hopefully be okay. It occurs to me as I write this that this won't handle strings with embedded null characters properly. If that were important, I would have to add a method to return the length of the most recently returned string. That would be a trivial enhancement.

Coincidentally, I'm having a discussion with someone who is using this API from rust as well. I'm hoping to spend some time improving some qpdf APIs over the next several weeks, though I can't guarantee anything. If you have suggestions as to how I can improve this to make it easier to use from C#, I'd welcome those suggestions. One thing that I am planning is moving most of the functionality from the CLI into the library and having interfaces that can be used to construct an operation similarly to what is happening with the CLI now. I don't know what that will look like yet, but I have some ideas. I want to expose that from the C API as well.

**Comment by jberkenbilt** [comment]
I have made a note to myself to add the thing that returns the length of the temporary buffer. For now, you'll just have to get its length as a null-terminated char*.

**Comment by lklein53** [comment]
Hi, yes i have read the comments about strings in the documentation and i am immediatly comparing the content of the `Creator` field and not using it afterwards anymore. So it should be fine if the buffer is cleaned by the call to `qpdf_cleanup`.
I also changed the code to copy the content, but this also didn't help

**Comment by jberkenbilt** [comment]
Okay, in that case, I don't have any further suggestions. I tried the following straight `C` code:

```C
#include <qpdf/qpdf-c.h>
#include <stdio.h>

int main(int argc, char* argv[])
{
    qpdf_oh trailer;
    qpdf_oh info;
    qpdf_oh creator;
    qpdf_data qpdf = qpdf_init();

    printf("%d\n", qpdf_read(
               qpdf,
               "/home/ejb/source/qpdf/qpdf/qpdf/qtest/qpdf/field-types.pdf",
               NULL));
    trailer = qpdf_get_trailer(qpdf);
    info = qpdf_oh_get_key(qpdf, trailer, "/Info");
    creator = qpdf_oh_get_key(qpdf, info, "/Creator");
    printf("%s\n", qpdf_oh_get_utf8_value(qpdf, creator));
    qpdf_cleanup(&qpdf);
    return 0;
}
```

and built with `clang -fsanitize=address -fsanitize=undefined -Wall a.c -lqpdf`. The program ran as expected with no memory errors. So I don't think it's likely to be a problem with qpdf itself.

Maybe someone else may have suggestions, or if you figure it out, feel free to post back here for the benefit of someone else who may bump into the same issue. Sorry I am not able to be of more help on this.

**Comment by lklein53** [comment]
Thank you very much for your effort. I will see if i can figure it out and post back if i have a solution

**Comment by lklein53** [comment]
Oh damn I figured it out. I messed up the order in which i free the memory in which the pdf is stored and the call to `qpdf_cleanup`. Sorry for the wrong issue report

**Comment by jberkenbilt** [comment]
No worries...anyway, it made me realize there was no way to know the length of the internal string and handle embedded nulls, so that will be fixed for the next version. :-) I'm glad you figured it out. Thanks for the follow-up.
