### ISSUE TITLE
qpdf --show-encryption doesn't work without providing a password

### ISSUE THREAD

**Issue by neuhaus** [qpdf/qpdf#598]
I wanted use qpdf to check a password protected PDF to see if it was using AES encryption or the weaker RC4 encryption.

Unfortunately just invoking `qpdf --show-encryption file.pdf` did not show any output other than `file.pdf: invalid password`.

Can qpdf not provide this information without providing a password?

**Comment by jberkenbilt** [comment]
I'm guessing this should be a small enhancement. I'll look through the code and see if I can make it work without a big change. It is definitely possible to know this without actually decrypting the file.

**Comment by jberkenbilt** [comment]
Unfortunately, it's not a trivial fix because the current flow requires the PDF file to be successfully processed, which requires the password. I am going to do some major rework of the top-level flow for qpdf 11, and I will try to work this in. There's actually quite a bit of information that can be obtained from encrypted files without a password. Probably I will have to add some flag to the library that will allow qpdf to continue on encrypted files without decrypting. I'll have to give it some thought.

**Comment by jberkenbilt** [comment]
I have this on the roadmap for qpdf 11. It probably won't happen before summer (and I can't make time commitments) but I have some ideas about how to handle it and may need the same required changes for a second purpose as well.

**Comment by jberkenbilt** [comment]
This is going in for qpdf 11 which I hope to get out in the next week or so.
