### ISSUE TITLE
Text is hidden after setting value of form fields

### ISSUE THREAD

**Issue by darwing1210** [qpdf/qpdf#655]
I'm trying to fill a blank empty PDF form with values using the example in https://github.com/qpdf/qpdf/blob/main/examples/pdf-set-form-values.cc but in the resulting PDF the fields are not visible (or are in white/transparent color) in the viewer until I try to edit the field.

Tried with `./pdf-set-form-values infile.pdf outfile.pdf PPPPPPP`

What I'm missing?, I'll appreciate any help and thanks for creating this awesome library

Screenshot taken with Mac preview (got the same result with Adobe viewer)
![image](https://user-images.githubusercontent.com/18296414/154591878-edd75aee-a240-4cec-bd78-ded2aee8fa8c.png)

[infile.pdf](https://github.com/qpdf/qpdf/files/8093016/infile.pdf)
[outfile.pdf](https://github.com/qpdf/qpdf/files/8093017/outfile.pdf)

**Comment by jberkenbilt** [comment]
Took me a while to figure it out, but the PDF file in question has its formula for creating appearances set to use a 0-size font for display. There is logic in qpdf to fall back to a fixed font size when that happens, but in this case, it seems that it is putting the font size in the wrong place. This is definitely a qpdf bug triggered by a PDF file that does something weird.

In this particular instance, calling `setNeedAppearances(true)` or otherwise not calling generateAppearance would bypass qpdf's appearance stream generation, and then the fields would show. qpdf is correctly setting the field values. It is just not correctly generating appearance streams.

I'll tag this as a bug and fix it the next time I work on qpdf, which might not be for a while, but I will definitely get to it. Thanks for the report, and sorry for the problem.

**Comment by jberkenbilt** [comment]
Actually, I think it's more or less a one-liner. I'm going to try a fix.

**Comment by jberkenbilt** [comment]
This fixes it but it is only a partial fix. There's still a bug with tf_idx == 0 if no Tf appears at all.

```patch
diff --git a/libqpdf/QPDFFormFieldObjectHelper.cc b/libqpdf/QPDFFormFieldObjectHelper.cc
index be70d2db..a31be830 100644
--- a/libqpdf/QPDFFormFieldObjectHelper.cc
+++ b/libqpdf/QPDFFormFieldObjectHelper.cc
@@ -833,16 +833,17 @@ TfFinder::handleToken(QPDFTokenizer::Token const& token)
         break;
 
       case QPDFTokenizer::tt_word:
-        if ((value == "Tf") &&
-            (last_num > 1.0) &&
-            (last_num < 1000.0))
+        if (value == "Tf")
         {
-            // These ranges are arbitrary but keep us from doing
-            // insane things or suffering from over/underflow
-            tf = last_num;
+            if ((last_num > 1.0) && (last_num < 1000.0))
+            {
+                // These ranges are arbitrary but keep us from doing
+                // insane things or suffering from over/underflow
+                tf = last_num;
+            }
+            tf_idx = last_num_idx;
+            font_name = last_name;
         }
-        tf_idx = last_num_idx;
-        font_name = last_name;
         break;
 
       default:
```

**Comment by jberkenbilt** [comment]
Results are not ideal in that qpdf doesn't actually know the size of the bounding box that it has to squeeze the text into, so the text will be truncated in the appearance streams. Fixing that would require quite a bit more effort as it would require understanding font metrics and calculating all the matrices. But this at least isn't throwing away the text and damaging other parts of the appearance stream.

**Comment by darwing1210** [comment]
It works, You are awesome!!! Thanks for taking the time

**Comment by jberkenbilt** [comment]
Thanks for catching it and providing a simple file that reproduced it!
