### ISSUE TITLE
Build fail with Visual studio 2010 

### ISSUE THREAD

**Issue by myongjin-do** [qpdf/qpdf#659]
Hi

I'm trying to build qpdf with visual studio 2010 because of my legacy project

However, an issue related to C++14 occurred.

Here is my error statement

===============================================================================

$ ./config-msvc
+ cl
+ grep -q 'for x64'
+ wordsize=64
+ CC=cl
+ CXX='cl -TP -GR'
+ ./configure --disable-test-compare-images --enable-external-libs --enable-werror --with-buildrules=msvc --enable-crypto-openssl --disable-crypto-gnutls
configure: loading site script /etc/config.site
checking for autoconf... 0
checking for autoheader... 0
checking for aclocal... 0
checking for sha256sum... 1
checking for gcc... cl
checking whether the C compiler works... yes
checking for C compiler default output file name... conftest.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... obj
checking whether we are using the GNU C compiler... no
checking whether cl accepts -g... yes
checking for cl option to accept ISO C89... none needed
checking for cl option to accept ISO C99... unsupported
checking whether we are using the GNU C++ compiler... no
checking whether cl -TP -GR accepts -g... yes
checking whether cl -TP -GR supports C++14 features with ... no
checking whether cl -TP -GR supports C++14 features with -std=c++14... no
checking whether cl -TP -GR supports C++14 features with +std=c++14... no
checking whether cl -TP -GR supports C++14 features with -h std=c++14... no
checking whether cl -TP -GR supports C++14 features with ... (cached) no
checking whether cl -TP -GR supports C++14 features with -std=c++1y... no
checking whether cl -TP -GR supports C++14 features with +std=c++1y... no
checking whether cl -TP -GR supports C++14 features with -h std=c++1y... no
configure: error: *** A compiler with support for C++14 language features is required.

**Comment by jberkenbilt** [comment]
There will be no possibility of building a current version of qpdf with such an old compiler. qpdf's requirement for C++11 is deep as it relies on thread-safe static initialization, and lambdas and other C++11 and 14 features are pervasive throughout the code. You may be successful with qpdf 9.0.2 or older as 9.1.0 was the first version to require a modern compiler. There were some performance issues in the 9 versions that were fixed in 10, but they would only be noticeable on very large files. Supporting a non-C++-14 compiler is a non-goal for qpdf at this time.

**Comment by myongjin-do** [comment]
Thanks for your answer so quickly
