### ISSUE TITLE
PDF shows previously hidden data

### ISSUE THREAD

**Issue by dreua** [qpdf/qpdf#672]
A PDF that seems to contain hidden data will display that data after a simple qpdf operation like:
```
qpdf --empty --pages filename.pdf 1 -- out.pdf
```

qpdf version 10.3.2

Original file:

![Bildschirmfoto von 2022-03-04 13-27-42](https://user-images.githubusercontent.com/9930093/156763707-2ca41bda-183d-4c07-83d2-4a8da11d11cf.png)

Output file:

![Bildschirmfoto von 2022-03-04 13-25-24](https://user-images.githubusercontent.com/9930093/156763804-f9dfc9d6-417b-45e2-ac48-b5ccf3a4e976.png)

As you can see, in the background appears 'John Doe' behind the name. I can only guess that it's a hidden text in the original PDF file.

Unfortunately I can't attach the file for privacy reasons, I'll send it to you via email instead.

Could you have a look whether that is a bug in qpdf?

*(Originally reported by [michael-schaefer-eu](https://github.com/michael-schaefer-eu) as https://github.com/pdfarranger/pdfarranger/issues/639)*

**Comment by jberkenbilt** [comment]
@dreua Hello -- I'm just acknowledging that I have seen your issue and received the file you sent by email. I hope I can find some time this weekend or early next week to study it. When I have some information, I'll let you know, and I can delete the file after I'm done investigating.

**Comment by jberkenbilt** [comment]
Without looking at it, I'd venture a guess that `qpdf filename.pdf --pages . 1 -- out.pdf` won't exhibit the same problem. Anyway, I'll study it soon.

**Comment by dreua** [comment]
>

**Comment by jberkenbilt** [comment]
The issue is that the `/OCProperties` key in the document catalog (`/Root` dictionary) is not preserved when starting with `--empty`. This is a new case that I was not previously aware of of a document-level construct that is not handled correctly by `--pages`. I'm adding the `pages` label to the issue so I can get to it when I'm ready to tackle those issues head-on. That's bubbling up close to the top.

A workaround would be to simply copy `/OCProperties` from the source file to the destination file. A correct fix would involve merging dictionaries across multiple files, and for that I'll have to study that part of the spec.

Note to self: I have saved the file privately in misc/bugs/672/. This file should be removed when the bug is fixed. Once I understand the issue, I should have no trouble hand-constructing a PDF that exhibits the identical behavior.

**Comment by michael-schaefer-eu** [comment]
@dreua , @jberkenbilt  sure you can keep that file if it helps you to fix that :)

**Comment by jberkenbilt** [comment]
This issue is part of the qpdf pages epic. If you are interested in following, please see #1104.
