### ISSUE TITLE
[Suggestion] More information when showing "WARNING:" on the commandline, in regards to damaged .pdf files

### ISSUE THREAD

**Issue by rubyFeedback** [qpdf/qpdf#679]
Hey there,

I just downloaded a .pdf file created by some student, and then uploaded to some exam-question pool.

Now I am working through it and remove some pages in that .pdf file, via qpdf.

Doing this on a first run shows this:

    WARNING: foobar.pdf: file is damaged
    WARNING: foobar.pdf: can't find startxref
    WARNING: foobar.pdf: Attempting to reconstruct cross-reference table
    qpdf: operation succeeded with warnings

Afterwards all worked fine. The part I am wondering about is the "qpdf: operation succeeded with warnings".

Right now I do not seem to be told which warnings were meant. Does this refer to the three WARNING 
statements above? Or does it indicate a warning that is not shown?

Either way my proposal is simple:

The line "qpdf: operation succeeded with warnings" could ideally be better and more verbose. As a start
I would also include how many warnings were triggered, e. g. "with 3 warnings". I would also suggest
that if there are not too many warnings, to show them in the next line with some indentation or something,
so that the user understands what is going on. Perhaps to also show some URL where to read up on
the reconstruction part. I believe I can not get the warnings shown anymore now that the .pdf at hand is
fixed, and it is a non-issue anyway because the subsequent qpdf-operations all are fine - but I worry a
bit in the event that the .pdf file may be damaged. Either way the TL;DR is to request the last message
to become a bit more clear. Perhaps "reconstruction succeeded with 2 minor warnings" or something
that makes it more clear where the last qpdf: operation refers to.

**Comment by mschilli87** [comment]
@rubyFeedback:
> Does this refer to the three WARNING statements above?

That's the only interpretation that came to *my* mind.

> Or does it indicate a warning that is not shown?

I get why you would think that now that I have read your post but I would be very surprised if that was the case. Why would `qpfd` do that?

If you read C++, you should be able to quickly figure this out with certainty from the source code. I'd start [here](https://github.com/qpdf/qpdf/search?l=C%2B%2B&q=%22operation+succeeded+with+warnings%22).

**Comment by jberkenbilt** [comment]
@rubyFeedback I appreciate your feedback and recognize that a catalog of the meanings of error and warning messages would be helpful. Assembling such a thing would be a very large undertaking and is probably not something I can get to in the near term. So I'll clarify a little with some insight into my approach.

* In the early days, qpdf starts its life as a PDF checker and used to issue warnings about anything it encountered that didn't conform to the spec as I understood it. When such warnings were around things that basically no one ever cared about (like the way deleted objects are supposed to be represented in the xref table), I removed them. Some are still there. Warnings of this type are pretty rare. These might be what you call "minor warnings". Honestly I'd have to dig through the code to determine whether there are actually still any warnings of this type. I don't want to completely eliminate these because they are useful to producers of PDF even though they are not useful to consumers. The theme of categorizing warnings has come up several times in various issues, and it's something I may want to consider.
* In the majority of cases, qpdf issues a warning when it has to take a guess about something. The world is full of bad PDF files. There are even some projects out there that are trying to catalog the various ways in which PDF files are broken. Perhaps the most common way PDF files are broken is that people modify parts of them without updating the cross reference table which includes the offset to each object in the file. In this case, what qpdf (and virtually every PDF reader) does is to attempt to scan through the file, locating objects, and reconstructing the cross reference table. Early versions of the PDF spec actually included guidelines on how to recover files and how to create PDFs that are likely to be successfully recovered. qpdf follows these heuristics plus others I have come up with over the years of looking at lots and lots of broken PDF files.

So what does this mean? If qpdf issues a warning, there is no possible way to know whether it's a major issue or a minor issue. In the case of trying to recover an xref table, a simple case of someone having modified contents without updating the xref table would trigger this, and qpdf would likely be able to recover fully. But a truncated file would also trigger it, and qpdf would only be able to partially recover. Also, someone opening the PDF file in a text editor that doesn't handle binary data and saving it would cause this, and the PDF file would probably be completely trashed. (I've seen this more times than you might think.) These situations all look the same to qpdf in its basic mode of just opening a file and preserving the contents.

This is probably not the answer you're looking for, but hopefully it sheds some light on this. I would say that most PDF readers are silent in their attempts to recover, and a damaged PDF file will just not work exactly right. For most of the world, a PDF "works" if it opens and displays properly with Acrobat Reader. Since that is a proprietary and closed-source tool, no one outside of Adobe really knows exactly what types of errors Acrobat tolerates.
