### ISSUE TITLE
I want to use it in my Java project, how do I do it?

### ISSUE THREAD

**Issue by Lalala-YD** [qpdf/qpdf#689]
I want to use it in my Java project, how do I do it?

**Comment by jberkenbilt** [comment]
The previous comment offers good suggestions, but the JSON interface is quite limited at this time. If you want to use qpdf from Java, your options at present are to write JNI code that uses qpdf's C or C++ API or to interface with it through the CLI. Over time, I intend to make it easier for other languages to use qpdf's functionality. For qpdf 11, I will be introducing full, bidirectional JSON serialization of PDF files, and I am hoping to add more functionality in time for creating a JSON API to expose some of qpdf's deeper functionality. The JSON interface the previous caller mentions is limited to only exposing what the qpdf command-line tool can do. This would enable you to get qpdf command-line functionality through JNI rather than a shell command execution but it would not expose the full functionality of the qpdf library.
