### ISSUE TITLE
Show attachment does not redirect the output to cout

### ISSUE THREAD

**Issue by Sicos1977** [qpdf/qpdf#691]
When using this code in my test project

```c#
var job = new Job();
var result = job.InputFile(Path.Combine("TestFiles", "withattachment.pdf"))
    .ShowAttachment("20_pages.pdf")
    .Run(out var output);
```

I would expect that the attachment is written to the redirected output stream but instead it is written to cout. So I suspect that somewhere the redirection of the error and output streams is not set.

I think the problem is in this code

```c++
    QPDFEmbeddedFileDocumentHelper efdh(pdf);
    auto fs = efdh.getEmbeddedFile(m->attachment_to_show);
    if (!fs) {
        throw std::runtime_error(
            "attachment " + m->attachment_to_show + " not found");
    }
    auto efs = fs->getEmbeddedFileStream();
    QUtil::binary_stdout();
    Pl_StdioFile out("stdout", stdout);  <-------- over here
    efs.pipeStreamData(&out, 0, qpdf_dl_all);
```

_Originally posted by @Sicos1977 in https://github.com/qpdf/qpdf/issues/683#issuecomment-1107476133_

**Comment by jberkenbilt** [comment]
Thanks for the report. I will make sure there is a proper fix for this before the next qpdf release. You have correctly identified the source of the problem. I will need to do a general check through the code to make sure that cerr/cout and stderr/stdout are handled properly with respect to setting output streams.

**Comment by Sicos1977** [comment]
I also see another problem when using this option. When people want to save the file to a file or stream then it will go wrong in my wrapper because I'm expecting a string... because the rest of all the method output textual information

In my wrapper code I do this

```c#
var json = JsonConvert.SerializeObject(this, settings);
var result = QPdfApi.Native.RunFromJSONWithResult(json, out var outPointer, out var errorPointer);
var outResult = Marshal.PtrToStringAnsi(outPointer);
var errorResult = Marshal.PtrToStringAnsi(errorPointer);
```

It always converts the data it gets back to a string and that will probably mess up all the data that is returned to me by the pointer from your code.

Still need to figure out how to solve that.

**Comment by jberkenbilt** [comment]
@Sicos1977 Next up is adding the ability to capture stdout and stderr in a more flexible fashion. This will be important when I expose the new json v2 API to the C API, and it should hopefully also alleviate many of the issues you encountered in your work. I'm interested in your input/feedback on my plans.

Right now, both QPDF and QPDFJob have C++ methods that allow redirection of standard output and standard error to `std::ostream`s, but this is not useful to the C API. Also, as you pointed out here, there are a few places in the code that use stdout or stderr instead of the ostreams, so those things slip through output capture.

What I'm planning to do on the C++ side is to use instances of `Pipeline` for all output. There is no portable way to go from FILE* to std::ostream, but a stdio FILE Pipeline has been in qpdf since the beginning, and a std::ostream Pipeline is there now and will be in qpdf 11. I also added a Pipeline that writes to a std::string, and a memory buffer pipeline as been there from the beginning.

For the C API, I was planning on implementing output and error capture by allowing the caller to pass in pointers to functions that get called with every write. For example, a function with this signature:

```C
void (*f)(char* data, unsigned int length, void* user_data)
```

could be passed to the C API along with user_data wherever a Pipeline is used in the C++ API. Use of the extra `user_data` parameter is something I generally try to do with C-based callbacks as it allows context to be passed through. I would make sure that there is a way to reset to the default and also to make sure that using the same function for output and error is supported. I may consider having a separate call specifically for warnings, but I'll have to see how feasible that is. There is some ambiguity around what is a warning for two reasons:
* Sometimes errors get converted to warnings, such as failure to decode a stream
* Some warnings are about usage and not about PDF validation, and those are handled separately, though I'd have to check the code to see if there are still any cases of that left now that failure to provide `--allow-weak-crypto` is an error.

There are a few other wrinkles like where verbose output goes. At present, it goes to stdout, and you can't use `--verbose` with any option that writes to stdout, but I could make that redirectable.

It might be possible to add a convenience method to gather up output, etc., to a buffer, but I'm reluctant to add support for that because people would be lazy and use it even though it would cause undesirable behavior for large things.

For pure C code, it would be easy enough to do something like this C-like psuedocode:
```C
void save(char* data, unsigned int length, void* user_data)
{
    FILE* f = (FILE*)(user_data);
   fwrite(data, 1, length, f);
}

void save_attachment()
{
    FILE* f = fopen("dest", "wb");
    qpdf_set_output(&save, (void*)f);
    qpdfjob-whatever(.... thing that calls --save-attachment ...);
    qpdf_set_output(NULL);
    fclose(f);
}
```
Those aren't the real function names, of course, but hopefully this illustrates the idea. I'm assuming it's possible to pass a callback like this into a C API from C# since this is a common pattern. The qpdf C API already has functions that take function pointers, such as qpd_register_progress_reporter.

Thoughts? I'll probably work on this in the next few weeks.

**Comment by Sicos1977** [comment]
Sounds good to me, I'm no expert in passing things from C# to C++ and back, but I'm good in borrowing things from other people ;-)

**Comment by jberkenbilt** [comment]
This will be fixed for qpdf 11. It is fixed now in the C++ API. I am going to add a C API for it. There is a new logger object, and I will add a C API for configuring the logger object. This will replace the setOutputStreams methods, which will be deprecated. Since I may have no portable way to deprecate things in the C API, I may remove those methods or change their behavior -- I'll figure it out when I get to updating the C API.

**Comment by jberkenbilt** [comment]
The closing commit includes an example of how to do this with the new logger C API.

**Comment by jberkenbilt** [comment]
Comments welcome. (after I push of course)

**Comment by jberkenbilt** [comment]
I'm going to make some changes from what I just pushed.
