### ISSUE TITLE
Typo in information that is returned with the json method

### ISSUE THREAD

**Issue by Sicos1977** [qpdf/qpdf#696]
```json
  "encrypt": {
    "capabilities": {
      "accessibility": true,
      "extract": true,
      "moddifyannotations": true,
      "modify": true,
      "modifyassembly": true,
      "modifyforms": true,
      "modifyother": true,
      "printhigh": true,
      "printlow": true
    },
```

I think moddifyannotations must be modifyannotation :-)

**Comment by jberkenbilt** [comment]
I see there is an inconsistency between the method name and the json field name for forms and annotations, but I'm not sure it's necessarily a problem with breaking compatibility to fix. It's hard for me imagine why I wasn't consistent. So I'm not inclined to fix this. But if I'm overlooking something and there's a reason you think there's a mistake here, please let me know.

I'm just starting work on JSON v2, which while primarily focused on serialization/serialization, does offer a rare opportunity for me to make non-compatible changes. Still, I'd like to keep them to a minimum.

**Comment by Sicos1977** [comment]
> I see there is an inconsistency between the method name and the json field name for forms and annotations, but I'm not sure it's necessarily a problem with breaking compatibility to fix. It's hard for me imagine why I wasn't consistent. So I'm not inclined to fix this. But if I'm overlooking something and there's a reason you think there's a mistake here, please let me know.
> 
> I'm just starting work on JSON v2, which while primarily focused on serialization/serialization, does offer a rare opportunity for me to make non-compatible changes. Still, I'd like to keep them to a minimum.

Uh I don't know if you understand what I ment... don't you write modify with one D instead of 2 DD's ? --> modifyannotations instead of moDDifyannotations

**Comment by jberkenbilt** [comment]
While I've got you on the line, the fix I made to the remove-attachment problem you reported (that it should have taken an array) was not backward-compatible. Before I release qpdf 11, I intend to make it so that the job json format will accept a single value in places where an array is expected and treat it as an array of one. This makes it possible for me to change a non-repeatable option to a repeatable option in the future without breaking old JSON just as it is now possible to do so without breaking the CLI. It would also have the beneficial side effect of not breaking any existing job json files that use a singleton for remote-attachment, though I doubt very many if any such files exist.

**Comment by jberkenbilt** [comment]
> Uh I don't know if you understand what I ment... don't you write modify with one D instead of 2 DD's ? --> modifyannotations instead of moDDifyannotations

You're right, I overlooked that. Actually it took me a minute to figure out what you were talking about at all.

Okay, now I have to decide how I'm going to deal with this. I guess I'll probably fix it for json v2 and leave it wrong for json v1. I can't believe it took so long for someone to notice. Thanks.

**Comment by jberkenbilt** [comment]
It's sadd when you make a tpyo and then bake it in by addding the missspellled word to the spelling checker dictioanry.

**Comment by Sicos1977** [comment]
I'm glad you understand now, sometimes it is hard for me to point out technical details because English is not my native language... Dutch is :-)

**Comment by jberkenbilt** [comment]
I had no idea. I consider myself something of an amateur linguist and can usually spot a non-native English speaker, but in all our interactions, I never noticed anything about your English that made me guess you were a non-native speaker. But this does explain sometimes what seems to be a lack of clarity in some of your explanations! I don't know any Dutch, but I have an aunt by marriage who is Dutch and did a job for the Netherlands branch of Elsevier once. In my limited experience, Dutch speakers who speak English tend to speak it exceptionally well. I'm not sure if this is because of the relative closeness of the languages (both Germanic with some similar quirks) or whether it has to do with the Dutch education system or whether I'm just wrong and I've had interactions with people who just happen to be good English speakers! One of the Elsevier people was a native speaker of Dutch but also fluent in French and English and was the only person in one meeting who spoke all three languages well. Most of us were either French-only or English-only, though all the Dutch speakers also spoke English. He would context switch between languages effortlessly during the first half of the day, but by the end of the day, he'd look at a person, pause, and then start speaking in the wrong language. The person would hold their hand up, and he'd switch. It must have been mentally exhausting, but I envy him to be able to have that problem. I'm an American and, although I've studied a couple of languages and some linguistics, I am only conversational in English. Well, that and a bunch of programming languages, but that doesn't really count. :-)

**Comment by jberkenbilt** [comment]
This is fixed in my local work branch for json v2. I'm not going to tag the issue with it because I am doing lots of rebasing and don't want to keep spamming this issue with every push.
