### ISSUE TITLE
Font is missing after underlay operation

### ISSUE THREAD

**Issue by yshyman** [qpdf/qpdf#709]
I am using tesseract to OCR the PDF documents and produce a pdf with invisible text which uses Glyphless embedded font.

Then I am merging this text pdf as an underlayer to my original pdf.

For a limited set of documents the embedded glyphless font is missing after underlay operation and causing an issue when opening document in strict pdf readers like Adobe Acrobat.

**Comment by jberkenbilt** [comment]
Is there any way you can share a sample document and recipe to reproduce the problem? Otherwise I won't be able to help. Usually I see hidden text from OCR included with `3 Tr` in the text block. This disables rendering regardless of the font. In any case, if qpdf is failing to include the embedded font, this probably means that it is not referenced in the resource dictionary of the page that you are underlaying. This is probably an error in how the underlay file is produced. If that can't be fixed, as a possible workaround, you could try reversing and overlay the other document on top of the one with the glyphless font, though that will have its own disadvantages.

I'm hoping to work on some significant enhancements to page operations like this sometime in the next several months. An example would increase the odds of this case being handled properly.

**Comment by yshyman** [comment]
I can try to find some samples that I can share with you,

**Comment by yshyman** [comment]
Unfortunately, I can't share the problematic document. But after some of experiments I bet something wrong with document itself. I was able to fix the problem by making a clone of the document using qpdf command:
`qpdf --empty --pages source.pdf 1-z -- clone.pdf`

After that everything working fine but cloned output is few kbs less in size than original.
