### ISSUE TITLE
Feature request: example of removing images?

### ISSUE THREAD

**Issue by mdecerbo** [qpdf/qpdf#71]
I was hoping to use QPDF's API to build a tool to remove all the images from a PDF file.
Leaving aside inline images for now, I tried the following:

```
QPDF qpdf;
qpdf.processFile(infilename, password);

std::vector<QPDFObjectHandle> pages = qpdf.getAllPages();
for (std::vector<QPDFObjectHandle>::iterator iter = pages.begin();
     iter != pages.end(); ++iter)  {
  QPDFObjectHandle& page = *iter;

  std::map<std::string, QPDFObjectHandle> images = page.getPageImages();
  for (std::map<std::string, QPDFObjectHandle>::iterator iter = images.begin();
     iter != images.end(); ++iter) {
    QPDFObjectHandle& image = (*iter).second;
    int object_id = image.getObjectID();
    QPDFObjGen og = image.getObjGen();
    if (image.isIndirect()) {
      int og_int = og.getObj();
      qpdf.replaceObject(object_id, og_int,  QPDFObjectHandle::newNull());
    } else {
      qpdf.replaceObject(og,  QPDFObjectHandle::newNull());
    }
  }
}
QPDFWriter w(qpdf, outfilename);
w.write();
```

But the images remain in qpdf when it is written out, so I assume I am doing something wrong.
Any chance of documenting how to do this?

**Comment by jbarlow83** [comment]
Not sure why that code sample doesn't work, although if I'm not mistaken qpdf::replaceObject only updates some sort of cache rather the real thing.

This works:

```c++
QPDFObjectHandle page = qpdf.getAllPages[0];
QPDFObjectHandle res = page.getKey("/Resources");
QPDFObjectHandle xobj = res.getKey("/XObject");
xobj.removeKey("/Im0");  // or whatever the image name is, which can be found in xobj.getKeys()

```

The resulting PDF will contain an error because the page's content stream in `page.getKey("/Contents")` still contains a reference to the image. Command line qpdf does not complain about the missing reference, but Acrobat displays an error.

Also the image could be drawn multiple times on multiple pages. You would have to parse the content stream to remove the commands to images as well.

An example of a content stream that draws an image is

```
q
545.280000 0 0 443.520000 0 0 cm
/Im0 Do
Q
```

You would need to remove the line "/Im0 Do" to remove the remaining reference to the image.

It might also be necessary to recursively delete xobject and resources if delete the image happens to make them empty, to remove empty objects from the PDF.

**Comment by jberkenbilt** [comment]
Sorry I overlooked this until the comment. @jbarlow83 is correct in pretty much all aspects of his response.

A few notes:
* You don't need to differentiate between whether the image is direct or not. As a rule, qpdf doesn't care. Anyway, images can't be direct because they are streams. You could replace the body of your loop with
```c++
            QPDFObjectHandle& image = (*iter).second;
            QPDFObjGen og = image.getObjGen();
            qpdf.replaceObject(og,  QPDFObjectHandle::newNull());
```
* I'm not sure why your code isn't working. It looks like maybe replaceObject is broken for streams. I'll leave this issue open as a reminder, though I don't know when I'd have time to look at it.

In any case, @jbarlow83's suggested implementation is better. Removing the references to the image *should* cause qpdf to drop the images because they are unreferenced. Still, I'm not sure why your code didn't remove the images even though it would create erroneous files.

**Comment by adamreichold** [comment]
Just add a data point on the question of whether this works on streams: I am doing the "replace-object-by-null" variant using the Rust bindings for QPDF and its works fine whittling down 14G of image heavy PDF documents to only 3.5G of mostly text and metadata.
