### ISSUE TITLE
Impossible to decrypt multiple PDF files in directory and sub-directories at once

### ISSUE THREAD

**Issue by SH2282000** [qpdf/qpdf#737]
Issue concerning decrypting multiple PDF files in directory and sub-directories at once:
- [ ] Create an option to do this from the command line
- [x] Here's my script, better ideas? 

```
filenames=`ls *.pdf && ls */*.pdf &&  ls */*/*.pdf &&  ls */*/*/*.pdf` #really bad... I know
#echo filenames
for eachfile in $filenames
do
   echo $eachfile
    qpdf --decrypt --password=<PASSWORD> --replace-input $eachfile
done
```
Otherwise... **really useful** program ❤️

In advance, thank you.

**Comment by jberkenbilt** [comment]
Slightly better is just
```
for eachfile in *.pdf
do
   echo $eachfile
    qpdf --decrypt --password=<PASSWORD> --replace-input $eachfile
done
```

The shell expands wildcards; you don't need to use ls to do it. Using a script is the best option. The `qpdf` command-line syntax is already quite complicated, and adding the ability to deal with multiple input files in a sensible and backward-compatible way is not something I have any intention to do. I'm glad you find qpdf to be otherwise useful. :-) Hopefully the script option will suffice. You can also just run this directly from the command-line without a script, as in

```
for i in *.pdf; do qpdf --decrypt --password=<PASSWORD. --replace-input $i; done
```

**Comment by SH2282000** [comment]
Yes, I thought there was a better way for this, thank you! 

I never really create scripts in shell because _in fine_ programmers are providing enough options to avoid the user to use their program within scripts (for simple usages).
