### ISSUE TITLE
Release tag changed from "release-qpdf-$version" to "v$version"

### ISSUE THREAD

**Issue by dreua** [qpdf/qpdf#772]
My [automation](https://github.com/flathub/com.github.jeromerobert.pdfarranger/pull/103) broke because of the changed tag schema, just wanted to confirm this has been changed on purpose and will stay that way?

**Comment by jberkenbilt** [comment]
Sorry, I added a note just now to the release notes. It was intentional, and it will stay that way. There are various tools that assume this convention. I forget why I changed it exactly. It might have been because of readthedocs. In any case, this seems to be a much more widely used convention, so I decided to adopt it. Sorry for the hassle.

**Comment by dreua** [comment]
No worries and thank you for the quick reply!
