### ISSUE TITLE
qpdf's test suite fails when run with zlib-ng

### ISSUE THREAD

**Issue by jberkenbilt** [qpdf/qpdf#774]
There are several qpdf tests that depend on the output of zlib. Since it seems that some Linux distributions are switching to zlib-ng, it's time for qpdf to support this as an alternative. This ticket tracks that work.

My initial thoughts are:
* Where possible, rewrite tests so that they don't depend on zlib's output. This may not be possible for some tests.
* For remaining tests, come up with some kind of sensible strategy that makes it safe and painless to support API-compatible zlib implementations.

Ideas:
* Have a registered set of zlib implementations that are known to work, and have alternative outputs for those cases
* ~~Have a filter that detects differences in compressed output and makes sure the actual output and the expected output both uncompress to the same thing~~
* Have at least one automated test in CI that ensures that at least two different zlib implementations work

**Comment by jberkenbilt** [comment]
Maybe I should switch the windows builds (via external-libs) to use zlib-ng.

**Comment by zdohnal** [comment]
Hi @jberkenbilt ,

I (as Fedora QPDF maintainer) was [pinged](https://bugzilla.redhat.com/show_bug.cgi?id=2254778) by people who runs the initiative to have zlib-ng instead of zlib for [Fedora 40](https://fedoraproject.org/wiki/Changes/ZlibNGTransition) about this issue, because they tried to build qpdf with zlib-ng and got plenty of errors in test suite.

They would like to have the transition ready by the end of January 2024 (when Fedora 40 is in beta), but it can be reverted if needed (at least the change page mentions it).

Since the issue is here for some time and I don't have any experience with zlib compressions to write a feature for QPDF to support two different zlib providers, it is possible we don't meet the date zlib people would like with the new feature.

Is it possible to somehow choose which underlying tests will be run, which one to omit or run the tests which do not depend on zlib?

I was able to find out I can specify the test suites which I can run with ```-I``` or use regexps, but those options are applied only on the main test suite names (f.e. libtests, examples etc.), but not on the tests in those test suites (f.e.  ```qpdfjob 40``` in ```qpdf``` test suite).

**Comment by jberkenbilt** [comment]
I'm getting ready to do some work on qpdf. I can try to prioritize this. I can't promise end of January. It is likely that, as an interim step, I can have some kind of cmake configuration that will suppress the tests that fail with zlib-ng, and I can add something to CI for it.

**Comment by zdohnal** [comment]
No problem! I wasn't expecting any result for the end of January since there are really plenty of errors (118 if I count correctly, but it is just a piece from the huge amount of tests qpdf runs - this amount of available tests is awesome!) - it would be great if we could have an interim cmake switch which would turn off zlib related tests, but I will be happy with anything.

**Comment by jberkenbilt** [comment]
I came up with a bunch of ideas and then noticed that the ideas I came up with were basically the same ones I wrote when I created the ticket. I'm going to spend some time on this today (the timing just worked out) and see what I can come up with.

**Comment by tuliom** [comment]
@jberkenbilt I managed to create a list of the impacted tests.
After applying the following patch and removing a number of tests, I managed to get a successful execution of the tests when linking with zlib-ng:

```
diff --git a/zlib-flate/qtest/zf.test b/zlib-flate/qtest/zf.test
index d864a130..469a5fb2 100644
--- a/zlib-flate/qtest/zf.test
+++ b/zlib-flate/qtest/zf.test
@@ -11,11 +11,11 @@ foreach my $level ('', '=1', '=9')
 {
     my $f = $level;
     $f =~ s/=/-/;
-    $td->runtest("compress",
-                 {$td->COMMAND =>
-                      "zlib-flate -compress$level < 1.uncompressed"},
-                 {$td->FILE => "1.compressed$f",
-                      $td->EXIT_STATUS => 0});
+    # $td->runtest("compress",
+    #              {$td->COMMAND =>
+    #                   "zlib-flate -compress$level < 1.uncompressed"},
+    #              {$td->FILE => "1.compressed$f",
+    #                   $td->EXIT_STATUS => 0});
 
     $td->runtest("uncompress",
                  {$td->COMMAND => "zlib-flate -uncompress < 1.compressed"},
@@ -36,4 +36,4 @@ $td->runtest("corrupted input",
                   $td->EXIT_STATUS => 3},
              $td->NORMALIZE_NEWLINES);
 
-$td->report(8);
+$td->report(5);
```

I removed the following tests/files:

- examples/qtest/c-objects.test
- examples/qtest/custom-filter.test
- examples/qtest/invert-images.test
- examples/qtest/overlay-page.test
- examples/qtest/qpdf-job.test
- examples/qtest/qpdfjob-c.test
- examples/qtest/qpdfjob-remove-annotations.test
- examples/qtest/set-form-values.test
- libtests/qtest/logger.test
- libtests/qtest/lzw.test
- libtests/qtest/matrix.test
- libtests/qtest/md5.test
- libtests/qtest/nntree.test
- libtests/qtest/numrange.test
- libtests/qtest/ph.test
- libtests/qtest/pl_function.test
- libtests/qtest/predictors.test
- libtests/qtest/qintc.test
- libtests/qtest/qutil.test
- libtests/qtest/random.test
- libtests/qtest/rc4.test
- libtests/qtest/runlength.test
- libtests/qtest/sha2.test
- libtests/qtest/sparse_array.test
- qpdf/qtest/attachments.test
- qpdf/qtest/basic-parsing.test
- qpdf/qtest/c-api.test
- qpdf/qtest/coalesce-contents.test
- qpdf/qtest/compression-level.test
- qpdf/qtest/copy-annotations.test
- qpdf/qtest/custom-pipeline.test
- qpdf/qtest/dangling-refs.test
- qpdf/qtest/decode-parameters.test
- qpdf/qtest/deterministic-id.test
- qpdf/qtest/encryption-parameters.test
- qpdf/qtest/encryption.test
- qpdf/qtest/error-condition.test
- qpdf/qtest/extensions-dictionary.test
- qpdf/qtest/filter-abbreviations.test
- qpdf/qtest/form-xobject.test
- qpdf/qtest/inline-images.test
- qpdf/qtest/linearization.test
- qpdf/qtest/linearize-pass1.test
- qpdf/qtest/many-nulls.test
- qpdf/qtest/merge-and-split.test
- qpdf/qtest/newline-before-endstream.test
- qpdf/qtest/page-errors.test
- qpdf/qtest/pages-tree.test
- qpdf/qtest/parsing.test
- qpdf/qtest/preserve-unref.test
- qpdf/qtest/qpdf-json.test
- qpdf/qtest/qpdfjob.test
- qpdf/qtest/replace-input.test
- qpdf/qtest/rotate-pages.test
- qpdf/qtest/specific-file.test
- qpdf/qtest/split-pages.test
- qpdf/qtest/stream-replacements.test
- qpdf/qtest/xref-streams.test

**Comment by tuliom** [comment]
> Have a registered set of zlib implementations that are known to work, and have alternative outputs for those cases

@jberkenbilt, may I try to discourage you from doing this?

I understand there are some cases where the comparison of the compressed data will be the only solution available, but I suggest to try to avoid this as much as possible because:

1. There is already a good number of zlib implementations.
2. Results for the same library may change depending on the architecture, e.g. zlib-ng is able to use the GZIP accelerator available on newer s390x servers. The same thing could happen for x86_64 and powerpc in the future.
3. Libraries may change their implementation in order to speed up output or improve compression ratio, changing their output.

**Comment by jberkenbilt** [comment]
@tuliom Indeed -- that is no longer part of my plan.

What I'm doing is:
* Removing dependency on zlib output where it makes sense
* Creating a tool that compares two PDFs to ensure that they are identical except for zlib data for cases where it matters.

No need to create lists of tests, etc. When I'm done, all the tests will pass with multiple zlibs.

**Comment by jberkenbilt** [comment]
In case anyone's interested, my work is being pushed to #1084. At this time, I've fixed a handful of tests and have added a CI job that runs with zlib-ng. The CI job meaningfully tests to make sure that it is setting up zlib-ng and getting different output from the default (with a note about what to do if zlib-ng becomes the default in the future). My first push was to make sure that I got a CI failure. I will not keep pushing to the branch to avoid needless CI failures, but I will push again when things are in good shape.

**Comment by jberkenbilt** [comment]
After today's work, 44 tests remain, mostly for linearized files and deterministic ID. I hope to be able to knock these out tomorrow and get this landed. I'll release 11.7.0 with this and maybe one or two other changes.

**Comment by jberkenbilt** [comment]
I have completed this work. When #1084 is through CI, I will merge it, and at that point, qpdf's test suite will pass with any zlib API-compatible zlib implementation. @zdohnal -- I'd be grateful if you can test. This bug will close automatically when I merge #1084, so that can be the signal. I will plan on releasing qpdf 11.7.0 with this change (along with a few other small changes) before the end of the month, so that should be in plenty of time.

**Comment by jberkenbilt** [comment]
If anyone's curious about this, look at #1084. The last commit includes updating `README-maintainer.md` with a description of the overall approach. The PR can be reviewed commit by commit and is broken into various stages of removing dependency on specific zlib output. There was no weakening of the test suite or suppression of any test. The entire work was in removing dependency on zlib's output from the test suite.

**Comment by jberkenbilt** [comment]
I forgot to include the fixes #774 in my commit comment! Anyway, the fix is merged, so I'm closing this, but please feel free to reopen or create another ticket if the changes in main don't work for you.

**Comment by zdohnal** [comment]
@jberkenbilt I have tested qpdf-11.7.0 with the fix and testing suite now passes even without our downstream removals, thank you for all your hard work, @jberkenbilt !

**Comment by jberkenbilt** [comment]
Excellent. Thanks for the follow-up @zdohnal
