### ISSUE TITLE
Handling of UTF-8 encoded strings that begin with the sequence U+00FE U+00FF

### ISSUE THREAD

**Issue by jbarlow83** [qpdf/qpdf#778]
One of my randomized tests found the following when it created a string "þÿ". I suppose since hitting that string is 1/2^16 it took a while to pop up.

```python
In [16]: as_bytes = 'þÿ abcdefgh'.encode('utf-8')

In [17]: as_bytes
Out[17]: b'\xc3\xbe\xc3\xbf abcdefgh'  

# This is fine
In [18]: bytes(pikepdf._qpdf._new_string_utf8(as_bytes))
Out[18]: b'\xfe\xff abcdefgh'

# This is the problem
In [19]: str(pikepdf._qpdf._new_string_utf8(as_bytes))
Out[19]: '\u2061扣摥晧
```

`_new_string_utf8()` calls `QPDFObjectHandle::newUnicodeString`.
`bytes()` calls `QPDFObjectHandle::getStringValue`.
`str()` calls  `QPDFObjectHandle::getUTF8Value`.

"U+00FE U+00FF" in UTF-8 encodes to `c3 b3 c3 bf`. We pass that to newUnicodeString, and since all of our code points just happen to be PdfDocEncoding compatible, utf8_to_pdf_doc converts the string to one that begins with `fe ff`. All fine, this is the correct representation of those code points in pdfdoc.

The trouble is that when we call `getUTF8Value`, the presence of `fe ff` triggers that pdfdoc string to be interpreted as UTF-16, returning a corrupted result instead of encoding back to UTF-8. All of the code points get byte-packed, hence the Asian characters.

**Comment by jberkenbilt** [comment]
Yeah, I never thought about that case. This almost feels like it should be part of a puzzle. I guess I need to make sure the byte representation of a string created with `newUnicodeString` never starts with `fe ff` (or `ff fe` since qpdf, like many readers, recognizes UTF16-LE even though not supported in the PDF spec) unless it is stored as UTF-16. I think the same thing would happen with a string that started with `﻿﻿﻿ï»¿`. Very tricky. I'll probably just hard-code the UTF-8 representations of the sequence of _characters_ `fe ff`, `ff fe`, and `ef bb bf` and make sure to go straight to UTF-16-BE when I see those without attempting pdf doc encoding first. It will be an easy fix. In other words, go straight to UTF-16 when the string starts with any of these byte sequences:

* `c3 af c2 bb c2 bf`
* `c3 be c3 bf`
* `c3 bf c3 be`

While this clearly is a qpdf bug that can be fixed, I'm reminded of this paragraph from the PDF spec, specifically `NOTE 3`:

> For text strings encoded in UTF-16BE, the first two bytes shall be 254 followed by 255. These two bytes represent the Unicode byte order marker, ZERO WIDTH NO-BREAK SPACE (U+FEFF), indicating that the string is encoded in the UTF-16BE (big-endian) encoding scheme specified in Unicode.
> ...
> NOTE 3
> This mechanism precludes beginning a string using PDFDocEncoding with the two characters thorn ydieresis, which is unlikely to be a meaningful beginning of a word or phrase.

**Comment by jberkenbilt** [comment]
Actually, a better fix is to make sure that anything that, when transcoding to PDF doc, starts with `fe ff`, `ff fe`, or `ef bb bf` is considered invalid because those are not valid sequences at the beginning of PDF doc encoded strings.

**Comment by jberkenbilt** [comment]
I have a fix in progres -- had about 20 minutes to work on it and will finish up tomorrow. Just mentioning this in case anyone's thinking of fixing with a PR (which isn't necessary since I already have most of the fix).
