### ISSUE TITLE
11.1.0 First argument is ignored

### ISSUE THREAD

**Issue by Hakunamawatta** [qpdf/qpdf#789]
When I run the appimage through the command line, the first argument is ignored.
```
$ qpdf --version
qpdf: an input file name is required

For help:
  qpdf --help=usage       usage information
  qpdf --help=topic       help on a topic
  qpdf --help=--option    help on an option
  qpdf --help             general help and a topic list

$ qpdf a --version
qpdf version 11.1.0
Run qpdf --copyright to see copyright and license information.

$ qpdf --help
qpdf: an input file name is required

For help:
  qpdf --help=usage       usage information
  qpdf --help=topic       help on a topic
  qpdf --help=--option    help on an option
  qpdf --help             general help and a topic list

$ qpdf a --help
Run "qpdf --help=topic" for help on a topic.
Run "qpdf --help=--option" for help on an option.
Run "qpdf --help=all" to see all available help.

Topics:
  add-attachment: attach (embed) files
  advanced-control: tweak qpdf's behavior
  attachments: work with embedded files
...
```
I installed the appimage to /usr/bin/local/

**Comment by jberkenbilt** [comment]
I am able to reproduce this. If you just invoke the appimage directly, it works, but if you rename the appimage to `qpdf`, you get this behavior. I will study it, figure out why it's broken, and add a test to make sure it stays fixed. Thanks.

**Comment by jberkenbilt** [comment]
It turns out this bug has been there for as long as there has been an AppImage. I can reproduce this going all the way back to qpdf 8.0.0. It's surprising it's never been reported before.

**Comment by jberkenbilt** [comment]
@probonopd @pdfkungfoo I have looked into this just a bit and determined that, since the first qpdf AppImage release, if you put the AppImage in your path and run it normally, it works as expected, but if you rename it or symlink to it from a path whose name matches one of the embedded binaries, the first argument is ignored. I'm certain that I can identify and solve the issue, which resides in the custom `AppRun` script. If you have a minute and are still involved in this, can you take a quick check over [build-appimage](https://github.com/qpdf/qpdf/blob/v11.1.0/appimage/build-appimage#L149) and see whether it is still doing what one would do now? The current code downloads https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage, runs it for a few steps, then replaces AppRun with a custom AppRun. Before I fix bugs in the custom AppRun, which I'm sure I can do readily, I wanted to make sure there isn't a more modern way to generate the AppImage that perhaps includes an auto-generated AppRun that doesn't suffer from this bug. When I get a chance in the next few days, if I don't hear otherwise, I'll go ahead and just fix AppRun. I haven't looked at the code yet, but I have good bash skills and have no doubt it will be a simple fix, so I'm not asking you to provide a fix, just to let me know if things have changed since you contributed the original code. Thanks!

**Comment by probonopd** [comment]
> if you rename it or symlink to it from a path whose name matches one of the embedded binaries, the first argument is ignored

...and (hopefully) the binary with the name of the first argument gets executed.

It's a feature, not a bug. (At least if the implementation is not broken by mistake.) If you rename or symlink the AppImage to match the name of one of the contained binaries and invoke, then the AppImage shall execute that binary instead of the default one. This is useful for tool collections like e.g., ImageMagick for which it would be impractical to make separate AppImages for each of the many binaries. So you can make just one AppImage and symlink it under different names, each invoking a different binary inside the AppImage.

If you don't need this functionality in qpdf, then you can remove it from the AppRun file.

There are many different ways in which you can make AppImages. AppRun can be a shell script, a binary executable, or a symlink. There is not one generally recommended way. As long as AppRun will run the payload application, it's fine.

**Comment by jberkenbilt** [comment]
@probonopd Thanks. There was a bug. There was an extraneous `shift` that it was doing. The `shift` was needed when you run `appimage executable args...` but was happening even if you used the symlink. See the linked commit (7a74a491b184125d2e5d2fb6e7604cc8506ea6de) for the fix.
