### ISSUE TITLE
All vtable symbols missing with MingW64 (QPDF_DLL_CLASS must be set)

### ISSUE THREAD

**Issue by jeromerobert** [qpdf/qpdf#799]
Currently when building with mingw64 gcc `QPDF_DLL_CLASS` is set to empty. As a consequence the generated libqpdf.dll is missing all `vtable` symbols.  When building with mingw64 `QPDF_DLL_CLASS` must be set to either `__declspec(dllexport)` or ` __attribute__((visibility("default")))`.

The mingw64 support as probably been broken by https://github.com/qpdf/qpdf/commit/90cfe80bacdd0d398631afce76c4182e08cc78b9
 
Ref https://github.com/pdfarranger/pdfarranger/discussions/739#discussioncomment-3781069

**Comment by jberkenbilt** [comment]
Hmm. I'm not sure how this got past my testing. I'll have to figure out a reliable way to test this on Windows. Trying to get this part right has been a nuisance. Looking carefully at the change, I see that it would have dropped QPDF_DLL_CLASS for that. I think I lost some of that testing when I moved qpdf.cc's contents into the library in QPDFJob because the tests weren't exercising vtables passing across the shared object barrier as well. There are things in test_driver.cc for this, but I see they are only for nested classes. What I really want is something to ensure that all public methods in all classes with headers in include/qpdf as well as all `extern "C"` functions appear in the binary interface. I will have to look into that. If not, I should write some tests that at least spot check to make sure at least one vtable, at least one nested class's vtable, etc. are in the binary interface.

I will make sure this is right for 11.2.

@jeromerobert On a completely unrelated note, my next "epic" for qpdf is to revamp the code involved in manipulating pages partially to make it possible to do many more manipulations from the command line (n-up, booklet, keep all except, specify the position/orientation of overlay and underlay, probably others) and, more importantly, to properly handle document-level properties such as outlines, form fields, article threads, and links when combining pages from different files. When I'm ready to work on this, I'm going to create a discussion ticket to discuss the API. If you're interested, I'll tag you on the ticket as your input would be valuable -- I imagine you have use cases that I may not have thought of. James Barlow will definitely be tagged on the discussion since I know he has already built some abstractions into pikepdf that are at a higher level than what's directly offered by qpdf. I will also tag some other active contributors or discussion participants. Are you interested in being in the discussion?

**Comment by jberkenbilt** [comment]
I don't really understand how mingw works here. There are already tests for vtable and typeinfo, and if I disable QPDF_DLL_CLASS, I get lots more failures. I think there is something weird about QPDFNameTreeObjectHelper and mingw. See #745 and #536. I am unfortunately not able to reproduce this, but I'm trying harder to force the vtable to appear for mingw and to come up with a test case that fails if it's not there. In any case, it seems harmless to define QPDF_DLL_CLASS for mingw even though it seems like it shouldn't actually be needed based on the other tests. I'm going to do some experiments to see if I can make this reproducible, but if not, I will put it back without understanding why and leave a comment that points to this and the other two issues.

**Comment by jberkenbilt** [comment]
That said, it does seem that the vtable symbols are missing from the DLL, so my previous comment is probably wrong.

**Comment by jeromerobert** [comment]
> I'm going to create a discussion ticket to discuss the API. If you're interested, I'll tag you on the ticket as your input would be valuable.

I'm not sure to have any valuable input but I would be happy to at least follow your discussions with James Barlow. Thank you !
