### ISSUE TITLE
Unable to execute Symbolic Link of qpdf on Windows

### ISSUE THREAD

**Issue by KaranKad** [qpdf/qpdf#805]
### Steps to reproduce

1. Download https://github.com/qpdf/qpdf/releases/download/v11.1.1/qpdf-11.1.1-msvc64.zip
2. Add `C:\SymbolicLinkPath\` folder to path.
3. Create Symbolic Link by running following command inside PowerShell Admin
```
New-Item -ItemType SymbolicLink -Path C:\SymbolicLinkPath\qpdf.exe -Target C:\Downloads\qpdf-11.1.1-msvc64\bin\qpdf.exe
```
4. Execute qpdf from command line.
5. Get no output.

**Comment by jberkenbilt** [comment]
I'm not a Windows expert, but I suspect this is because qpdf loads the qpdf DLL which must be in the path. I'm betting that if you symlink the DLLs included in the bin directory as well or add them to the path, it would work. This would be the case with any executable that needs DLLs included in its distribution, not just qpdf.

**Comment by KaranKad** [comment]
Thanks for this info, I'll close this issue.
