### ISSUE TITLE
Get the file name of the output from that of the input

### ISSUE THREAD

**Issue by DesBw** [qpdf/qpdf#813]
Is it possible to pass the name of the input file to the output file using some kind of variable?

I am splitting pdf files using qpdf. I don't want to assign new names for the output. I rather want the output file to be the name of the input with the usual suffixes: 

`qpdf --split-pages=50  MyInputFile.pdf  @F\ %d.pdf`

I want to get this file name pattern like this: **MyInputFile  001-050.pdf**. The @F variable calls the name of the input. 

Is this possible?

**Comment by jberkenbilt** [comment]
That's not there right now. I suppose it could be a possible enhancement, but I also feel like it wouldn't be that hard to have whatever invokes qpdf take care of that detail. Anyway, I'll mark it as an enhancement. I'd probably use `%f` rather than `@f` since `@` starts an argument filename and there's no reason to use two different meta-characters.

**Comment by Dellu** [comment]
That will be a great enhancement. Yes, %f makes more sense. Thank you.

**Comment by jberkenbilt** [comment]
I've decided not to do this -- qpdf's CLI parsing is already quite complex. I think it's better to just handle this with the shell or whatever invokes qpdf.
