### ISSUE TITLE
page is blank after proccessed pdf file with flatten-annotation

### ISSUE THREAD

**Issue by maisen20** [qpdf/qpdf#827]
Hello together,

unfortunately i have a problem when flattening a pdf file. The last page just appears blank. I have tried a few things but I can't get the complete PDF file to be output correctly.

Unfortunately, I can't publish the PDF file here for everybody, because it contains sensitive information, which should not be easily accessible to the public. But if someone can help me with the troubleshooting, I can send the PDF file.

The problem occurs with the last page, which contains various text fields (annotations), images and lines.

I have already tried the following:
`qpdf --flatten-annotations=all input.pdf output.pdf`
`qpdf --flatten-annotations=all --preserve-unreferenced input.pdf output.pdf`
`qpdf --flatten-annotations=all --generate-appearances input.pdf output.pdf`
`qpdf --check input.pdf (no issues found)`

> PDF Version: 1.7
> File is not encrypted
> File is not linearized
> No syntax or stream encoding errors found; the file may still contain
> errors that qpdf cannot detect

Some infos:
- qpdf version 11.2.0

- pdf was created with Bluebeam PDF Library 19
- content was created with Bluebeam Revu x64
- pdf version 1.7

If someone could help me I would be very grateful.

**Comment by jberkenbilt** [comment]
If you send me the file by private email, I can attempt to diagnose it and delete the file when I'm done. My email is ejb@ql.org. I may not get to it immediately, but I will get to it.

**Comment by maisen20** [comment]
> If you send me the file by private email, I can attempt to diagnose it and delete the file when I'm done. My email is [ejb@ql.org](mailto:ejb@ql.org). I may not get to it immediately, but I will get to it.

Thank you very much, I have sent you an email.

**Comment by jberkenbilt** [comment]
Received -- I'll let you know when I can get to it. Thanks for sharing the file. I will delete it when I'm done. I do this often. It's a huge help to be able to diagnose problems with actual files that qpdf doesn't handle well.

**Comment by maisen20** [comment]
Good day

I hope you started well into the new year and would like to ask if you already had time to look at the problem with my PDF?

Kind regards
Marcel
Am 28. Nov. 2022, 14:39 +0100 schrieb Jay Berkenbilt ***@***.***>:

**Comment by jberkenbilt** [comment]
So sorry -- things got crazy and it slipped my mind. I am looking at it now. Thanks for the nudge!

**Comment by jberkenbilt** [comment]
I figured it out, and it's going to be a small fix. I will make a fix and I will also post here how you can repair the file in the meantime with `qpdf --json`.

**Comment by jberkenbilt** [comment]
1. Find the object number for page 4: `qpdf --json --json-key=pages FLATTEN_TEST.pdf | jq -r '.pages[]|select(.pageposfrom1 == 4)|.object'`
2. In this case, it was `102 0 R`. Export as json just that object: `qpdf --json-output --json-object=102 FLATTEN_TEST.pdf /tmp/a.json`
3. Add an empty resources dictionary to the page: `jq '.qpdf[1]."obj:102 0 R".value."/Resources" = {}' < /tmp/a.json >| /tmp/b.json`
4. Update the original file with the fix: `qpdf --update-from-json=/tmp/b.json FLATTEN_TEST.pdf fixed.pdf`

Now you can use `--flatten-annotations` on fixed.pdf without losing the last page.

The fix was actually a one-liner. The pull request includes a hand-generated PDF that fails in exactly the same way as your test file, which I can now delete. Thanks. This will be in whatever release is next, probably 11.3.0.

**Comment by jberkenbilt** [comment]
Interestingly, the line of code that was wrong has a comment over it: `This should never happen and is not exercised in the test suite`. The comment was actually wrong though -- it is legal for a page to not have a `/Resources` dictionary. I guess the version my brain at the time of writing that comment didn't know that. I wonder when it got fixed.

**Comment by maisen20** [comment]
Thank you very much for your help and this will be fixed in future versions. Very much appreciated.
