### ISSUE TITLE
How to remove security restrictions from PDF

### ISSUE THREAD

**Issue by fury182** [qpdf/qpdf#833]
I have a PDF file that I cannot compare to another PDF in Adobe Acrobat because it says the document has security settings which prevent comparison. I think this has to do with the properties in the image below:

![pdf_security_restrictions](https://user-images.githubusercontent.com/91354347/205511808-a29c371a-99e9-4fce-af40-b5576089c201.png)

I ran qpdf like: qpdf --decrypt input.pdf output.pdf

But the security settings which prevent comparison are still there.

I saw qpdf has options like --annotate , --modify which I was thinking would target the properties in the screenshot but these are only for --encrypt, not for --decrypt.

So do you know if there's a way to run qpdf that would enable me to compare this PDF to another?

Thanks

**Comment by jberkenbilt** [comment]
I can't think of an explanation other than operator error. Are you looking at output.pdf rather than input.pdf? There is no way that, in the command you gave, output.pdf would still have security restrictions. `qpdf --decrypt` definitely removes all restrictions.

**Comment by fury182** [comment]
@jberkenbilt I double checked and comparison doesn't work for the output.pdf. I also tried editing (I don't need this, was just testing, I only need comparison) and it says "This document has been signed and can not be edited.". Maybe it has something to do with "signing"? Is there a command for removing this?

Thanks

**Comment by jberkenbilt** [comment]
Yes, it's possible it could have to do with signing. qpdf still doesn't support digital signature. I think I need to make that a priority.

**Comment by jberkenbilt** [comment]
I'm not sure how regular encryption interacts with digital signature. I will have to read that section of the spec. If it is an issue around signing, it may not be that easy to fix. Is there any way you could send me the file? If the file is okay to share with me individually but not okay to post, I can give you my email and you can send it. If not, that's okay...I can try other ways to reproduce it. I have a commercial Adobe Acrobat license at work.

**Comment by fury182** [comment]
@jberkenbilt Thanks for looking into this. Unfortunately I can't share it, but you should be able to reproduce. It has been signed with Adobe Sign. At the top of the original file there's this:

![adobe_sign_signature](https://user-images.githubusercontent.com/91354347/205518067-3afd80e8-dd50-4751-a4c3-d00784976d35.png)

Thanks

**Comment by jberkenbilt** [comment]
Okay, I will look at it "soon" but not imminently. It may be a few weeks before I have a chunk of time to study this.

**Comment by fury182** [comment]
@jberkenbilt I'm hesitant to follow the procedure as the file is sensitive and wouldn't want to leak info.

But I managed to reproduce it from scratch with a test file with my Acrobat Pro subscription (you said you had one).

Just create a new test PDF and go to Adobe Acrobat Sign (included with Acrobat Pro) and request signatures from yourself and another email address belonging to yourself. Then make sure it's signed by both. Then take the file ending with "- signed.pdf" and try to remove restrictions from it. It will not work, and in Acrobat, the resultant file will show at the top "Certification by  is invalid"

Thanks

**Comment by jberkenbilt** [comment]
This bash script will do the trick.
```
#!/bin/bash
infile="$1"
outfile="$2"
if [ "$outfile" = "" ]; then
    echo 1>&2 "Usage: $0 infile outfile"
    exit 2
fi
root="$(qpdf --json --json-key=qpdf --json-object=trailer "$infile" | jq -r '.qpdf[1].trailer.value."/Root"')"
perms="$(qpdf --json --json-key=qpdf --json-object="$root" "$infile" | jq -r '.qpdf[1]."obj:'"$root"'".value."/Perms"')"
qpdf --json --json-key=qpdf --json-object="$perms" "$infile" | jq '.qpdf[1]."obj:'"$perms"'".value = null' > /tmp/new-perms.json
qpdf --decrypt "$infile" "$outfile" --update-from-json=/tmp/new-perms.json
```

What's going on here is that there is a `/Perms` dictionary in the document catalog that needs to be removed. Using qpdf json v2 (introduced in 11.0.0), it is possible to do this from the command-line, but I can add something like `--remove-permissions` for what will most likely end up being 11.3.0. In the meantime, the above will work. What this does:
* Find the document catalog by looking up the `/Root` key in the trailer
* Find the permissions dictionary by looking up `/Perms` in the catalog
* Replace `/Perms` with a null object, which is the same as removing it; save the resulting json to a file
* Decrypt the input and also remove the permissions object.

Of course Adobe's tools no longer report the document as secured or show a signature panel, even though the contents show the history, and the restrictions are no longer present on the file.

I was not aware of (or had forgotten about) the `/Perms` entry in the document catalog, though it has been there since PDF 1.5. (When I originally wrote the first version of qpdf, the latest version of the standard was 1.3, but 1.5 had been released long before the first open source release. I just overlooked or forgot about it since then.)

I'll have to study this file more closely. At an initial glance, I can see two things that differ from my original assumptions:
* Although the document appears to have a digital signature, it lacks a `/DSS` key in the document catalog. I will have to study the spec more closely.
* The mechanisms used here are not deprecated. This is a different mechanism from what I had guessed by skimming over the spec.

Anyway, let me know if the above script works for you.

**Comment by jberkenbilt** [comment]
I should have said to run the above with the input and output file as two arguments, e.g.
* save the above as /tmp/remove-perms and make it executable
* /tmp/remove-perms infile.pdf outfile.pdf

This assumes Linux or Mac, and you have to have jq. Windows will be a little different. If necessary, I could either provide a C++ or Python program that does this or describe how to do it manually with a text editor.

**Comment by fury182** [comment]
I tried the script (on Linux). Now the document says allowed for all restrictions, and no longer has the "Certification by is invalid" at the top. However, I still can't compare or edit the document, with the same error message: "This document has been signed and can not be edited." and "These documents have security settings which prevent comparison. Please modify the security settings to allow editing and try again.".

Did this work for you with a document you signed for yourself? I'm using Adobe Acrobat Pro 2022.003.20282 in a virtual machine.

Thanks

**Comment by jberkenbilt** [comment]
I didn't specifically try those things. There may be more keys I need to drop. Can you give me an exact formula for seeing the problem? I do not know my way around Acrobat.

**Comment by fury182** [comment]
@jberkenbilt I'm not an expert in Acrobat Pro either (I just purchased it 2 weeks ago). But in my version (which should be the latest), I just click on "Edit" and get "This document has been signed and can not be edited." Additionally, I get the message again if I insist and click on "Add Content" > "Text" (under Edit).

Thanks

**Comment by jberkenbilt** [comment]
My guess is that I will be able to figure out which key to remove to just remove the signature entirely by reproducing it with the samples I made before. When I have a chance to do that, I will update the script.

**Comment by rubyFeedback** [comment]
The discussion above is interesting also for other users. :)

**Comment by fury182** [comment]
@jberkenbilt Yes, this seems to remove all restrictions allowing compare & edit. Many thanks!

**Comment by jberkenbilt** [comment]
Great! I'll leave this open as a reminder to consider adding an option to the CLI to do what my script does.

**Comment by jberkenbilt** [comment]
The `--remove-restrictions` flag and the API `QPDF::removeSecurityRestrictions` will be in 11.3.
