### ISSUE TITLE
Question - is there any way to add user specified text to each page of a pdf?

### ISSUE THREAD

**Issue by uat230214** [qpdf/qpdf#906]
Hi,
I tried to understand the manual and searched through the issues pages, but I have been unable to identify if the asked thing is possible or not.

I am not interested in overlay or underlay. I would like a similar effect but with just an snippet of text.

It is a kind of annotation or sometimes also called stamping and/or watermarking. What I saw is that QPDF is able to do that but with input pdfs, not found with just text. Do not know precise name for what I look for....

The main purpose is to add my name in a specified position in each page of the pdf. I know how to do that with imagemagick convert but all is converted to image... There are also online and gui based tools, and paid command line, but have not find a free command line...

If it is not possible with QPDF, any hint about  free command line tool for windows is mostly welcomed!

Thanks!

**Comment by jberkenbilt** [comment]
There isn't a way to do this directly with qpdf, but I have a Python script (using pikepdf) that I wrote a long time ago that does this and which I use routinely for my own personal use. I have never tested it on Windows, but I imagine it would work fine. The code is inlined here and attached as [pdf-add-text.txt](https://github.com/qpdf/qpdf/files/10778381/pdf-add-text.txt). You'll probably want to save it as `pdf-add-text.py` and run it with a suitable Python environment.

This is just something I wrote for my own use. It's not very flexible. In particular:
* You have to specify x and y coordinates in PDF points, which are 1/72 of an inch with 0, 0 as the lower-left corner.
* It hard-codes `/Fpat` as the font resource. This is probably not going to clash with anything, but a more robust solution would generate a unique font identifier.
* It just uses Helvetica, one of the built-in fonts. This is hard-coded.

Example: to add the word `quack` (why not?) to the text in a 24-point font 1 inch from the left and 2 inches from the bottom of the page:

```
python3 pdf-add-text.py --src /home/ejb/source/examples/pdf/minimal-updated.pdf --dest /tmp/1.pdf --text quack --size 24 --page 1 --x 72 --y 144
```

I don't know whether this will help you or not. It wouldn't be very hard to create something using this as a starting point if anyone wanted to do it.

Here's the code.

```python
#!/usr/bin/env python3
import os
import sys
import argparse
import pikepdf

whoami = os.path.basename(sys.argv[0])


def parse_args(args=sys.argv[1:], prog=whoami):
    parser = argparse.ArgumentParser(
        prog=prog,
        description='Add a text string to a PDF file',
    )
    parser.add_argument('--src',
                        help='final PDF file',
                        required=True)
    parser.add_argument('--dest',
                        help='final PDF file',
                        required=True)
    parser.add_argument('--text',
                        help='text to place',
                        action='append',
                        required=True)
    parser.add_argument('--size',
                        action='append',
                        help='font size')
    parser.add_argument('--page',
                        help='page to insert signature into, numbered from 1',
                        type=int,
                        required=True)
    parser.add_argument('--x',
                        help='x coordinate in points',
                        type=int, action='append',
                        required=True)
    parser.add_argument('--y',
                        help='y coordinate in points',
                        type=int, action='append',
                        required=True)
    return parser.parse_args(args)


options = parse_args()
if (not ((len(options.text) == len(options.x)) and
         (len(options.text) == len(options.y)) and
         (len(options.text) == len(options.size)))):
    exit('text, x, y, and size must be specified the same number of times')

pdf = pikepdf.Pdf.open(options.src)
page = pdf.pages[options.page - 1]
if '/Resources' not in page:
    page['/Resources'] = pikepdf.Dictionary()
if '/ProcSet' not in page['/Resources']:
    page['/Resources']['/ProcSet'] = pikepdf.Array()
procset = [x for x in page['/Resources']['/ProcSet']]
if pikepdf.Name('/Text') not in procset:
    page['/Resources']['/ProcSet'] = pikepdf.Array(
        [*procset, pikepdf.Name('/Text')])
if '/Font' not in page['/Resources']:
    page['/Resources']['/Font'] = pikepdf.Dictionary()
if '/Fpat' not in page['/Resources']['/Font']:
    font = pdf.make_indirect(pikepdf.Dictionary(
        Type=pikepdf.Name('/Font'),
        Subtype=pikepdf.Name('/Type1'),
        Name=pikepdf.Name('/Fpat'),
        BaseFont=pikepdf.Name('/Helvetica'),
        Encoding=pikepdf.Name('/WinAnsiEncoding')
    ))
    page['/Resources']['/Font']['/Fpat'] = font
content = 'Q\nq\n'
for i in range(0, len(options.text)):
    content += f'''BT
  /Fpat {options.size[i]} Tf
  {options.x[i]} {options.y[i]} Td
  ({options.text[i]}) Tj
ET
'''
    content += 'Q'
page.contents_add(pikepdf.Stream(pdf, 'q\n'.encode()), prepend=True)
page.contents_add(pikepdf.Stream(pdf, content.encode()), prepend=False)
pdf.save(options.dest, compress_streams=False)
```

**Comment by uat230214** [comment]
@jberkenbilt 
Thanks for your kind help and moreover for qpdf.
It was some years ago I played with python and my current knowledge level went down to windows CMD...
Finally I had to treason you and got some functionality similar to my needs with jpdftweak.
It is able to "impress" a diagonal watermark (no more positioning options) with a given lettersize, color and transparency with user input text. Surprisingly it is very powerful in the sense that it is able to use the empty spaces for the watermark while being "stamped" on top but traslucent - and as I chose gray color, black letters do not get damaged.
In this sense, it makes my perfect fit, as underlay was not what I needed and full overlay would not be either... Yes, I would love to control where it is placed and the orientation...
Although the author asnwered some questions last year, code in sourceforge is almost ten years old... I am tempted to politely ask for an enhancement (position, slant) but ...

Thanks again for the help and all the fish!

**Comment by rubyFeedback** [comment]
Interesting. I just found pikepdf today, when I was looking for a GUI actually, to rotate a .pdf file.
(We can use the commandline qpdf variant just fine, but I needed a value less than 90° and was
not sure which one to use, so I thought a GUI may be useful, and then I found a python-gtk 
script that depended on pikepdf.)

**Comment by jberkenbilt** [comment]
> We can use the commandline qpdf variant just fine, but I needed a value less than 90° and was
> not sure which one to use...

Rotation by multiples of 90 degrees can be done using the `/Rotate` key in the page dictionary. Other forms of rotation are more complex to implement and would require modifying the content streams and calculating adjusted bounding boxes. That most likely explains why so many more tools support 90-degree rotation.



> IMO sourceforge is semi-dead. There is still new code published, but compared to github it is very
> inactive, and also less usable.

Yeah, sourceforge has not improved very much in the past 20 years that I've been using it. Its trackers are almost impossible to use, and their bug reporting and email system are beyond awful. I still publish binary releases there and still get a few thousand downloads a week, so I know it's active, but all my real activity is on github, and I know a lot of other people do that as well. I have occasionally gotten messages from users on sourceforge that I haven't been able to answer because of issues with sourceforge's email system. But I probably get less than one message on sourceforge a year whereas there is lots of activity on the github issue tracker.

**Comment by uat230214** [comment]
Some feedback just in case someone hits this thread in the future.
I contacted jpdftweak author, and the code is just frozen. I believe he would be happy if someone would take over his code. But probable there are more modern codes filling the space.

On another note, I found the solution to be another "competing" initiative (competing in the sense of supporting CMD pdf manipulation, in a general sense).

pdfcpu is able to text stamp (or overlay) with a fine grained control of position, rotation, type, etc. Only issue is the easeness or not of stamping non-english characters, I am still trying to understand how this can be carried out, as it is probably my lack of knowledge than a sw limitiation, being probably related to CMD usage.

**Comment by jberkenbilt** [comment]
@uat230214 Regarding non-English characters, the problem here is that PDF doesn't have native direct support for non-English characters, hard as this is to believe. This is an artifact of PDF being a relatively old file format. In any case, when you put English (ASCII) characters in a PDF file, you can just create a text string that actually matches the string you want to display, but if you want non-ASCII characters outside a narrow range of special characters that are part of the PDF Doc Encoding character set, you have to embed a font and create your own mapping between arbitrary character code points and font glyphs, and then if you want the text to be possible to extract, you need to also create a mapping. It's not terribly difficult, but it's much less straightforward than just embedding ASCII text. Typically one also embeds only a subset of the font containing only the glyphs that you actually need. When PDF was new, fonts containing a wide range of Unicode characters were rare if they existed at all, so you had to find fonts that contained whichever characters you wanted and switch fonts depending on what characters you needed. These days there are decent Unicode fonts that contain characters from across a wide range of languages, so the task is easier, but still not simple.

I have some code I wrote for work that knows how to overlay text of a specific font given the font metrics, but it is not intelligent about font subsetting (which would require additional external dependencies) or custom character mappings. Maybe someday I will add some support to qpdf for this. By the way, one runs into the same problem with non-ASCII text in form fields. With ASCII text, the PDF file can provide rendering instructions so the reader with form capabilities and render the filled-in form, but with non-ASCII characters, the rendering software has to do the whole font subsetting/character mapping thing.

One of the projects on my "someday maybe" list is to create a tool like this that uses qpdf and the freetype library. If anyone reading this wants to take it on, I'm happy to provide assistance on the PDF side of it and share the code I have sitting around that creates a little bit of an abstraction around font metrics. It's not much, but it would be a good starting point for something like the above that works with arbitrary Unicode data.

**Comment by uat230214** [comment]
Thanks for the insights. 
Astonishment stoned me... 
Ay least now I know that I Will not bé able to do It currently

**Comment by GitHubRulesOK** [comment]
For a "Dirty" windows methood see (https://github.com/qpdf/qpdf/issues/830)
