### ISSUE TITLE
[FATAL VULNERABILITY] Remove PDF file's password with one click

### ISSUE THREAD

**Issue by rainbowsource** [qpdf/qpdf#912]
Use this program to remove all PDF encryption with one click, regardless of whether it is AES-256 or other encryption algorithms. Download it here: http://app.pdfdo.com/software/PDFdo_Password_Remover_setup.zip. This makes all encryption seem pointless, even funny. If the problem is not solved, I think it is better to remove the PDF encryption function directly. Anyway, it can be cracked by others at any time with a click of the mouse.

**Comment by rainbowsource** [comment]
My test command is:
`qpdf test.pdf --encrypt "" "p87pK7!p#J3rh8AV8p24jNT&!athv6#VC$k$tSMQLX&BuZ3dc7RWt!CEw4BwHyR4" 256 --accessibility=n --annotate=n --assemble=n --extract=n --form=n --modify-other=n --modify=none --print=none -- test_Encrypted.pdf`

**Comment by jberkenbilt** [comment]
You used an empty user password.  A simple qpdf --decrypt would have succeeded. No cracking was required.

**Comment by jberkenbilt** [comment]
For clarification on how encryption works with PDF, see https://qpdf.readthedocs.io/en/stable/encryption.html
I suspect if you used an equally strong password for both user and owner, the password remover would not succeed in removing the password.

**Comment by rainbowsource** [comment]
So you're saying that encrypting a PDF's edit permissions is pointless without adding the PDF's user's open password?

**Comment by rainbowsource** [comment]
Oh, after reading the documentation you provided, I see. Even if the user password is "123456", it will not be cracked. However, if the user password does not exist, it is meaningless to unilaterally encrypt the editing authority of the PDF.

Test command:
`qpdf test.pdf --encrypt **"123456"** "p87pK7!p#J3rh8AV8p24jNT&!athv6#VC$k$tSMQLX&BuZ3dc7RWt!CEw4BwHyR4" 256 --accessibility=n --annotate=n --assemble=n --extract=n --form=n --modify-other=n --modify=none --print=none -- test_Encrypted.pdf`

**Comment by jberkenbilt** [comment]
@rainbowsource You have correctly understood. PDF encryption is only enforced against people who use proprietary PDF readers. :-) However that is still most people. However, digital signature is stronger in that, while tools like qpdf can definitely still override the restrictions, a consumer can tell that the restrictions have been overridden, so a recipient can verify that the file is not the author's original. Ultimately there is no even theoretical way to create an unbreakable edit restriction using a file format that is self-contained and readable on the desktop, though sometimes files lack enough metadata to edit them easily. I'm going to change the title of the issue so that people scanning issue titles don't get confused about whether qpdf has a vulnerability.

**Comment by rainbowsource** [comment]
@jberkenbilt But sir, I still have a problem. I will not set the PDF user password too complicated, because I always provide this password to the reader. But I found that no matter how complicated my management password is set, as long as there is a user password, you can just erase all the PDF encryption. Is this inevitable?

**Comment by rainbowsource** [comment]
Even if the user password is very complicated, as long as I provide it to the user, he can easily pass the user password to erase all encryption.

**Comment by jberkenbilt** [comment]
@rainbowsource Yes, that is the reality of PDF encryption.

**Comment by rainbowsource** [comment]
@jberkenbilt Thanks Reply. This reminds me of an old saying in China: 防君子不防小人。This sentence means, Guard against the gentleman but not the villain. :)

**Comment by jberkenbilt** [comment]
I like that. One thing I have often said is, "Thing you are worried about is not what will ultimately get you." Seems similar in spirit.
