### ISSUE TITLE
Add support for --optimize-images to optimize images nested in groups

### ISSUE THREAD

**Issue by cdosborn** [qpdf/qpdf#923]
I'd like to fix this issue, but could benefit from a "Use this approach.." as I'm new to c++ and the code base.

1. optimize is not optimizing all images, it doesn't recurse into the document https://github.com/qpdf/qpdf/issues/909#issuecomment-1461198532
2. It's easy to make it recurse, but that breaks the replacement logic.

If you just make it recurse, it finds the images, but then always inserts them at the top level of the page, rather than in the resources dict where they were found. 

Here is a [test pdf](https://github.com/qpdf/qpdf/files/10952121/test.pdf)
 that when passed through `--optimize-images` does not compress the sole image.

I could use some help with a suggested approach to change this. I'm also okay if someone else wants to fix this.

**Comment by jberkenbilt** [comment]
Looking more closely, I don't think there's anything to fix. The comments in `QPDFPageObjectHelper` for `getImages` explicitly states that it doesn't recurse into form XObjects and to use `forEachImage` instead. I'm going to close this for now and make comments in #909

**Comment by jberkenbilt** [comment]
I read the original message too fast. I see you were using pikepdf for illustrative purposes.

**Comment by jberkenbilt** [comment]
The key will be to use `forEachImage` instead of `getImages` in `QPDFJob::handleTransformations`. I think it will not be a complicated fix, but the code is pretty involved and easy to break, and we have to be careful about compatibility. If you'd like to take a crack at it, I'm happy to review. More likely than not, it would take me about the same amount of time to implement a fix as it would to figure out the fix enough to guide someone else through it. If you're really interested in contributing to qpdf and have the time to play around with it, please feel free. Otherwise, I can commit to fixing this for whatever the next release is as I believe it will not take me very long to fix it.

**Comment by jberkenbilt** [comment]
Looking at change history, it seems that, when I added `forEachImages`, I just forgot to update `--optimize-images`. What I will need to do is fix that and also check to see whether there are other `getImages` calls within the library.

**Comment by jberkenbilt** [comment]
Another possible fix would be to modify getImages to take an optional argument that tells it whether to recurse into form xobjects. I'd have to check more closely to see what the implications would be. Note that adding a literal optional argument would be ABI breaking so, for the time being, it would have to be an overloaded function with an ABI comment marker which I would resolve for qpdf 12.
