### ISSUE TITLE
Add option for renumbering PDFs

### ISSUE THREAD

**Issue by 5dma** [qpdf/qpdf#939]
Not all PDF generators are smart enough to have the source document’s page number match the PDF page number. For example, a source document may have an introduction with page numbers set in lower-case roman, and body text with page numbers set in Arabic. The resulting PDF's pages are all set in Arabic, giving the reader a confusing presentation.

For a description of the use case, see [Renumber pages in a PDF](https://helpx.adobe.com/in/acrobat/using/manipulating-deleting-renumbering-pdf-pages.html#renumber_pages).

Request is to provide command-line options that renumber the pages in a PDF. One implementation may be

`qpdf infile.pdf --renumber --pages 1-10:a 11-15:i 16-75:1 -- outfile.pdf`

`infile.pdf` - existing PDF file
`--renumber` -- operation is to renumber the existing PDF. This option indicates that the character after a page range indicates a type of numbering.
`--pages` -- Introduces page ranges
`1-10:a` -- The first 10 pages of the PDF are numbered in lower-case alpha, starting at `a`.
`11-15:i` -- The next five pages are numbered lower-case roman, starting at `i`.
`16-75:1` -- The remaining pages are numbered in Arabic, staring at `1`.

Need to support these numbering types:

- None
- Standard (1, 2, 3)
- Lower Case Roman Numerals (iii, iv, v, vi)
- Upper Case Roman Numerals (III, IV, V, VI)
- Lower Case AlphaNumerics (a, b, c)
- Upper Case AlphaNumerics (A, B, C)

Future requirement: Add a prefix to each page number.

Thank you!

**Comment by jberkenbilt** [comment]
I think this could fit into the significant page processing work I have planned for the next few months.

**Comment by rubyFeedback** [comment]
That may indeed be useful - kind of fitting into qpdf "post-processing" (if we can even use this term).

Some .pdf files seem to use peculiar ordering. I don't know the pdf specification, but I think sometimes the early pages, but especially the appendix-pages at the end can be displayed in pdf viewers different to other pages. Not sure if my memory fails me here but I think that was the case. My primary job is to get qpdf to chop things away, so I may miss everything else. :P

**Comment by ed0d2b2ce19451f2** [comment]
See also issue #348.

I've found myself wishing the CLI tool had this feature a few times now.  I offer the following proposal for consideration.

## Draft documentation of proposed interface
qpdf allows you to use the `--set-page-labels` option to specify the page labels of the output file.  Page labels are specified by dividing the document into one or more labeling ranges (sequences of consecutive pages) and specifying the labeling scheme for each.

Usage: <code>qpdf <em>in.pdf</em> --set-page-labels <em>labeling-range</em> [...] -- <em>out.pdf</em></code>

<code><em>labeling-range</em></code> must appear one or more times between `--set-page-labels` and the `--` that terminates the option.  Each <code><em>labeling-range</em></code> specifies the page labels for a labeling range starting with the specified page and continuing until the next labeling range or the end of the document, and is a string of the following form:

<code><em>first-page</em>/[<em>numbering-style</em>[:<em>starting-value</em>]][/<em>prefix</em>]</code>

where:
- <code><em>first-page</em></code> indicates the first page of the labeling range, and must be one of the following:
  - a decimal integer indicating the 1-based index forward from the first page (`1` for the first page, `2` for the second page, etc.)
  - a decimal integer preceded by `r` indicating the 1-based index backward from the last page (`r1` for the last page, `r2` for the second-to-last page, etc.)
  - `z` indicating the last page
- `/` is a literal separator character
- <code><em>numbering-style</em></code> indicates the numbering style, and must be one of the following:
  - `D` indicates decimal Arabic numerals
  - `R` indicates uppercase Roman numerals
  - `r` indicates lowercase Roman numerals
  - `A` indicates uppercase letters (A to Z for the first 26 pages, AA to ZZ for the next 26, etc.)
  - `a` indicates lowercase letters
- `:` is a literal separator character
- <code><em>starting-value</em></code> is a positive decimal integer indicating the starting value of the numbering.  If not specified, a value of 1 is assumed.
- `/` is a literal separator character
- <code><em>prefix</em></code> is a string (possibly empty) indicating the label prefix.

A <code><em>labeling-range</em></code> starting with the first page is required.  If more than one <code><em>labeling-range</em></code> starting with a particular page is provided, only the last is used.

Example invocation:
`qpdf input_file_with_11_pages.pdf --set-page-labels "1//front cover" z//index/glossary 2/a:2 4/D:4 r3/D/X- -- output_file.pdf`

Resulting page labels:
`front cover`, `b`, `c`, `4`, `5`, `6`, `7`, `8`, `X-1`, `X-2`, `index/glossary`

See also `--remove-page-labels`.

## Notes
This scheme is intended to provide full coverage of the page labels feature as described by section 12.4.2 of ISO 32000-1:2008 or ISO 32000-2:2020.

This scheme allows distinction between absence of prefix and empty string prefix.  This seems potentially useful, for testing if nothing else, but I'm not sure if there are any significant downsides.  If allowing an empty string prefix is undesired, <code><em>labeling-range</em></code> could instead be of the form <code><em>first-page</em>/[<em>numbering-style</em>[:<em>starting-value</em>]]/<em>prefix</em></code> with empty <code><em>prefix</em></code> meaning absence of prefix.

`/` was chosen as separator because it isn't used in the page-range syntax.  A future desire for a related option where that is relevant seems conceivable.

**Comment by jberkenbilt** [comment]
@ed0d2b2ce19451f2 At a glance, this looks great. When I have a chance, I will study it in more depth and include something like this.

I'm also trying to work out the meaning of your github username. Neither interpreting it as a UTF-8 or UTF-16 (LE or BE) string hex encoded nor simply converting to decimal revealed anything obvious. Unless it's just a way to be anonymous, which is fine. :-)

**Comment by jberkenbilt** [comment]
I've worked through my pages epic plans enough to realize that there are no blockers to implementing this, and with such a well-thought-out proposal, I see no reason to delay. If I have some time, I will try to knock this out for 11.7.1 (or 11.8.0). As always, no guarantees. :-)

**Comment by jberkenbilt** [comment]
This issue is part of the qpdf pages epic. If you are interested in following, please see #1104.

**Comment by jberkenbilt** [comment]
This will definitely be in 11.8.0. I'm at the tail end of finishing it up....just working on writing tests and release notes.

**Comment by jberkenbilt** [comment]
@ed0d2b2ce19451f2 Thanks -- I'll take a look.  These look straightforward enough. When I'm the right mindspace, I'll read carefully and either agree or say why I disagree with each suggestion.

**Comment by jberkenbilt** [comment]
I've fixed the bug and updated the documentation. Thanks for taking the time to report those. I've considered the wish-list items and have decided not to implement them. While I recognize the value of this for the purpose of generating test files, I think it's probably mostly undesirable for the cases you mentioned to behave differently from each other, and generation of test files can be enhanced by directly manipulating the `/PageLabels` dictionary after running `--set-page-labels`. There are other things it also doesn't do, like generate number trees that are more than one level deep. Also, it's not simple to implement as I'd have to enhance the implementation to keep track of whether a value was omitted or empty, and that would require rewriting the parsing code which currently uses a regular expression and a data structure with default values. If I thought it were a high-value feature, I'd do it, but I think it's usually not what people will want.

For generating from the CLI, my suggestion would be to use `--set-page-labels` and then use qpdf JSON to mutate and rewrite the page labels. Example:

```bash
qpdf --set-page-labels 1:D 5:D 9:D -- 20-pages.pdf /tmp/out.pdf
root=$(qpdf --json --json-key=qpdf --json-object=trailer /tmp/out.pdf | jq -r '.qpdf[1].trailer.value."/Root"')
qpdf --json-output --json-object="$root" /tmp/out.pdf /tmp/root.json
# edit /tmp/root.json to mutate the page labels dictionary
qpdf --update-from-json=/tmp/root.json /tmp/out.pdf /tmp/out2.pdf
```
In the general case, you'd have to consider `/PageLabels` being indirect, but qpdf doesn't write it that way. (Maybe it should have? But these are typically small.)

**Comment by jberkenbilt** [comment]
The fix to the start page check and documentation will be in 11.9.0 which I intend to release sometime next week or no later than next weekend.
