### ISSUE TITLE
Writing the stream in json in "clear" form

### ISSUE THREAD

**Issue by TeoColuccio** [qpdf/qpdf#940]
I'm trying to port a test pdf file in json format, but I'd like to keep everything contained in the stream in clear form.
I've already read in the documentation, that qpdf, is not able to extract plain text. But here the problem is different, because I'm not starting from a compressed pdf, but from one written by me from the structure (for educational purposes).
This is therefore the starting stream in clear text because it is written by hand (later, I make the pdf usable with pdftk):
```
stream
1. 0. 0. 1. 50. 700. cm
BT
   /F0 36. Tf
   (Hello, World!) Tj
ET
endstream
```
However, when this is extracted in the json, it doesn't remain in this form, but becomes (base64 encoding):
```
"stream": {
    "data": 
        "MS4gMC4gMC4gMS4gNTAuIDcwMC4gY20KQlQKICAvRjAgMzYuIFRmCiAgKEhlbGxvLCBXb3JsZCEpIFRqCkVUIAo="
```
So is there a way, not to decrypt the text of a stream, but simply to copy an already decompressed stream?

**Comment by jberkenbilt** [comment]
If you are looking for plain streams for educational purposes, I recommend using `--qdf` instead of JSON. Even if this were not base64-encoded, it would have the newlines replaced by \n, etc. While it may be the case that your particular streams are all text, stream data can be anything, so qpdf can't represent stream data without some kind of binary to ASCII encoding. I'm not sure what you are referring to with the term "decrypt" above. Anyway, the `--qdf` option creates a PDF file with decoded, uncompressed streams primary for human viewing and manipulation while keeping the file as valid PDF.  Here's the [relevant section of the docs](https://qpdf.readthedocs.io/en/stable/qdf.html).
