### ISSUE TITLE
Why doesnt QPDF output a bit-to-bit identical PDF file when linearizing despite using the same source PDF file?

### ISSUE THREAD

**Issue by WeAreLegion999** [qpdf/qpdf#944]
Would like to know why QPDF doesnt output a bit-to-bit identical file when I use the same source file. 

Used to cmd "qpdf --linearize x.pdf y1.pdf" and then again "qpdf --linearize x.pdf y2.pdf" 

When doing a bit-to-bit comparison, y1.pdf and y2.pdf are not bit-to-bit identical.
There is a UUID at the beginning and end of the document which change at every instance a new PDF is generated despite using the same source PDF.

example:
top:
trailer << /Info 1031 0 R /Root 1036 0 R /Size 1136 /Prev 1982614               /ID [<6ed5b9a9daf4616a9da7afa2928057c0><1a4ffc251aca1824fde0b022fa1f4dc8>] >>
bottom:
trailer << /Size 1035 /ID [<6ed5b9a9daf4616a9da7afa2928057c0><1a4ffc251aca1824fde0b022fa1f4dc8>] >>

In this, the string "1a4ffc251aca1824fde0b022fa1f4dc8" changes to something else every time a new PDF is generated. 
If anyone knows whats happening here and what that string means, please let me know!
Thanks in advance!

**Comment by jberkenbilt** [comment]
Take a look at [this section of the docs](https://qpdf.readthedocs.io/en/stable/cli.html#idempotency) and let me know if that clears it up for you. If not, I can try to explain further.

**Comment by kashanrat** [comment]
Thanks for your quick reply! Im not too tech savvy but it was certainly helpful. So please correct me if Im wrong: from my understanding, the variation of linearized PDF outputs from the same source PDF is because of a randomly generated document ID in this case (by design of QPDF) and the string itself is pretty much meaningless. 

May I also know if this particular string has anything to do with the information of the PC itself (OS/geo tags/usernames etc)? Thank you!

**Comment by jberkenbilt** [comment]
Your understanding is correct: the /ID is meaningless. There are two strings. According to the spec, the behavior is supposed to as follows:
* When a file is created, an ID is generated and used as both strings
* Whenever the file is modified, the first string is preserved and a new string is generated as the second string

The PDF spec recommends a way to generate the ID which qpdf approximately follows. The ID is basically a hash of various information that includes aspects of the contents of the PDF, the filename, and a timestamp. When `--deterministic-id` is used with qpdf, the ID is generated based on a hash of a normalized version of the content. That way, the same source will generate the same ID each time.

qpdf does not include any information from the PC. It only includes the contents of the PDF and, unless `--deterministic-id` is specified, the timestamp, and the filename. I can't say for sure about what other software does. But the bottom line is that the ID is a meaningless string and changing it doesn't change anything about the file, though it could potentially confuse external applications that expect certain behavior. Note that changing the ID of an encrypted file will make it impossible to decrypt the file because the encryption key is partly derived from the ID.

Does this help? Let me know if you have any further questions.

**Comment by kashanrat** [comment]
I think this explanation is adequate. My whole issue exists because I'm trying to permanently and irreversibly erase a hash which is contained in the metadata of a PDF. Just by using the ExitTool,  "exiftool -all:all= <path.pdf> -o <output1.pdf>", the hash concerned doesnt show up on the metadata, albeit still being inside the PDF itself (can be found by inspecting the PDF in a text editor). 

Linearizing the output PDF (from ExitTools) using QPDF erases the hash from the PDF content, but I was concerned if any part of the hash concerned was still recoverable (and/or linked) to the random string in the output file of QPDF.

I have used `--deterministic-id ` on the same document having 2 different hashes, and verified that the outputs are byte-for-byte identical, indicating the hash concerned indeed has no impact on the string generated in QPDF. Thanks a lot for your quick answer! Really appreciate the help!

**Comment by jberkenbilt** [comment]
Thanks for following up. I always find it gratifying to hear of different ways people are using qpdf, and your having provided this explanation may help someone else with a similar problem.

**Comment by errge** [comment]
Just a small comment for all this discussion: the pdfprivacy latex package (that you can combine with pdfjam), has an option called `nopdftrailerid`, that completely removes this id, according to my debugging with `mutool show foobar.pdf grep`.

https://mirror.init7.net/ctan/macros/latex/contrib/pdfprivacy/pdfprivacy.pdf

If these PDF formats are valid according to the spec (works with atril/evince/xpdf/etc), then it would be cool to have a similar `--no-id` option in qpdf.  Deterministic id is good enough for privacy, but I'm also going for filesize...
