### ISSUE TITLE
Binary distributions of 11.4.0 (Appimage and zip) fail with library errors (Debian 10)

### ISSUE THREAD

**Issue by matthewlenz** [qpdf/qpdf#971]
```
$ .local/share/qpdf/bin/qpdf --help
.local/share/qpdf/bin/qpdf: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/mlenz/.local/share/qpdf/bin/../lib/libqpdf.so.29)
.local/share/qpdf/bin/qpdf: /usr/lib/x86_64-linux-gnu/libp11-kit.so.0: no version information available (required by /home/mlenz/.local/share/qpdf/bin/../lib/libgnutls.so.30)

```

```
$ ./qpdf-11.4.0-x86_64.AppImage --help
/tmp/.mount_qpdfYVhCEn/usr/bin/qpdf: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_qpdfYVhCEn/usr/bin/../lib/libqpdf.so.29)
/tmp/.mount_qpdfYVhCEn/usr/bin/qpdf: /usr/lib/x86_64-linux-gnu/libp11-kit.so.0: no version information available (required by /tmp/.mount_qpdfYVhCEn/usr/bin/../lib/libgnutls.so.30)
```

Maybe I've overlooked something?

**Comment by jberkenbilt** [comment]
I'm probably building the AppImage with too recent of an Ubuntu release. I switched it from18.04 to 20.4 because 18.04 was out of security support and I was no longer able to get a suitable cmake. I will have to re-evaluate how I build the AppImage if it doesn't work with debian 10.

**Comment by matthewlenz** [comment]
It's not a huge deal.  That's interesting though, I always thought Appimage was almost entirely self contained.  Learn something every day. :D  Could you not just include those libs with your distributions?

**Comment by jberkenbilt** [comment]
The AppImage includes libraries that are not "always there" on every Linux distribution. The way it works is that you build your AppImage on a relatively old version of the OS, and then the AppImage bundles all the libraries that the application uses except the standard libraries. Since applications linked with the older libraries generally work with newer ones but not the other way around, this ensures that the AppImage will work on any distribution at least as recent as the one you built it on. It might be possible to manually include the older libraries, but the library bundling part is done by the final stage of AppImage creation that uses a tool they provide to do that part. With bookworm (debian 12) coming out soon, debian 10 will move into "oldstable" status, so debian 10 is already getting pretty old, and I may just decide that it's too old for the AppImage. The only impediments to building qpdf on an older distribution at this point would be a C++ compiler that has good C++17 support and a sufficiently recent version of cmake. I imagine debian 10's default versions of stuff are too old, so backporting maybe a bit more challenging. Ubuntu 18.04 can do it with a custom cmake, but maybe it's not worth the trouble.

**Comment by jberkenbilt** [comment]
Given that debian 10 is now "oldstable" and is out of security support, I am not going to modify the AppImage creation to support that old of a version. My policy is to build the AppImage using the oldest supported Ubuntu LTS release. It's not perfect, but it handles most distributions that are currently in use and supported.
