### ISSUE TITLE
Remove metadata from PDF but keep some as well

### ISSUE THREAD

**Issue by bertalanimre** [qpdf/qpdf#98]
Dear Dev. Team.

I've came across a personal issue with cleaning PDF files.

While qpdf cleans the files very beautiful, I've notices we have needs to keep the page numbers inact and not re-counted, plus the table of contents are also needs to be kapt along with the clickability of some text refering to specific pages.

Is it possible to set qpdf to delete everything except X and Y data or reverse? Delete only A and B and C and D... skipping X and Y from the command.

Thank you in advance!

Regards:
Bert

**Comment by Nokia808** [comment]
@jberkenbilt 
Hi. This is a reminder about this issue because we, know, have PDF Mix Tool as a front-end for QPDF & need to fix this issue for better handling output file from original input to preserve metadata .....

PDF Mix Tool to be a perfect front-end for QPDF need, for certain functions, to remove some metadata & preserve others in the file output.

Please take care, kindly, for this issue.

**Comment by jberkenbilt** [comment]
It's hard for me to understand what is being requested here, but I'm going to close this issue -- I'm working on enhancements to qpdf that will enable link annotations, outlines, and several other document-level constructs to work correctly with page merge and split operations, and I believe this issue will likely be covered by that work. Most likely, there are issues with the `pages` label that already cover this, but as far as I can tell, everything suggested here is on my roadmap.
